### ISSUE TITLE
normal webpack config will not deal with node_modules!

### ISSUE THREAD

**Issue by wszgxa** [NightCatSama/vue-slider-component#1]
such as:

``` js
loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /node_modules/
      },
```
so `import` `export` in https://github.com/NightCatSama/vue-slider-component/blob/master/index.js will throw an error in browser

**Comment by NightCatSama** [comment]
I use the program created in vue-cli is no problem, you can try directly import .vue file
