### ISSUE TITLE
CSS issue for Mobile

### ISSUE THREAD

**Issue by theromie** [NightCatSama/vue-slider-component#100]
Issue with mobile width less than 360px
I tried to fixed css for mobile by adding media query as:
`@media (max-width: 360px) {
    .vue-slider-horizontal .vue-slider-process{
        width: 320px !important;
    }
  }`
but its not working. Slider is going out of the mobile width.
![slider](https://user-images.githubusercontent.com/11131555/30199387-26617180-9490-11e7-88d7-ef458c52c61f.png)

**Comment by NightCatSama** [comment]
If you want to modify the component width, you do not need to change the width of the internal elements of the component, you can modify the container width (the `width` prop of the component must be a percentage or `auto`.

And only in the case of triggering `window.resize` event will update the components, or need to manually call the `refresh` method.

**Comment by theromie** [comment]
Can you show me example?

**Comment by NightCatSama** [comment]
Many of the demo files are self-adapting, you can try to modify the screen width, the components will be adaptive adjustment.

**Comment by theromie** [comment]
Its only happening first time. When you open <div> again its showing perfect. Please check issue

**Comment by NightCatSama** [comment]
Did i mistake your question?

![image](http://7xqnme.com1.z0.glb.clouddn.com/17-9-8/31312207.jpg)

**Comment by theromie** [comment]
Its happening because of i am showing div and hidding

**Comment by NightCatSama** [comment]
Oh, the component is in a hidden state or in a hidden container that is unable to update the component.

Is this the case?

[#exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions)

**Comment by theromie** [comment]
yeah, even i did using refresh();

**Comment by NightCatSama** [comment]
you can try to add `this.$nextTick()`

**Comment by theromie** [comment]
even tried this also but not working

**Comment by theromie** [comment]
anyways fixed issue. Thanks
