### ISSUE TITLE
On change?

### ISSUE THREAD

**Issue by joer80** [NightCatSama/vue-slider-component#101]
I have lazy enabled but it is not firing on change.  Is there another way to do that?

`<vue-slider v-on:change="filterPrice()"></vue-slider>`

`<vue-slider v-on:change="filterPrice()" ref="slider" v-model="value" :lazy="true" :real-time="true" :show="true" :min="0" :max="250000" :interval="1000" tooltip-dir="bottom"></vue-slider>`

**Comment by NightCatSama** [comment]
should be `v-on:callback`

**Comment by joer80** [comment]
I think this is how to do it!

v-on:click.native="filterPrice()"

(Edit:  Sorry, didnt see your response yet.  I will give that a go!)

**Comment by joer80** [comment]
Looks like they both work!

**Comment by joer80** [comment]
Thanks for sharing this project.  Its great!

**Comment by xavierpena** [comment]
@NightCatSama 

I see that `v-on:callback` is called when the mouse is finally up.

Is there a way to have a callback when the label changes? That is to say: when the user drags the button and the label shows a different value.

Adding `@Watch` to `value` has the same effect as `v-on:callback`.

I also tried to use `formatter` (I am using Typescript):

        formatter: (index) => {
            this.someFunction(index);
            return index + "!";
        }

But it says "You may have an infinite update loop in a component render function". I thought that using an arrow function would allow having `this` inside the `formatter` function.

**Comment by xavierpena** [comment]
Solved:

I was using `lazy: false` in my configuration.

Changing it to `lazy: true` resolved the issue.
