### ISSUE TITLE
Missing CSS prefixes

### ISSUE THREAD

**Issue by adi518** [NightCatSama/vue-slider-component#102]
There's an issue with older devices like iPhone 5, where CSS is missing vital prefixes for things like `transform`. I tried adding imported modules prefixing to my project, but so far [no luck](https://github.com/vuejs-templates/webpack/issues/909). Please consider adding prefixing to your build.

**Comment by NightCatSama** [comment]
No real machine I am very difficult to test, if you can, then you can push pr to complement the prefixes.

[#553](https://github.com/NightCatSama/vue-slider-component/blob/master/src/vue2-slider.vue#L553)

**Comment by adi518** [comment]
Hi,

I can actually help you with that: https://apple.stackexchange.com/questions/68836/where-can-i-download-safari-for-windows

The last Safari desktop version for Windows has this exact problem. The problem is not with the JS driven CSS (because as we can tell, it's prefixed). The problem is with the static CSS (tool-tip for example). I forked and added `autoprefixer` to Webpack, which solves it.

**Comment by NightCatSama** [comment]
Thanks for your advice, I have added autoprefixer.

Please update to` version@2.4.1`.
