### ISSUE TITLE
Reversing Vue Slider causes blue bar to fill from wrong end

### ISSUE THREAD

**Issue by patientplatypus** [NightCatSama/vue-slider-component#104]
Using the reverse command will cause the blue bar to fill from the wrong end. Here is what it looks like: http://imgur.com/a/SlK7z.

Here is the code that I am using:

`<vue-slider ref="slider" :tooltip="false" :max="15000" :min='2000' v-model="timetoend" :reverse="true"></vue-slider>`

**Comment by NightCatSama** [comment]
I test the reverse command is feasible. [https://jsfiddle.net/2xy72dod/68/](https://jsfiddle.net/2xy72dod/68/)

Whether it is for this reason. [https://github.com/NightCatSama/vue-slider-component#exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions)

If not, hope to provide more clues.
