### ISSUE TITLE
How can i call refresh method from the parent component ?

### ISSUE THREAD

**Issue by ouraios** [NightCatSama/vue-slider-component#105]
I have a v-show in my parent component which show a loader waiting for an ajax call to complete.
When the ajax call is done i show my page containing the vue-slider.
So i have the exception for vue-slider on initialization, but how can i call the refresh method of vue-slider from the parent component ??

**Comment by NightCatSama** [comment]
Solution on the document. [https://github.com/NightCatSama/vue-slider-component#exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions)

**Comment by ouraios** [comment]
Yeah but i didnt understand the solution is to multiple solutions that you described ? Or is it one big solution following those steps ?
So i need to set real-time to true after the v-show show the slider ?

**Comment by NightCatSama** [comment]
Is not a step, it is a variety of choices.

The simplest can using `v-if` instead of `v-show`, or call the `refresh` method.

**Comment by ouraios** [comment]
As i was asking in my title : how can i call refresh method then ???

**Comment by NightCatSama** [comment]
[https://jsfiddle.net/2xy72dod/80/](https://jsfiddle.net/2xy72dod/80/)

**Comment by NightCatSama** [comment]
my bad.  :sweat_smile:

**Comment by ouraios** [comment]
Great thanks i didnt know we could do that in Vue ! You did an awesome work with this component !
