### ISSUE TITLE
Show min and max values on the slider edges

### ISSUE THREAD

**Issue by yusupprog** [NightCatSama/vue-slider-component#106]
Hi. Nice component!
How can I show min and max values at the edges?

**Comment by NightCatSama** [comment]
Unfortunately, the current component does not provide api can be effectively achieved.

But you can own it through other methods to achieve it, I wrote an example, you can refer to it.

[https://jsfiddle.net/2xy72dod/82/](https://jsfiddle.net/2xy72dod/82/)
