### ISSUE TITLE
With scoped css, no way to change tooltip color and process color.

### ISSUE THREAD

**Issue by prograhammer** [NightCatSama/vue-slider-component#11]
Thanks for the great component!

One issue I have though is with altering the css. With the css scoped, I don't see a way to change the `background-color` on the tooltip and the process bar (which are set at color #3498db). Any ideas on how this can be accomplished? Or am I left to fork the repo and adjust the css?

**Comment by prograhammer** [comment]
It looks like I was able to solve this by adding a specific class to the component, then in my global app.scss `#app .some-specific-class .vue-slider-process`. Is this the best way to do this?

**Comment by NightCatSama** [comment]
Good advice, indeed in less user setting style configuration properties.

My idea is to add `dot-style` and `tooltip-style` properties, can let users covered by the method of inline styles.

If you have a better idea, please let me know

**Comment by prograhammer** [comment]
Updated my answer response above.

**Comment by prograhammer** [comment]
Yeah, I'm actually wondering what the best approach is when it comes to situations like this in scoped css. In my own components, I've added a few more props for changing some of the themed parts that I think user's would want. It seems fine for a few props, but can feel excessive to do this for lots of css. I'm starting to think the best solution is to stick to BEM style and provide a scss file with components for users to use. The user can then use "scoped" css in the parent components, where they can override the css locally (I think). Thoughts on that?

**Comment by NightCatSama** [comment]
I don't want to increase the priority by way of `#app`

I think the most ideal situation like this:
```css
<style lang="scss">
      .custom-class .vue-slider-dot {
         background-color: red;
      } 
</style>
```
But the priority is lower than `.vue-slider-dot [data-v-3]`.

**Comment by prograhammer** [comment]
Oh you're right! I left tha `#app` in there! Not needed.

**Comment by prograhammer** [comment]
What are your thoughts on my suggestion about providing scss file and BEM style? Feel free to close this issue after adding your final thoughts. Thanks again for the great work on this!

**Comment by NightCatSama** [comment]
I don't think too much should not ask the user for a component, because not all users are SCSS, BEM style as well.

If cannot very good solve the problem of priority, I prefer to use `dot-style`

**Comment by prograhammer** [comment]
yeah, `dot-style` and `process-style` is great idea. I think the process style is nice to have because we might want to show warning level at certain ranges and we can change the process bar color dynamically.

**Comment by NightCatSama** [comment]
Generally is ready, because before the tooltip is `:after`, so change the dom spent a lot time.

example is ready now, but i still need to synchronous modified vue1.x, and modify the document. So I still need some time to release a new version.

Thanks again for your issue.

**Comment by NightCatSama** [comment]
Ok, Add four props on style. [click here](https://nightcatsama.github.io/vue-slider-component/example/#demo4)

**Comment by prograhammer** [comment]
This is great! Thank you!
