### ISSUE TITLE
Set multiple options at once.

### ISSUE THREAD

**Issue by Aterr** [NightCatSama/vue-slider-component#110]
Hi there!
I was looking for a solution, to set all necessary options in slider by something like this:

```
<vue-slider ref="slider" v-model="rangeSliderOptions.value" :options="SliderOptions"></vue-slider>

data(){
 return{
  SliderOptions: {...}
 }
}
```
but did not found it in docs.
would be very helpful!

**Comment by NightCatSama** [comment]
You can use `v-bind`, the official documentation has instructions.

[https://vuejs.org/v2/api/#v-bind](https://vuejs.org/v2/api/#v-bind)

```
<!-- binding an object of attributes -->
<vue-slider ref="slider" v-model="rangeSliderOptions.value" v-bind="SliderOptions"></vue-slider>
```
