### ISSUE TITLE
All piecewise points are at the zero point

### ISSUE THREAD

**Issue by halidm** [NightCatSama/vue-slider-component#112]
Installed the slider in vue2 theme which is based on Vuetify (not Vueify) and the slider for some reason has all the points displayed at the origin, I can't drag the button but if I do the value changes and the button stays still.

**Comment by NightCatSama** [comment]
Is it because of this? [exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions)

**Comment by NightCatSama** [comment]
If not, hope to provide code or screenshot related clues.

**Comment by halidm** [comment]
Yes, thanks for the assistance I tried that before, but because I am using a stepper that is loading all steps at mount, putting the this.$nextTick in mounted didn't work, so had to watch for parent's value isActive to do this! thanks again--great component

**Comment by NightCatSama** [comment]
I am not very able to understand your problem. Can you elaborate, or show the next code.

Thank you for your praise.
