### ISSUE TITLE
How to pass the range value to the @callback function ? 

### ISSUE THREAD

**Issue by nacimux** [NightCatSama/vue-slider-component#113]
I use the vue-slider-component to filter a list of product, so i would like to capture the value (range[min,max]) to use it it my filter function.
How can i do it ?

UPDATE : when i pass the v-model as @callback parameter i get the value in my function, but if for example i select a range from "0 to 5000" i got "0 4000" so the maxx value is not taken.

**Comment by NightCatSama** [comment]
`@callback` can return the value of the range.

example: <https://jsfiddle.net/2xy72dod/96/>

**Comment by nacimux** [comment]
Thx for the response 👍
