### ISSUE TITLE
Issue that slider moves the value to max and not clickable after that

### ISSUE THREAD

**Issue by realdah** [NightCatSama/vue-slider-component#116]
I have page section that use v-if to show and hide.
in this section, I have used a few vue-slider-component, code is similiar like below.

`<vue-slider ref="slider" :lazy="true" formatter="{value} %" v-model="product.subsidy"></vue-slider>`

For the first load, it works perfectly fine.
When I hide this section then goes back (I have multiple tabs in this page), the value and position looks just good. However, when I click on slider, it moves to the max value of it, and then stuck there forever.

I have opened vue detector console, i can see that my model object has the right value in the beginning. 
The problem comes from 
currentSlider : 1

When currentSlider is 0, everything works just fine, when it turns to 1, it has problem.

Has anyone else faced similar issue like me?

![image](https://user-images.githubusercontent.com/1226199/31041839-faab6812-a569-11e7-88fa-84aab1164eaf.png)

**Comment by NightCatSama** [comment]
I can not reproduce your situation, can you restore the situation?

(<https://jsfiddle.net/NightCatSama/2xy72dod/120/>)

In the case of a single slider, the `currentSlider` is theoretically not affecting the component.

**Comment by realdah** [comment]
Interesting enough, I could not reproduce this issue in JSFiddle neither.
Let me compare my local code carefully tomorrow.

Thank you for the quick response!

**Comment by realdah** [comment]
I did a few more investigation today, seems like this issue only happens when slider in a table. it works perfectly fine when i put them outside of a table tag. However the same issue is happening in jsFiddle. Which makes me have a strong feeling that there might be some stylings pollution in our code base (the current code base is legacy and ugly which I am trying to upgrade with vuejs.)

I will keep you posted whenever I identified the root cause.

**Comment by realdah** [comment]
I think I found the root cause now.

It is due to the this.offset calculation in your component.

The problem is very rare and need timing.  say for example, if I have a bootstrap responsive UI. which has menu in left side and content in right side.

if in case, the right side content is loaded faster than left menu side, then the offset data will be wrong, because it is calculated with assumption that there is no left menu. then, when mouse clicked, it will calculate as

`t.clientX - this.offset`

While this.offset is cached in the beginning and will never updated.


I can fix from my end to make sure the UI always have the same layout without timing issue. but I feel it is not good to cache the offset when slider component is initialized. i could image that if there is dynamic layout change, the slider will have some potential position issues.



I have updated jsFiddle to reproduce this issue:
https://jsfiddle.net/2xy72dod/124/

**Comment by NightCatSama** [comment]
There are two ways to solve, one is to change the component location after using the refresh method, or use the `real-time` to real-time update the component.

jsFiddle: <https://jsfiddle.net/NightCatSama/2xy72dod/125/>

**Comment by NightCatSama** [comment]
But use the real-time attribute only when the value is the minimum value, otherwise there may be other problems.

So the best solution is to use the refresh method to update the component.

like this: <https://jsfiddle.net/NightCatSama/2xy72dod/126/>

**Comment by realdah** [comment]
Thank you NightCat, I fixed problem in our UI to make sure it is stable then no need to call slider refresh.  The solution from your jsfiddle example looks good to me too.
