### ISSUE TITLE
Non-square sliders

### ISSUE THREAD

**Issue by jbesta** [NightCatSama/vue-slider-component#118]
Current implementation uses `dot-size` option in order to determine both `width` & `height` of sliders. This is not suitable if one wants to have non-square sliders. Main reason is that component itself uses `dot-size` value to calculate `padding` of wrapper elements as well as for proper positioning of sliders.

**Comment by NightCatSama** [comment]
Sorry, the reply time is so late.

I saw your pr, also merged, because I think this is a good extension.

But if you want a square, then it is not enough to do.

Although it is not very convenient, but you can use the `slider-style` to do, before someone raised the issue #90

**Comment by jbesta** [comment]
Thanks for accepting the PR.

I am not sure I understood your last comment - the PR is to support rectangular sliders (that are correctly aligned) which were needed for my use case. Otherwise you would end up with something like this https://jsfiddle.net/39dbyr6f/.

**Comment by NightCatSama** [comment]
Yes, you are right, you can update to version@2.4.3.
