### ISSUE TITLE
Slider Issue in Modal

### ISSUE THREAD

**Issue by rvasoya** [NightCatSama/vue-slider-component#121]
It's not sliding inside modal,
But when height chage of browser it's slide to max value automatically.

**Comment by rvasoya** [comment]
:real-time="true"
Sorry for raising issue it's solved

**Comment by NightCatSama** [comment]
`:real-time="true"` is not the best solution.

More solutions can refer to here <https://github.com/NightCatSama/vue-slider-component#exceptions>

**Comment by chaymag** [comment]
I had the same problem , could not move the slider but after I added :real-time="true" , I was capable of moving it. The only problem is : the maximum value when the slider first shows is always set at position" 0 " (the two values max and min were both on same position = 0 no matter what the values were. Any idea on how to solve this please?

**Comment by NightCatSama** [comment]
@chaymag Refer to the solution link above.

**Comment by chaymag** [comment]
I already did but I still haven't found the solution , I'm also having a problem when using multiple sliders.
If I change one slider , the other ones change as well.

**Comment by NightCatSama** [comment]
You have to make sure to call refresh after the component is visible.

**Comment by chaymag** [comment]
Thank you it worked.

**Comment by Glideh** [comment]
I had this issue too (using a collapse with bootstrap-vue).
Here is how I did for the record:

```vue
<b-btn v-b-toggle.filters>Filters</b-btn>
<b-collapse id="filters" @shown="showFilters">
    <!-- ... -->
    <vue-slider ref="amountSlider" v-model="amount"></vue-slider>
</b-collapse>

<script>
export default {
// ...
    methods: showFilters() {
        this.$refs.amountSlider.refhresh();
    }
// ...
}
</script>
```

**Comment by agriboz** [comment]
> I had this issue too (using a collapse with bootstrap-vue).
> Here is how I did for the record:
> 
> ```
> <b-btn v-b-toggle.filters>Filters</b-btn>
> <b-collapse id="filters" @shown="showFilters">
>     
>     <vue-slider ref="amountSlider" v-model="amount"></vue-slider>
> </b-collapse>
> 
> <script>
> export default {
> // ...
>     methods: showFilters() {
>         this.$refs.amountSlider.refresh();
>     }
> // ...
> }
> </script>
> ```

Fixed typo.
