### ISSUE TITLE
Slider does not move when arrow keys are used to change value

### ISSUE THREAD

**Issue by colinStevenson** [NightCatSama/vue-slider-component#122]
I am able to update the value of the slider with keyboard arrow keys, however, the slider position does not change to reflect the value change.

**Comment by colinStevenson** [comment]
I was able to make a local copy of the vue2-slider.vue component and put a watch on the val property and call syncValue when this.val !== this.value - there might be a cleaner way of doing this but it does the trick for the time being.

**Comment by NightCatSama** [comment]
I tested that it was working properly. <https://jsfiddle.net/2xy72dod/154/>

Can you explain your situation in more detail?

If it can be displayed under your code, or in jsfiddle to reproduce the scene

**Comment by colinStevenson** [comment]
Hi @NightCatSama, sorry for the lack of clarity. The challenge we are having is that the user can tab to focus the range input element  and use the left and right keys to modify the value (good for keyboard accessibility). When the value is changed with the keyboard, the value displayed on the tooltip is updated (this.val) but the components value (this.value) does not stay in sync. If you check out https://jsfiddle.net/d6e2snyh/ , I've made the input slightly visible so you can click on it to focus it or tab to it, at which point, you can use the left and right arrow keys to change the value of the displayed on the tooltip and note that the slider position does not change, nor does the value displayed below in the h1. 

Not sure if keyboard accessibility was an intended feature with this lib but this may be a quick win for the sake of web accessibility. Either way, thanks for the great bit of code!

**Comment by NightCatSama** [comment]
I think I know your problem, and when the slider is in the drag state, set the value of the component will appear value and val does not match the exception.

In this case, how do you expect the component to handle this situation.

**Comment by colinStevenson** [comment]
My expectation is that when the user uses the keyboard to update the value of the input, the slider should move to reflect the changed value and the displayed value should update as well.  Here is the code I added in a local version to solve the issue:

`
watch: {
...
val () {
	if(this.val !== this.value) {
		this.syncValue();
	}
},
`

**Comment by NightCatSama** [comment]
In the case of using only the keyboard to modify the value, the component will be the value of the normal update.(<https://jsfiddle.net/d6e2snyh/1/>) 

Only in the mouse to hold the slider so that the components in the drag state, the use of keyboard to modify the value of the value of the situation will not be synchronized. But this will only happen at a very low probability.
