### ISSUE TITLE
Bug with transition-group with key

### ISSUE THREAD

**Issue by adrianoresende** [NightCatSama/vue-slider-component#123]
I found bug, when has `transition-group` with `key`, the slide work but not has move or change value.

```vue
<transition-group :name="slideTransition">
  <div class="step" key="1" v-show="stepCurrent == 1">
    ...
  </div>
  <div class="step" key="2" v-show="stepCurrent == 2">
    <vue-slider ref="slider" v-model="value"></vue-slider>
  </div>
</transition-group>
```

**Comment by NightCatSama** [comment]
You can refer to the document's [exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions).

Simple example:
```
<transition-group :name="slideTransition" :after-enter="refreshSlider">
  <div class="step" key="1" v-show="stepCurrent == 1">
    ...
  </div>
  <div class="step" key="2" v-show="stepCurrent == 2">
    <vue-slider ref="slider" v-model="value"></vue-slider>
  </div>
</transition-group>
// ....
  methods: {
    refreshSlider: function () {
        this.$nextTick(() => this.$refs.slider.refresh())
    }
  }
```

**Comment by justanotherco** [comment]
Hey @NightCatSama 
First of all great component, really handy 👍 

However, I'm having the same issue and tried your solution, but it doesn't work. When you use the nextTick, the slider then does become "active" but jumps to the maximum value and stays stuck there. Here is a fiddle showing it:

https://jsfiddle.net/sometip/8hwdt0Ls/

Is there a way to get the slider to work in a Transition Group?

Thanks again

**Comment by NightCatSama** [comment]
I'm sorry, I made a big mistake.

`after-enter` is an event rather than an property. So it should be `@after-enter="refreshSlider"`.

This is a modified example: <https://jsfiddle.net/8hwdt0Ls/1/>

And I used v-if to replace v-show, otherwise there will be a transition state.

**Comment by adrianoresende** [comment]
Interessant this cycle transition work with function
Thanks @NightCatSama ;)

**Comment by justanotherco** [comment]
Thanks @NightCatSama , that was it, works perfect now 👍
