### ISSUE TITLE
Slider detects clicks in incorrect position when it was scrolled

### ISSUE THREAD

**Issue by anikolaev** [NightCatSama/vue-slider-component#124]
Here is an example: 
https://jsfiddle.net/ux93ar4u/

Just scroll it to the right and try to click at "80", "90". It selects "50" and "60" instead.

**Comment by NightCatSama** [comment]
You can try using `real-time`, like <https://jsfiddle.net/ux93ar4u/1/>.

**Comment by anikolaev** [comment]
Great, thank you, @NightCatSama . Any possible performance issues?

**Comment by NightCatSama** [comment]
Each time you drag or click, the component will calculate and update the width and height. I think it should not have serious performance problems.

**Comment by anikolaev** [comment]
Ok, nice to hear. It works now.
