### ISSUE TITLE
vue 2.5 the "scope" attribute for scoped slots have been deprecated

### ISSUE THREAD

**Issue by ankurk91** [NightCatSama/vue-slider-component#125]
Hi,

Vue v2.5.2
vue-slider-component 2.4.3

I am getting this warning in console.

```
Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.
```
In order to fix the i just changed `scope` to `slot-scope`, see 
```html
<template slot="tooltip" slot-scope="tooltip">
                    <div class="diy-tooltip text-center">
                      {{ myMethod(tooltip.value) }}
                    </div>
</template>
```
The [gh-pages](https://nightcatsama.github.io/vue-slider-component/example/) need to be updated.

**Comment by NightCatSama** [comment]
Thank you for the reminder that I will modify it.

**Comment by ankurk91** [comment]
fixed in 
https://github.com/NightCatSama/vue-slider-component/commit/64abd0f006e473d46ff221420b64571a732f2795
