### ISSUE TITLE
Problem between two slider

### ISSUE THREAD

**Issue by Lono17** [NightCatSama/vue-slider-component#126]
Hi NightCatSama. I am using two sliders at same time. If I move the first slider, the second slider have to change the value but the second slider value don´t support a function. How can I fix it? Are there any possibility?.
Thanks in advance

**Comment by NightCatSama** [comment]
like that? [demo5](https://nightcatsama.github.io/vue-slider-component/example/#demo5)

**Comment by Lono17** [comment]
Not exactly, in demo5 use the same value. My project it´s like money conversor. I choose a value in "$" in the first slider and with a function I calculate the value in "€" for set in the second slider.

**Comment by NightCatSama** [comment]
I wrote an example, I wonder if it can solve your problem.

<https://jsfiddle.net/2xy72dod/169/>
