### ISSUE TITLE
Stop Drag Event propagation when in a draggable component

### ISSUE THREAD

**Issue by advancedlogic** [NightCatSama/vue-slider-component#127]
I am trying to embed your component into a [(vue-draggable-resizable)](https://github.com/mauricius/vue-draggable-resizable) component but when I drag the slide, also the component below starts moving. I am trying to add a `stopPropagation` on the event _@drag-start_ but without success.
Any suggestion?

**Comment by NightCatSama** [comment]
You can try the `event-type` attribute to make the component unusable.

**Comment by advancedlogic** [comment]
It does not work. The problem is not to disable your component but disable the drag of the component below. How can I get the event on `@drag-start` and `@drag-end` in order to fire a `stopPropagation()`?

**Comment by NightCatSama** [comment]
I added the stopPropagation property to prevent the event from bubbling.

In version 2.4.4 you can use `:stop-propagation="true"` to prevent bubbling.

**Comment by advancedlogic** [comment]
Thanks, it works :)

**Comment by mbranicky** [comment]
In current 3.2.5 version this attribute is still available? I am using it but no effect. Was it removed in the past versions?

**Comment by NightCatSama** [comment]
@mbranicky  Try this?

```html
  <vue-slider 
    @mousedown.native.stop="_ => null" 
    @mousemove.native.stop="_ => null" 
  />
```

**Comment by mbranicky** [comment]
@NightCatSama unfortunately it doesn't work. I tried several combinations, no luck. However I workaround the solution in a way that in @drag-start event I temporarily disable the draggable attribute of the parent element, which is also a draggable component. And in @drag-end I again enable the same draggable attribute. Works nice.

**Comment by d4rkmen** [comment]
Vue2 verision of vue-slider-component 2.8.16 still cant drag, when placed on a draggable compenent, parent drag is called.
To fix this, you have to call preventDefault() for corresponding events
Workaround:
```html
            <div draggable="true" @dragstart.prevent="(e)=>null" @dragend.prevent="(e)=>null">
              <vue-slider v-bind="options"></vue-slider>
            </div>
```
