### ISSUE TITLE
'Failed to resolve directive: el' when inside a bootstrap-vue popover 

### ISSUE THREAD

**Issue by lachezargrigorov** [NightCatSama/vue-slider-component#129]
## Detailed description

I'm trying to render this slider component inside a [bootstrap-vue popover](https://bootstrap-vue.js.org/docs/components/modal#tooltips-and-popovers) but it fails with following warn message: 
`
Failed to resolve directive: el
`

<img width="85" alt="screen shot 2017-11-21 at 18 31 55" src="https://user-images.githubusercontent.com/3510976/33084987-0ce7d92e-ceec-11e7-8b51-5eaabc398ba7.png">

### HTML
```html
 <b-popover  placement="bottom" target="popoverId" triggers="click blur">
     <vue-slider ref="slider" v-model="value"></vue-slider>
 </b-popover>
```
### root.js

```javascript
import vueSlider from 'vue-slider-component/src/vue-slider.vue'
Vue.component('vue-slider',vueSlider)
```

### component.js

```javascript
 export default {
        props: [],
        data()
        {
            return {
                value : 1
            };
        }
    };
```

## Environment

* vue: 2.5.3
* bootstrap-vue: 1.1.0
* vue-slider-component: 2.4.5

**Comment by lachezargrigorov** [comment]
Sorry, my mistake.

**Comment by lachezargrigorov** [comment]
The slider is rendered now but the mouse (drag) event is very laggy and slow and at 99% in the cases the piecewise dot block at the init positions and didn't move anymore. I've rendered two sliders binded to the same data source to make the issue clear. See the screenshot below. 

<img width="414" alt="screen shot 2017-11-22 at 18 02 13" src="https://user-images.githubusercontent.com/3510976/33137312-471d5d7a-cfb0-11e7-9728-58d567dd93cf.png">

### Console
`
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] 'message' handler took 161ms

[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
`

**Comment by NightCatSama** [comment]
I am sorry for late reply.

Are you experiencing the problem for this reason?

<https://github.com/NightCatSama/vue-slider-component#exceptions>

example: <https://jsfiddle.net/2xy72dod/253/>
