### ISSUE TITLE
Component still active after navigating to new component with vue router

### ISSUE THREAD

**Issue by PsychicCat** [NightCatSama/vue-slider-component#13]
I was having a problem with refresh() being called after navigating from a component using vue-slider-component. 

I got the console warnings to go away by doing this, but it seems that the slider is not being destroyed when navigating away using vue-router.

Not sure if this is an issue for you or Vue Router.

```javascript
		refresh() {
		    if(this.$refs.elem){
                this.getStaticData()
                this.setPosition(0)
			}
		}
```

**Comment by PsychicCat** [comment]
I think i figured it out, need to remove the event listener for resize to unbindEvents...

i will submit a PR

**Comment by NightCatSama** [comment]
thank.
