### ISSUE TITLE
I want use prop "piecewiseLabel",and "piecewise"

### ISSUE THREAD

**Issue by ackemaneva** [NightCatSama/vue-slider-component#131]
but I don't want to slide the block.i just want  #display some label. @NightCatSama

**Comment by ackemaneva** [comment]
`year: {
        value: [
          "0", "20"
        ],
        data: [
          "0",
          "5",
          "10",
          "15",
          "20",
        ],
        piecewise: true,
        piecewiseLabel: true,
        clickable:true,
        width: "100%",
        dotSize: 16,
        min: 0,
        max: 20,
        tooltip: "always",
        formatter: "{value}年",
        bgStyle: {
          "backgroundColor": "#deaf3b",
          "boxShadow": "inset 0.5px 0.5px 3px 1px rgba(0,0,0,.36)"
        },
        tooltipStyle: {
          "backgroundColor": "#666",
          "borderColor": "#666"
        },
        processStyle: {
          "backgroundColor": "#999"
        },
        piecewiseStyle: {
          "backgroundColor": "#ccc",
          "visibility": "visible",
          "width": "12px",
          "height": "12px"
        }
      },`

**Comment by NightCatSama** [comment]
You can try using `slot`.

**Comment by ackemaneva** [comment]
emmm,i don't want use it. can i use some prop that can change this  from your component?

**Comment by ackemaneva** [comment]
sorry,are you from China?

**Comment by ackemaneva** [comment]
i used this slider component a period. i want change my website's some style by your component.  can i send a email to you?  thank you very much!

**Comment by NightCatSama** [comment]
of course.

**Comment by NightCatSama** [comment]
I think slot can be easily customized piecewise.

I wrote a simple example: <https://jsfiddle.net/2xy72dod/256/>

**Comment by ackemaneva** [comment]
对不起，我可能说的不明白，英文不好，别介意。我想表达的是，该组件有分段功能，但是分段后，我不能选择一小段之间的数字了。比如，分段中有0-10这一个小段，但是我没法选择0-10中间的任何一个数了。而且，我不想分段间隔interval为1，那样下面的label就太拥挤了。您能给个解决方案么？如果有，那太感谢了

**Comment by NightCatSama** [comment]
不好意思，现在没有实现这种分段后再分段的功能。
