### ISSUE TITLE
Position Bug

### ISSUE THREAD

**Issue by iGerchak** [NightCatSama/vue-slider-component#132]
Hi!
When dynamically changing the position of the block (for example: after DOM load, I change margin-left: 200px, for a block with slider), the markers are not working properly.

**Comment by NightCatSama** [comment]
This exception is written on the document.

<https://github.com/NightCatSama/vue-slider-component#exceptions>

example:  <https://jsfiddle.net/2xy72dod/254/>

**Comment by NightCatSama** [comment]
Similarly, you just need to `refresh` the component after setting the margin (maybe need `$nextTick`).

**Comment by iGerchak** [comment]
Thank you very much!
