### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by 99percent6** [NightCatSama/vue-slider-component#134]
Hi!
I use slider in another vue-component on localhost. 
After adding slider to the template it is displayed on the page, but when update this page i see  `500 | Internal Server Error`  and in a Terminal `ReferenceError: document is not defined`.
`<template>
    <div class="sidebar">
            <price-slider
                v-model="value"
                v-bind="options">
            </price-slider>
        </div>
    </div>
</template>`

Also i tried this variant template:
`<template>
    <div class="sidebar">
         <no-ssr>
            <price-slider
                v-model="value"
                v-bind="options">
            </price-slider>
         </no-ssr>
        </div>
    </div>
</template>`

`import PriceSlider from 'vue-slider-component'`
`export default {
  components: {
    ColorButton,
    SizeButton,
    PriceButton,
    RangeSlider,
    'no-ssr': NoSSR,
    **PriceSlider**
  },
  data () {
    return {
      sliderValue: 50,
      value: [0, 100]
    }
  },
  mixins: [coreComponent('core/blocks/Category/Sidebar')]`

What am I doing wrong?

**Comment by NightCatSama** [comment]
I am sorry, I have not tried to use components for ssr, you can refer to other people's solutions.

[Using it with NUXT.js](https://github.com/NightCatSama/vue-slider-component#using-it-with-nuxtjs)

[issue#75](https://github.com/NightCatSama/vue-slider-component/issues/75)

**Comment by 99percent6** [comment]
Added this code:
`if (process.browser) {
    // in older versions of nuxt, it's process.BROWSER_BUILD
    let VueSlider = require('vue-slider-component')
    components['vue-slider'] = VueSlider
}`
and all run, thanks
