### ISSUE TITLE
slider width causes slider dot to be out of place

### ISSUE THREAD

**Issue by danpottshimself** [NightCatSama/vue-slider-component#135]
Using: Vue 2.4.3 and vue-slider-component 2.4.7

html: 
 <vue-slider ref="slider" v-model="value" :width="width" :height="height" :class="pointerClass" :bgStyle="bgStyle" :piecewiseStyle="piecewiseStyle" :processStyle="processStyle" :dotSize="dotSize" :min="min" :max="max" :interval="interval" :disabled="disabled" :clickable="clickable" :show="show" :speed="speed" :reverse="reverse" :lazy="lazy" :tooltip="tooltip" :piecewise="piecewise">
    </vue-slider>

vue component data:
public value = 1;
public width = 1400;
public height = 8;
public dotSize = 30;
public min = 1;
public max = 90;
public interval = 1;
public disabled = false;
public clickable = true;
public show = true;
public speed = 0.5;
public reverse = false;
public lazy = true;
public tooltip = "always";
public piecewise = true;
public pointerClass = "diamond-slider";
public processStyle = {
  "backgroundColor": "rgba(71, 113, 255, 0.66)"
};
public bgStyle = {
  "backgroundColor": "transparent",
}
public piecewiseStyle = {
"backgroundColor": "#FFFFFF",
"visibility": "visible",
"width": "6px;",
"height": "6px;"
};

In the below image i have clicked on the last possible dot on the slider. Even when dragging it seems the speed/velocity does not catch up to the mouse and is far behind. Can anyone help identify why this is happening? 

***************************************
EDIT: I found out that the problem is when the width value is set to higher than 280.
****************************************

<img width="952" alt="screen shot 2017-12-18 at 16 31 13" src="https://user-images.githubusercontent.com/13645940/34116554-e1f0234a-e410-11e7-887d-a61aa05856d3.png">

**Comment by NightCatSama** [comment]
Is it because you have set `dotSize = 30`, but your diamond does not look that big?

Because `dotSize` is used to calculate the position of the slider.

**Comment by NightCatSama** [comment]
My guess should be wrong.

Based on the parameters you provided I failed to reproduce the problem.

Can you reproduce the problem in jsfiddle? <https://jsfiddle.net/2xy72dod/312/>

**Comment by danpottshimself** [comment]
@NightCatSama woke up and tried again, seems to be fine now.... its made me look silly :P 
Sorry for bothering and thanks for helping :)
