### ISSUE TITLE
Multiple Piecewise from Slots

### ISSUE THREAD

**Issue by alexpvieira** [NightCatSama/vue-slider-component#137]
Hi. I´m trying to add some piecewises into my slider only on specific indexes but only the last one added is currently showed.

There's any way I could archieve that?

My current code for showind the piecewises is:

`<template slot="piecewise" slot-scope="{ label, active, index }">
                <div v-if="index === 10" class="my-piecewise" :data-value="label"></div>
           </template>`

`<template slot="piecewise" slot-scope="{ label, active, index }">
                <div v-if="index === 20" class="my-piecewise" :data-value="label"></div> 
            </template>`

Thanks.

**Comment by NightCatSama** [comment]
My test is normal: <https://jsfiddle.net/2xy72dod/318/>

**Comment by alexpvieira** [comment]
I've used your exemple and only one piecewise is showed (the last one).

https://jsfiddle.net/ktqfaozn/

I need to set three different ones into the same slider.

**Comment by birdspider** [comment]
@alexpvieira use only one named slot, i.e. put 2 or more diffs inside a single named slot

**Comment by alexpvieira** [comment]
@birdspider thank you! It worked.
