### ISSUE TITLE
Adding tooltip on the vue-slider-progress Div

### ISSUE THREAD

**Issue by sunnyboi21** [NightCatSama/vue-slider-component#138]
Hi, I  wanted to add a tooltip in the middle of the progress bar. I was wondering if you could add a :class or attach another tooltip option to it.

Thanks

**Comment by NightCatSama** [comment]
Sorry, there is no such feature, maybe you can add your own class and then modify the component.

e.g:
```vue
<template>
  <vue-slider v-model="value" class="my-slider"></vue-slider>
</template>

<style>
.vue-slider-component.my-slider .vue-slider {
  background-color: #f04f45;
}
</style>
```
