### ISSUE TITLE
Stacking/Blocking on the the max value

### ISSUE THREAD

**Issue by PauloVanetti** [NightCatSama/vue-slider-component#139]
the sliders stacks/blocking on the max/end value when u touching this after remounting parents component

**Comment by NightCatSama** [comment]
Is this the case? <https://github.com/NightCatSama/vue-slider-component#exceptions>

**Comment by PauloVanetti** [comment]
<slider v-model='value' class='vane-default-trail-10'></slider>

this class is only contains 
margin-top: 10px

i think this is a reason of issue yup ?

**Comment by NightCatSama** [comment]
This should be caused by a calculation error when the component is initialized. Because your situation is very consistent with the [exception](https://jsfiddle.net/2xy72dod/254/).

You can try to display the component after the page is loaded.

e.g.
```vue
<slider :show="show" v-model='value'></slider>
<slider ref="slider" v-model='value'></slider>

export default {
  data () {
    return {
      show: false,
      value: 0
    }
  },
  mounted () {
    this.show = true
    // or
    this.$refs.slider.refresh()
  }
}
```

**Comment by luisdfp** [comment]
I faced the same problem while using the slider inside a router view that has a slide-in transition when it is mounted. Managed to fix it by refreshing the slider after the transition animation ends.

`<template>
  ...
        <vue-slider 
          ref="slider"
          class="price" 
          v-model="price" 
          :min="500" 
          :max="10000" 
          :interval="100" 
          :tooltip="false" 
        >        
        </vue-slider>
...
</template>

<script>
import vueSlider from "vue-slider-component";

export default {
  components: {
    vueSlider
  },
  data() {
    return {
      price: 1000
    }
  },
  mounted(){
    // Wait for the transition animation to end and then refresh the slider.
    let self = this
    setTimeout(function(){
      self.$refs.slider.refresh()
    }, 1000)    
  }
};
</script>`

**Comment by NightCatSama** [comment]
@luisdfp If you are using `<transition>` or `<transition-group>`, you can refer to this [solution](https://jsfiddle.net/8hwdt0Ls/1/).

**Comment by PauloVanetti** [comment]
TypeError: this.$refs.slider.get is not a function :(

**Comment by PauloVanetti** [comment]
TypeError: this.$refs.slider.refresh is not a function

**Comment by PauloVanetti** [comment]
oh i have checked everything in the component info into the console 

this.$refs.slider['0'].refresh()

thats work
