### ISSUE TITLE
Slider not updating When more then one slider present on page.

### ISSUE THREAD

**Issue by devravi** [NightCatSama/vue-slider-component#140]
In my vue app, I'm loading two vue-slider as child components.
Both are related with two different model. (numA and numB).

I'm using v-show to hide show according to selected tab. See below example:
https://jsfiddle.net/6qx9ob2y

When switching from tab1 to tab2, 
I read values from input box and set to model I used for slider.

Some how Progress on slider not visible. But tooltip show values showing correctly.
Also you can not drag slider to increase decrease values.

**Comment by NightCatSama** [comment]
if the component initialization in a v-show="false" / display: none container, there may be an exception.

In the document there is a detailed description of the [exception](https://github.com/NightCatSama/vue-slider-component#exceptions)

**Comment by devravi** [comment]
@NightCatSama Solved using v-if:
https://jsfiddle.net/6qx9ob2y/1/

Thanks a lot :heart: ;
