### ISSUE TITLE
Errors with after short component life (Vue2)

### ISSUE THREAD

**Issue by devorld** [NightCatSama/vue-slider-component#141]
Hello!

I'm using vue-slider-component in our project, and I've got errors when it was in construction like that:

```
<spinner v-if="isContentLoading"></spinner>
<div v-else>
  <vue-slider-component></vue-slider-component>
</div>
```

I spent hours and found the reason:
1. at first our variable `isContentLoading` (which is mapped from store) had initial value "false" and vue-slider-component started initializing vue-slider-component;
2. vue-slider-component executed `.mounted()`, which set code for `$nextTick`;
3. then `isContentLoading` changed to "true" value;
4. vue-slider-component executed `.beforeDestroy()`;
5. next tick started and executed code, which was set in step 2, with rising errors.

As a temporary solution I copied source of component to our project and added flag isComponentExists, wich sets in false in `.beforeDestroy()` and checks in `mounted()` -> `$nextTick` block.

**Comment by NightCatSama** [comment]
I have merged your pr, please update to the latest version.

**Comment by devorld** [comment]
Thanks for a quick response!
