### ISSUE TITLE
custom class not working??

### ISSUE THREAD

**Issue by alziqziq** [NightCatSama/vue-slider-component#143]
thanks for great component.
 
 .custom-class .vue-slider .vue-slider-dot {
    background-color: red;
  }

why its not working??

**Comment by NightCatSama** [comment]
Are you using a scoped style?

e.g. <https://jsfiddle.net/2xy72dod/395/>

**Comment by alziqziq** [comment]
it does not work on components.
but it works on global css

**Comment by NightCatSama** [comment]
In the scoped style does not work. (<https://vue-loader.vuejs.org/en/features/scoped-css.html>)

I think it is best to use the component's properties.

**Comment by alziqziq** [comment]
oke thank :+1: :+1: :+1:
