### ISSUE TITLE
Load first component fails

### ISSUE THREAD

**Issue by tiagoarasilva** [NightCatSama/vue-slider-component#145]
Hi,

I'm trying to use this component but when I first load the slider, the first line doesn't use the width properly. The slider is only "fixed", for instance if I resize my window or if open an inspect. This only happens in 1 first slider, as I have a function to add new line, each line contains a slider, besides the first one, the rest is automatically fine.

JS:
```JS
components: {
        'vueSlider': window['vue-slider-component']
    },
```
HTML:
```HTML
<td class="text-center">
     <vue-slider ref="slider" v-model="rule.value" :options="options"></vue-slider>
</td>
```

An example of what I'm talking about:

![screenshot from 2018-01-24 18-05-24](https://user-images.githubusercontent.com/11027931/35348845-36227d22-0131-11e8-9cc5-677dfa63e223.png)

Is this a bug? The HTML/JS framework that I'm using is Foundation 6

Thanks,

**Comment by tiagoarasilva** [comment]
The workaround for this was making sure that in the action of adding a new slider for the first line it should trigger the refresh automatically, so I had to force it:


```JS
this.$watch(function () {
                    this.$nextTick(function () {
                        for (var i = 0; i < this.$refs.slider.length; i++) {
                            this.$refs.slider[i].refresh();
                        }
                    });
                });
```

Like this. I cool feature for this it would be forcing this same action automatically without making the other component making it for it.

**Comment by NightCatSama** [comment]
Is this the case? <https://github.com/NightCatSama/vue-slider-component#exceptions>

**Comment by tiagoarasilva** [comment]
Yes and I used the solution number 2 as suggested and nothing happens.

**Comment by NightCatSama** [comment]
I am sorry, I have not used that framework, can not judge where the error caused.

It looks like the width of the table is reduced after the component is initialized.

You initialize the first piece of data is dynamically rendered?

**Comment by NightCatSama** [comment]
@tiagoarasilva Maybe you can try adding this code after loading the data.

```js
  this.data = res.data // simulate loads the data
  this.$nextTick(() => {
    this.$refs.slider.refresh() // refresh the component
  })
```

**Comment by tiagoarasilva** [comment]
Even this one doesn't work. That was my 1st try

**Comment by NightCatSama** [comment]
I am sorry, I do not know what is the reason.

**Comment by sanjsharma** [comment]
I am having the same problem. Slider slides only after I resize.

**Comment by NightCatSama** [comment]
@sanjsharma Because the component is bound `resize` event to call the `refresh` method.

You just have to call the `refresh` method after the layout is modified, just as I commented on earlier.

**Comment by sanjsharma** [comment]
@NightCatSama I am calling the vue-slider inside bootstrap collapse where it does not work but it works outside the collapse block. But, calling refresh inside updated() hook solved it. Thanks.
      updated() {
        this.$nextTick(function () {
          this.$refs.slider.refresh()
        })
      }

**Comment by ojczeo** [comment]
@NightCatSama this is nice solution: https://github.com/Akryum/vue-resize

**Comment by NightCatSama** [comment]
@ojczeo Thanks for your recommendation, but may not be able to solve the root cause, such as `display: none`, and `left`, `top`, and `transform`  cannot be listened.

**Comment by NightCatSama** [comment]
It is no longer necessary to call refresh in the latest version.

**Comment by hsoyier** [comment]
> It is no longer necessary to call refresh in the latest version.

Hi, could I ask what should we do instead of calling refresh to resize in v3??

**Comment by NightCatSama** [comment]
@hsoyier What do you want to refresh?
