### ISSUE TITLE
20.cb2049a8ab9da9fc15d4.js:1 [VueSlider error]: Prop[interval] is illegal, Please make sure that the interval can be divisible

### ISSUE THREAD

**Issue by Horzen** [NightCatSama/vue-slider-component#146]
i used vue2.x & my vue-slider-component's version is 2.5.3
i write a component with  vue-slider-component in my application,then i used it in 3 places.Then i found a problem:the 1st time i opened slider,it will console an error just like my tittle“Prop[interval] is illegal”，but the component still can be used. 
![screenshot_1](https://user-images.githubusercontent.com/32396611/35545315-78492c60-05a9-11e8-927d-fed5a4f9a755.jpg)
And when i opened it in another place,it will also console the same error and it did not work.
![screenshot_2](https://user-images.githubusercontent.com/32396611/35545346-a3776dd4-05a9-11e8-813d-414e93ac9002.jpg)
here is my option :
![screenshot_3](https://user-images.githubusercontent.com/32396611/35545404-f03a448e-05a9-11e8-8113-527f62682043.jpg)
![screenshot_4](https://user-images.githubusercontent.com/32396611/35545405-f1dfe0a0-05a9-11e8-8e33-374cb28a097e.jpg)

i also tried ":formatter='getValue'",but it still did not work.
where did i go wrong?

**Comment by NightCatSama** [comment]
Because of your second component, `max - min` can not be divisible by interval, ie `(1000 - 10) / 50 = 19.8`.

If you think this matches your expectations, you can turn off console printing by setting the property `debug = false`.

**Comment by Horzen** [comment]
my component used 2 sliders. i deleted the 2nd one.but it only can be used in 1st page,the 2nd page still did not work.it seems this problem has no relationship to 'interval' .it just exists in 'switch between different pages'
Page 1:
![page1](https://user-images.githubusercontent.com/32396611/35546356-f20c7afc-05ae-11e8-9225-aeed6882725d.jpg)
Page 2:
![page2](https://user-images.githubusercontent.com/32396611/35546393-fcfc3952-05ae-11e8-8ba6-a57e3f2ac5eb.jpg)

**Comment by NightCatSama** [comment]
Is this a problem with console printing?

**Comment by Horzen** [comment]
nope

**Comment by NightCatSama** [comment]
If it is because of page switching can not use the problem, you can refer to <https://github.com/NightCatSama/vue-slider-component#exceptions>

**Comment by Horzen** [comment]
thank u.i tried use v-if instead of v-show.it works.
