### ISSUE TITLE
How to display label in start , and end when using 2 slider?

### ISSUE THREAD

**Issue by xsmartweb** [NightCatSama/vue-slider-component#147]
This is my configuration.

``
value: [
                30,
                80
            ],
            options: {
                eventType: 'auto',
                width: "100%",
                height: 4,
                dotSize: 16,
                dotHeight: null,
                dotWidth: null,
                min: 0,
                max: 100,
                interval: 1,
                show: true,
                speed: 0.5,
                disabled: false,
                piecewise: false,
                piecewiseStyle: false,
                piecewiseLabel: false,
                tooltip: "always",
                tooltipDir: 'top',
                reverse: false,
                data: null,
                clickable: true,
                realTime: false,
                lazy: false,
                formatter: "${value}",
                bgStyle: {
                  "backgroundColor": "#fff",
                  "boxShadow": "inset 0.5px 0.5px 3px 1px rgba(0,0,0,.36)"
                },
                sliderStyle: [
                {
                    "backgroundColor": "#3498db",
                    "width": "10px",
                    "height": "10px",
                    "top": "-3px"
                },
                {
                    "backgroundColor": "#3498db",
                    "width": "10px",
                    "height": "10px",
                    "top": "-3px"
                }
                ],
                processStyle: null,
                piecewiseActiveStyle: null,
                piecewiseStyle: null,
                tooltipStyle: {
                    "border": "0px",
                    "background-color": "transparent"
                },
                labelStyle: null,
                labelActiveStyle: {
                  "color": "#3498db"
                }
            }
``

**Comment by NightCatSama** [comment]
Do not know what your needs are?

If you need to customize, you can try [#slot](https://github.com/NightCatSama/vue-slider-component#slot)

**Comment by ken-mills** [comment]
I created labels at start and end using slot as suggested.

```                
<vue-slider
		id="ride-slider"
		ref="slider"
		v-model="value"
		v-bind="options"
		:data="sliderValues"
		v-on:callback="mouseFired"
>
	<div slot="label" slot-scope="props" class="sliderLabel">
		<span v-if="props.index === 0">{{ props.label }}</span>
		<span v-if="props.index === 12">{{ props.label }}</span>
	</div>
</vue-slider>
```

**Comment by faislwani** [comment]
marks:{
                        '0':{
                            label:'Strongly Disagree',
                            labelStyle: {
                                color: '#69c0ff',

                            }
                        },
                        '20':'',
                        '40':'',
                        '60':'',
                        '80':'',
                        '100':{
                            label:'Strongly Agree',
                        },

                    },

**Comment by faislwani** [comment]
`marks:{
                        '0':{
                            label:'Strongly Disagree',
                            labelStyle: {
                                color: '#69c0ff',

                            }
                        },
                        '20':'',
                        '40':'',
                        '60':'',
                        '80':'',
                        '100':{
                            label:'Strongly Agree',
                        },

                    },`

**Comment by faislwani** [comment]
marks:{
                        '0':{
                            label:'Strongly Disagree',
                            labelStyle: {
                                color: '#69c0ff',
                            }
                        },
                        '20':'',
                        '40':'',
                        '60':'',
                        '80':'',
                        '100':{
                            label:'Strongly Agree',
                        },
}
