### ISSUE TITLE
How can I make the min value of the slider a function?

### ISSUE THREAD

**Issue by ddesroches** [NightCatSama/vue-slider-component#148]
My code computes new ranges for the sliders and I need to update the min value. Today I have:

      <vue-slider
        v-model="parcel.agreed.price"
        @input="updateActualDiscount()"
        :value="parcel.agreed.price"
        :min="min"
        :max="max"
        :interval="0.01"
        :processStyle="processStyle"
        >

A "min" is a fixed function from data():

    module.exports = {
      data() {
        return {
          min: _.round((1 - this.parcel.floorDiscount) * this.parcel.listPrice, 2),
          max: _.round((1 - this.parcel.minDiscount) * this.parcel.listPrice, 2),
        };
      },

'parcel.floorDiscount' can change so I need 'min' to be dynamic. Any suggestions?

I am a Vue novice so please provide an example.

**Comment by NightCatSama** [comment]
The `min` value can be dynamically changed, did not see any problems
