### ISSUE TITLE
I want to call a function when an update is done in the component

### ISSUE THREAD

**Issue by emperorjm** [NightCatSama/vue-slider-component#15]
I am trying to figure out how update a data value when the component value is changed. Other components incorporate a @input or @change or something where I can put in the name of the vue function to be called when a change in value has been made. Is therefore such an option?

**Comment by NightCatSama** [comment]
Do you have a try to call `@callback` ?

**Comment by emperorjm** [comment]
The @input, @callback works but the update function is called multiple times when the slider is moved. I want to be able to only call the function when the user releases the slider. I tried @drag-end but it doesn't seem to trigger the function.

**Comment by NightCatSama** [comment]
`@drag-end` only at the end of the drag and drop, click or directly set value is not triggered.

if you use `vue2`, can use `:lazy="true"` to avoid multiple update.

**Comment by emperorjm** [comment]
@drag-end actually calls the function when the slider is let go. Thanks.

**Comment by NightCatSama** [comment]
you are welcome, Could you tell me solve your problem ?

**Comment by emperorjm** [comment]
I have one more issue. The @callback event works when I click a point on the slider and send the values to the function [349000, 54670000, __ob__: Observer] which I am able to parse and use. Now the @drag-end event is activated when the slider is dragged but it is sending the entire component object as the parameter to the function without the set values. How do I get the @drag-end event to send the same json object like the @callback event [349000, 54670000, __ob__: Observer]?

**Comment by emperorjm** [comment]
This is my slider:
<vue-slider
                                        tooltip="hover"
                                        :min="market_capitalization_slider.min"
                                        :max="market_capitalization_slider.max"
                                        :formatter="formatter"
                                        :lazy="true"
                                        v-model="market_capitalization_slider.market_capitalization"
                                        @drag-end="updateMarketCapitalization"
                                        @callback="updateMarketCapitalization">
                                    </vue-slider>

This is the code use for the update function:
updateMarketCapitalization(newSelected) {
			this.searchForm.market_capitalization = [parseInt(newSelected[0]), parseInt(newSelected[1])];
		},

**Comment by NightCatSama** [comment]
return the component object as the parameter is order to more convenient operation components.

If you only need to value, e.g.
```js
dragEnd (context) {
    console.log(context.val)
}
```

**Comment by NightCatSama** [comment]
You try to modify like this:
```js
updateMarketCapitalization(newSelected) {
    this.searchForm.market_capitalization = newSelected.val;
},
```

**Comment by NightCatSama** [comment]
But I'm a little don't understand you the meaning of this method, is a two-way binding didn't work?

**Comment by emperorjm** [comment]
Two way binding does work but I want to resubmit the form with the updated dated each time the value is changed and the reason I am using update function.

**Comment by NightCatSama** [comment]
Only use `lazy` and `@callback` can't do that?

**Comment by emperorjm** [comment]
The @callback event doesn't get triggered when the slider is dragged. It only get triggered when I click son the slider.

**Comment by emperorjm** [comment]
So you suggestion worked. I had to create two (2) functions:

`updateMarketCapitalization(newSelected) {
			var data = newSelected;
			console.log(newSelected);
			this.searchForm.market_capitalization = [parseInt(data[0]), parseInt(data[1])];
			this.updateTabs();
		},

		updateMarketCapitalization2(newSelected) {
			var data = newSelected.val;
			console.log(newSelected);
			this.searchForm.market_capitalization = [parseInt(data[0]), parseInt(data[1])];
			this.updateTabs();
		},`

updateMarketCapitalization2 is used for @drag-end and updateMarketCapitalization used for @callback. it works now. Thanks again.

**Comment by NightCatSama** [comment]
oops, it's a bug. I will repair as soon as possible, i'm sorry.

**Comment by NightCatSama** [comment]
I't ok, update the components can be normal use.

**Comment by emperorjm** [comment]
Can I update via NPM or will have to update via git?

**Comment by NightCatSama** [comment]
update the component, just like:
```base
npm update vue-slider-component
```
The latest version of v2.1.1
