### ISSUE TITLE
Control with keyboard

### ISSUE THREAD

**Issue by larsenwork** [NightCatSama/vue-slider-component#150]
Any plans on supporting keyboard navigation/control of the slider element? 

Cheers

**Comment by NightCatSama** [comment]
There is currently no such plan:pensive:.

**Comment by larsenwork** [comment]
👌 no stress, I might do a pr at one point. Feel free to close this

**Comment by rickardd** [comment]
I would like suggest keyboard navigation but also consider accessibility for everyone. This would increase the usage audience, e.g government sites and other sites with hight accessibility requirements. 

https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/slider/slider-1.html

**Comment by larsenwork** [comment]
@rickardd yep, that was also my motivation for wanting keyboard support 😄
