### ISSUE TITLE
Is the following possible: 0-100 range, label every 10, interval of 1?

### ISSUE THREAD

**Issue by adamzerner** [NightCatSama/vue-slider-component#153]
I don't see a way to make something like this:

<img width="361" alt="screen shot 2018-02-17 at 12 05 13 pm" src="https://user-images.githubusercontent.com/3144254/36345184-f323942c-13da-11e8-8e7d-ed9848a52f36.png">

Where you could drag the ball in between the labels. The only way to set labels seems to be with the `piecewiseLabel` property, but with that the labels have to appear at every interval.

**Comment by NightCatSama** [comment]
You can try to use the slot, I wrote a simple example, <https://jsfiddle.net/2xy72dod/667/>.

Hope to help you, looking forward to your feedback.

**Comment by adamzerner** [comment]
That makes sense, thank you.

It might be a good idea to add examples for piecewise and label to the documentation for slots in addition to just having tooltips.

**Comment by assembledadam** [comment]
Does this work on the latest vuejs? I'm thinking not. For a start, the "slot-scope" directive appears to no longer work, in favour of "scope".

Also, I get [Vue warn]: Duplicate presence of slot "label" found in the same render tree - this will likely cause render errors.

Using vue 2.4.2 and and vue-slider-component 2.5.8

**Comment by NightCatSama** [comment]
@assembledadam In vue2.5 above, please use `slot-scope` instead of `scope`.

**Comment by assembledadam** [comment]
Sorry, my bad, didn't have the latest vuejs it seems. 

But this does reveal (for anyone checking out this thread wanting to produce similar results), this won't work < vue 2.5.

**Comment by Bambuko1** [comment]
How can I do that if i used data options?
