### ISSUE TITLE
Label collision control

### ISSUE THREAD

**Issue by daviceitor** [NightCatSama/vue-slider-component#154]
In the [formatter example](https://nightcatsama.github.io/vue-slider-component/example/#QuickStart) when the values are close, one overlap the other. Would be nice something like (val1 - val2) label between both of them. Now i'm doing [tricky](https://www.dropbox.com/s/jlfbqaic5pcjnjs/slider_label_collision.mov?dl=0) things with js for this and for collision with the slider edges. Some hope to get it natively in the future??

**Comment by NightCatSama** [comment]
Your implementation is great.

I think if you only consider the issue of overlapping, you can set `tooltipDir`

For example, <https://jsfiddle.net/2xy72dod/661/>
