### ISSUE TITLE
Feature Request: Drag behaviour for range

### ISSUE THREAD

**Issue by benosman** [NightCatSama/vue-slider-component#155]
Would you consider adding a drag behaviour to this component, along the lines of the one in noUiSlider.

When two points are selected, you can drag the range bar and move it to left/right (or up/down) and it keeps the same distance between the two.

See here for a demo:
https://refreshless.com/nouislider/behaviour-option/

**Comment by NightCatSama** [comment]
Thanks for your advice, I added the Fixed property, see the [example](https://nightcatsama.github.io/vue-slider-component/example/#demo8).

Please updated to version 2.5.5, looking forward to your feedback.

**Comment by benosman** [comment]
@NightCatSama  Thanks for looking into this so quickly, much appreciated!

Your new property is close, but I probably didn't explain well enough:

The behaviour I am looking for is that when you drag the dots they work individually as normal, but when you drag the range bar (between the two dots) that moves it up and down the scale like with this fixed property.  (of course the bar would need height to be increased to add a bigger drag zone)

**Comment by NightCatSama** [comment]
Now in the case of `fixed=true`, the range bar can be dragged.

Updated 2.5.6 version:smile:

**Comment by benosman** [comment]
@NightCatSama  - very nice! :)

Some feedback:
- Now the bar can be dragged, it would be cool if there was a hybrid mode where dots could still be moved as usual (non-fixed) but if you drag bar it is fixed
- It would be handy to have a class change on the component to indicate what state the slider is in - e.g. state-drag state-bar-drag.
- Ability to choose cursor for each state (that could be done easily if the class is set).

**Comment by NightCatSama** [comment]
thank you for your feedback.

I added a new `processDragable` property to control whether or not I can drag bar.

And now the component adds the state classes `vue-slider-state-drag` and `vue-slider-state-process-drag` to show if it is dragged.

And the text in Firefox will be selected bug fixes.

Updated 2.5.7 version.

**Comment by benosman** [comment]
@NightCatSama - seems to work perfectly now!

Thank you so much for your quick action on this! :smile: :+1:

**Comment by datadesigncollective** [comment]
Does this still work? I would need this exact functionality and couldn't find anything about it in the docs and and couldn't make it work either.
(Otherwise awesome component, thanks a lot!)
Steve

**Comment by NightCatSama** [comment]
@datadesigncollective 

This is a 2.x version issue, may be inconsistent with some implementations of 3.x.

 you can refer to this example for details:
<https://nightcatsama.github.io/vue-slider-component/#/basics/range?hash=limit-the-distance-between-the-sliders>

**Comment by datadesigncollective** [comment]
I'm using the latest version and thought to ask here because I'm looking for exactly this: 
"The behaviour I am looking for is that when you drag the dots they work individually as normal, but when you drag the range bar (between the two dots) that moves it up and down the scale like with this fixed property. (of course the bar would need height to be increased to add a bigger drag zone)"
Which got an "I added a new processDragable property to control whether or not I can drag bar." reply from you.
If this doesn't exist anymore, let me know and I'll open a new feature request.

**Comment by NightCatSama** [comment]
@datadesigncollective Yes, drag the range bar is not supported now.
