### ISSUE TITLE
Vertical Slider Mouse Control Error under Dynamic Sized Elements

### ISSUE THREAD

**Issue by Parthian** [NightCatSama/vue-slider-component#158]
**Problem**
Vertical slider would snap to :min level on any operation. 
But if clicking or sliding from about half way up the slider the dot would move. Essentially, the mouse would have to be offset to work.

Multiple bugs/reactive issues muddled things for a while (got caught by the v-show thing). Also, refreshes caused by opening Web Dev Tools would sometimes 'fix' the problem. As would using v-if set to true via a radio button. OR sometimes the first use would be fine until a refresh of the browser. 

Eventually, put a new slider at the top of my complex page. Worked fine. Then noticed the height of the buggy offset was similar to the height of a Tabbed Item currently active. Penny dropped. My vertical slider is underneath a Vuetify Tab Element, the height of which changes depending on the tab selected.

**Bug?**
Looks like a dynamically sized element like tab-items confuses the vertical height. Maybe a problem in Vuetify but suspect not.
```
  <v-layout row>
    <v-flex xs12 style="height: 145px;">
     <v-tabs dark grow color="blue" height="40">
... tab stuff ....
then another component with layout flex etc 
      <vue-slider v-show="productType === 'digital'" :min="10" :max="5000" :lazy="true" ref="sliderV" :height="vHeight" :width="vWidth" v-model="vmSliderHeight" :direction="'vertical'"></vue-slider>
```

Adding the layout/flex with style="height: 145px;"  fixes the issue. Class would be neater. 

Possibly happens with other elements where final height isn't known until perhaps render time??? Tables etc? Maybe a Vuetify thing.

**Comment by NightCatSama** [comment]
Use the component's `show` property to replace `v-show` to try to work properly.

I guess the reason for this: <https://github.com/NightCatSama/vue-slider-component#exceptions>

**Comment by Parthian** [comment]
That was quick. Yes, had got around the v-show issue using the nexttick/refresh approach. So just tried :show in place of v-show. And removed my height:145. Slider appeared with appropriate truethiness but bug back. Note, I also used a horizontal slider also under the tab. It occasionally would fail but much more reliable. 

Suspect it is the same basic issue but the solutions you have don't work in this circumstance. 
Perhaps mention my solution of ensuring fixed height elements above a slider.

**Comment by NightCatSama** [comment]
Is it possible that the component's style is affected by the height of the outside world?

**Comment by Parthian** [comment]
Maybe.
 ```
   <v-layout row wrap class="mt-0" v-if="!loading">
    <v-flex sm5>
      <v-flex sm12>
          <position-selector></position-selector>
      </v-flex>
      <v-flex sm12>
          <mapping></mapping>
      </v-flex>
    </v-flex>
```
The Position Selector component contains nothing more than a Vuetify Tab. This changed its height as each tab item was selected.
The mapping component contains the snippet of code shown in original post. A map and your vertical slider component. 
No heights set on anything explicitly. 
So without my CSS to force the height the entire mapping component would move up and down. Taking the vertical slider with it. 
This appears to confuse the slider pretty much as per your known fault. 
Once the code in position-selector has a fixed height the bug in my mapping component goes away. 
Of course, is Vuetify a factor or not? I think not - particularly as a simple CSS height made the issue go away.

**Comment by NightCatSama** [comment]
You try to reach the following two points:

1. Set the `width` and `height` properties of the component, because the default is auto, there is an error in the vertical component.

2. After switching the label to call the `refresh` method, and the best thing to do is to use a tab component's event, since the tab's transition animation also affects the component's initialization.

**Comment by Parthian** [comment]
Just to be clear. I have worked around the problem by setting the height of my <position-selector> component (or rather the Flex box containing the dynamic sized element). I've made the position selector height big enough for all of my tabs. Ideally, this is a hack as I shouldn't change another component to fix a problem elsewhere. I'm not sure if that covers your suggestion 1.

Not sure I understand 2. And note that it isn't just the different heights of the various tabs. Any height of a tab **content** is enough. 
E.g.
https://vuetifyjs.com/en/components/tabs#example-fixed-tabs
This fixed tab is just an example without content. So no height to worry about. 
Whereas:
https://vuetifyjs.com/en/components/tabs#example-content
The content exists here. With lorem etc. The height of the white area with lorem... would be enough to break a vertical slider underneath. 
Which I think is what you are getting at with 2. Your slider is initialized before the browser knows what height the Content of the tab will be. Even 1 pixel of tab content height would presumably break the vertical slider. But I don't want to rely on events etc in the position-selector component other than fixing its height. 

How about leaving this for now. I'm sure when you have a fix for the exception you've already found my specific problem will disappear too. 
Great component. It's just an oddity of my design that has uncovered this issue.
Cheers

**Comment by NightCatSama** [comment]
I am ashamed because I can not fix this exception. 

I can not know what kind of environment the slider component is initialized because I can not monitor this behavior and I can only initialize it with the hook `mounted` method in the vue. That is the reason for this exception.

**Comment by rnenjoy** [comment]
I had the same problem when having the sliders inside a vuetify flexbox grid. I think you guys are right that the problem is because it is mounted before it knows the dimensions of the box. Luckily my problem solved itself, cause I wont show it until you press a button. But if i show it right from the start, the slider shows right, but when clicking it is completely off.
