### ISSUE TITLE
Doesn't work when inside of a Bootstrap modal

### ISSUE THREAD

**Issue by adamzerner** [NightCatSama/vue-slider-component#159]
When inside of a Bootstrap modal, the slider doesn't work. See https://jsfiddle.net/ovw8hzLw/.

**Comment by NightCatSama** [comment]
This is a known anomaly.

There are solutions in the document. 
<https://github.com/NightCatSama/vue-slider-component#exceptions>

This is one of the ways you can refer to <https://jsfiddle.net/ovw8hzLw/5/>.

**Comment by adamzerner** [comment]
I see. Thanks.

**Comment by janswist** [comment]
It doesn't work for me. Using Bootstrap 4.1 - tried each method from js fiddle.

**Comment by NiltonMorais** [comment]
It doesn't work for me. Using Bootstrap 4.1 - tried each method from js fiddle.
Range is enabled, but value not set default v-model

**Comment by tokomeno** [comment]
Can someone explain why this is not working?
