### ISSUE TITLE
Disabling start animation

### ISSUE THREAD

**Issue by FKobus** [NightCatSama/vue-slider-component#16]
Is there a way to disable the startup animation? I added the slider to a component that can toggle visibility, but everytime when open/close the component the slider is animating. The max bullet moves to it's position.

I couldn't find it in the docs, that's why I'm asking it here.

**Comment by NightCatSama** [comment]
Thank you for the issue, I will be resolved as soon as possible.

**Comment by NightCatSama** [comment]
Well, now no longer animated when initialized.

I pushed a new version in npm, you can try to update to the latest version `@2.1.2`.

**Comment by FKobus** [comment]
@NightCatSama Sweet! Works like a charm now!
