### ISSUE TITLE
Vue Slider Component OPTIONS not working

### ISSUE THREAD

**Issue by akinhwan** [NightCatSama/vue-slider-component#160]
Hello am I missing something with my vue-slider?

I have a separate single file component with the following options. However the only thing that is being read is the value option.

`<script>
import vueSlider from 'vue-slider-component'

export default {
  name: 'slider',
  data () {
    return {
        value: 33,
        width: "auto",
        height: 6,
        direction: "horizontal",
        dotSize: 20,
        eventType: "auto",
        min: 0,
        max: 100,
        interval: 12,
        debug: false,
        disabled: false,
        show: true,
        realTime: false,
        tooltip: "hover",
        clickable: true,
        tooltipDir: "top",
        piecewise: true,
        lazy: false,
        useKeyboard: false,
        reverse: false,
        speed: 0.5,
        formatter: null,
        focusStyle: null,
        bgStyle: null,
        sliderStyle: null,
        tooltipStyle: null,
        processStyle: {
            "backgroundCOlor": "#999"
        },
        piecewiseStyle: null
    }
  },
  components:{
      vueSlider
  },`

**Comment by akinhwan** [comment]
Nevermind I found that in the live example on JSFiddle i need to bind to :options. This was not clear upon initial quick start documentation or the github page.

**Comment by NightCatSama** [comment]
This is the basic usage of the vue framework. (Related issuse #152 )

**Comment by NightCatSama** [comment]
`v-bind="options"` and `:options` are different, `:options` is equivalent to `v-bind:options`.
