### ISSUE TITLE
Using Functions, setValue Method?

### ISSUE THREAD

**Issue by akinhwan** [NightCatSama/vue-slider-component#161]
I saw that there is setValue in the Functions section of the API, and that there are buttons for each of the demos that setValue and getIndex etc. However there are no examples of how these are called or written in a single file component. Help?

**Comment by NightCatSama** [comment]
Use `ref` to call subcomponent methods.

I update the live demo <https://jsfiddle.net/2xy72dod/1240/>.

If you use the `v-model` binding value, set the value directly on it, do not need to call `setValue`.

**Comment by akinhwan** [comment]
Thank you @NightCatSama you can close this issue!
