### ISSUE TITLE
Disabling bookends (first and last) piecewise Index/Value

### ISSUE THREAD

**Issue by akinhwan** [NightCatSama/vue-slider-component#162]
![selection_034](https://user-images.githubusercontent.com/10124722/37164041-48252a26-22c7-11e8-978b-12a0df05e59e.png)
In the above image, I have styled the slider to act as a timeline. I have included in my data array, empty strings every other time label. I found that creating an empty string at the beginning and end of the data array allowed me to give a good margin, and also since there are no piecewise styling for the first and last I noticed. 

So my question is, how would I disable someone from ever going to the first or last index, since they are not really valid,  only placeholders.

Thanks once again for your help!

**Comment by NightCatSama** [comment]
Sorry, there is currently no direct way to ban the first and last index.

You can try to `watch`  the value or use the component's callback method to determine if the current index is the first or last value, then go to manually set the value.

Of course, the best way is to delete the first and last values.

**Comment by akinhwan** [comment]
Thank you again for your quick response, and recommendation.
Yes I could always delete first and last, but piecewise marks are not created for first and last data points. And I am using the piecewise markers styled as vertical lines as my timeline
