### ISSUE TITLE
Making hit box (click area) bigger

### ISSUE THREAD

**Issue by akinhwan** [NightCatSama/vue-slider-component#163]
How would I enable the user to click in a more generous detectable zone. As of now the :vue-slider::after seems to be the height of the track in which it is possible to click and move the slider dot.

**Comment by NightCatSama** [comment]
The most straightforward way is to modify the style of the component.

like it:
```html
<vue-slider :style="{ paddingTop: '20px', paddingBottom: '20px'}"></vue-slider>
```
