### ISSUE TITLE
Vue-slider-component installs git hooks

### ISSUE THREAD

**Issue by lukadefar** [NightCatSama/vue-slider-component#168]
Starting with version 2.5.9, the package installs git pre-commit-msg hooks,
in a project that is using this vue-slider-component as a (dev-)dependency.

I have fixed the version to 2.5.8 which doesn't suffer from this issue, but this should be resolved
as it should not alter the git hooks of a repo where the package is just a dependancy.

**Comment by NightCatSama** [comment]
Sorry, this is my negligence, 2.6.0 has been fixed.
