### ISSUE TITLE
Infinite loop when min or max is not an integer

### ISSUE THREAD

**Issue by NicolleLouis** [NightCatSama/vue-slider-component#169]
**Issue:** 
When the min or max is equal to undefined, the slider doesn't throw an error but it creates an infinite loop with the value changing forever (I had a callback with a watch on 'value'). This slows the bug resolution.

**Solution:** 
- do not send undefined instead of an integer
- in the mounted function if the props min or max or undefined I output the error and destroy the slider.

Thanks for this component :)

**Comment by NightCatSama** [comment]
The min and max attributes are only allowed to pass numbers. Maybe you can add more judgments when passing variables.
