### ISSUE TITLE
插件在ipad端，滑动的时候有延迟，感觉很卡，应该调试哪个参数？

### ISSUE THREAD

**Issue by ss7247** [NightCatSama/vue-slider-component#170]
插件在ipad端，滑动的时候有延迟，感觉很卡，应该调试哪个参数？

在PC端调试时非常流畅，在移动端特别是 ipad的时候有明显的延迟感，导致的结果就是卡

**Comment by NightCatSama** [comment]
你可以试试打开文档的 [example](https://nightcatsama.github.io/vue-slider-component/example/) 看看会不会卡

如果会的话那应该是机能问题了，无法解决

**Comment by ss7247** [comment]
@NightCatSama   我就是用ipad 访问过 https://nightcatsama.github.io/vue-slider-component/example/ 了，也是感觉到卡，所以才来提

**Comment by NightCatSama** [comment]
那应该没办法了，可能是一直动态设置滑块的 transform 和 进度条的 width，移动端处理起来会卡吧

**Comment by zjxuzhj** [comment]
移动端使用存在卡顿和多个同时使用时存在点击失效情况
