### ISSUE TITLE
Increasing the dot size in a responsive way

### ISSUE THREAD

**Issue by adamzerner** [NightCatSama/vue-slider-component#173]
I'd like to increase the size of the dot at certain screen widths:

```
@media (max-width: 600px) {
  .vue-slider-component .vue-slider .vue-slider-dot {
    width: 25px !important;
    height: 25px !important;
  }
}
```
1. This approach increases the size of the dot, but the actual slider doesn't adjust and it isn't vertically centered properly:

<img width="226" alt="screen shot 2018-04-02 at 12 04 49 pm" src="https://user-images.githubusercontent.com/3144254/38211050-1334a03e-366e-11e8-85a6-8e82c47657ca.png">

2. It seems that `!important` is required.

Is there a better way to do this?

Note: If you only need to respond to mobile vs. non-mobile, https://stackoverflow.com/questions/3514784/what-is-the-best-way-to-detect-a-mobile-device-in-jquery works.

**Comment by borbah** [comment]
I have the same problem! That's funny that two guys with the same name encountered the same issue at the same time xD Is there a way to style that dot with media queries?

**Comment by NightCatSama** [comment]
You should use the component's `dotSize` property to control the size of the slider.

example:
```
<vue-slider :dot-size="window.innerWidth < 600 ? 25 : 16"></vue-slider>
```

Of course, if you need to consider the screen shrinking, you may also need to listen for the resize event.

**Comment by adamzerner** [comment]
Ah, I see, thanks.
