### ISSUE TITLE
lazy slider does not fire events when dragged to the borders

### ISSUE THREAD

**Issue by jpkontreras** [NightCatSama/vue-slider-component#174]
thats really is. 
When lazy is selected  if you play with it for a while you will see that 
events are not being triggered if controls are dragged to the borders or initial position

**Comment by NightCatSama** [comment]
What is the event? Can you reproduce the bug in [jsfiddle](https://jsfiddle.net/2xy72dod/1240/)?

**Comment by erichard** [comment]
I'm able to reproduce this with the callback event. No event fired when I drag to the right limit.

**Comment by jaapfaes** [comment]
I've encountered the same problem. This happens when you drag the slider back to its initial value in lazy mode. Which is usually 0 (so at the border of the slider). 
I've created a fiddle that illustrates the problem: https://jsfiddle.net/2xy72dod/9600

**Comment by NightCatSama** [comment]
@jaapfaes The `callback` is not triggered when the updated value equals the current value.

So the best component's value is updated synchronously.
