### ISSUE TITLE
Click event on slider component

### ISSUE THREAD

**Issue by matewiszt** [NightCatSama/vue-slider-component#175]
We have the drag-end event on the slider component but what if I want to apply the same method to the click event (when a value is clicked on the slider)? There is no onclick event handler in the API...

**Comment by NightCatSama** [comment]
Yes, you can use the `@click.native` if you just listen for component click events.

**Comment by NightCatSama** [comment]
If you need to click on the callback event after the trigger value is changed, I will consider adding it later.

It's a bit busy recently, I'm really sorry.

**Comment by matewiszt** [comment]
Don't say sorry, I like your component ;)
I used the `@click.native`. For now, it is OK but later I want to replace it because it is triggered also on drag. If you want, I will send a PR so it can be included in the project.

**Comment by NightCatSama** [comment]
@matewiszt If you can submit pr, it would be great :smile:.

**Comment by Chaitali1223** [comment]
You can use a callback like this
 <vue-slider ref="slider" v-model="value" v-bind="options" @callback="log"></vue-slider>
