### ISSUE TITLE
How to segment, but do not automatically slide to a node?

### ISSUE THREAD

**Issue by qingyun1029** [NightCatSama/vue-slider-component#176]
What I need to achieve now is the integration of the two effects.[All effects](https://nightcatsama.github.io/vue-slider-component/example/#QuickStart)——"Custom Label" and "Lazy",

**The former**: Although there are many nodes, it can click anywhere, and it will not automatically slide to a node.
**The latter**: there are many nodes on the line

To sum up: I hope that a line can be divided into a few points（For example, 5 nodes.  the minimum value is 0; the maximum value is 100.）, and then I can click anywhere on the line and do not automatically slide to a node.

I need your help. Thank you very much.

**Comment by NightCatSama** [comment]
Is this effect? 

<https://nightcatsama.github.io/vue-slider-component/example/#demo8>

**Comment by qingyun1029** [comment]
@NightCatSama 
There is also a problem, I have encountered some problems with vue 2.5 version to achieve this effect（**Custom Label**）, is there an online example? E.g: [Live demo](https://jsfiddle.net/2xy72dod/1240/)

**Comment by NightCatSama** [comment]
I wrote an live demo and hope this is what you need.

<https://jsfiddle.net/2xy72dod/2450/>

**Comment by qingyun1029** [comment]
@NightCatSama Thank you very much！
 but it is a little bit worse than I need. I hope that the split point is not on the line, but on the line, similar to the **Lazy** effect

**Comment by NightCatSama** [comment]
You can modify the style yourself.

If it is a value problem, it can also be achieved through a Watcher.

**Comment by qingyun1029** [comment]
@NightCatSama Thank you very much, I tried to modify the code first, hoping to implement it, thanks again !

**Comment by qingyun1029** [comment]
@NightCatSama Great, I did what I wanted.
This plugin is very easy to use, very flexible, and well-expanded. Although I don't know much about the internal implementation, it's really easy to use. Thanks again!

I will continue to study this plug-in to learn something about vue that I don't know
