### ISSUE TITLE
Slider width occasionally renders too wide in Safari/Webkit

### ISSUE THREAD

**Issue by noahlh** [NightCatSama/vue-slider-component#178]
Apologies in advance if I've done something wrong, but I'm wondering if I've found a bug.  Everything works beautifully on Chrome, but on every 3rd or 4th page load in Safari/Webkit, the slider doesn't seem to respect the `width` option (currently set to 100% of its container) and renders way too wide.

I've tried adding in a `.refresh()` on `mounted`, but that doesn't seem to work.  Attached are two screenshots showing the rendering issues (correct and incorrect).  Any thoughts or pointers would be appreciated!

<img width="1152" alt="screen shot 2018-04-15 at 9 39 06 pm" src="https://user-images.githubusercontent.com/113276/38790424-10ffd0b2-40f6-11e8-993b-8c8499c479c5.png">

<img width="1268" alt="screen shot 2018-04-15 at 9 39 31 pm" src="https://user-images.githubusercontent.com/113276/38790427-138c6930-40f6-11e8-896a-7d870657a681.png">

**Comment by NightCatSama** [comment]
You can call the refresh method after switching pages.

```js
this.switchPage()
```

**Comment by noahlh** [comment]
Thanks!  Sorry, I should be a bit more clear -- I'm not actually switching pages, this happens on initial page load (but only occasionally, i.e. every 3rd or 4th time the page is loaded initially).

I was guessing a refresh was needed - cool.  What's the optimal time to call after initial load to assure no issues?  I've tried adding it under a `mounted` hook, but it still seems too soon.  Is there another event that fires after `mounted`? (something like the equivalent of jQuery's `.ready()`)?

**Comment by NightCatSama** [comment]
You should make sure to call the `refresh` method after the container is fully loaded.

**Comment by noahlh** [comment]
Ok cool - will make some changes and report back shortly (and close the issue!)

**Comment by andreud** [comment]
@noahlh im having your exact same issue, did you get around it?

**Comment by noahlh** [comment]
oh crap I realized I did the bad-contributor thing and never followed-up here.  I don't remember if this solved the issue -- I have a feeling we isolated it to being a Safari bug.

**Comment by andreud** [comment]
I got aorund it calling $refs.mySlider.refresh() inside a setTimeout()

**Comment by NightCatSama** [comment]
It is no longer necessary to call refresh in the latest version.
