### ISSUE TITLE
Avoid cursor to cross each other

### ISSUE THREAD

**Issue by ElMacx** [NightCatSama/vue-slider-component#179]
Hey,

I'm currently using your slider and I wanted to know if it's possible to avoid the cursor to cross each other. I mean when you are moving one to the other one, when you're at the same value, it change cursor to keep sliding.
Is there a way to block the cursor when I reach the value of the other cursor ?

Thank you!

**Comment by NightCatSama** [comment]
There is currently no way to do it directly. 😢

**Comment by NightCatSama** [comment]
In the latest version, you can do this with the disabled attribute.

<https://jsfiddle.net/NightCatSama/2xy72dod/6860/>
