### ISSUE TITLE
Problem when component is initiated with display: none

### ISSUE THREAD

**Issue by adrianolobo** [NightCatSama/vue-slider-component#18]
Hi, first of all thank you for the nice slider component :).

There is a problem when the slider is initiated with ```display:none```, as shown in the attached image. When the slider appears it cannot be interacted.

I found a quick fix, when the window is resized the component works again, so I have to manually call ```window.dispatchEvent(new Event('resize'))```

![slider issue](https://cloud.githubusercontent.com/assets/13997867/22880923/447c5a12-f1cb-11e6-862f-353121bb9caf.png)

**Comment by NightCatSama** [comment]
Yes, there is such a problem. I have that solution at the bottom of the document.

**Comment by adrianolobo** [comment]
Oh, sorry, didn't saw that.
I will use ```this.$refs.slider.refresh()``` instead of ``` indow.dispatchEvent(new Event('resize')) ```.

**Comment by NightCatSama** [comment]
Thank you for your support.

**Comment by mathiasleroy** [comment]
I can't access the ref of my vue-slider. Is there another way to use the refesh() ?  

In the meantime I'm going to use the window.dispatchEvent(new Event('resize')).
