### ISSUE TITLE
[FR] More handlers

### ISSUE THREAD

**Issue by undavide** [NightCatSama/vue-slider-component#181]
Hi,
any chance in the future to support >2 handlers? I run into your repository while looking for a Vue component to make a range slider with _falloff_, something like:

![](http://i.giphy.com/l46Cs36c9HrHMExoc.gif)

Thanks!

**Comment by NightCatSama** [comment]
Sorry, it's hard to add this feature to the current architecture, so I won't add this feature recently.

**Comment by NightCatSama** [comment]
Support for more handles in the latest version.
