### ISSUE TITLE
The value of the slider is 0, the minimum value is 1, the value of this slider can not be less than the minimum value

### ISSUE THREAD

**Issue by goors** [NightCatSama/vue-slider-component#183]
My initial value is not 0 but 1 same as min value. So i dont get this.

**Comment by NightCatSama** [comment]
I didn't understand what problem you are having

**Comment by goors** [comment]
I am getting error that is saying: 

`The value of the slider is 0, the minimum value is 1, the value of this slider can not be less than the minimum value`

That is not true. Value of slider is 1 and min value is 1 and slider is saying that my value is 0.

**Comment by NightCatSama** [comment]
Can you show your code?

**Comment by NightCatSama** [comment]
Where `shared_props.surface.total` is defined? It is the value you really passed to the component

**Comment by goors** [comment]
Yes that is 1. From the store by default.

**Comment by NightCatSama** [comment]
I think it's possible that your value is asynchronously assigned.

**Comment by goors** [comment]
I was unable to resolve this. Still an issue.

Funny thing is when you set :min=50 and :value=100 it shows that value is 50 and also rewrites model to 50 (by default model value is 100)

**Comment by goors** [comment]
So, it is like :min is rewriting model value!!!

**Comment by NightCatSama** [comment]
When the value is less than the minimum value, the value is set to the minimum value.

Maybe you can try to restore it. <https://jsfiddle.net/2xy72dod/1240/>

**Comment by goors** [comment]
It is not less ... 

model value is 100 and min value is 50 and nodel is rest to 50.

**Comment by goors** [comment]
how to build your project?
i am getting this error:

```
ERROR in ./src/vue2-slider.vue
Module parse failed: /myproject/node_modules/vue-slider-component/src/vue2-slider.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
|   <div
|     ref="wrap"
 @ ./src/index.js 1:16-40
```

i did npm install and so on.

**Comment by goors** [comment]
Anyway, for some reason if i put model like this:

`v-model="some.netsted.thing.model" `

i am getting that min value error.

but when i do:

```
data(){
  return{
    some_model: some.netsted.thing.model
  }
}
```

and then `v-model="some_model" ` error is gone.

**Comment by NightCatSama** [comment]
The value of computed cannot be set. The value of store cannot be directly set. It should be modified by dispatch action or commit mutation.

You can not use `v-model`, use `:value` and `@callback` to set the value of store.

example: <https://jsfiddle.net/2xy72dod/2857/>
