### ISSUE TITLE
Dynamic Interval Gaps

### ISSUE THREAD

**Issue by sunnyboi21** [NightCatSama/vue-slider-component#184]
I was wondering if you could build in auto interval levels.
For example, in this jsfiddle, https://jsfiddle.net/2xy72dod/2846/
I need the gap between 3 and 10 to be wider by 7 spaces where as the gap between 1 and 3 should be 2 spaces. And I don't want to include values between 3 - 10.

**Comment by KhalitovAdel** [comment]
Yes it will cool. I need this option too

> Мне было интересно, если вы могли бы встроить автоматические интервальные уровни. 
> Например, в этом jsfiddle, [https://jsfiddle.net/2xy72dod/2846/,](https://jsfiddle.net/2xy72dod/2846/)
> мне нужно, чтобы промежуток между 3 и 10 был больше на 7 пробелов, тогда как промежуток между 1 и 3 должен составлять 2 пробела. И я не хочу включать значения от 3 до 10.

**Comment by NightCatSama** [comment]
This feature is supported in the latest version.

<https://nightcatsama.github.io/vue-slider-component/#/basics/marks>
