### ISSUE TITLE
Disable individual slider on multi-slider

### ISSUE THREAD

**Issue by davidAlittle** [NightCatSama/vue-slider-component#186]
If there are two points on a slider (a range), I'd like one to be read-only (but still data-bound).

The use-case is for a showing both `actual` and `requested` values of a prop that can't change instantaneously: so when you look at the slider, it appears to have just 1 point. As you drag away, you see that there is a second that can't be edited that shows the current (or `actual` ) value. After you drop the draggable end, which sends a `requested` value to the system, the `actual` moves to reflect the actual in the system (this is a mechanical system- so, say, for example, I'm dragging to change speed. the machine can't change speed instantly, so there is some time while the machine gets to the `requested` speed).

**Comment by NightCatSama** [comment]
In the latest version, you can set the disabled property array type.
