### ISSUE TITLE
VueSlider Error : the value of this slider can not be greater than the maximum value

### ISSUE THREAD

**Issue by killuaz93** [NightCatSama/vue-slider-component#188]
I have some problem, when I update parameter max in component and then setValue greater than last maximum value, for example : 

Step : 
1. Min : 0, Max : 100
2. Update Max : 120 then call refresh() function
3. setValue ([0, 110]) => return error

**Error log :** 
[VueSlider error]: The value of the slider is 0,110, the maximum value is 100, the value of this slider can not be greater than the maximum value
printError @ index.js?1831:1
i @ index.js?1831:1
(anonymous) @ index.js?1831:1
limitValue @ index.js?1831:1
setValue @ index.js?1831:1
...

I think, the cause is setValue called before refresh function done.
Can I use some callback function in refresh function, or there is another way to solve this?

**Comment by NightCatSama** [comment]
I tried it is normal, can you reproduce the problem?

<https://jsfiddle.net/NightCatSama/2xy72dod/2864/>

**Comment by killuaz93** [comment]
Thank you for quick response, this is updated fiddle :
https://jsfiddle.net/2xy72dod/2866/

When, we click setUpdateThenSet button, first click value = [0, 100], second click value = [0, 110]

**Comment by NightCatSama** [comment]
This may be because `watch` is not triggered immediately. It can be solved using `nextTick`.

<https://jsfiddle.net/NightCatSama/2xy72dod/2867/>

**Comment by killuaz93** [comment]
It solved, thanks for you to mention it :))
