### ISSUE TITLE
progress color

### ISSUE THREAD

**Issue by lam-bun** [NightCatSama/vue-slider-component#189]
Thanks for your library.
How can I replace progress color with my own image(1px)

**Comment by NightCatSama** [comment]
You can try setting `backgroundImage` in `progress-style` prop.

**Comment by lam-bun** [comment]
Thanks, I will try.
I found that there are only color in slider, can I replace my own image, like pretty-slider, how can I replace the color dot with Image

**Comment by NightCatSama** [comment]
You can use various `*-style` properties to set the background image.
