### ISSUE TITLE
Error while switching between range and single slider

### ISSUE THREAD

**Issue by mlanin** [NightCatSama/vue-slider-component#19]
Problem is, when you'll try to manually change value from ['0','0'] value to '0', seems like `slider` property will be computed earlier then template will rerender and `refs` will not appear in $refs var, so `slider` will be set to undefined :(

I tried many ways but didn't find a working solution (except rerendering whole slider). May be you have one?

**Comment by NightCatSama** [comment]
I publish a new version, you can update the component to see if the normal switch.

**Comment by mlanin** [comment]
@NightCatSama now it works like a charm! ) Thank you!
