### ISSUE TITLE
'useKeyboard' not working when 'formatter' was set or 'interval' is not 1

### ISSUE THREAD

**Issue by xqxian** [NightCatSama/vue-slider-component#191]
Thanks for your great work! It's a wonderful plugin but I found the 'useKeyboard' feature not working if a formatter (e.g., 'formatter={value}%') was set or 'interval' is not equal to 1 (e.g., 'interval=2') when using in 'range' mode (giving an array as value). Can you have a look at it? This is a very useful feature to control the values accurately. Thanks!

**Comment by NightCatSama** [comment]
I failed to test the bug: <https://jsfiddle.net/2xy72dod/2923/>

Can you reproduce it and talk about it in detail?

**Comment by xqxian** [comment]
Sure, see: [https://jsfiddle.net/Alexu/tauo7gr1/2/](url)

**Comment by NightCatSama** [comment]
Thank you for your feedback.

This bug has been fixed in version 2.6.3.

**Comment by xqxian** [comment]
@NightCatSama Thanks for your work! But there is still a little problem in the latest version:
![snipaste_20180526_180443](https://user-images.githubusercontent.com/21199814/40574992-585e0e22-610f-11e8-8cdc-1747cce477fa.png)
If 'interval' is set to '0.01', sometimes there are too many decimal places...

**Comment by NightCatSama** [comment]
@xqxian It's fixed. update to version`2.7.1`

**Comment by xqxian** [comment]
Great job!
