### ISSUE TITLE
formatter - using function examples request

### ISSUE THREAD

**Issue by SMen1** [NightCatSama/vue-slider-component#195]
Thank you for your excellent component and hard work!

I am requesting help or examples regarding the tooltip formatter.

In your documentation you refer to this:

formatter: (v) => `¥${v}`

but I can see no advantage over 

formatter='¥{value}'

which is documented in the examples while I cannot find an example using =>.

I am expecting to be able to pass an additional argument / call a method but I am having difficulties.

I am adding duration to start time to give me "from time to time" in the tooltip.

This code below works fine but I doubt very much that it is correct practice, but being new to Vue and ES6  after many attempts this is what I have fallen back on:

formatter: (v) => {
        let duration = document.getElementById("duration").value;
        let v2 = v + +duration
        let h = Math.floor(v / 60);
        let m = v % 60;
        h = h < 10 ? '0' + h : h;
        m = m < 10 ? '0' + m : m;
        let h2 = Math.floor(v2 / 60);
        let m2 = v2 % 60;
        h2 = h2 < 10 ? '0' + h2 : h2;
        m2 = m2 < 10 ? '0' + m2 : m2;

        return `From ${h}:${m} to ${h2}:${m2}`
        }

I only want one slider, not two, and for performance I really need to use lazy - doing this in the tooltip seems the best approach performance wise.

I also run a variant of the above as a method like so:

convertMinsToHrsMins(mins) {
      let h = Math.floor(mins / 60);
      let m = mins % 60;
      h = h < 10 ? '0' + h : h;
      m = m < 10 ? '0' + m : m;
      return `${h}:${m}`;
    },

but cannot call it. I must be missing something pretty obvious, so apologies. 

Any guidance very much appreciated.

**Comment by NightCatSama** [comment]
After I tested your method is no problem.

<https://jsfiddle.net/2xy72dod/2928/>

And the advantages of string types are only brief.

**Comment by SMen1** [comment]
Thank you very much again... 

I have experimented some more thanks to your fiddle, and in fact the formatter works exactly as I expected so long as I return the data function as per your fiddle.

data () {
    return {
    value: 1,
    duration: 60
...

and not when just using the cdn and

 data: {
    value: 1,
    duration: 60
  }

which I think was my mistake.

So long as I return the data then everything that I had been trying works as expected e.g.: 

var app = new Vue({
  el: '#app',
  data () {
    return {
    	value: 200,
        duration: 60,
      options: {
        min: 0,
        max: 1380,
        tooltip: 'always',
        tooltipDir: 'top',
        formatter: (v) => `From ${this.convertMinsToHrsMins(v)} to ${this.convertMinsToHrsMins(v + this.duration)}`
      }
    }
  },
  methods: {
  	convertMinsToHrsMins(mins) {
      let h = Math.floor(mins / 60);
      let m = mins % 60;
      h = h < 10 ? '0' + h : h;
      m = m < 10 ? '0' + m : m;
      return `${h}:${m}`;
    }
  },
  mounted () {
  },
  components: {
    'vueSlider': window[ 'vue-slider-component' ],
  }
})


My only puzzle then, is should I in fact be able to use the formatter when just using the CDN and simply 
data: {
    value: 1,
    duration: 60
  }
options: {
        min: 0,
        max: 1380,
        tooltip: 'always',
        tooltipDir: 'top',
        formatter: (v) => `From ${this.convertMinsToHrsMins(v)} to ${this.convertMinsToHrsMins(v + this.duration)}`
      }

or is this simply not possible for reasons I have yet to grasp?

At any rate, thank you for your rapid response - it has been a great help.

**Comment by NightCatSama** [comment]
For the type of data you can refer to the vue official [documentation](https://vuejs.org/v2/api/#data).

> When defining a component, data must be declared as a function that returns the initial data object, because there will be many instances created using the same definition. If we use a plain object for data, that same object will be shared by reference across all instances created! By providing a data function, every time a new instance is created we can call it to return a fresh copy of the initial data.

**Comment by SMen1** [comment]
Thank you. :-) 

I needed the heads up, as I just 'dived in' using the CDN. You have been a great help.

**Comment by SoundousBahri** [comment]
Please update the documentation
the prop to pass is "formatter" not "tooltip-formatter" as it says in the documentation

**Comment by NightCatSama** [comment]
@SoundousBahri 

This issue is version 2.0, `tooltip-formatter` is version 3.x.
