### ISSUE TITLE
dot Animation

### ISSUE THREAD

**Issue by akinhwan** [NightCatSama/vue-slider-component#196]
I added a css animation to the `.vue-slider-component .vue-slider-dot` selector. And it is disabling me from being able to use the slider dot (broke main functionality)
Is it possible to add an animation while still being able to use the dot to slide around?

**Comment by NightCatSama** [comment]
The `dot` sliding animation is using transition, you can set the `transition-timing-function` of `dot` and `process`.

If you want to be more complex, you may not be able to achieve.
