### ISSUE TITLE
vue slider not working probably if the container position is absolute 

### ISSUE THREAD

**Issue by abusalameh** [NightCatSama/vue-slider-component#197]
I tried to make like a drawer panel that slides from left to right and added vue slider to it. 
when I slide the container using css from 
```left:0``` to ```left: 40%``` 
the slider only slides to max value or to min value

**Comment by NightCatSama** [comment]
you can refer to the [exception](https://github.com/NightCatSama/vue-slider-component#exceptions) in the document.
