### ISSUE TITLE
label-style

### ISSUE THREAD

**Issue by huangyq199205** [NightCatSama/vue-slider-component#198]
![1](https://user-images.githubusercontent.com/28775848/41278727-21cc7b0e-6e5d-11e8-8f36-ab07cb2aceff.png)
大佬，先谢谢你提供的一个很棒的组件！如果选择区间的时候，上面的 label一直都是这样展示就好了，如果可以这样设置的话？请教一下改怎样配置~

**Comment by NightCatSama** [comment]
现在不支持这种设置哦

**Comment by huangyq199205** [comment]
是不是以后可以支持一下啊。

**Comment by huangyq199205** [comment]
@NightCatSama  是不是以后可以支持一下啊。

**Comment by NightCatSama** [comment]
@huangyq199205 应该不会吧 233
