### ISSUE TITLE
Slider dot bug

### ISSUE THREAD

**Issue by pi0neer** [NightCatSama/vue-slider-component#199]
Vertical slider's dot goes down on click sometmies and then i can't move it anymore, sometimes after refreshing working fine, but i changed nothing. Does anyone has same issue?Please, help

**Comment by pi0neer** [comment]
There is no error occurring, I'm using vuteify, so maybe there is something with that, here's my parameters: `scrollParams: {
          value: 15,
          width: 4,
          height: 400,
          dotSize: 22,
          eventType: "auto",
          min: 0,
          max: 100,
          interval: 1,
          disabled: false,
          show: true,
          tooltip: "false",
          piecewise: false,
          processStyle: {
            backgroundColor: '#f55753',
            width: '8px'
          },
          sliderStyle: {
            marginLeft: '2px',
            border: '2px solid #f55753'
          },
          bgStyle: {
            width: '8px'
          },
          style: {
            "marginLeft": "30px"
          },
          direction: "vertical",
          speed: 0.5
        }`

**Comment by NightCatSama** [comment]
No bugs have been tested using your parameters, is it possible that this kind of [exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions) is possible?

**Comment by pi0neer** [comment]
Nope, i actually found a problem, it looks like somehow your slider conflicting with vue-tabs, i'm not really sure why, but maybe you could try it yourself to reproduce

**Comment by clementroche** [comment]
I have the same problem without vue-tabs. @pi0neer did you find a solution ?

**Comment by matt-e-king** [comment]
@pi0neer @NightCatSama I am experiencing the same issue and I believe it has to do with the slider's position moving **vertically** on the page. I haven't dug into the source code, so I don't know exactly what would be causing this. But here is a gif:

![sliderbug](https://user-images.githubusercontent.com/3094245/45722622-13e89980-bb62-11e8-98de-5110b70a4b4a.gif)

I hope this helps! (thanks for the contribution @NightCatSama!)

**Comment by NightCatSama** [comment]
Fixed the exceptions in the latest version.
