### ISSUE TITLE
How to bind parameters with nested value?

### ISSUE THREAD

**Issue by bubnenkoff** [NightCatSama/vue-slider-component#20]
I want to add few sliders, but can't understand how to separate their values.
Examples show only putting all stuff to data, like:

```
data: {
    value: 1,
    max: 500
  }
```

But I want to do something like:
```
data: {
   price: {
       value: 1,
      max: 500
    }
  }
```
But how to bind nested value to slider?

**Comment by NightCatSama** [comment]
Is this able to solve your problem?
```html
<slider :max="price.max" v-model="price.value"></slider>
```

**Comment by bubnenkoff** [comment]
Sorry, but how to use: `setValue([1,6])` with nested element like price above?
` <button @click="setValue([1,6])">xxx</button>`

**Comment by bubnenkoff** [comment]
Can't understand how to change default style.

I am trying to do next:
```
  <div class="MySlider"><vue-slider ref="slider" :speed="price.speed" :interval="price.interval" :formatter = "price.formatter" :max="price.max" :min="price.min" v-model="price.value"></vue-slider></div>
```

```
                tooltipStyle: {
						backgroundColor: '#red',
						borderColor: '#666'
					},
                price: {
                    value: [1.5,10],
                    min: 1,
                    max: 10,
                    interval: 0.5,
                    formatter: "{value} тыс. ₽",
                    bgstyle: {
                        backgroundColor: '#red',
                    }
                }
```

Can I put style `tooltipStyle` outside if I need it's global? How I should bind slider and style?

**Comment by bubnenkoff** [comment]
I can't understand how binding with default parameters works.

For example my code:
```
    export default {
        name : "LeftMenu",
        data() {
            return {
                default: {
                tooltipStyle: {
						backgroundColor: '#red',
						borderColor: '#666'
					}
                },
                price: {
                    value: [1.5,10],
                    min: 1,
                    max: 10,
                    interval: 0.5,
                    formatter: "{value} тыс. ₽"
                }
```

What should I add to slider to bind it with default?

**Comment by NightCatSama** [comment]
Did not see that you have passed `tooltip-style` down to the component. just like:
```html
<vue-slider :tooltip-style="tooltipStyle"></vue-slider>
// ....
data() {
    return {
        tooltipStyle: {
            backgroundColor: '#red',
            borderColor: '#666'
        }
    }
}
```

**Comment by bubnenkoff** [comment]
Do not work :( 
![default](https://cloud.githubusercontent.com/assets/6514326/23455835/31618a92-fe82-11e6-9673-033c215a8b65.png)

**Comment by bubnenkoff** [comment]
It's seems that default keyword is bad. 

I changed 
```
 :tooltip-style="my.processStyle"
```

And:

```
    export default {
        name : "LeftMenu",
        data() {
            return {
                my: {
                processStyle: 
                {
						backgroundColor: 'green',
						borderColor: '#666'
				},
                tooltipStyle: 
                {
				backgroundColor: 'red',

```
And got it work. But with default it's not working

**Comment by NightCatSama** [comment]
I'm sorry I wrote `#red` in the reply, should be `red`.

After my test, the cause of the bug is not a default keyword.

**Comment by bubnenkoff** [comment]
>After my test, the cause of the bug is not a default keyword.
It's blame on this keyword...
![default](https://cloud.githubusercontent.com/assets/6514326/23458692/56b15578-fe8e-11e6-83a2-1d84d914e967.png)

**Comment by NightCatSama** [comment]
`default` is the keyword to the vue. so there is no relationship with the components.
