### ISSUE TITLE
Re-calculation of "width" on progressbar causes minor glitches

### ISSUE THREAD

**Issue by jebkor** [NightCatSama/vue-slider-component#200]
I've been playing around with your component, and so far it has worked great. One thing I've noticed is that when the slider has been running for a while, it seems that some calculation hiccup happens, and some graphical glitches happen. Nothing major, and maybe you've already noticed them.

![recalculation](https://user-images.githubusercontent.com/21107805/41525605-da7527e0-72e1-11e8-998f-585e6634e197.PNG)

From the tests I've tried, it seems to happen, because you are using "width" to tell the progressbar, how wide it should be. Maybe "transform" would be better?

I have attached some screenshots, for you to see.

I don't have a solution as of now, but I'm trying to see if I can't come up with something,

**Comment by NightCatSama** [comment]
This looks like a problem with the browser rendering.

**Comment by jebkor** [comment]
I suppose it could be the fault of the rendering engine, but I gather you're not going to look further into this?

**Comment by NightCatSama** [comment]
I have not encountered you this problem. I do not know what caused it.

What do you mean by transform to replace width, I have no idea. Maybe you can try modifying the [source code](https://github.com/NightCatSama/vue-slider-component/blob/master/src/vue2-slider.vue#L872) to solve the problem. If I can, then I update or you submit pr.

**Comment by jebkor** [comment]
Sure, I'll look into it when I get some spare time. Thanks for taking your time to reply to the issue 😄

**Comment by andreud** [comment]
I got aorund it calling $refs.mySlider.refresh() inside a setTimeout()
