### ISSUE TITLE
How to use different slider instead of default slider with one input 

### ISSUE THREAD

**Issue by sachin499** [NightCatSama/vue-slider-component#203]
I had gone through docs but also i am not able to find how to use different slider given by vue-component-slider instead of default slider with one input

**Comment by NightCatSama** [comment]
Can't understand what you mean, can you describe in detail?

**Comment by sachin499** [comment]
i mean the default  slider is showing for only one range but in pretty slider example you have provided with r=two input ranges right so how can i configure pretty slider example n my app

**Comment by NightCatSama** [comment]
Just set the value to an `array` type.
