### ISSUE TITLE
Initial width does not respect container, on resize it is ok

### ISSUE THREAD

**Issue by atilkan** [NightCatSama/vue-slider-component#204]
On initial page load width looks like SS below. White edge is container. I am having this behaviour with some libraries and tools but on different apps.

![screen shot 2018-06-26 at 15 03 23](https://user-images.githubusercontent.com/1254613/41910578-bbfd71b0-7952-11e8-87ee-2b968537a453.png)

After triggering resize:

![screen shot 2018-06-26 at 15 08 36](https://user-images.githubusercontent.com/1254613/41910611-d91c4032-7952-11e8-8545-76d53717d5a7.png)

**Comment by atilkan** [comment]
Note: If i give extra time to render it is working as expected:

```
setTimeout(() => {
//init here
}, 100)
```
Normally i do this:
`document.addEventListener("DOMContentLoaded", page.init)`

**Comment by NightCatSama** [comment]
This exception is described in the documentation.

<https://github.com/NightCatSama/vue-slider-component#exceptions>

**Comment by atilkan** [comment]
But my problem is not one of them.

**Comment by NightCatSama** [comment]
Seems to be caused by incorrect container width when the component is initialized.

Is it possible that the code in the third-party library is causing?

**Comment by atilkan** [comment]
It is a normal relative css container using css-grid. No other script running.

**Comment by NightCatSama** [comment]
The default width of the component is `auto`. Maybe you can also try to call the `refresh` method after the page is rendered.

**Comment by atilkan** [comment]
@NightCatSama I wrote the workaround above to be helpful, just settimeout.
