### ISSUE TITLE
ssr rendered incorrect

### ISSUE THREAD

**Issue by soberlyxq** [NightCatSama/vue-slider-component#205]
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render
重新安装modules后，插件在控制台报错了。但是不影响功能。

**Comment by NightCatSama** [comment]
组件默认是不支持ssr的，你可以参考下其他人的做法。

<https://github.com/NightCatSama/vue-slider-component/issues/114>

<https://github.com/NightCatSama/vue-slider-component#using-it-with-nuxtjs>

**Comment by soberlyxq** [comment]
早已加上了no-ssr。 怀疑是依赖包版本原因。正在排查。
