### ISSUE TITLE
Equivelent of html5 "onchange" event

### ISSUE THREAD

**Issue by elbojoloco** [NightCatSama/vue-slider-component#208]
Is there an event that I can listen for that behaves the same as the html5 onchange event? The drag-end works fine, but I also want it to fire if the range is clicked instead of dragged. I don't want to use the default callback for value update because that fires too often.

![slider](https://user-images.githubusercontent.com/7912315/42561927-b8321f64-84fa-11e8-81ed-25c353f32c7f.gif)

**Comment by NightCatSama** [comment]
You can use the `callback` event.

**Comment by NightCatSama** [comment]
No, logically, `onchange` will be triggered whenever the value changes.

If you want the sliding process to not trigger an update, you can use the `lazy` attribute.

**Comment by elbojoloco** [comment]
Yes, this is exactly the behavior I was looking for. Thank you! Great package.
