### ISSUE TITLE
Fixed range issue

### ISSUE THREAD

**Issue by max13fr** [NightCatSama/vue-slider-component#211]
Hello,

There is an issue in the range slider when we set the fixed flag with specific min & max.

Here the example:
https://jsfiddle.net/2xy72dod/4505/

As you can see, if you try to drag or use the right dot, the range is stucked at the minimum value.
Only the left dot is working.

I think the issue is caused by the min & max (when we set it to 0 - 100 the issue disappear).

Thanks in advance,
Best regards, Max

**Comment by NightCatSama** [comment]
Thank you for your feedback, it has been fixed in version 2.7.3.

**Comment by max13fr** [comment]
A huge thanks you for your reactivity and you're awesome plugin !

It's work like a charm now.
