### ISSUE TITLE
Tooltip Position on start and end

### ISSUE THREAD

**Issue by gayakkv** [NightCatSama/vue-slider-component#213]
Is there a way to change tooltip position at start and end of the slider.
Start position -
![slider-start](https://user-images.githubusercontent.com/3424451/42928496-0d6976d4-8b55-11e8-9bdf-f4839451b31a.png)
Middle position -
![slider-middle](https://user-images.githubusercontent.com/3424451/42928602-6154278a-8b55-11e8-8f83-1468a5552bbd.png)
End Position -
![slider-end](https://user-images.githubusercontent.com/3424451/42928494-0d3b0b14-8b55-11e8-9a98-c376e26908f0.png)

**Comment by NightCatSama** [comment]
Sorry, it is currently not possible to directly configure parameters to do this.

Maybe you can try using the `tooltip-style` attribute or `slot` to achieve.
