### ISSUE TITLE
Why bower not found this package

### ISSUE THREAD

**Issue by rustam87** [NightCatSama/vue-slider-component#214]
Bower doesnt found this package. I cant use another package's system

**Comment by NightCatSama** [comment]
ok.

**Comment by rustam87** [comment]
you added to bower but not all versions 
Bower said 
available versions in https://github.com/NightCatSama/vue-slider-component.git: 2.5.9, 2.3.5, 2.2.9, 2.2.6, 2.2.5, 2.2.4, 2.2.2, 2.2.1, 2.2.0, 2.1.9, 2.1.8, 2.1.7, 2.1.6, 2.1.5, 2.1.4

But i want 2.7.4
Is it real?

**Comment by NightCatSama** [comment]
Sorry, I haven't used bower, I'm just a simple `bower register`, if you can, pull the project down and upload it yourself.

**Comment by rustam87** [comment]
Maybe it wil be interested.
i finded last commit in intereting version here and specify in my bower.json
"vue-slider-component": "https://github.com/NightCatSama/vue-slider-component.git#581ebad28bfd42d384af9ecae2227d391fd9deda"
And i got 2.7.5 version
