### ISSUE TITLE
After scale , position is wrong.

### ISSUE THREAD

**Issue by huangxiaoyiloveyou** [NightCatSama/vue-slider-component#218]
Hello!
my page after a zoom, drag the slider position is wrong.What way can solve this problem。

Scaling method:
this.$refs.contentPage.style.transform =
        "scale(" + this.scale.x + "," + this.scale.y + ")";
      this.$refs.contentPage.style.transformOrigin = "0 0";

**Comment by NightCatSama** [comment]
The [exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions) is stated in the documentation.

Add `this.$nextTick(() => this.$refs.slider.refresh())` after scale

**Comment by a22773889g** [comment]
Hi, I have the same problem.

I'm using css3 scale transform to scale a div that contains the slider, and the slider's position is wrong.

What way can I solve this problem.

**Comment by a22773889g** [comment]
> The [exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions) is stated in the documentation.
> 
> Add `this.$nextTick(() => this.$refs.slider.refresh())` after scale

Hi, I have the same problem.

I'm using css3 scale transform to scale a div that contains the slider, the slider's position is wrong.

What way can I solve this problem.

**Comment by NightCatSama** [comment]
@a22773889g 

Updated v3.2.10 to add zoom parameter to support zoomed scenes. For more details, see the documentation.

<https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=zoom>

**Comment by a22773889g** [comment]
@NightCatSama Thanks for your help. You saved my life.

**Comment by miaulightouch** [comment]
appreciate your effort, this issue cause really big issue to our business. after updated, problem solved smoothly. I'm grateful for your kind assistance.
