### ISSUE TITLE
VueSlider : Value auto set 0 after reload and cant change it.

### ISSUE THREAD

**Issue by HaoCao216** [NightCatSama/vue-slider-component#219]
For the first load, it works perfect. When I reload page again, the value and position looks just good. But when I click on slider, it moves to the min value of it, and then stuck there forever. 
Only on my local, eddit fiddle works good

**Comment by james-wasson** [comment]
+1

**Comment by NightCatSama** [comment]
Any errors?

**Comment by HaoCao216** [comment]
and no errors :(

**Comment by HaoCao216** [comment]
I try to fix follow another issue, add " this.$nextTick(() => this.$refs.slider.map(slider => slider.refresh())) ", refresh slider after reload the page. But on first click, slider scroll to 0 value before it  work
p/s: It work on mobile screen.

**Comment by NightCatSama** [comment]
I can't tell what went wrong, can you reproduce it in the online example?

**Comment by SpadeGod** [comment]
@HaoCao216 @AusPrinzip 
我有同样的问题，如果父元素没有设置v-show属性，就完美显示，如果父元素设置了v-show为false，那么就会发生这个问题：dot在mix的位置，且不能拖动，拖动会造成绑定的数值直接从mix到max，dot不会产生位移，没有动画。
后面我发现slider本身也有一个show属性，我尝试显式设置它和父级元素的v-show一致，这个问题就解决了。我猜可能是slider内部的v-show和外部的v-show产生了冲突，没仔细看代码，你们可以试试看。
translate the above words
i have same problem, whenever i render slider first time in page is done. but if i set `v-show: "false"` in slider , its no work , just can drag mix direct to max have no animation.
i find the resolve is set the `show` prop. if you want show , explicit set like this `:show="true"` and vice set false. you can try it .

**Comment by xeroxstar** [comment]
I had same issue, once i click on the tooltip it's scrolls to the 0 and i cant drug it anymore. No errors in the console and the slider loads on my page but after first click it's slides to the 0 and i can't drag it. Anyways, this link([](https://github.com/NightCatSama/vue-slider-component#exceptions)) helped me to keep going. I also added a setTimeout before i call the refresh and the slider is draggable after this fix.

**Comment by ssc-hrep3** [comment]
Calling the refresh method helped to work around this problem. In my case, the slider was in a box which changed its position (`transform: translate` change). I also used a timeout before refreshing the slider (refresh after the box transform transition finishes).

**Comment by NightCatSama** [comment]
It is no longer necessary to call refresh in the latest version.

**Comment by berdnikov** [comment]
Hi. I have the same issue after update. Dot freezes on 0 and I can't drug it

**Comment by NightCatSama** [comment]
@berdnikov What is the version number, is there a screenshot or the like?

**Comment by berdnikov** [comment]
@NightCatSama "vue-slider-component": "^3.0.7"

**Comment by berdnikov** [comment]
@NightCatSama sorry, screenshot is simple - just slider with dot which doesn't move. If value !=0, dot jumps to 0 if i touch it

**Comment by NightCatSama** [comment]
Sorry, I don't have any idea 😢 .

Can you try to reproduce it in jsfiddle?

<https://jsfiddle.net/NightCatSama/2xy72dod/10253/>

**Comment by berdnikov** [comment]
Ok, thanks for answer! in jsfiddle is OK :(

**Comment by NightCatSama** [comment]
@berdnikov I can't help you :(

**Comment by berdnikov** [comment]
@NightCatSama  I found the reason. This was the parent block's zoom. thank you for fast reaction. Good luck
