### ISSUE TITLE
[Vue Warns] : Error in event handler for "input"

### ISSUE THREAD

**Issue by fgzetech** [NightCatSama/vue-slider-component#220]
Hi, I need to use this plugin but I have a problem.

-[Vue warn]: Error in event handler for "input": "TypeError: Cannot use 'in' operator to search for 'value' in "

- [Vue warn]: Cannot set reactive property on undefined, null, or primitive value:

I'm using Vue 2.5.16 with Babel and Webpack.
My code is in: https://jsfiddle.net/2xy72dod/5416/

**Comment by NightCatSama** [comment]
Where is the error?

**Comment by fgzetech** [comment]
@NightCatSama I replicated the code from jsfiddle in my own project. The errors dissapear when I remove the vue-slider code.
I put the data inside 
myObj: {
   customProp: {
      //here is the data
   }
}


This is my html:
<vue-slider ref="slider" v-model="myObj.customProp.value" v-bind="myObj.customProp.options"></vue-slider>

**Comment by NightCatSama** [comment]
Sorry, I can't reproduce it.

Look at the warning that you should set the property on a undefined or null or primitive value.

![image](https://user-images.githubusercontent.com/13888962/43358296-e704b958-92c1-11e8-9a50-968755b5dd2f.png)
