### ISSUE TITLE
Can i change padding of slider

### ISSUE THREAD

**Issue by rustam87** [NightCatSama/vue-slider-component#221]
I dont't need padding of slider. Is it possible?

**Comment by NightCatSama** [comment]
Of course, I wrote a simple example.

<https://jsfiddle.net/2xy72dod/5673/>

**Comment by rustam87** [comment]
why is not working in my case?

I specified padding in sliderOption

[](https://jsfiddle.net/2xy72dod/5845/)

**Comment by NightCatSama** [comment]
should be ` style: { padding: '0px', }`. 

The Component has no `padding` attribute

**Comment by rustam87** [comment]
Sorry i didn't see that vue-slider has `:style="{ padding }"`
