### ISSUE TITLE
Clicking on custom label does not always propagate the expected value

### ISSUE THREAD

**Issue by dmke** [NightCatSama/vue-slider-component#222]
I was expecting to set the label's value, when clicking on it. Obviously the mouse position has higher precedence:

![label](https://user-images.githubusercontent.com/327411/43450203-7b65bda8-94b2-11e8-88e7-f5a7879d743f.gif)

https://jsfiddle.net/dmke/eywraw8t/223390/

Maybe I'm using it wrong?

Updating the model in the label's click handler does not work:

```vue
<template slot="label" slot-scope="label">
  <span v-if="true" @click="value = label">{{ label }}</span>
</template>
```

**Comment by NightCatSama** [comment]
I wrote two examples.

<https://jsfiddle.net/0tvm1nsc/>

<https://jsfiddle.net/8ycov173/>

Does it meet your expectations?

**Comment by dmke** [comment]
The latter one (`@click.stop`) works for me, thank you!
