### ISSUE TITLE
Support logarithmic scale

### ISSUE THREAD

**Issue by netstuff** [NightCatSama/vue-slider-component#224]
Is it possible to redefine `getValue` and `setValue` methods to release logarithmic scale. It very useful when min/max value limits has a huge difference (e.g. 1000/10000000).

It can looks like this:
```
getValue () {
    return Math.round(Math.pow(10, this.val));
}

setValue (val, ...) {
    this.val = Math.log(val) / Math.log(10);
}
``` 

Thank u very much!

**Comment by NightCatSama** [comment]
Sorry, I don’t understand the meaning of doing this very well.

However, I think `setValue` and `getValue` should not be redefine. If you want to reprocess the value, you can use `watch` or `computed (getter/setter)`.

**Comment by sbusso** [comment]
Seconding this request, a logarithmic scale would be nice.

**Comment by tvld** [comment]
Would indeed be perfect... Cant find good log-scale slider

**Comment by zhiyishou** [comment]
4th request for this scale

**Comment by NightCatSama** [comment]
@zhiyishou Logarithmic scale can be more easily implemented in the 3.x version.

<https://jsfiddle.net/hsgzpoy3/>

**Comment by ThermScissorpunch** [comment]
Logarithmic scale would be very helpfull!
