### ISSUE TITLE
setIndex not working correctly

### ISSUE THREAD

**Issue by luiguild** [NightCatSama/vue-slider-component#225]
When I create the component, I pass this values `['00AM', ..., '12AM']` using v-model, and work as well.
![image](https://user-images.githubusercontent.com/16566338/43796422-a7384948-9a5a-11e8-97cd-d50e96a64c8d.png)

Now, when I change the the content of the array, I can't set an index based on the new array... I need set the value/index to the last item
![image](https://user-images.githubusercontent.com/16566338/43796435-aef9a6cc-9a5a-11e8-80fb-cd9c2ab83e79.png)

I'm already tray do it, but the component continue setting the index based on the first array referenced during the creation
```
this.$refs.slider.setIndex([
    0,
    this.hours.length - 1
])
```

**Comment by NightCatSama** [comment]
Maybe you need to add `nextTick`.

e.g. <https://jsfiddle.net/NightCatSama/2xy72dod/6368/>

If you still have problems, please use the online example to restore.
