### ISSUE TITLE
Unique Callback for each handle

### ISSUE THREAD

**Issue by gooca** [NightCatSama/vue-slider-component#229]
Thanks for this slider, it's been a joy to use.

I have a slider with two handles. When the first one moves on callback, I want to run a function, while when the second one moves, I want to run a different function. Is there any way to detect which handle is being moved?

**Comment by NightCatSama** [comment]
You can distinguish by getting the data of the component.

I wrote a simple example, I hope this will help you. 

<https://jsfiddle.net/2xy72dod/6709/>

**Comment by gooca** [comment]
Thank you, this is exactly what I was looking for! Thanks for such a well-made slider.
