### ISSUE TITLE
slider tooltip overlaping

### ISSUE THREAD

**Issue by bubnenkoff** [NightCatSama/vue-slider-component#23]
I think tooltips should not be overleaped even if points on same place or very near each other. They should be shifts as on attached img:

![default](https://cloud.githubusercontent.com/assets/6514326/23377809/64fc8a3c-fd42-11e6-9e28-3d000632051b.png)

**Comment by NightCatSama** [comment]
Thank you for your suggestion, but that is strange when the slide.

So I tried to use other ways to solve this problem, i modified the `tooltipDir` and` sliderStyle` and `tooltipStyle` prop to support the Array type. look at [demo](https://nightcatsama.github.io/vue-slider-component/example/#demo6)

**Comment by trandaison** [comment]
The link is died. Can you update an example @NightCatSama
