### ISSUE TITLE
image or font-awesome-icon as a dot

### ISSUE THREAD

**Issue by dithh** [NightCatSama/vue-slider-component#230]
how can i use image or  more preferably a font-awesome icon as a dot in this slider? i only see dot-disabled-style property  is there a property for a active dot style?

**Comment by NightCatSama** [comment]
The `sliderStyle` property is the style of the control point.

If you want to use an image, you can set the background image.

e.g. <https://jsfiddle.net/NightCatSama/2xy72dod/6740/>
