### ISSUE TITLE
Key events

### ISSUE THREAD

**Issue by nxl6969** [NightCatSama/vue-slider-component#231]
Is it possible to add keyup/keydown/keypress event listeners to the slider? The only event that seems to work for me is the @input event but it doesn't suit me. If it's not possible, it would be a neat feature since you already allow keyboard slider traversing.

**Comment by NightCatSama** [comment]
Why do you need for these events?

**Comment by nxl6969** [comment]
I am validating the slider values after the drag-end (checking that they are not both 0 ([0, 0] ) and I was thinking of doing the same thing after a key event is triggered...

**Comment by NightCatSama** [comment]
I added an `on-keypress` event that fires when I press the keyboard to modify the value.

please update to `2.7.7`

**Comment by nxl6969** [comment]
Thank you very much :)
