### ISSUE TITLE
Prevent crossing of range sliders

### ISSUE THREAD

**Issue by andreas-groos** [NightCatSama/vue-slider-component#232]
When using range how can one prevent the lower slider going above the upper? I couldn't find anything in the demos, they all behave that they can 'cross'.
I tried putting a watcher on the range values and overriding it but it also doesn't work.
```javasacript
watch: {
    range: function(v) {
      if (this.range[0] >= this.range[1]) {
        console.log("crossing");
        this.range[1] = this.data.endYear;
      }
    }
  }
```

**Comment by NightCatSama** [comment]
There is no direct property control now, but it can be implemented using `disabled`.

e.g. <https://jsfiddle.net/NightCatSama/2xy72dod/6860/>

**Comment by andreas-groos** [comment]
OK, thanks, that works...

**Comment by NightCatSama** [comment]
Version 2.7.9 adds the `enable-cross` attribute.
