### ISSUE TITLE
reverse config

### ISSUE THREAD

**Issue by jjhesk** [NightCatSama/vue-slider-component#233]
given the range from 0 to 100.
The slider handle is at 50 that will be [0 - 50] are selected. If I want to do a reverse, can i do [50-100] just by switching the reverse bool to true?

How can I achieve this event?

**Comment by NightCatSama** [comment]
No, `reverse` only affects the direction of the slide, does not affect the value.

**Comment by jjhesk** [comment]
what can it be done by having this effect? anyone would able to help me to think?

**Comment by NightCatSama** [comment]
This can be done in the latest version.

<https://jsfiddle.net/NightCatSama/2xy72dod/10249/>
