### ISSUE TITLE
How can I make pieces only for certain numbers?

### ISSUE THREAD

**Issue by Livog** [NightCatSama/vue-slider-component#235]
Right now I can see that the function piecewiseDotWrap in the computed object is returning the prices to be outputted. My problem is that when you have from 0 to 5000 it renders 5000 node elements in the DOM and it makes the whole experience feel laggy. Is there a way to change / only output the key numbers like 1000, 2000, 3000 etc. Can I override the piecewiseDotWrap function?

**Comment by NightCatSama** [comment]
You can use `slot`, you can refer to [demo8](https://nightcatsama.github.io/vue-slider-component/example/#demo8).

**Comment by Livog** [comment]
@NightCatSama Thanks for a quick reply, I tested that, but it still prints out all the nodes in the DOM that is NOT visible. So when it's controlling 5000 nodes, and you pull it back and forth, it lags super much.

**Comment by NightCatSama** [comment]
You are right, but I can't think of a good way to solve it.

**Comment by Livog** [comment]
Could not the whole ".vue-slider-piecewise-item" be a slot?

**Comment by NightCatSama** [comment]
It shouldn't work, because the position of each point needs to be calculated.

**Comment by Livog** [comment]
I made a custom solution that printed out the pipes in %. If you add the pipes array to this.rangeOptions and add a div#pipes where ever you want it. This should print the on mounted() :) If anyone else wants the same solution. Might need to modify a bit but the base is there.
`pipes: [
                        { 'key' : 'class1', 'value': 0 },
                        { 'key' : 'class2', 'value': 500 },
                        { 'key' : 'class3', 'value': 1000 },
                        { 'key' : 'class4', 'value': 5000 },
                    ]`

`printPipes() {
var pipeWrap = document.getElementById('pipes');
                for (var i = 0; i < this.rangeOptions.pipes.length; i++) {
                    var newPipe = document.createElement("SPAN"),
                        nextVal = 100;
                    newPipe.style.left = (100 / this.rangeOptions.max) * this.rangeOptions.pipes[i]['value'] + '%';
                    if(this.rangeOptions.pipes[i+1] !== undefined)
                        nextVal = parseFloat((100 / this.rangeOptions.max) * this.rangeOptions.pipes[i+1]['value']);

                    var currentVal = parseFloat((100 / this.rangeOptions.max) * this.rangeOptions.pipes[i]['value']);
                    newPipe.style.height = (this.rangeOptions.height / 3) + 'px' ;
                    newPipe.style.width = nextVal - currentVal + '%';
                    newPipe.classList.add('pipe');
                    newPipe.classList.add(this.rangeOptions.pipes[i]['key']);
                    
                    pipeWrap.appendChild(newPipe);
                }
}`
