### ISSUE TITLE
How can I set a minimum diff value?

### ISSUE THREAD

**Issue by Livog** [NightCatSama/vue-slider-component#236]
Hi!

I m trying to make the diff of the 2 values to never be less than 50. Is there an easy way to increase the necessary value so the diff is at least 50 all the time?

**Comment by NightCatSama** [comment]
Is it like this?

<https://jsfiddle.net/2xy72dod/7625/>

**Comment by Livog** [comment]
No sorry, maybe I explained it weird. Let's say you have a range slider between 1 and 1000. If you try to pull dot one closer to dot 2 and the value between does 2 is less then 50 it should either start adding value more to dot2 so the diff never crosses 50. Or reversed that you start pulling down dot2 it should subtract from dot1s value so the diff never got below 50. Maybe that's a more advanced explanation.

**Comment by NightCatSama** [comment]
No parameters can be set directly now, but it can be implemented by `watch`.

<https://jsfiddle.net/2xy72dod/7655/>

**Comment by NightCatSama** [comment]
<https://nightcatsama.github.io/vue-slider-component/#/basics/range>
