### ISSUE TITLE
showing decimal value

### ISSUE THREAD

**Issue by rassemdev** [NightCatSama/vue-slider-component#238]
I want to show decimal value, but vue-slider only showing integer. And also i couldn't set decimal points to interval. Is there any way to flace decimal point?

**Comment by NightCatSama** [comment]
Can set the decimal interval.

<https://jsfiddle.net/2xy72dod/8064/>

**Comment by rassemdev** [comment]
thanks.. it works. My problem were somewhere else, that's why it wasn't showing decimal value
