### ISSUE TITLE
Conditions (v-if) broken after reaching vue-slider-component limits

### ISSUE THREAD

**Issue by juanbrujo** [NightCatSama/vue-slider-component#239]
I'm using vue-slider-component next to an input, sharing `v-model` binding. When input reaches v-slider-component limits (min and max), console throws an error and breaks a `v-if` warning validation I'm using.

![screen shot 2018-09-12 at 13 26 16](https://user-images.githubusercontent.com/362186/45440430-9967d780-b692-11e8-88de-c3467fe08936.png)

Removing the vue-slider-component directive from the <template> and just using the input works:

![screen shot 2018-09-12 at 13 31 17](https://user-images.githubusercontent.com/362186/45440451-a97fb700-b692-11e8-9ef6-231a27dece35.png)

tried options `show: false, debug: false, disabled: false` and nothing works.

Fiddle: https://jsfiddle.net/2xy72dod/8065/

Thanks for any help, great component, very customizable.

**Comment by NightCatSama** [comment]
You can bind a component's value without using `v-model`.

<https://jsfiddle.net/2xy72dod/8070/>

**Comment by juanbrujo** [comment]
Gorgeous! 😍 closing, thanks a lot!
