### ISSUE TITLE
Slider errors using custom data

### ISSUE THREAD

**Issue by machinek56** [NightCatSama/vue-slider-component#240]
Hi!
I'v updated this component from v2.6.2 to latest 2.7.7 and encountered errors in console, that break slider functionality. I define custom data for slider.

slider options: 
```javascript
optionsTerm: {
      useKeyboard: true,
      data: [],
      lazy: false,
      tooltip: false,
      piecewise: true,
      class: 'q5f_slider',
      processStyle: {
         'backgroundColor': '#F51935'
      },
      bgStyle: {
        'backgroundColor': '#ececec'
      }
    },
```

html: 
```html
<vue-slider ref="slider"
            v-model="optionsTerm.value"
            v-bind="optionsTerm"
            @callback="setPaymentNum">
</vue-slider>
```

![image](https://user-images.githubusercontent.com/12989125/45538505-ee7d2800-b80f-11e8-9f0a-d69d6b65bc15.png)

How to fix that?

**Comment by NightCatSama** [comment]
Why is `data` an empty array and I don't see `value`. 😓

**Comment by machinek56** [comment]
I set them in initialization function below
```javascript
this.optionsTerm.data = this.termRange
this.termRangeSlider = this.termRange
this.setValue('optionsTerm', this.paymentNum)
```

**Comment by NightCatSama** [comment]
You can render the component after the initialization is complete.

```vue
<vue-slider v-if="initialized" />
```

```js
this.initValue()
this.initialized = true
```

**Comment by machinek56** [comment]
Thanks, now it works well!
And i have another question.
When i have in data single item, how can i move slider dot to the end of process?

![image](https://user-images.githubusercontent.com/12989125/45545481-145ff800-b823-11e8-96d2-8649f2ff1d5b.png)
