### ISSUE TITLE
value square bracket cannot be removed!!

### ISSUE THREAD

**Issue by rash0** [NightCatSama/vue-slider-component#241]
hello, after i used the double range slider....icouldnt remove the square brackets from the value...anyway to remove it, or customize it ??
![1](https://user-images.githubusercontent.com/40761345/45892270-3563b280-bdfa-11e8-850c-1981c4f19672.png)

`data() {
    return {
      value: [
        100,
        750
      ],
      options: {
      width: "auto",
      height: 4,
      dotSize: 10,
      min: 0,
      max: 1000,
      show: true,
      useKeyboard: true,
      tooltip: "hover",
      formatter: (v) => `$${v}`,
      mergeFormatter: (v1, v2) => `$${v1} ~ $${v2}`,
      processStyle: {
        "backgroundColor": "#999"
      }}
    }
  }`

**Comment by NightCatSama** [comment]
Can you reproduce your problem?

<https://jsfiddle.net/2xy72dod/1240/>

**Comment by rash0** [comment]
yea sure, here it is 

https://jsfiddle.net/2xy72dod/8485/

**Comment by NightCatSama** [comment]
Because value is an array, if you show it directly, it will show square brackets.

<https://jsfiddle.net/2xy72dod/8544/>
