### ISSUE TITLE
[FR] Custom zero position

### ISSUE THREAD

**Issue by DenisNP** [NightCatSama/vue-slider-component#246]
Hello there!

By default zero progressbar position is always **= min** in non-range mode, even if **min < 0**. So, it will be cool to have something like this:
![custom zero position](https://user-images.githubusercontent.com/720975/46508136-b54f3b00-c844-11e8-8c22-47e436367676.gif)

**Comment by NightCatSama** [comment]
In the latest version, you can do it with `process`.

<https://nightcatsama.github.io/vue-slider-component/#/basics/process>
