### ISSUE TITLE
Default value : none

### ISSUE THREAD

**Issue by Shimabuk** [NightCatSama/vue-slider-component#248]
Is there a way to not have any default value. My options looks like this :  
`      		options: {
		          value: '',
		          width: '80%',
		          tooltip: 'always',
		          disabled: false,
		          piecewise: true,
		          piecewiseLabel: true,
		          style: {
		            marginLeft: '10%'
		          },
		          data: [
		            '0',
		            '1',
		            '2',
		            '3',
		          ],
		          piecewiseStyle: {
		            backgroundColor: '#ccc',
		            visibility: 'visible',
		            width: '12px',
		            height: '12px'
		          },
		          piecewiseActiveStyle: {
		            backgroundColor: '#3498db'
		          },
		          labelActiveStyle: {
		            color: '#3498db'
		          }
		      	},`

**Comment by NightCatSama** [comment]
Then how do you want to display when there is no value?

**Comment by Shimabuk** [comment]
Something like : 
![without default value](https://user-images.githubusercontent.com/1370352/46701212-79203e00-cc7b-11e8-9dd8-b9c30c430c3b.jpg)

Or if there is a way to display differently a slider which just loaded with a default value, and a slider with a value that has been really selected by the user.
Thanks for your quick answer.

**Comment by NightCatSama** [comment]
Sorry, there is currently no way to implement this function directly.

But it can be achieved by a slightly more complicated means. I wrote an example and hope to help you.

<https://jsfiddle.net/2xy72dod/8734/>

**Comment by Shimabuk** [comment]
Okay thanks for your help.
This way should be enough for me.

Cheers

**Comment by NightCatSama** [comment]
There is a problem with the previous example. When you click the first one, there will be no response.

<https://jsfiddle.net/2xy72dod/8781/>
