### ISSUE TITLE
Using vue2 slider component, startAnimation: false still animating

### ISSUE THREAD

**Issue by kgrosvenor** [NightCatSama/vue-slider-component#249]
Why is this still animating?

Component

  ` <vue-slider :startAnimation="false" v-bind="fatSlider" `v-model="model.carbs"></vue-slider>`

Slider options

`sliderSettings: {
          interval: 1,
          fixed: true,
          processDragable: true,
          piecewiseLabel: false,
          tooltip: false,
          startAnimation: false
        }`

**Comment by NightCatSama** [comment]
try `start-animation`.

**Comment by kgrosvenor** [comment]
still animating

**Comment by kgrosvenor** [comment]
is it when you programmatically set values it still animates, is there a way to disable that on inital model setting?

**Comment by kgrosvenor** [comment]
Thank you, thats just what i needed
