### ISSUE TITLE
vue2 range slider with max range

### ISSUE THREAD

**Issue by revgum** [NightCatSama/vue-slider-component#251]
I've been fiddling with this component a bit, and it's quite nice, but I wonder if you could recommend a solution for my problem?

I'd like a range slider that can be set up to a max range, and if the max is reached then the slider becomes fixed and continues to drag in the following direction. The slider sets fixed to false if the value is being set to something less than the max of the range.. This way the whole bar is dragged when the max range is reached, but not dragged if the range is less than the max range.

**Comment by NightCatSama** [comment]
Updated version 2.7.10 with the `min-range` and `max-range` properties added.

<https://jsfiddle.net/2xy72dod/8850/>

**Comment by revgum** [comment]
That's really great, and I can see a use-case for that implementation as well, thank you! 

What do you think about it working like my demonstration here shows? (I ended up solving this, for now, using the callback method to adjust the indexes based on which slider had changed the value)

![range-demo](https://user-images.githubusercontent.com/32885/46917649-49747d00-cf7e-11e8-9f63-78b1a59e7a16.gif)

**Comment by revgum** [comment]
I left a comment, but didn't realize that the implementation works exactly like I had described.. Thank you for such a quick response and turnaround on this idea! Also, thanks for a great component!

**Comment by NightCatSama** [comment]
Sorry, version `2.7.10` has a bug, please update to `2.7.11`
