### ISSUE TITLE
Set slider min/max value dynamically

### ISSUE THREAD

**Issue by alexgeofilter** [NightCatSama/vue-slider-component#252]
Found this issue raised in the past:

https://github.com/NightCatSama/vue-slider-component/issues/148

I can set the minimum value by directly setting the min property of the slider on the page, however it will immediately revert on next input. The error is:

"[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "min""

I have attempted to set the value directly through the $props route, however this results in the same error. What is the proper method of setting a new min/max value on the slider?

**Comment by alexgeofilter** [comment]
Fixed this by implementing options via "v-bind='slider_options'", slider_options being an object in my vue to store my slider config. I had to search for a while before finding the single example of v-bind on the live demo. This would be a very useful thing to directly point out on the readme as its not obvious how to use this method even with previous vue experience.

**Comment by NightCatSama** [comment]
Has the problem been solved?

**Comment by vijaymayekar** [comment]
@alexgeofilter 
Can you please share code snippet for using min and max dynamically. 

I want to set min & max based on another checkbox value.

```
           <vue-slider
              ref="slider"
              :max="10000000"
              :min="10000"
              :interval="10000"
              :formatter="toCurrencyFormat"
              :tooltip=false
              v-model="amount"
            ></vue-slider>
```
