### ISSUE TITLE
how to set a empty value

### ISSUE THREAD

**Issue by BiggerKai** [NightCatSama/vue-slider-component#253]
<vue-slider  v-model="value" direction="vertical" :min=1 :max=5></vue-slider>
when value is null then tip
The value of the slider is null, the minimum value is 1, the value of this slider can not be less than the minimum value
and also chose minValue
I hope that value is null and has min prop and not show sliderStyle

**Comment by NightCatSama** [comment]
duplicate #248

**Comment by BiggerKai** [comment]
3q, i use another v-model replace use 2 slider to resolve
when @callback v-model real value = tmp null value
