### ISSUE TITLE
❓ Include slot for dot

### ISSUE THREAD

**Issue by renatodeleao** [NightCatSama/vue-slider-component#254]
Heys, thanks for your work on this 🙏 

Similar to `label` `tooltip` and `piecewise`, would think adding a slot for dot content would be a good addition?

### Use case
sometimes the dragHandler (dot) can be a more complex shape. At the moment we can use `background-image` to apply images and icons or even `content: "unicode"` for icon fonts. We can also use svg with some with the help of some [encoding sass trickery](https://codepen.io/jakob-e/pen/doMoML): this with the help `vue-svg-loader` and vue `.sfc` we can avoid the copying svg code into sass: but that's a lot of ifs to include a simple SVG, and there might be usecases with more complex HTML structures. Do you think this makes or is just "over-engineering"?

**Comment by NightCatSama** [comment]
Thank you for your suggestion. Added `slot="dot"` in version 2.8.0.

e.g. <https://jsfiddle.net/2xy72dod/8985/>

It is worth noting that the width and height of the custom dot must be synchronized with the component's `dotSize` / `dotWidth & dotHeight`.

**Comment by renatodeleao** [comment]
@NightCatSama damn that was fast  ! Thanks a lot!
