### ISSUE TITLE
v-model value

### ISSUE THREAD

**Issue by BiggerKai** [NightCatSama/vue-slider-component#256]
when click slider from bottom to top or random click sometimes
the value is not 1 2 3 4 5?
how to get value like 1 2 3 4 5 when click from bottom to top
https://jsfiddle.net/BiggerKai/bx9kghu4/16/

**Comment by NightCatSama** [comment]
<https://jsfiddle.net/bx9kghu4/33/>

**Comment by BiggerKai** [comment]
3ks a lot
