### ISSUE TITLE
multiple slider

### ISSUE THREAD

**Issue by agriboz** [NightCatSama/vue-slider-component#257]
I would like to know, how can i update value of a multiple range slider? I tried with using `@callback` function, however it doesn't work as expected.

[Demo](https://jsfiddle.net/2xy72dod/9048/)

**Comment by NightCatSama** [comment]
I don't know what problem you have encountered.

Is the console printed wrong? `console.log(k, i)` is correct

**Comment by agriboz** [comment]
it doesn't update `selected` data according to index and value.
