### ISSUE TITLE
不设置默认value造成bug

### ISSUE THREAD

**Issue by udbmnm** [NightCatSama/vue-slider-component#26]
我发现不设置默认value会造成设置max和width无效，max会一直为120，width会出现莫名奇妙的宽度

**Comment by NightCatSama** [comment]
请告诉我你的配置参数~ 我这边试了一下是可以的：
```
<vue-slider :max="120" :width="200"></vue-slider>
```

**Comment by udbmnm** [comment]
@NightCatSama  :min="1"  :interval="1"

**Comment by NightCatSama** [comment]
会不会是因为最小值是1，但是value默认值是0而导致的

**Comment by udbmnm** [comment]
有可能，我还没仔细研究你代码

**Comment by NightCatSama** [comment]
好的，有疑问可以问我:smiley:~

**Comment by udbmnm** [comment]
@NightCatSama 好的，感谢开源这么6的组件
