### ISSUE TITLE
Refresh doesn't refresh data/options property.

### ISSUE THREAD

**Issue by pawelbujna** [NightCatSama/vue-slider-component#261]
Hello!

I've putted vue slider component inside my own wrapper component called ParentSlider. And inside it theres vue slider from you. 

`<ParentSlider 
 :min="min"
 :max="max"
 :data="data"
ref="slider"
v-model="val">`

In my page component im using 2 ParentSlider components that are togglet with v-if. Only 1 of them should accept data property.

`<div v-if="index==1">
<ParentSlider 
 :min="min"
 :max="max"
 :data="data"
ref="slider"
v-model="val"></div>`

`<div v-if="index==2">
<ParentSlider 
 :min="min"
 :max="max"
ref="slider"
v-model="val"></div>`

Parent slider accepts :data property(not required) that comes from another parent component and passes it down to vue-slider-component on 'created' method

`created: function () {
   if (this.data) {
      this.options.piecewise = true
      this.options.piecewiseLabel = true
      this.options.data = this.data
  }
}`

And the slider itself look like this:

`<vue-slider ref="csoSlider"
                @callback="callback"
                v-model="currentValue"
                v-bind="options"
                :min="min"
                :max="max"></vue-slider>`

The problem is if I pass data array to only 1 parentSlider component it doesnt refresh and shows up on second ParentSlider also. Even if im refreshing components on toggle like so: 

` watch: {
    'index' () {
      this.$nextTick(() => this.$refs.slider.$children[0].refresh())
    }
  }`

Dont know how to force options object to refresh. Is there any way?

tell me if example is needed

**Comment by NightCatSama** [comment]
Generally speaking, if you use v-if to judge, it should be re-rendered.

You try adding a key attribute to see if it works.

```vue
<div v-if="index==1" key="slider1"> <ParentSlider :min="min" :max="max" :data="data" ref="slider" v-model="val"></div>

<div v-if="index==2" key="slider2"> <ParentSlider :min="min" :max="max" ref="slider" v-model="val"></div>
```

**Comment by pawelbujna** [comment]
Hell of a trick.. it worked!! With your solution refresh method is not needed anymore. Didn't know about that so thank you very much for help!
