### ISSUE TITLE
Is there a way to set different background colors every block? [question]

### ISSUE THREAD

**Issue by a631807682** [NightCatSama/vue-slider-component#262]
Is there a way to set different background colors every block?
like this:
![color-slider](https://user-images.githubusercontent.com/11827916/47974842-6536f300-e0e6-11e8-93d0-8992ef865c1d.png)

有没有办法设置不同位置的背景颜色？比如0-10是绿色，10-20是红色。

**Comment by NightCatSama** [comment]
Setting segmentation styles directly is not supported at the moment, although it is a bit of a hassle, but you can set it by `process-style`.

<https://nightcatsama.github.io/vue-slider-component/example/#demo6>

**Comment by a631807682** [comment]
I  computed points and use `linear-gradient` to set segmentation styles by `bgStyle`.
It's not pretty but thanks a lot.
```
        ...
        bgStyle: {
          background: "-webkit-linear-gradient(left, #eee 0%, #eee 10%, red 10%, red 39%, green 39%, green 59%, #eee 59%, #eee 100%)"
        }
        ...
```
