### ISSUE TITLE
vue-slider-process css wrong after changing inverse prop

### ISSUE THREAD

**Issue by KCMertens** [NightCatSama/vue-slider-component#264]
Need to clear the old values of `left/right` and `top/bottom` 
at https://github.com/NightCatSama/vue-slider-component/blob/6d41e5dde4917c53c380d5e9825cc1c9601a209f/src/vue2-slider.vue#L967 

Like `this.$refs.process.style[!this.reverse ? 'top' : 'bottom'] = ''`

**Comment by NightCatSama** [comment]
Thank you for your feedback, fixed in version 2.8.1
