### ISSUE TITLE
Having width 100% inside a flexbox causes the dot to slide outside the slider.

### ISSUE THREAD

**Issue by axelfriberg** [NightCatSama/vue-slider-component#265]
Hello,

Currently I am trying to achieve a layout where I have one button on each side of the slider and having the slider take up as much space at it can. What I have done is that I have one wrapper element around the two buttons and vue-slider that has "display: flex;" and setting the width of vue-slider to '100%'. The problem is that the dot now moves outside of the slider. See that attached image.
![slider_bug](https://user-images.githubusercontent.com/2886590/48489124-96b86880-e822-11e8-8e1b-e6d81b608af0.PNG)

I guess this has to do with the fact that it does not know that what width it is supposed to be when it is created. Cause resizing the window causes the bug to correct itself.

I tried adding `mounted() {
    this.$nextTick(() => this.$refs.sliderRef.refresh());
  }` to my component but that does not seem to work. Any other suggestions to fix having the width be auto and inside a flex layout?

**Comment by axelfriberg** [comment]
Adding `:real-time="true"` as a prop to vue-slider seemed to fix the issue. Is there any performance downside to using real-time or why is it not enabled by default?

**Comment by NightCatSama** [comment]
You can try adding a container(`flex: 1`) wrapper component.

`:read-time` will recalculate the component size in each drag, on the low performance mobile side may cause Caton

**Comment by axelfriberg** [comment]
I tried:
```HTML
<div style="flex: 1;">
 <vue-slider></vue-slider>
</div>
```

But it is still the same issue unfortunately.

**Comment by axelfriberg** [comment]
Is there a way to only calculate the size once on mount? Is it supposed to be the way I tried previously with `refresh()`?

**Comment by occamz** [comment]
this.refresh() should probably be called internally after /src/vue2-slider.vue:1123. But here is an ugly quickfix that I used @axelfriberg:

```js
mounted() {
  var slider = this.$refs.slider;
  var interval = setInterval(() => {
    if(slider.isMounted) {
      slider.refresh();
      clearInterval(interval);
    }
  }, 200);
},
```

**Comment by NightCatSama** [comment]
It is no longer necessary to call refresh in the latest version.
