### ISSUE TITLE
dot not draggable

### ISSUE THREAD

**Issue by MrQuery** [NightCatSama/vue-slider-component#269]
hi,
i took the first example from the documentation for use in vue 2.x
i set the value to 5
when it loads the tooltip says 5 but when i'm trying to drag the dot it's not moving from the zero position and in the tooltip i can read "100".
my code is exactly the same as in the documentation. and no error in console.

thank you for your help! i need this for work.

![slideissue](https://user-images.githubusercontent.com/10139382/48705275-08b0f900-ebf9-11e8-8143-7a36a46cb1e9.png)

**Comment by drashoor** [comment]
How did you solve this issue?? @MrQuery

**Comment by flyke** [comment]
In my project, some sliders are draggable, some are not.
The ones that are not draggable, i give a ref and a drag start event, like this:

```
<vue-slider
  v-model="verkoopKans"
  ref="slider"
  :interval="5"
  :min="0" :max="100"
  width="100%"
  @drag-start="updateSlider()"
></vue-slider>
```

And then I define the method updateSlider() like this:

```
updateSlider: function() {
  this.$refs.slider.refresh();
},
```
I really wish I knew why some sliders just work, and some are not draggable and need this 'hack', but for now, I don't have a clue. Maybe sliders visible on page load just work, and sliders somewhere inside a v-if don't but I'm not sure.

**Comment by jez500** [comment]
I had this same issue, the slider was inside a div that had a class applying `display: none` and when that was changed to `display: block` the dot was stuck at the start and not draggable.

Fix for me was adding a key to the slider that changed when visibility was changed. Eg:

```
<div :class="isVisible ? 'visible' : 'hidden'">
  <vue-slider :key="isVisible "></vue-slider>
</div>
```

So it seems vue-slider detects its width on load and if in a hidden div it assumes the width is 0 (ignoring the width prop). 

Version tested `2.8.16`

**Comment by NightCatSama** [comment]
@jez500 The width calculation problem has been fixed in version 3.x.
