### ISSUE TITLE
Start animation (disable via options)

### ISSUE THREAD

**Issue by FKobus** [NightCatSama/vue-slider-component#27]
As described in #16 I asked for a disablement of the start animation. In 2.1.2 it was resolved, but in 2.1.7 it's back.

Is it possible to disable it via an option?

**Comment by NightCatSama** [comment]
I'm sorry:cry:. please update to last version.

**Comment by FKobus** [comment]
It's working again. Maybe customizable via an option? So you leave the animation choice to the developer?

**Comment by NightCatSama** [comment]
I think Start animation should not exist, this time is just my fault.

Now nobody needs this option, if someone else needs it later, I will add it.

**Comment by rajagopalx** [comment]
Is there any way to enable start animation ?
