### ISSUE TITLE
关于piecewise nodes问题

### ISSUE THREAD

**Issue by Andraw-lin** [NightCatSama/vue-slider-component#271]
是否支持自定义piecewise nodes？例如，value为 [ 0, 2880 ] , 这时候只想在 value 为1440时展示piecewise nodes，然后其他地方都不展示，而且0到1440间不是跨区间滑动而是可以按1递增或递减滑动。

**Comment by KhalitovAdel** [comment]
> 是否支持自定义piecewise nodes？例如，value为 [ 0, 2880 ] , 这时候只想在 value 为1440时展示piecewise nodes，然后其他地方都不展示，而且0到1440间不是跨区间滑动而是可以按1递增或递减滑动。

I do not understand your language. Can you write in English?

**Comment by NightCatSama** [comment]
新版本支持非线性设置了
