### ISSUE TITLE
disable tooltip on click and show input filed instead of tooltip value?

### ISSUE THREAD

**Issue by goors** [NightCatSama/vue-slider-component#273]
Is this possible? It would be convenient if you can click and see input where you enter number, hit enter and show tooltip with value again, of course with slide to that value.

**Comment by NightCatSama** [comment]
Is it possible to use the tooltip's slot implementation?

**Comment by goors** [comment]
You can't because that is part of this dot slot and it is always movable.

**Comment by BarbaraWiacek** [comment]
I achieved it like this:

```
<template slot="tooltip" slot-scope="{ value }">
    <span v-on:click.stop="editValue(id)">
        <input v-show="editingValue" v-model="newValue" v-on:change="pushValue('slider', newValue)" />
        <span v-show="!editingValue">{{inputValue}}</span>
    </span>
</template>
```

The variable "editingValue" hides and shows the input/span 
The `v-on:click.stop` prevents the event propagation and movement of the dot when you click on the tooltip, then launches the "editValue" function:

```
methods: {
    editValue (sliderId) {
            this.editingValue = true;
            this.newValue = '';
    },
    pushValue(slider, newValue) {
            this.editingValue = false;
            this.slider.value = newValue;
    }
}
```

**Comment by goors** [comment]
@BarbaraWiacek this works only if slider  contains one value. What if it is a range or multiple values?

**Comment by LedzZm** [comment]
Well you could use a custom input component that emit input/blur or w/e events with the value and catch it in the slider component, then change the sliders value with the provided function.

Let me know if this helped at all, or if i should be more precise.
