### ISSUE TITLE
the program was die when the value was big

### ISSUE THREAD

**Issue by muzi131313** [NightCatSama/vue-slider-component#275]
````
<!-- In vue2.5 above, please use slot-scope instead of scope -->
<template slot="label" scope="{ label, active }">
  <span :class="['custom-label', { active }]" v-if="label % 10 === 0">
    {{ label }}
  </span>
</template>
````
````
{
width: "100%"
show: true
value: 39
min: 0
max: 100
piecewiseLabel: true
tooltip: false
}
````
if the max was `10000`，terrible thing exits

**Comment by NightCatSama** [comment]
Added the `partwise-filter` parameter in version 2.8.3.

This can control the amount of rendering, I wrote a simple example.

<https://jsfiddle.net/NightCatSama/2xy72dod/9985/>

**Comment by muzi131313** [comment]
`input[type="range"]` does not support ie9， so I wrap a new vue component, refer to [dragger demo](https://jsbin.com/dulifezi/2/edit?html,js,output)

**Comment by muzi131313** [comment]
your github repo has not push the tag `2.8.3`，but you publish npm version。sorry notice this at just now.
