### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by tamanna-makkar** [NightCatSama/vue-slider-component#276]
When we click on slider handler, then I got this error -  Cannot read property 'getBoundingClientRect' of undefined, anybody have any Idea why this is happening?

**Comment by NightCatSama** [comment]
Can you let me see the specific error, which line of code is reporting an error?

**Comment by tamanna-makkar** [comment]
yes, please see the screenshot below
![image](https://user-images.githubusercontent.com/32664347/50507638-547e7a00-0aa4-11e9-9227-6a106c59e2a3.png)

**Comment by NightCatSama** [comment]
What are the component parameters you passed?

**Comment by tamanna-makkar** [comment]
am using range slider, so By default the values are = [2016, 2030] and on sliding the range slider am passing the year param
like this  - <vue-slider @click.native="addFilter('startJaar', value)" ref="slider"  v-model="value" v-bind="options"></vue-slider>

**Comment by NightCatSama** [comment]
I still can't reproduce it  😢 

<https://jsfiddle.net/NightCatSama/2xy72dod/10113/>

**Comment by tamanna-makkar** [comment]
@NightCatSama I used @drag-end event, I was not aware of this, that this event does exist :)
thanks your slider is really nice
