### ISSUE TITLE
document

### ISSUE THREAD

**Issue by hqzh** [NightCatSama/vue-slider-component#278]
support Chinese？

**Comment by NightCatSama** [comment]
之前也想过加中文文档，但是因为打算重构就没做了。并且最近有点忙，所以进度缓慢。

不好意思，所以还是先不支持了，以后重构了新文档再一并支持。

目前，如果是 api 的话，绝大多数都可以在[demo](https://nightcatsama.github.io/vue-slider-component/example/#demo)里有中文描述。

**Comment by hqzh** [comment]
got it
