### ISSUE TITLE
为什么第一下点首先回零

### ISSUE THREAD

**Issue by taeyeat** [NightCatSama/vue-slider-component#279]
为什么第一下点首先回零，然后怎么拖怎么点都没反应，停留在0或者最大值
<div class="h_slider">
              <vueSlider v-model="square" :min="0" :max="maxSize" :interval="1" :dot-size="isSmallScreen ? 16 
                    : 25"  ref="s_slider"></vueSlider>
</div>

**Comment by taeyeat** [comment]
如果用refresh是可以拖动的，但是第一下拖的时候会瞬间回零，然后再瞬间到我拖的地方，如果直接点进度条，会直接回零，再次点击才会回到我点的地方

**Comment by NightCatSama** [comment]
这么奇怪，你看看能不能在线上复现

<https://jsfiddle.net/2xy72dod/8746/>

**Comment by taeyeat** [comment]
复现不出来 但错误跟https://jsfiddle.net/2xy72dod/254/   这个例子的第一个很像，直接变成最大值或最小值，然后就拉不动了

**Comment by NightCatSama** [comment]
你有没有放在一个异步显示(v-show)的容器中。

如果组件初始化渲染在一个 display: none 的容器中，就会有这种情况

**Comment by NightCatSama** [comment]
最新版本中已经修复该问题
