### ISSUE TITLE
Is there any constraints when I create a new slider with range control?

### ISSUE THREAD

**Issue by hijiangtao** [NightCatSama/vue-slider-component#28]
Actually, I created a slider with range control (which means the `value` is an Array) and put it into a pre-defined grid system layout, but it didn't display normally, the two sliders overlapped at the begin (the position of range minimum value), but the background element shows the normal width. 

In fact, I suspect the default width of my slider is the width of its container's width, as I found the description in README, so I went to check my container's width and re-defined it to a absolute value (300px or so), but the abnormal things still exists. So I didn't think it's a problem of my bad container's width initialization styles.

The interesting thing is that when I resize the screen, the sliders will update to the normal position (Maybe there is some special tricks running in the resize operation).

I thought if there is any constraints when I initialize the component?

The abnormal effect shows like below:

![image](https://cloud.githubusercontent.com/assets/4990015/23740273/d3e3e344-04dd-11e7-825d-b28c7535ba68.png)

While the normal effect should shows like below:

![image](https://cloud.githubusercontent.com/assets/4990015/23740293/eafdddc8-04dd-11e7-88dc-ea9a494b305b.png)

Thanks a lot.

**Comment by NightCatSama** [comment]
if the component initialization in a v-show="false" container, will appear exception( The slider cannot be used, because the component unable to initialize the size in display: none ).

Is this the case?

**Comment by hijiangtao** [comment]
Well, that's exactly the case I met, I forgot the display property controlled by `v-show` when I just focused on the container's width property. Sorry about the disturbance and thank you very much.

**Comment by NightCatSama** [comment]
Never mind:smile:

**Comment by hijiangtao** [comment]
Hey, I know this question is very stupid but I wonder how to call the `refresh` function after I initialize the instance? I use `document.getElementById` to locate the instance and `refresh` it but this doesn't work...

**Comment by NightCatSama** [comment]
Refer to this: [https://vuejs.org/v2/guide/components.html#Child-Component-Refs](https://vuejs.org/v2/guide/components.html#Child-Component-Refs)

**Comment by NightCatSama** [comment]
eg:
```js
<vue-slider ref="slider"></vue-slider>

...

this.show = true
this.$nextTick(() => {
    this.$refs.slider.refresh()
})
```

**Comment by hijiangtao** [comment]
Well then, thanks very much.
