### ISSUE TITLE
formatter Prop is executing twice with one value slider

### ISSUE THREAD

**Issue by martynasmartynas** [NightCatSama/vue-slider-component#280]
formatter Prop is executing twice (and one of them is undefined) when you have single value slider. In my opinion it should run only once, when you have one value slider.

This pice of code:
```
                formatter: function (v) {
                     console.log(v);
                     return v + '$';
                 }
```

Prints in console:
_924000
undefined_

**Comment by NightCatSama** [comment]
Fixed in the latest version
