### ISSUE TITLE
@click.native throws error

### ISSUE THREAD

**Issue by savina-09** [NightCatSama/vue-slider-component#286]
hi @NightCatSama, 

I have used the slider to trigger an action on click as below:-

<vue-slider ref="slider1" @click.native="callToAction(value)" v-model="value" v-bind="options"></vue-slider>

the action triggers successfully on click as well as drag, but in console I get the following error:-

![image](https://user-images.githubusercontent.com/25683029/51110093-5030bb80-181d-11e9-9b30-c4b4405e6cbe.png)

Any suggestions on above?

**Comment by NightCatSama** [comment]
I have not been able to reproduce this error, what is your `options`?

**Comment by savina-09** [comment]
The value and options are as below:-
      
      value: [2016, 2029],
      options: {
        min: 2016,
        max: 2029,
        tooltipDir: 'bottom',
        lazy: false,
        height: 4,
        dotSize: 20,
        useKeyboard: true,
        clickable: true,
        debug: true,
        bgStyle: {
          'backgroundColor': 'rgba(34,34,34,0.3)'
        },
        processStyle: {
          'backgroundColor': '#000066'
        },
        tooltipStyle: {
          'backgroundColor': '#fff',
          'borderColor': '#fff',
          'color': '#000066',
          'fontWeight': 'bold',
          'fontSize': '15px',
          'lineHeight': 'normal'
        },
        sliderStyle: {
          'border': '1px solid #000066',
          'boxShadow': '-2px 2px 5px 0 rgba(83,147,255,0.5)'
        }
      },

**Comment by NightCatSama** [comment]
Still no error.

<https://jsfiddle.net/e618qrc9/1/>

**Comment by savina-09** [comment]
yes, it gives no error while I simply log it.

But I am using the value to make an api call (this.$emit('set-filter', filterUpdate)) and afterwards reload the same component having slider in it.

**Comment by NightCatSama** [comment]
Sorry, I don't know where the problem is.

Maybe you can set a unique key for the component.
