### ISSUE TITLE
Process bar does not expand to full width in production but does in development

### ISSUE THREAD

**Issue by ZeroGodForce** [NightCatSama/vue-slider-component#287]
Hey @NightCatSama 

I've implemented the slider and got it working as needed in development, but when I build for production the process bar ends up with an extremely small width - maybe only one pixel.  The dot barely moves either, just enough for the tooltip to render 0, NaN and 100 - so maybe 3 pixels?

I even tried copying one of the examples in, but I got the same result

> Development
![in_dev](https://user-images.githubusercontent.com/1764852/51120529-34251e00-180d-11e9-801a-6a2e21dca885.png)

> Production
![in_prod](https://user-images.githubusercontent.com/1764852/51120530-34251e00-180d-11e9-997b-7e5917ac2587.png)

The code I've got is here"
```js
slid: {
        value: 0,
        formatter: '{value}%',
        lazy: true,
        tooltip: 'always',
        piecewise: false,
        style: {
          'marginBottom': '30px'
        },
        bgStyle: {
          'backgroundColor': '#fff',
          'boxShadow': 'inset 0.5px 0.5px 3px 1px rgba(0,0,0,.36)'
        },
        sliderStyle: {
          'backgroundColor': '#f05b72'
        },
        tooltipStyle: {
          'backgroundColor': '#3498db',
          'borderColor': '#3498db'
        },
        processStyle: {
          'backgroundImage': '-webkit-linear-gradient(left, #f05b72, #3498db)'
        }
      }
```

As far as I can tell, I don't have any CSS styles that might interfere, but even if I did, wouldn't I have the same problem in development?

Thanks

**Comment by NightCatSama** [comment]
It looks like there is a problem with the width of the initialization.

You can try setting the fixed width, will this happen?

**Comment by NightCatSama** [comment]
Sorry, I don't have any idea. 😢

**Comment by ZeroGodForce** [comment]
Thanks anyway.  I'll keep trying and let you know when (or if) I figure it out

**Comment by PatrykTucki** [comment]
Have you figured it out @ZeroGodForce? I have similar issue that only happens in production.

**Comment by ZeroGodForce** [comment]
@PatrykTucki I'm not too sure, I tried so many things I lost track, but I got something working in the end.  I'll go over my code, find out what it is and let you know ASAP

**Comment by NightCatSama** [comment]
It is no longer necessary to call refresh in the latest version.

**Comment by ZeroGodForce** [comment]
@PatrykTucki I think discovered a css class clash - which only happened when the production process concatenated all of the styles into one stylesheet (something that doesn't happen in development).  As a possible result (I can't be 100% sure as I've moved on to a couple of other projects since then) the working code I ended up with looks like this: 

```js
slid: {
        value: 0,
        formatter: this.getFormat(),
        lazy: true,
        tooltip: 'always',
        piecewise: false,
        style: {
          'marginBottom': '30px'
        },
        bgStyle: {
          'backgroundColor': '#fff',
          'boxShadow': 'inset 0.5px 0.5px 3px 1px rgba(0,0,0,.36)'
        },
        width: '100%',
        tooltipClass: 'custom-vue-slider-tooltip-style',
        processClass: 'custom-vue-slider-process-style'
      }
    }
  }
```

As you can see, I added some custom additional classes to increase the wrapping elements' Sith Power (specificity) and added `width: '100%'` as a main property.  Between these, I think that's what forced the correct style to render.  Don't know if that will help it might be worth a try regardless.  

Good hunting.
