### ISSUE TITLE
Get tooltip value (lazy mode)

### ISSUE THREAD

**Issue by elbojoloco** [NightCatSama/vue-slider-component#288]
Hi

It would be really awesome if it was possible to get the tooltip value while in lazy mode aswell. I want to display the current val while sliding (in a different location than the tooltip), but I also need lazy mode to save my back-end. Is there any way to get this data? I thought maybe emit the `input` event regardless of lazy or not, since the event is not in the docs I doubt it will hurt people's current integration.

GIF of lazy mode behavior:
![customtooltiplocation](https://user-images.githubusercontent.com/7912315/51325390-17872100-1a6d-11e9-8332-3f19ec3c53a0.gif)

**Comment by NightCatSama** [comment]
I added the `drag` event in `v2.8.6`, although it is not the best solution, but it can solve your problem right now.

e.g. <https://jsfiddle.net/8gc6nmuo/>

**Comment by elbojoloco** [comment]
That is exactly what I need, thank you!

Is there a way to contain the handle within the slider range? (so the dot doesnt overflow)

**Comment by NightCatSama** [comment]
Currently unable to achieve this feature 😢
