### ISSUE TITLE
currentValue doesn't  update on value change

### ISSUE THREAD

**Issue by boehmli** [NightCatSama/vue-slider-component#290]
I want to use Vuex to pass the values from Slider A to Slider B, but somehow the currentValue seems to lose its reactivity.  
Slider B
`vue-slider(:value="dataValue")`

Where dataValue is the computed getter from my store. The Vue dev Tools show, that the value prop has been updated, but not the currentValue. Calling refresh() doesn't change anything.
Any ideas what I'm doing wrong?

**Comment by NightCatSama** [comment]
Have you tried the `setValue` setting?

**Comment by boehmli** [comment]
setValue has worked. Anyway, it's working again. I guess it was a timing problem, with Promises it works now.
Thank you for the quick answer!
