### ISSUE TITLE
Is there a possible way to show value inside the Dot?

### ISSUE THREAD

**Issue by JefferyHus** [NightCatSama/vue-slider-component#291]
I would like to show the value inside the dot instead of a tooltip. If this is not yet possible I can send a PR to make this a possible option.

**Comment by NightCatSama** [comment]
Can be implemented using `slot`.

<https://github.com/NightCatSama/vue-slider-component#slot>

**Comment by NightCatSama** [comment]
e.g. <https://jsfiddle.net/NightCatSama/2xy72dod/10231/>

**Comment by JefferyHus** [comment]
and is there any possible way to use hours as values?

**Comment by NightCatSama** [comment]
of course. <https://jsfiddle.net/y9s56cvf/>

**Comment by JefferyHus** [comment]
Something like this 'HH:mm A'

**Comment by NightCatSama** [comment]
You should do it yourself, and these are not related to the component.

<https://jsfiddle.net/m7trz24v/>

**Comment by JefferyHus** [comment]
thanks !!
