### ISSUE TITLE
Is it possible to change the sliderbar height and slider size?

### ISSUE THREAD

**Issue by templth** [NightCatSama/vue-slider-component#292]
Hello,

Is it possible to change the sliderbar height and slider size through style properties? If so, which style property (with configuration keys )can I use?

Thanks for your help!
Thierry

**Comment by NightCatSama** [comment]
Do you need `dot-size`?

<https://jsfiddle.net/NightCatSama/2xy72dod/10226/>

**Comment by templth** [comment]
It's exactly what I'm looking for! Thanks for your help!
