### ISSUE TITLE
Having some implementing issue

### ISSUE THREAD

**Issue by ohakubi** [NightCatSama/vue-slider-component#293]
any example for the usage in the compute function? how to implement the slider in to function? use the fetched data on the slider?

**Comment by NightCatSama** [comment]
```vue
<vue-slider ref="slider3" v-bind="slider" v-model="slider.value"></vue-slider>
```

`v-bind` is the basic usage of the vue framework, can avoid writing too many properties on the template.

Related documents: <https://vuejs.org/v2/api/#v-bind>

**Comment by ohakubi** [comment]
okay, understand that part, what about inside the compute? the main problem, is putting the slider inside that "one" function.

**Comment by ohakubi** [comment]
and also it's look like this... https://imgur.com/a/6ma7kIw

**Comment by NightCatSama** [comment]
I don't know what you want to do

**Comment by ohakubi** [comment]
okay the problem is; I am trying to make two handle. So that's why I am giving two value. like this. 

```
data() {
        return {
            slider:{value:[0, 500]
```

but then the slider going weird. Actually with one handle there is no problem like below. I how can I use two handle? 

```
data() {
        return {
            slider:{value: 500}
```

**Comment by NightCatSama** [comment]
When the value is an array, it is two handle.
