### ISSUE TITLE
Snap to nearest ten?

### ISSUE THREAD

**Issue by creativejeff** [NightCatSama/vue-slider-component#294]
Hi! First of all. Wonderful slider we have here! Great job, really.

So my question is, is it possible to have a range of 0 - 100 and still be able to snap to the nearest 10?

Eg: slider is on 57 and the cursor is released now go to 60 and return 58, 59 and 60 while the slider goes to 60.

Second question, is it possible to only display each 10 in the label aswell in the toolTip? E.g we have a range of 0 - 100 but the toolTip and label only shows 0, 10, 20, 30 and so on..

I'm guessing there's no native support for this, but maybe someone has a clue how to achieve this?

Much thanks!!!

**Comment by NightCatSama** [comment]
The second one can be implemented, but the first one does not currently have this feature.

<https://jsfiddle.net/hw3kjo1r/>
