### ISSUE TITLE
import error; Props not work except 'value'

### ISSUE THREAD

**Issue by JesseBlackman** [NightCatSama/vue-slider-component#3]
I use it in my template file like this:
`import vueSlider from 'vue-slider-component';`
chrome console report error in /vue-slider-component/index.js:
`index.js?81fc:1 Uncaught SyntaxError: Unexpected token import`  
  
so I import like tihs:
`import vueSlider from 'vue-slider-component/vue2-slider.vue';`  
there is no error,and the slider appeared.but i set max,min props doesn't work.  

`import vueSlider from 'vue-slider-component/vue2-slider.vue';

export default {
  components: {
    vueSlider
  },
  data() {
    return {
      height: 10,
      min: 1,
      max: 5,
      val: 2
    }
  },
  methods: {
    getValue(value) {
      /* Two-way */
      this.val = value
    },
    setValue(num) {
      this.val = num
    }
  }
}

</script>`

**Comment by NightCatSama** [comment]
Thank you for your issue.

Direct use of the index.js is really have a problem, because cannot be used directly in node_modules es6 module method. I'll fix the bug as soon as possible.

and you set max,min props doesn't work. Can because there is no set width prop, because the default is to display: block, So you need to include the component parent element has a width or set the width prop.

**Comment by NightCatSama** [comment]
Can be used right now like this:
`import vueSlider from 'vue-slider-component'`

**Comment by JesseBlackman** [comment]
Thanks! I can import the mode directly by name now.but i still couldn't set the width,max,min props.
![screenshot from 2016-10-24 20-05-07](https://cloud.githubusercontent.com/assets/7440033/19645025/453eae62-9a25-11e6-825e-147e2d4f290f.png)  
![screenshot from 2016-10-24 20-05-23](https://cloud.githubusercontent.com/assets/7440033/19645052/66915eb6-9a25-11e6-8e48-7ae363b3f08f.png)

**Comment by NightCatSama** [comment]
Because you don't have the attribute is passed to the component.
Just like:
```js
<vue-slider :width="width" :min="min" :max="max" :val="val"></vue-slider>
...
data() {
  return {
    width: 150,
    min: 1,
    max: 5,
    val: 1
  }
}
```

or

```js
<vue-slider v-bind="options"></vue-slider>
...
data() {
  return {
    options: {
      width: 150,
      min: 1,
      max: 5,
      val: 1
    }
  }
}
```

**Comment by JesseBlackman** [comment]
Ah... I just started learning vue.js.  
Thank you for your work.

**Comment by NightCatSama** [comment]
you are welcome, i also thank you help me find the bug.

**Comment by JesseBlackman** [comment]
close
