### ISSUE TITLE
Static Dot Functionality

### ISSUE THREAD

**Issue by michaelpelletier** [NightCatSama/vue-slider-component#300]
I appreciate you merging [my PR](https://github.com/NightCatSama/vue-slider-component/pull/298)! But a change you made with it breaks what I was intending. 😢 

I wanted to be able to include a string for the Static Tooltip, but since you've combined the originalValue and originalLabel into a single staticValue property (which is admittedly cleaner) it doesn't give me the flexibility that I need. By reducing the input to simply the original value as a number, it isn't clear what it relates to. While the code says staticValue should accept a string, doing something like `staticValue: 'Original: 5%',` handles the tooltip correctly, but (naturally) breaks the static dot positioning. 

Maybe we can have a separate (optional) staticLabel property that falls back to staticValue if it is unused, but fills in the tooltip if it is? Happy to open another PR if that's easiest, but wanted to explain first.

**Comment by michaelpelletier** [comment]
Fixed with https://github.com/NightCatSama/vue-slider-component/pull/303. Thank you, @NightCatSama! 🎉❤️

**Comment by NightCatSama** [comment]
Thank you also for your contribution to the project. 🌹
