### ISSUE TITLE
Feature request: Allow dot-size to be any size

### ISSUE THREAD

**Issue by giftedprimate** [NightCatSama/vue-slider-component#304]
Currently we can only place a number in `dot-size` which is made into px. It would be nice to be able to use any size i.e. view port sizing, em, rem etc.

I am using CSS to do this but it is problematic due to the fact I have to use JQuery to center the dot based on the diff of the default size and the CSS size I have given it.

App this is implemented on is https://mathbot.com

Thanks!

**Comment by NightCatSama** [comment]
Sorry, you can only try to implement it with slot.

Because other units can't calculate the specific value very well.
