### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by DaanKouters** [NightCatSama/vue-slider-component#305]
On the 'moving' event i get this error in console:
`Unable to preventDefault inside passive event listener invocation.`

I can't find a way to solve this, do more people encounter this?

**Comment by NightCatSama** [comment]
https://github.com/NightCatSama/vue-slider-component/blob/master/src/vue2-slider.vue#L701

It seems that no one has ever encountered it after I added `{ passive: false }`.

**Comment by DaanKouters** [comment]
I'm sorry @NightCatSama for not coming back to you about this.
I totally overlooked a lib in the framework which took care of passive listeners. This was what throwed the error. Not vue=slider-component
