### ISSUE TITLE
Not correct value @click.native

### ISSUE THREAD

**Issue by Sabe67** [NightCatSama/vue-slider-component#306]
Hi,

When I click or drag my slider, it don't stop at the correct value.

As you can see on the attach file, the slider stop before my mouse.
![example](https://user-images.githubusercontent.com/13998579/52960700-a8695900-3399-11e9-87c9-621f9bcd5290.png)

**Comment by NightCatSama** [comment]
Maybe the location of the component has changed, you can try calling the refresh method.

Exception details <https://github.com/NightCatSama/vue-slider-component#exceptions>

**Comment by Sabe67** [comment]
Yeah thank you, now it's work.

I added this method on the updated hook and now it's fine.

I just don't know why the location change.

**Comment by NightCatSama** [comment]
May be asynchronous data causing layout changes.
