### ISSUE TITLE
min & max array Value

### ISSUE THREAD

**Issue by diadal** [NightCatSama/vue-slider-component#308]
is there any way to make this work I need to set different max for vote and %
<img width="342" alt="screenshot 2019-02-20 at 1 33 34 pm" src="https://user-images.githubusercontent.com/19895516/53092196-69abde00-3514-11e9-9333-ce64cf45bff3.png">

**Comment by NightCatSama** [comment]
Have you encountered any problems?

**Comment by diadal** [comment]
the percentage mix data is different from votes max data did you understand example 
max: 100 for % then max: 10000 for vote

**Comment by NightCatSama** [comment]
like this? <https://jsfiddle.net/tveqsm6u/>

**Comment by diadal** [comment]
sweet one more thing is there any to add two tooltip same slider to get something like this
<img width="315" alt="screenshot 2019-02-20 at 7 19 39 pm" src="https://user-images.githubusercontent.com/19895516/53114638-8a8c2780-3544-11e9-99d1-4377d672e663.png">

**Comment by diadal** [comment]
or I can I pass addition css to `vue-slider-always vue-slider-dot` `style="width: 0px; height: 0px; top: 0px; transition-duration: 0s; transform: translateX(89px);"`

**Comment by NightCatSama** [comment]
Now there is no way to display two tooltips in one slider except for manually writing css.

**Comment by diadal** [comment]
what about this how to add addition css to `vue-slider-always vue-slider-dot` or `margin-top` to `style="width: 0px; height: 0px; top: 0px; transition-duration: 0s; transform: translateX(89px);"`

**Comment by diadal** [comment]
this solve my issue `tooltip="always dot-class"`
