### ISSUE TITLE
delay after mouseclick on slider node

### ISSUE THREAD

**Issue by PsychicCat** [NightCatSama/vue-slider-component#31]
I can't seem to figure this out. Have you ever had the problem with a lag between the time you click the slider node and it registers the move? 

Sorry for the vague details but it is hard to reproduce this.

**Comment by NightCatSama** [comment]
Not very clear about the problems you are experiencing.

Is there a delay after dragging or clicking the slider to move?

tell me more information

**Comment by PsychicCat** [comment]
@NightCatSama actually, I think it only happens when I'm using hot modules in webpack. i will close this...

**Comment by sauraja** [comment]
I'm also getting the same issue. How to resolve please?
