### ISSUE TITLE
请问组件里面哪个函数是重置数据的？

### ISSUE THREAD

**Issue by hzcbeyond** [NightCatSama/vue-slider-component#312]

**Comment by NightCatSama** [comment]
你想重置什么

**Comment by hzcbeyond** [comment]
为什么第一下点首先回零或者是最大值，然后怎么拖怎么点都没反应，停留在0或者最大值，我现在是这个问题， 想请问一下这个问题在当时那个版本修复了吗 当前使用的版本 version v2.x.

**Comment by NightCatSama** [comment]
修复啦，你可以看看能不能升级下

不然的话可以用 `refresh` 方法重置组件

<https://github.com/NightCatSama/vue-slider-component/tree/v2#exceptions>

**Comment by NightCatSama** [comment]
在当时那个版本没修复，3.x 才修复的

**Comment by hzcbeyond** [comment]
请问一下 V3.0版本 输入数字改变拖动条的数值的函数是哪个？

**Comment by NightCatSama** [comment]
直接修改 value 的值就可以了。

<https://nightcatsama.github.io/vue-slider-component/#/zh-CN/advanced/input>

**Comment by hzcbeyond** [comment]
有没有内置的方法？  这个 syncValueByPos() 方法是内置改变方法吗  能否直接调用组件里面内置方法，传我需要改变的值过去。

**Comment by NightCatSama** [comment]
暂时只能通过 `this.$refs.slider.control.setValue` 设置了。

我晚上更新多个 `setValue` 方法上去吧。

**Comment by hzcbeyond** [comment]
如果数值超级大的话，组件是不是就不能用了   max: 975180480243.7943 ,   interval: 9751804802.437943,
error(Uncaught TypeError: Cannot read property 'disabled' of undefined)

**Comment by NightCatSama** [comment]
是的，数字类型是有上限的

**Comment by hzcbeyond** [comment]
那有什么方法能够解除这个上限吗？ 我需要用到比较大的数字。

**Comment by NightCatSama** [comment]
大数字会失去精度，你可以使用 Decimal.js 转字符串再使用。

我写了个例子：

<https://jsfiddle.net/NightCatSama/2xy72dod/10291/>

**Comment by NightCatSama** [comment]
@hzcbeyond 解决了吗

**Comment by hzcbeyond** [comment]
const MAX = new Decimal(8302007.9741)
const GAP = 100
const INTERVAL = MAX.dividedBy(GAP)
const DATA = Array.from(new Array(GAP + 1), (_, i) => INTERVAL.times(i).toString())
 data () {
    return {
    	value: DATA[0],
      options: {
        data: DATA
      }
    }
  },
请问是上面const定义 都需要用到 还是只用new Decimal（）的功能 转一下就行。

**Comment by NightCatSama** [comment]
上面的 `dividedBy, times, toString` 都是 `decimal.js` 的东西的

用 `decimal.js` 就是为了大数字计算的时候，避免失去精度。

**Comment by hzcbeyond** [comment]
就是我用了这个例子： https://jsfiddle.net/NightCatSama/2xy72dod/10291/  之后，
我调用  this.$refs.slider.control.setValue() 这个函数的时候，函数不起作用，不会更新value值;

**Comment by NightCatSama** [comment]
试试这样： <https://jsfiddle.net/NightCatSama/2xy72dod/10298/>

**Comment by hzcbeyond** [comment]
如果我是一个 输入框的话 输入值就更新进度条，应该怎么做呢？

**Comment by NightCatSama** [comment]
任意值吗，只有匹配上的值才行。。。

**Comment by hzcbeyond** [comment]
如果我不用decimal.js 的东西的话 是可以根据任意值更新进度条的，但是比较大数字传过去组件就用不了。
emmmmm... 我在试一下有没有别的方法。

**Comment by NightCatSama** [comment]
好吧

**Comment by hzcbeyond** [comment]
在请问一下 如果是这两个数字  max:3226952627.4788,   interval:32269526.274788,  为什么拉倒最后的时候会倒退到 初始的时候。

**Comment by NightCatSama** [comment]
应该是精度丢失，然后值匹配不上吧，我看拉到最大 value 变成了 3226952627.4788003。

然后多了 0.00000003 和 max 匹配不上

**Comment by hzcbeyond** [comment]
怎么能解决这种精度的问题，我把max值用了 decimal.js
