### ISSUE TITLE
Adding and deleting values dynamically after clicking the slider rail doesn't update the slider

### ISSUE THREAD

**Issue by panuchka** [NightCatSama/vue-slider-component#316]
#### Describe the bug

The slider works fine on updating values dynamically when array changes. However, there is a weird problem that happens when you **click** the slider bar/rail and then add/remove a new value. It seems that the slider doesn't update that way.

![slider-bug](https://user-images.githubusercontent.com/6607517/54135445-7ab88280-4422-11e9-917c-020cf2e17174.gif)

#### Additional context

This can be reproduced going to the example page:
https://nightcatsama.github.io/vue-slider-component/#/basics/simple
By copy pasting the code below into the 'Multiple sliders'-example. **You must also click the slider between 51-90 in the 10 second time period (do not drag!)**

```
<template>
  <div>
    <vue-slider v-model="value_2"></vue-slider>
    <vue-slider v-model="value_3"></vue-slider>
    <vue-slider v-model="value_4"></vue-slider>
  </div>
</template>

<script>
  module.exports = {
    components: {
      VueSlider
    },
    data: function () {
      return {
        value_2: [0, 50],
        value_3: [0, 50, 80],
        value_4: [0, 50, 80, 100],
      }
    },
    mounted() {
      console.log('click between 51-90 on value_2 slider before the timeout triggers')
      console.log('value_2', this.value_2)
      setTimeout(() => {
        this.value_2.push(99)
        console.log('value_2', this.value_2)
      }, 10000)
    }
  }
</script>
```

#### Environment

 - Windows 10
 - Vue version: 2.6.8.
 - Component Version: 3.0.7.

**Comment by NightCatSama** [comment]
Thank you for your feedback.

this is the missing bug in the previous version.

please update to `3.0.8`.

**Comment by panuchka** [comment]
Yeap, seems working! Thank you again for the quick fix!
