### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by anneangersbach** [NightCatSama/vue-slider-component#32]
Hi.... 

in the documentation it says **real-time**, however you use **realTime**.

**Comment by NightCatSama** [comment]
Use is like that, you can look at this
[https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case](https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case)

**Comment by anneangersbach** [comment]
thanks for pointing that out... however the kebab-case didn't work for me... then again,.... maybe I need to ask my colleague about our linter ;)

**Comment by NightCatSama** [comment]
What is the specific performance? can't drag and drop, or unable to initialize components.

**Comment by anneangersbach** [comment]
It works fine... I just had syntax trouble - and when I did it right with "real-time" instead of realTime it was just our eslint that was angry. So you can close this. Just my inexperience with vue.
