### ISSUE TITLE
Not able to style marks in slider

### ISSUE THREAD

**Issue by rishabhgoel9797** [NightCatSama/vue-slider-component#322]
![Screenshot 2019-03-15 at 11 15 22 AM](https://user-images.githubusercontent.com/22225114/54411048-f14fcb80-4713-11e9-8e9b-df47bc7c3132.png)

**Comment by NightCatSama** [comment]
You can refer to this example.

<https://nightcatsama.github.io/vue-slider-component/#/basics/marks>
