### ISSUE TITLE
Wrong display on range with float

### ISSUE THREAD

**Issue by gregurco** [NightCatSama/vue-slider-component#323]
#### Describe the bug

Hello!
There is a wrong display of range slider if `min` or `max` is float value. The slider is simply gray and it's impossible to change any values.

Screen:
![Selection_793](https://user-images.githubusercontent.com/4052904/54480815-01f86280-4836-11e9-949e-41082a890320.png)

Example: 
https://jsfiddle.net/nmcxpzks/2/

#### Environment (If you feel unrelated, please delete the block)

 - Vue version: v2.5
 - Component Version: latest

Thanks.

**Comment by NightCatSama** [comment]
Because `interval` defaults to 1, floating point cannot be divisible.

<https://jsfiddle.net/2ehrwfgk/>

**Comment by gregurco** [comment]
@NightCatSama thanks :+1:
