### ISSUE TITLE
Variable range sliders

### ISSUE THREAD

**Issue by gflohr** [NightCatSama/vue-slider-component#324]
#### Describe the feature

Variable range sliders would be cool.

#### Describe the solution you'd like

I want to start with a slider that goes from 0 at the left to for example 100 at the right. When the slider gets closer to the upper bound of the range, the range should automatically be extended so that I can actually enter arbitrarily large values.

Implementing that without making the slider jump is probably not trivial. But maybe you have an idea.

**Comment by NightCatSama** [comment]
I can't think of how to achieve it.

**Comment by gflohr** [comment]
Don't worry. I'll have a try myself. I'll reopen the issue, when I find a solution.
