### ISSUE TITLE
Label for value

### ISSUE THREAD

**Issue by KevinJordil** [NightCatSama/vue-slider-component#325]
#### Describe the feature

To be able to add a label to the value
When we move the cursor, the label is displayed instead of the current value

#### Describe the solution you'd like

An array for :data with the value and the label

**Comment by NightCatSama** [comment]
Show label on `tooltip`?

e.g. <https://jsfiddle.net/NightCatSama/2xy72dod/10324/>

**Comment by lenic10** [comment]
I think I had the same issue.
This is how i solved it: https://jsfiddle.net/07j85mkg/

**Comment by NightCatSama** [comment]
@lenic10 oops. I have never thought about this usage 😄

**Comment by KevinJordil** [comment]
@lenic10 Thank you. That's exactly what I needed.
