### ISSUE TITLE
How to disable styles?

### ISSUE THREAD

**Issue by Sergey-Ssn** [NightCatSama/vue-slider-component#326]
Hi,
I want to disable CSS styles plugin, I do not see a way to do it?

**Comment by NightCatSama** [comment]
What is CSS styles plugin?

**Comment by Sergey-Ssn** [comment]
> 
> 
> What is CSS styles plugin?

vue-slider-component , can I disable styles?

**Comment by NightCatSama** [comment]
What do you want to do, whether it is a style with the slider disabled or not using the default style of the slider?

**Comment by Sergey-Ssn** [comment]
not using the default style of the slider  https://yadi.sk/i/p0XVuOLLauGBAg

I use my own styles and I don't need to load slider styles doing the double work of overriding css

**Comment by NightCatSama** [comment]
Version 2.0 is not easy to rewrite styles, you can upgrade to version 3.0.


You can refer <https://nightcatsama.github.io/vue-slider-component/#/style>

**Comment by Sergey-Ssn** [comment]
> 
> 
> Version 2.0 is not easy to rewrite styles, you can upgrade to version 3.0.
> 
> You can refer https://nightcatsama.github.io/vue-slider-component/#/style

Yes version 3 solved my problem, thanks
