### ISSUE TITLE
Slider thinks it's in it's old position when a new Bootstrap column is added

### ISSUE THREAD

**Issue by adamzerner** [NightCatSama/vue-slider-component#327]
## Describe the bug

Slider in second column doesn't slide when a third column is added and the Bootstrap column class changes from `col-sm-6` to `col-lg-4`.

## Additional context

Here is a gif demo:

![vue-slider-component-issue](https://user-images.githubusercontent.com/3144254/54848084-85cea680-4c9d-11e9-98f8-8be921f89df2.gif)

Some notes:

- The second slider seems to think that it is still in it's initial position. Because when the mouse position is where the second slider previously was, it starts to move.
- The issue goes away once you resize the window. Even slightly.

Somehow I wasn't able to reproduce it. My code is almost _exactly_ the same as the code I have in the CodePen though. I'll share both.

### My code

**index.html**
```
<!DOCTYPE html>
<html>
  <head>
    <title>Premium Poker Tools</title>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```

**main.js**
```
require('bootstrap');

import Vue from 'vue';
import App from './App';

new Vue({
  el: '#app',
  template: '<App/>',
  components: { App }
});
```

**App.vue**
```
<template>
  <div id="app">
    <div class="container">
      <div class="row">
        <div v-bind:class="columnClass" v-for="(player, playerIndex) in players">
          <vue-slider
            v-model="player.value"
            v-bind="sliderOptions"
          >
          </vue-slider>
        </div>
      </div>
      <button class="btn btn-default" v-on:click="players.push({ value: 0 })">
        Add player
      </button>
    </div>
  </div>
</template>

<script>
  import VueSlider from 'vue-slider-component';

  export default {
    name: 'app',
    data: function () {
      return {
        sliderOptions: {
          dotSize: 16,
        },
        players: [{
          value: 0,
        }, {
          value: 0,
        }],
      };
    },
    computed: {
      columnClass: function () {
        if (this.players.length === 2 || this.players.length === 4) {
          return 'col-md-6';
        }

        return 'col-lg-4';
      },
    },
    components: {
      'vue-slider': VueSlider,
    },
  };
</script>

<style lang="scss">
  $icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
  @import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";
</style>
```

### CodePen

I was unable to reproduce it with the CodePen even though the code is almost exactly the same is the code I have above.

https://codepen.io/anon/pen/NJezzv?editors=1010

**HTML**
```
<div id="app">
  <div class="container">
    <div class="row">
      <div v-bind:class="colClass" v-for="(player, playerIndex) in players">
        <vue-slider
          v-model="player.value"
          v-bind="options"
        ></vue-slider>
      </div>
    </div>
    <button class="btn btn-default" v-on:click="addPlayer()">
      Add player
    </button>
  </div>
</div>
```

**JS**
```
new Vue( {
  el: '#app',
  data () {
    return {
    	players: [{
        value: 0,
      }, {
        value: 0,
      }],
      options: {
        dotSize: 16,
      },
    };
  },
  computed: {
    colClass: function () {
      if (this.players.length === 2) {
        return 'col-md-6';
      } else {
        return 'col-lg-4';
      }
		},
  },
  methods: {
  	addPlayer: function () {
      this.players.push({
        value: 0,
      });
    },
  },
  components: {
    'vueSlider': window[ 'vue-slider-component' ],
  }
})
```

## Environment

 - OS & Version: MacOS 10.14.3
 - Vue version: 2.5.21 (`"vue": "^2.5.21",` in `package.json`)
 - Component Version: 2.8.14 (`"vue-slider-component": "^2.8.14",` in `package.json`)

**Comment by NightCatSama** [comment]
In version 2.x you may need to call the `refresh` method after rendering.

The specific reason can be seen here: <https://github.com/NightCatSama/vue-slider-component/tree/v2#exceptions>

I suggest you upgrade the [3.x](https://github.com/NightCatSama/vue-slider-component) version and fix this exception.
