### ISSUE TITLE
refresh function missing

### ISSUE THREAD

**Issue by desthercz** [NightCatSama/vue-slider-component#328]
Hi, refresh function from v2 no longer works. It seems to be removed. Is there any reason for this? I used it for restarting the component in certain situations and now i am unable to.

 - Component Version: v3.0.16

**Comment by NightCatSama** [comment]
What data do you want to reset?

**Comment by senner007** [comment]
I need a refresh function as well. There is some strange behavior when the visibility of the slider is toggled. The vue-slider-dot translate goes to minus. What I basically need is a function that recalculates the translate x when it reappears on the screen

**Comment by NightCatSama** [comment]
In version 3.0, most of the slider's properties are generated by `get`, so when `prop` changes, it changes automatically. I don't know what I can refresh.

I hope to have an online example to reproduce it.

@desthercz @senner007

**Comment by senner007** [comment]
More info : It happens when the container element display is set to none and the window is resized.  
I will try to reproduce with an example

**Comment by senner008** [comment]
Sorry I can not reproduce the bug. It seems to be fixed in the latest version

**Comment by NightCatSama** [comment]
I closed the issue.

If there is still a problem, open it again.
