### ISSUE TITLE
能够给进度条添加slot?  can you provide a slot for process?

### ISSUE THREAD

**Issue by pangao66** [NightCatSama/vue-slider-component#329]
能够给进度条添加slot ?   can you provide a slot for process?
![QQ截图20190327111936](https://user-images.githubusercontent.com/20113031/55048396-fc471c00-5082-11e9-967a-ec627668b439.png)
如图, 需要在进度条上显示 结果, 难以定位 需要提供 进度条的slot
as this picture , I need to show the result on the processBar  , now I can't get the position for it ,so it will be provide a slot for the process bar

**Comment by NightCatSama** [comment]
Added process slot in version `3.0.17`.

document: <https://nightcatsama.github.io/vue-slider-component/#/zh-CN/api/slots>

example: <https://nightcatsama.github.io/vue-slider-component/#/zh-CN/advanced/components-slots>

**Comment by pangao66** [comment]
![image](https://user-images.githubusercontent.com/20113031/55131780-f6bd0500-515a-11e9-9048-8fdc80cde923.png)

**Comment by phuclh** [comment]
@NightCatSama how can I use slot process for multiple sliders? Something like this:

![demo](https://user-images.githubusercontent.com/6707194/64055221-fe386e00-cb3f-11e9-97a3-477fff09d512.jpg)

**Comment by NightCatSama** [comment]
@phuclh Slot process added index parameter in version 3.0.40.

Can refer to this example:

<https://nightcatsama.github.io/vue-slider-component/#/advanced/components-slots?hash=process-slot>

**Comment by phuclh** [comment]
@NightCatSama that's super cool. Thank you so much!!!
