### ISSUE TITLE
Will you add piecewise labels?

### ISSUE THREAD

**Issue by anneangersbach** [NightCatSama/vue-slider-component#33]
Hey, so I find the piecewise slider very very useful. Will you add labels that are visible before the user selects a step?
Like this:
![image](https://cloud.githubusercontent.com/assets/161883/24206214/dc2da6b2-0f1d-11e7-89c4-c4df35c34228.png)

**Comment by NightCatSama** [comment]
That's a good idea,  I'll add the prop to control display labels.

**Comment by NightCatSama** [comment]
i add prop `:piecewise-label="true"` to display labels, just like: [https://nightcatsama.github.io/vue-slider-component/example/#demo2](https://nightcatsama.github.io/vue-slider-component/example/#demo2)

**Comment by anneangersbach** [comment]
very cool! Thank you! :)
