### ISSUE TITLE
Is it possible to make dot stick to values multiple of interval while dragging?

### ISSUE THREAD

**Issue by i-v-k** [NightCatSama/vue-slider-component#330]
I have an interval=10 and while I drag I dont want dot to move on any value between 0, 10, 20, 30, 40, 50 and so on. So that dot will stick to values only multiple of interval and dont move at all on other values while dragging. Thanx in advance!

**Comment by NightCatSama** [comment]
In the `v3.0.19`, the `adsorb` property has been added to achieve this effect. 😄 

<https://nightcatsama.github.io/vue-slider-component/#/basics/simple?hash=adsorb>

**Comment by i-v-k** [comment]
Great, thanx!
you are simply the best! 😄
