### ISSUE TITLE
Vertical slider is misaligned when dragging not on top of the page

### ISSUE THREAD

**Issue by awaken1ng** [NightCatSama/vue-slider-component#331]
As per title, vertical slider is misaligned when dragging not on top of the page
![](https://user-images.githubusercontent.com/20689137/55150546-e7e84980-517e-11e9-9b77-faeeca2c9a52.gif)
https://jsfiddle.net/82s1jat4/

v2 had `realTime` option which I used to fix this before, but now unavailable in v3
Browser is Firefox, haven't tested in Chrome

**Comment by NightCatSama** [comment]
Thank you for your feedback, fixed in version `3.0.21`.

**Comment by awaken1ng** [comment]
It is indeed, thank you for the quick fix
