### ISSUE TITLE
Unable to move slider dot on iOS devices 

### ISSUE THREAD

**Issue by twisterio-official** [NightCatSama/vue-slider-component#332]
#### Describe the bug

I am using Vue slider component (v 3.x) and I have noticed strange bug on iOS devices. Sometimes, I just cant move our slider dot. I tried to remove all of my custom props and styles, but it does not help. Also I have noticed, that I cant focus on `.vue-slider-dot`. Unfortunately, there are no certain steps to reproduce this issue, but following information could be useful:

- Vue version 2.5.17;
- Component Version 3.0.12, also tried with 3.0.19 and 2.8.14, same issue;
- iOS 11 and lower. **On iOS 12 and later we can`t reproduce this issue**;
- Browser Safari.

Any suggestions about it?

**Comment by NightCatSama** [comment]
I don't have a device debugging that is smaller than ios12. Is there an error?

**Comment by twisterio-official** [comment]
No, there are no errors in console

**Comment by alikkane** [comment]
Doesn't work on mobile, any help ?

**Comment by NightCatSama** [comment]
I failed to reproduce this error in the emulator (iPhone7+, iOS10.2) 😢 .

**Comment by twisterio-official** [comment]
Solved the problem. I`ve noticed, that demo at jsfiddle works perfectly, so I`ve assumed that the problem is in my build. After updating laravel mix slider works good at iOS mobile devices

**Comment by NightCatSama** [comment]
I am glad to hear this news. 😄

I closed this issue, and if someone has encountered this situation, can open another issue.
