### ISSUE TITLE
IE11 Object doesnt support property or method 'includes'

### ISSUE THREAD

**Issue by Tmilly** [NightCatSama/vue-slider-component#334]
I am unable to get vue-slider to work on IE, only error I have is that 'Object doesn't support property or method includes' which IE does not support. Does the newest version of vue-slider
not support IE? I can see in the source code that there are some examples of .includes() instead of indexOf().

 - Vue-Slider v3.0.21

**Comment by NightCatSama** [comment]
Already fixed in version 3.0.22.

**Comment by Tmilly** [comment]
Cheers,
Thanks for the promptly reply and the quick fix. I appreciate it!
