### ISSUE TITLE
[v2] reaction with googlemap

### ISSUE THREAD

**Issue by theara72** [NightCatSama/vue-slider-component#336]
#### Describe the bug

while i try to use it with googlemap v3, googlemap react on this plugin change value.
this reaction make whole current component slow down.
i use vuejs 2.5.17.

please kindly check this issue.

**Comment by NightCatSama** [comment]
Is it possible because the value changes too fast?

You can try using the setting `lazy` equal to `true`.

**Comment by theara72** [comment]
it work great. thank

**Comment by theara72** [comment]
sorry, but let check this.
![ezgif-5-b51575efe330](https://user-images.githubusercontent.com/16434941/55449790-ce1b8c00-55ee-11e9-9691-850157a3ee6d.gif)

**Comment by NightCatSama** [comment]
In fact, the component is concerned with changes in values, you can use `@change` to monitor if there is a problem with the change in value. 

`googlemap` rendering problems you have to debug yourself.

**Comment by theara72** [comment]
i found cause of issue is i initialize map many time in same component.
