### ISSUE TITLE
tooltipPlacement not support array string. Ex. :tooltipPlacement ="['right', 'left']"

### ISSUE THREAD

**Issue by ponleukea** [NightCatSama/vue-slider-component#338]
#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: [e.g. macOS, Windows, Linux]
 - Vue version: [e.g. v2.0, v2.5, v2.6]
 - Component Version: [e.g. v3.0.2]

**Comment by NightCatSama** [comment]
Thank you for your feedback, fixed in `v3.0.25`.

**Comment by ponleukea** [comment]
Thank you now is done 😄 .
