### ISSUE TITLE
How can i pass the object in marks 

### ISSUE THREAD

**Issue by rishabhgoel9797** [NightCatSama/vue-slider-component#341]
`ages: {
        '0': 'All+',
        '1': '7+',
        '2': '13+',
        '3': '16+',
        '4': '18+'
      },`

I want to pass this object in marks and want to have v-model to keys as 0, 1, 2, 3 etc. The problem is its working but the spacing between the marks is taking the difference of keys (which is 2-1=3-1 =1). I want to have custom equal spacing between all. Please help asap
![Screenshot 2019-04-09 at 3 39 21 PM](https://user-images.githubusercontent.com/22225114/55792210-c7ed4a00-5add-11e9-91cf-af06b1309c22.png)

**Comment by NightCatSama** [comment]
Try setting `max = 4`?

**Comment by rishabhgoel9797** [comment]
It worked perfectly. One more thing i need to ask i want to leave one interval and then start

**Comment by NightCatSama** [comment]
I don't know if you want specific features, you can try `min = -1`.
