### ISSUE TITLE
How can I pass dates?

### ISSUE THREAD

**Issue by mawieutc** [NightCatSama/vue-slider-component#344]
I would like to pass dates, for the user to chose a period of time. the default values would be from 'today' to 'in one year'.
Is there any possibility to do this?
Thanks in advance,
Marie

**Comment by NightCatSama** [comment]
You can switch to a numeric type first.

e.g. <https://jsfiddle.net/NightCatSama/2xy72dod/10366/>

**Comment by mawieutc** [comment]
Thank you very much!
