### ISSUE TITLE
Support multiple ranges in a slider?

### ISSUE THREAD

**Issue by tomlla** [NightCatSama/vue-slider-component#347]
Hi. @NightCatSama .
Thanks for creating vue-slider-component!!
Especially it is usefull for  admin web page, setting page etc...
This is awesome, practical component, and it has sophisticated programing interface.

#### Describe the feature

I'd like to create multiple ranges slider in my application.
like this

```
|----◆====range-1=====◆------◆====range-2====◆-------|
```

#### Describe the solution you'd like
I think `vue-slider-component` implements these behaviors for supporting multiple ranges 

1. When `:value` receives `Array<Array<Number, Number>>`, `vue-component-slider` renders multiple ranges in the slider. 
  `<vue-slider :value="[[10, 20], [30, 40]]">`
2. Each dots doesn't overlay adjacent range.

#### Additional context (If there is no relevant content, please delete the block)
let me know other workaronds/solutions if exists on vue-component-slider.

Should i create another compnent that supports multiple ranges in a slider. :thinking:

**Comment by NightCatSama** [comment]
You can do this with `v-model="[10, 20, 30, 40]"` and `process`

e.g.  https://jsfiddle.net/NightCatSama/2xy72dod/10375/

**Comment by tomlla** [comment]
omg..! thank you!!!  :+1: :+1: :+1: :+1: :+1: 
That is what I had been looking for!

---

> Each dots doesn't overlay adjacent range.

Your example doesn't meet this requirement.

But I got to stop overlay using `enableCross: false`. :smile:
