### ISSUE TITLE
Mark objects don't seem to work when data is Array<number>

### ISSUE THREAD

**Issue by jdnz** [NightCatSama/vue-slider-component#348]
For custom data that is an array of strings, e.g.,

```<vue-slider v-model="value1" :data="['0', '1']" :marks="{'0': 'start', '1':'end'}"></vue-slider>```

the marks object works as expect. But for an array of numbers

```<vue-slider v-model="value1" :data="[0, 1]" :marks="{'0': 'start', '1':'end'}"></vue-slider>```

the marks all appear at the start of the slider.

**Comment by NightCatSama** [comment]
There is no way, the key of the object is not support the number type.

It is recommended that you pass the `mark` with the `Function` type.

e.g. <https://jsfiddle.net/cLrfdsgm/>

**Comment by jdnz** [comment]
Thanks, using a function would work in my case. I guess I just expected it to work since when there is no custom data it works. And in that case I thought the data would be just an array of numbers from 0 to 100. Is it that in the default case the numerical values are internally represented as strings?

**Comment by NightCatSama** [comment]
When using `data`, if you pass `mark` using an object type, only string types are supported. 

But by default case (`min`/`max`...), the key of the object will be converted to a numeric type.

https://github.com/NightCatSama/vue-slider-component/blob/00af0b1a18104fbe4234faa2ae16c0c15c6df072/lib/utils/control.ts#L380-L383

It is easy to see that if data is present and `data` is of type `Array<number>`, the index cannot be obtained using `indexOf`. (e.g. `[0, 1].indexOf("0") // -1`)

**Comment by jdnz** [comment]
Right. To me it would make sense if val was first converted to numeric type when data is of numeric type. Then the mark object would work the same way in both cases to avoid confusion. But I'm not sure how that affects the rest of the code.

**Comment by NightCatSama** [comment]
The `data`  is an object type and cannot be directly said to be a number or a string type, as it may exist. (e.g. `:data="[-1, '-1', 0, '0']"`)

**Comment by jdnz** [comment]
Ah ok, I hadn't really thought about mixed types in the data. I guess there could a be a check that all the data is numeric and in that case convert, but perhaps it is too specific.

**Comment by mrleblanc101** [comment]
This is very confusing.
Currently I have: 
```
:data="[33, 66, 100]"
:marks="{ '33': 'Faible', '66': 'Moyen', '100': 'Fort' }"
```
which result in this:
<img width="304" alt="Capture d’écran, le 2021-06-11 à 14 33 57" src="https://user-images.githubusercontent.com/17392251/121733916-1897cd80-cac2-11eb-951f-b6e5bd315dcf.png">
but i don't want to convert all my value to String. I don't think String and Number mixed type should be supported. So converting the key to a number for the comparaison wouldn't be an issue, no ?

**Comment by mrleblanc101** [comment]
Otherwise, could we get an Array type for marks ? 
We wouldn't need to define key as we could simply use the index, no ?
For example:
```
:data="[33, 66, 100]"
:marks="[ 'Faible', 'Moyen', 'Fort' ]"
```

**Comment by mrleblanc101** [comment]
Seem like this should work:
```
  :data="[
      {
          label: 'Aucun',
          value: 0,
      },
      {
          label: 'Faible',
          value: 33,
      },
      {
          label: 'Moyen',
          value: 66,
      },
      {
          label: 'Fort',
          value: 100,
      },
  ]"
```
but now I can't select the element «Aucun» with a value of 0. When I inspect with the Vue-devtools, a value is emited from `0` to `33`, but not from `33` to `0`.

**Comment by mrleblanc101** [comment]
Sorry, I think I found out.
I'm not sure why but seems like using `v-bind="$attrs" v-on="$listeners` with a wrapper component wasn't working.
I've changed for : `:value="value" @change="$emit('input', $event)"` and everything work fine now.
