### ISSUE TITLE
max-value won't be applied to slider position

### ISSUE THREAD

**Issue by christianmalek** [NightCatSama/vue-slider-component#35]
If I change the `max` value, the position of the slider won't be changed. This results in two problems:
1. The position of the slider doesn't represent the correct value.
2. If the `max` value has been changed before clicking on the slider the slider will update. This results in unpredictable value changes.

Example:
Let's imagine there is a slider-component with `min=0` and `max=100`. I set the slider to `50`.
![image](https://cloud.githubusercontent.com/assets/2873986/24490261/16e2ae1a-1522-11e7-99bb-f202ae065278.png)

Then I set `max=50`. As you can see the slider didn't change (visually).

![image](https://cloud.githubusercontent.com/assets/2873986/24490315/6376475a-1522-11e7-8abf-f7fbb8cd7e93.png)

If I now just click on the slider it would change the value to `25`.

![image](https://cloud.githubusercontent.com/assets/2873986/24490322/6c6f4c58-1522-11e7-8081-89f6d2665685.png)

Do you have a solution for this problem?

**Comment by NightCatSama** [comment]
You can try to call the `refresh` method after set the `max`.

**Comment by NightCatSama** [comment]
just like:
```js
this.max = 50
this.$nextTick(() => {
  this.$refs.slider.refresh()
})
```

**Comment by christianmalek** [comment]
@NightCatSama Where exactly should I call this? And what is `this.$refs.slider`? I have no reference to that. Sorry, I'm pretty new to Vue.

**Comment by NightCatSama** [comment]
you can look at the official documentation: [https://vuejs.org/v2/guide/components.html#Child-Component-Refs](https://vuejs.org/v2/guide/components.html#Child-Component-Refs).

example :
```js
<vue-slider ref="slider" v-model="val" :max="max"></vue-slider>
```

**Comment by NightCatSama** [comment]
And I will push a new version later, automatically to monitor the change of the Max and min calls refresh.

**Comment by christianmalek** [comment]
@NightCatSama
> you can look at the official documentation: https://vuejs.org/v2/guide/components.html#Child-Component-Refs.

Thanks. I overlooked this part in the documentation.

> And I will push a new version later, automatically to monitor the change of the Max and min calls refresh.

Then I will just wait. Thank you. Your component is awesome!

**Comment by NightCatSama** [comment]
Now correctly in @ 2.2.3 version of listening to the `max` and `min` change.

**Comment by christianmalek** [comment]
@NightCatSama Works like a charm. Thanks!
