### ISSUE TITLE
I want to pass a object in marks but doesn't looks good

### ISSUE THREAD

**Issue by rishabhgoel9797** [NightCatSama/vue-slider-component#350]
`ageGroup: {
        '0': '0',
        '1': 'All',
        '2': '7+',
        '4': '13+',
        '5': '16+',
        '7': '18+'
      },`

I want to pass this object but this doesn't looks as per the requirements. It should have equal spacing in between and tooltip should show All, 13+, etc. Please check it.
![Screenshot 2019-04-22 at 12 53 42 PM](https://user-images.githubusercontent.com/22225114/56488968-c1a79680-64fd-11e9-8908-42d0e12d8f66.png)

**Comment by NightCatSama** [comment]
Please provide all the parameters you passed.

**Comment by rishabhgoel9797** [comment]
`options: {
        dotSize: 24,
        width: 'auto',
        height: 8,
        backgroundColor: 'black',
        direction: 'ltr',
        min: 0,
        max: 6,
        interval: 1,
        disabled: false,
        clickable: true,
        duration: 0.5,
        lazy: false,
        tooltip: 'focus',
        tooltipPlacement: 'top',
        tooltipFormatter: void 0,
        useKeyboard: true,
        enableCross: true,
      }`

**Comment by NightCatSama** [comment]
And `mark = ageGroup`, right?

The key of mark corresponds to the value on the component, why `max = 6` but there is `'7': '18+'`. And there is no definition of `3`, so the spacing between 2 and 4 will be longer.

You can use `data`, e.g. <https://jsfiddle.net/NightCatSama/2xy72dod/10388/>

**Comment by rishabhgoel9797** [comment]
Yes. Worked Fine just tell me one more thing where i can put my other options and how can i show those keys(All, 13+, etc.) in tooltip

**Comment by NightCatSama** [comment]
You can try `tooltipFormatter: val => this.ageGroup[val]`.

**Comment by NightCatSama** [comment]
I fixed the `mark` is an object, `include` does not work. in version 3.0.30.

I wrote an example of whether this is what you need.

e.g. <https://jsfiddle.net/NightCatSama/2xy72dod/10400/>

**Comment by NightCatSama** [comment]
If you need the same interval then use `data`.

Just like the example I wrote before.

**Comment by rishabhgoel9797** [comment]
Thanks Bud it worked perfectly fine

**Comment by NightCatSama** [comment]
Is the value empty?

**Comment by rishabhgoel9797** [comment]
So i just wanted to leave equal space at beginning thats why i assigned to 0 but instead no value should be passed

**Comment by NightCatSama** [comment]
like this? <https://jsfiddle.net/NightCatSama/2xy72dod/10406/>

**Comment by rishabhgoel9797** [comment]
Yes. But the spacing is not equal now

**Comment by rishabhgoel9797** [comment]
The point is i want to start leaving some space in left

**Comment by NightCatSama** [comment]
I have done my best.

<https://jsfiddle.net/od0xzkfj/>

**Comment by rishabhgoel9797** [comment]
Perfect this is what i am exactly looking for. Thanks a lot
