### ISSUE TITLE
Different intervals on multiple sliders

### ISSUE THREAD

**Issue by vuktomic** [NightCatSama/vue-slider-component#351]
Hi, is it possible to add different intervals on multiple sliders?

For example, on a single slider, I can set the following:
```
<vue-slider
    v-model="value"
    :interval="(value < 20) ? 1 : 10"
    :max="100"
></vue-slider>
```
That would set the interval to 1 if the current value of the slider is less than 20, and 10 if it is above.

Is it possible to achieve the same with multiple sliders? Is it possible to pass the currently selected slider into `:interval`?

Thanks!

**Comment by NightCatSama** [comment]
Is it like this?

<https://jsfiddle.net/NightCatSama/2xy72dod/10415/>

**Comment by vuktomic** [comment]
Yes, that is exactly what I need, but with two values, is that possible?

**Comment by NightCatSama** [comment]
What are the two values? Two sliders?

**Comment by vuktomic** [comment]
I meant two points on the same slider, but your solution works perfectly, so the issue is solved.

Thanks a lot for your help!

**Comment by NightCatSama** [comment]
Passing values using arrays is fine.

<https://jsfiddle.net/NightCatSama/2xy72dod/10417/>
