### ISSUE TITLE
IE11 render error : "TypeError: Object doesn't support property or method 'from'"

### ISSUE THREAD

**Issue by Pistil-Studio** [NightCatSama/vue-slider-component#353]
Thx for your work

#### Describe the bug

render error only ie ie11 (tested on ie Edge and real browsers).

#### Additional context (If there is no relevant content, please delete the block)

<img width="1025" alt="Capture d’écran 2019-04-29 à 12 35 25" src="https://user-images.githubusercontent.com/6927671/56890997-4e60d000-6a7b-11e9-96cd-fac205726ade.png">

 - OS & Version: [e.g.Windows]
 - Vue version: [e.g.  v2.6]
 - Component Version: [e.g. v3.0.28]

**Comment by NightCatSama** [comment]
Thanks for the feedback, fixed in version `3.0.31`

**Comment by Pistil-Studio** [comment]
you are the boss. Thx a lot it work like a charm
