### ISSUE TITLE
Required Tag

### ISSUE THREAD

**Issue by TP18** [NightCatSama/vue-slider-component#354]
#### "Required" to select a value like a radio button gruop

I am trying to make a mood slider from 1-5; currently i just set the default at 3. it would be great if the default would not be set and that the user has to adjust the slider to his mood rating. 1-5 if he doesn't use the slider then a required alert would come similar to textarea/dropdown/radio buttons.
#### Describe the solution you'd like

a required tag to that the user has to set some data between 1-5 for example.

**Comment by TP18** [comment]
what do you think?

**Comment by NightCatSama** [comment]
I don't think this is what the component should do, you can judge by adding a variable, such as `@change="isChange = true".

**Comment by TP18** [comment]
ok thanks!
