### ISSUE TITLE
Range mode - Detecting which handle is dragged 

### ISSUE THREAD

**Issue by jjones3535a** [NightCatSama/vue-slider-component#355]
When using Range Mode, is it possible to detect which handle is being dragged?  The left or the right one?

**Comment by NightCatSama** [comment]
Can be obtained by `focusDotIndex`.

```vue
<vue-slider ref="slider" />
```
```ts
const activeDotIndex = this.$refs.slider.focusDotIndex
```

**Comment by jjones3535a** [comment]
That works perfectly!  Thank you for creating this wonderful library.  Very much appreciated.
