### ISSUE TITLE
Bound value is sometimes undefined

### ISSUE THREAD

**Issue by Christilut** [NightCatSama/vue-slider-component#356]
#### Describe the bug

I have the range slider initialized with value `[0, 5]` but sometimes it appears that the value is `undefined`. I think this should never be possible right? Is there a situation that can cause the bound value on v-model to change to undefined?

Now I have to explicitly check if `value !== undefined` before using it.

#### Environment

 - OS & Version: macOS, Chrome 73
 - Vue version: 2.6.10
 - Component Version: 3.0.31

**Comment by NightCatSama** [comment]
Is it because your value is set asynchronously?

Maybe you can try `v-if`, like `<vue-slider v-if="value !==  undefined" v-model="value" />`

**Comment by Christilut** [comment]
Okay this was a completely unrelated bug in my code causing this that I figured out 1 minute after writing this, thanks! :)
