### ISSUE TITLE
[v2] Uncaught TypeError: Super expression must either be null or a function 

### ISSUE THREAD

**Issue by Tribunal51** [NightCatSama/vue-slider-component#359]
#### Describe the bug

I got this error but the slider shows up fine
![image](https://user-images.githubusercontent.com/26390741/57612925-6ad23180-757e-11e9-9422-9220a46047f8.png)

![image](https://user-images.githubusercontent.com/26390741/57612899-5aba5200-757e-11e9-96e7-4f346b8cca5a.png)

Also if I want to change the styling of the value displayed over the thumb tack, what parameter do I change?

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: [Windows]
 - Vue version: [v2.5,]
 - Component Version: [e.g. v3.0.31]

**Comment by NightCatSama** [comment]
How do you use it?

Does thumb tack mean tooltip? you can modify styles using `tooltip-style`.

**Comment by Tribunal51** [comment]
The issue is resolved, I included the script for the slider in the blade file by mistake along with defining it in the vue component creating a cyclic import loop. 
Thank you for this amazing component.

**Comment by ashikalgar** [comment]
@Tribunal51: Hello
Which script you have added for slider and where we can found 'blade ' file.
I am also getting issue like this and it is getting after upgrading latest version of **'vue-slider-component'** 
**Error Msg:** Uncaught TypeError: Super expression must either be null or a function
