### ISSUE TITLE
滑动组建在vue-router下会出错

### ISSUE THREAD

**Issue by cmideal** [NightCatSama/vue-slider-component#36]
拖动一点，就会变成0或者100，然后不可滑动，
错误提示会提示这个
TypeError: Cannot read property 'addEventListener' of undefined
TypeError: Cannot read property 'offsetWidth' of undefined

**Comment by NightCatSama** [comment]
我猜可能是组件初始化的时候并未渲染到页面上，也就是文档最底部有写到的，你看看是不是因为那个原因~
