### ISSUE TITLE
Slider rail is not showing

### ISSUE THREAD

**Issue by janswist** [NightCatSama/vue-slider-component#360]
#### Describe the bug

Slider doesn't seem to be shown, but it actually is invisible (it takes space, but elements are not visible). Tt reacts to clicks and clicks placement where it should normally be and it normally updates value. It's just like rail and dot is not shown. I migrated from vue-slider-component 2.6.x to 3.0.31 just now. I'm not using custom styles.

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: MacOs
 - Vue version: 2.9.3
 - Component Version: 3.0.31

**Comment by NightCatSama** [comment]
Did you introduce a css file?

**Comment by janswist** [comment]
Jeez, that was really rookie mistake. Completely forgot about that - works now! Thank you
