### ISSUE TITLE
a vue.esm is in the dist file and make it too big

### ISSUE THREAD

**Issue by yinzhida** [NightCatSama/vue-slider-component#361]
when i has installed this component and build my project in umd mode，the dist file size become too large。i analysis it and find there is a total vue.esm.js in the dist file. i think this component as a plugin should not contain the dependency of vue.

**Comment by NightCatSama** [comment]
When building with vue-cli library mode, it will default to `require('vue')`.

The component itself does not use `vue`, I mentioned the related issue, but they do not intend to change.

**Comment by NightCatSama** [comment]
How did you introduce `vue` in itself?

Maybe you can fix it through webpack configuration, use [externals](https://webpack.js.org/configuration/externals/#root) or set `resolve.alias`

**Comment by yinzhida** [comment]
> How did you introduce `vue` in itself?
> 
> Maybe you can fix it through webpack configuration, use [externals](https://webpack.js.org/configuration/externals/#root) or set `resolve.alias`

I want import my plugin through independent .umd file with all dependencies.

**Comment by yinzhida** [comment]
> When building with vue-cli library mode, it will default to `require('vue')`.
> 
> The component itself does not use `vue`, I mentioned the related issue, but they do not intend to change.

I found that in the src/main.js line5, import Vue from 'vue', when webpack build, it maybe put vue to the dist file.

**Comment by yinzhida** [comment]
> When building with vue-cli library mode, it will default to `require('vue')`.
> 
> The component itself does not use `vue`, I mentioned the related issue, but they do not intend to change.

Although I can't confirm the exact location, I can confirm that the dependence of this component leads to the dependence of my plugin on vue.

**Comment by yinzhida** [comment]
set webpack config externals to undefined may help Locate the problem。the dist file size will show the result。

**Comment by yinzhida** [comment]
I run the build package command find the dist file size in this project is right. may be the problem is caused by the different version of webpack? I have no idea now.

**Comment by NightCatSama** [comment]
May be caused by `require('vue')`.

<https://cdn.jsdelivr.net/npm/vue-slider-component@latest/dist/vue-slider-component.umd.js>

**Comment by yinzhida** [comment]
ok,i knowwhat you now, can this project make vue as a peerdependency, and remove the require expression?

**Comment by yinzhida** [comment]
this project not really need vue, the require expression make one who develop vue plugin using this component need resolve it by additinal webpack config.

**Comment by NightCatSama** [comment]
@yinzhida Yes, I am also thinking about this, but `@vue/cli`'s [library build](https://cli.vuejs.org/guide/build-targets.html#library) will automatically introduce vue.

**Comment by yinzhida** [comment]
> @yinzhida Yes, I am also thinking about this, but `@vue/cli`'s [library build](https://cli.vuejs.org/guide/build-targets.html#library) will automatically introduce vue.

Personally, I think a direct reference to Vue inside a Vue plugin should be bypassed. But as you said, webpack configuration solutions may be acceptable in general.

**Comment by joallard** [comment]
Yep, using 'vue.esm' in alias makes VueSlider add ~900KB to the bundle.
