### ISSUE TITLE
marks with html

### ISSUE THREAD

**Issue by jlcanizales** [NightCatSama/vue-slider-component#363]
Hello,
Im trying to use on marks label a font awesome icon, but it shows the html even if I use scape html, there is any way to add  `label: '<i class="fas fa-tint"></i>',`

**Comment by NightCatSama** [comment]
You can use slot to render custom html.

example: <https://jsfiddle.net/NightCatSama/2xy72dod/10438/>

document: <https://nightcatsama.github.io/vue-slider-component/#/advanced/components-slots?hash=label-slot>
