### ISSUE TITLE
Change the label if the value matches a specific value

### ISSUE THREAD

**Issue by Brotzka** [NightCatSama/vue-slider-component#364]
Hi!

My marks reach from 0 to 12. What I want to accomplish is that the label for 0 is "not filtered". For every other value the value should also be displayed as label.

I've tried slots for label, step, mark. But all I've reached is that every label had the value of the currently selected label.

This is what it looks like:
![image](https://user-images.githubusercontent.com/9106911/57835022-f980c180-77bd-11e9-9065-c50a2e194644.png)

This is what it should look like:
![image](https://user-images.githubusercontent.com/9106911/57835052-0dc4be80-77be-11e9-9dc1-7c39a52c0537.png)

Thanks!

P.S. great package!!

**Comment by NightCatSama** [comment]
I wrote a simple example, is it what you need?

<https://jsfiddle.net/NightCatSama/2xy72dod/10445/>

**Comment by Brotzka** [comment]
Thank you, that's perfect!
