### ISSUE TITLE
dotStyle ::after styling

### ISSUE THREAD

**Issue by A1rPun** [NightCatSama/vue-slider-component#365]
#### Describe the bug

When styling the dot there is an `::after` pseudo element with some additional styling, how can I style or remove this element from within my Vue component?
I know I can use a [slider slot](https://nightcatsama.github.io/vue-slider-component/#/advanced/components-slots?hash=slider-slot) but this overrides my dynamic `dotStyle` styling. I can also add this global styling to get what I need but I think there should be an option.
```html
<style lang="scss">
.vue-slider-dot-handle::after {
  background-color: transparent;
}
</style>
```

#### Additional context

![Slider](https://i.ibb.co/zHdhmZL/1558085397.png)

#### Environment
```console
$ vue info
```
```
 Environment Info:
  System:
    OS: Linux 5.0 Arch Linux
  Binaries:
    Node: 11.14.0 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Firefox: 66.0.3
```

**Comment by NightCatSama** [comment]
Sorry to reply so late (have been replied before, but it seems to have not been sent).

Because this style is introduced in the style file, not all styles have this effect, you can use other theme styles (such as default.css or antd.css).

**Comment by A1rPun** [comment]
@NightCatSama Thank you for your response. Both `default.css` and `antd.css` have additional styling on the dot, the `default` theme is the least noticeable but it's still there. So all styles have this `::after` effect.

Are you planning to make this configurable via the component? I take no as an answer too ;)

**Comment by NightCatSama** [comment]
`default.css` has no `::after` style on the `dot`, only use `::after` to implement a arrow on the `tooltip`.

<https://github.com/NightCatSama/vue-slider-component/blob/master/lib/theme/default.scss>

**Comment by A1rPun** [comment]
I assumed the box shadow was coming from the `::after` element, my bad. I can resolve it now using `boxShadow: 'none'` on the `dotStyle` configuration :tada:.
