### ISSUE TITLE
@click isn't working

### ISSUE THREAD

**Issue by harshanaravindakshan** [NightCatSama/vue-slider-component#366]
Hello,

I am attempting to use an input tag that updates the position of the dots on my slider when the input tag value is updated. The @.click doesn't seem to be working for me but in your example, it works (https://jsfiddle.net/NightCatSama/2xy72dod/10233/). Any idea what's wrong with my code?

**HTML**
```
<div id="app">
   <vue-slider ref="slider" v-model="value1" v-bind="options" :min-range="1" @change="callback" :tooltip-formatter="formatter" :tooltip="'always'"/>
</div>

<button @click="reset">test</button>
```

**JS**
```
new Vue({
 el: '#app',
 data: function() {
     return {
         value1: [0,16],
         options: {
             min: 0,
             max: 30,
             interval: 1,
         },
         formatter: (v) => mmddyyyy(xaxisDaily[v])
     }
 	},
 methods: {
     callback: function(val) {
         //something
         },
     reset() {
     	this.$refs.slider.setValue([2,5]);
        console.log('test');
     } 
	},
 mounted() {},
 components: {
         'vueSlider': window['vue-slider-component'],
 }
})
```

Using latest version of vue slider component

**Comment by NightCatSama** [comment]
It looks like there is no problem.

The v2.x version of the component used by that link.

This is using the 3.x version, but it works. 

<https://jsfiddle.net/NightCatSama/2xy72dod/10449/>

**Comment by NightCatSama** [comment]
Maybe you can set value1 directly

```
This.value1 = [2, 5]
```

**Comment by harshanaravindakshan** [comment]
Thanks for your help! That part works now.

Now, the tooltip doesn't seem to be showing unless I click on the slider. I've already set the :tooltip="'always'" and I've tried setting the tooltip to 'always' within the options.

**Comment by harshanaravindakshan** [comment]
^ It happens on page load. After I click on the slider once, the tooltip persists.

**Comment by NightCatSama** [comment]
Can't restore bug?

**Comment by harshanaravindakshan** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49285402/58195830-bc18aa00-7c7d-11e9-82c4-09facba6875c.gif)

**Comment by NightCatSama** [comment]
It’s weird, can you restore it in the online example?

**Comment by harshanaravindakshan** [comment]
I've actually found out the reason for the bug and it's on my end. 

I'm trying to format my tooltip by iterating through an array that only gets defined after about 4 seconds after page load. Is there any way for me to set a default format (date) and then after the array gets defined, it switches over to that format? 

Also, just to throw a second problem (and hopefully last) out there related to this. My slider is used as a range of dates. I'm using a date picker (combodate API) to change the min and max of the slider. It's all working fine except for the fact that after the new start and end dates are set, the tooltip doesn't change dates unless I move the slider around. Is there a way for me to refresh the tooltip or the slider altogether? Or, any other suggestions?

Thank you for the prompt responses btw, you've been a great help :)

**Comment by NightCatSama** [comment]
Excuse me, I really can’t think of why this is the case.

It looks like the tooltip and the slider are not showing (the tooltip is in the slider element)

You can look at the data inside the component, such as whether `dots` are normal (should be an array) to determine whether it is a rendering problem or a data problem.

**Comment by harshanaravindakshan** [comment]
I just found an alternative to the first issue so it's working now. 

Any idea about the second issue I mentioned?

**Comment by NightCatSama** [comment]
No 😢

**Comment by harshanaravindakshan** [comment]
Is it possible to set a delay on the @click functionality? I tried setting a timeout function but it didn't work. Or, is there any alternative to @click that I could use?

**Comment by harshanaravindakshan** [comment]
Also, I'm trying to attack the second issue by moving the slider by 1 using setIndex() and then setting the index back to 0. However, when I call both those functions under one method, it seems to toggle. I have to click once for the slider to move by 1 and then click again for the slider index to go back to 0. Not sure why this is happening. Any idea?

**Comment by NightCatSama** [comment]
I have to find the reason first, just listen to your description, I really don’t know why.
