### ISSUE TITLE
Is there a way to turn off errors.

### ISSUE THREAD

**Issue by senner007** [NightCatSama/vue-slider-component#367]
Hi
I get the error: "[VueSlider error]: The "value" cannot be greater than the maximum."
because I allow the user to recalculate the min max after component mount.
It doesn't cause any problems
 
Is there a way to turn off errors.?

**Comment by NightCatSama** [comment]
Can set `silent` to `true`.

**Comment by catsclaw** [comment]
I'm getting the exact same bug. And it clearly _is_ a bug. At no time is the value higher than the max. What is causing this?

**Comment by NightCatSama** [comment]
@catsclaw Is it because of this situation? [#343](https://github.com/NightCatSama/vue-slider-component/issues/343)

**Comment by catsclaw** [comment]
I don't think so. My logic is:

Calculate the new max, and the new value. Ensure they are correct.
If the current max is less than the new max, set the new max.
Set the new value.
Set the new max.

So at every step, the values should be correct. I've even tried setting the value to[0, 1] before setting the max and the new value.

**Comment by NightCatSama** [comment]
@catsclaw  Can you reproduce it in the online example?

<https://jsfiddle.net/NightCatSama/2xy72dod/10339/>

If this does not affect the use, set `silent` to `true`.
