### ISSUE TITLE
How in vue-slider-component make selection options bigger

### ISSUE THREAD

**Issue by PetroGromovo** [NightCatSama/vue-slider-component#368]
#### Describe the feature

Hello,
In my bootstrap 4.3 / vuejs 2? app I use vue-slider-component "^3.0.31" ( https://nightcatsama.github.io/vue-slider-component/#/ )
defining as :
```
<label for="range_vue_slider_test" class="mb-5">Vuejs slider test</label>
<vue-slider
	v-model="slider_test_value"
       :enable-cross="false"
       :min="0"
	:max="1"
	:interval="0.20"
	:marks="true"
	tooltip="always"
	tooltipPlacement="top"
	:tooltip-formatter="val => val+' M'"
></vue-slider>
```
I define big values from 0 till 1000000, with "M" label and it looks good for me :
https://prnt.sc/nsaipa
But setting 
```interval="0.20" 
```
I have scale with options 
```0, 0.2, 0.4, 0.6, 0.8, 1
```
and now when moving 2 runners I can select only one of options mentioned above.
But I need to select more options, say 
```0, 0.05, 0.1, 0.15, 0.2...
```
If for scales above to interval="0.05" then all labels are one above other and nothing is visible at all.

If there is a way to make it?

Thanks!

**Comment by NightCatSama** [comment]
I don't know what problem you have encountered.

If you are referring to the use of different intervals for the two sliders, you should not be able to do so now.

If the label is too crowded, you can use the array type to pass the marks

**Comment by PetroGromovo** [comment]
Sorry, if I put what I need unclear.
Now it ok how slider looks and all is ok with labels visible, but the problem is that moving both runners
I can select one of options : 0, 0.2, 0.4, 0.6, 0.8, 1
Are there some additive props to make more available options selectable when moving runners, like 
0, 0.05, 0.1, 0.15, 0.2, 0.2.5, 0.3...
or maybe more values selectable.

**Comment by NightCatSama** [comment]
like this? <https://jsfiddle.net/NightCatSama/2xy72dod/10452/>

**Comment by PetroGromovo** [comment]
Thank you! 
That is I searched for.
One more question : is there is a way for max value to show "Infinity" option? 
Any idea how that could be done?

**Comment by NightCatSama** [comment]
Is this? 😃  <https://jsfiddle.net/NightCatSama/2xy72dod/10456/>

**Comment by PetroGromovo** [comment]
Thanks! 
Great!
