### ISSUE TITLE
 disabled by default and activated by click

### ISSUE THREAD

**Issue by PetroGromovo** [NightCatSama/vue-slider-component#369]
#### Describe the feature

Hello,
In my bootstrap 4.3 / vuejs 2 app I use vue-slider-component "^3.0.31"
and I want to know if there is a way to make some components disabled by default, 
like “Alexa” at the printscreen
https://prnt.sc/nt7uzi

But when user click on the component, it becomes active(Like "Domain Authority") and that must inflence value of model vars related ?
In othere words in need diabled status, and activating it by clicking on it,,,

Thanks!

**Comment by NightCatSama** [comment]
Is this what you want?
```html
<vue-slider 
  :disabled="disabled" 
  @click.native="disabled = false" 
/>
```

**Comment by PetroGromovo** [comment]
Yes, I tried to disable by : 											 
```
   :disabled="slider_range_domain_authority_disabled"											 
   @click.native="slider_range_domain_authority_disabled = false"

```
and it is disabled by default, but is not clickable. 
Also I tried like:											 
```
    :disabled="slider_range_domain_authority_disabled"
    @click.prevent="alert(22);"

```alert did not popup. 
Which is the right way ?

**Comment by NightCatSama** [comment]
Can set a container element.
```vue
<div @click="disabled = false">
  <vue-slider :disabled="disabled" />
</div>
```

**Comment by PetroGromovo** [comment]
Great! 
Thank!
