### ISSUE TITLE
When adsorb is set to true, slider doesn't show correct points

### ISSUE THREAD

**Issue by mxs42** [NightCatSama/vue-slider-component#370]
#### Describe the bug

When adsorb is set to true and interval option is used, slider doesn't show correct points.
https://nightcatsama.github.io/vue-slider-component/#/basics/simple

#### Additional context (If there is no relevant content, please delete the block)
As you can see, there is no point at '90', also it shows point at 0.
![00083_firefox](https://user-images.githubusercontent.com/34000717/58817341-365d0d00-8634-11e9-81ee-e741cdae5ed6.png)

**Comment by NightCatSama** [comment]
Thank you for your feedback, fixed in 3.0.32.
