### ISSUE TITLE
Error when use direct JS src

### ISSUE THREAD

**Issue by joelpanor** [NightCatSama/vue-slider-component#372]
Hello,

Thank you for for this plugin. But I have an error when I try to use it with direct JS

`Uncaught TypeError: Super expression must either be null or a function
    at _inherits (inherits.js:5)
    at vue-slider-dot.tsx:7
    at Module.fb15 (vue-slider-dot.tsx:7)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
    at webpackUniversalModuleDefinition (universalModuleDefinition:9)
    at universalModuleDefinition:10`

I included it in a script tag in my html file :

`<script src="https://cdn.jsdelivr.net/npm/vue-slider-component@3.0.3/dist/vue-slider-component.umd.js"></script>`

**Comment by NightCatSama** [comment]
You can refer to the usage of the online example, and also use JS directly.

<https://jsfiddle.net/NightCatSama/2xy72dod/10339/>

**Comment by joelpanor** [comment]
I included `<script src="https://cdn.jsdelivr.net/npm/vue-slider-component@latest/dist/vue-slider-component.umd.min.js"></script>` in my body tag

But I have a similar error

`Uncaught TypeError: Super expression must either be null or a function
    at g (vue-property-decorator.js:86)
    at vue-slider-dot.tsx:7
    at Module.fb15 (vue-slider-dot.tsx:7)
    at r (bootstrap:19)
    at 2350 (bootstrap:83)
    at bootstrap:83
    at universalModuleDefinition:9
    at universalModuleDefinition:1`

**Comment by NightCatSama** [comment]
It should not be a component error.

I just created an `index.html` and it's ok.

![image](https://user-images.githubusercontent.com/13888962/59479489-cfd7ba80-8e8f-11e9-8ae1-117a112bc689.png)
