### ISSUE TITLE
When using Range mode with a minimum range, there should be a modifier to stop the slider when range is hit

### ISSUE THREAD

**Issue by HMnadav** [NightCatSama/vue-slider-component#373]
We use the slider to filter on a price range for products, and we want to keep a minimum range of, say , 100. Currently, when the range is reached, both sliders continue moving, maintaining the rage.

It would be great if, once the range is reached the sliders stop moving.
E.g. User sets the top end to 1500, and the minRange I set is 150. Once the bottom end reaches 1350, the bottom range will not push the top range anymore, and same for the other way.

Thanks!

**Comment by NightCatSama** [comment]
Does `minRange` not meet your needs?

<https://jsfiddle.net/NightCatSama/2xy72dod/10464/>

**Comment by HMnadav** [comment]
Hi @NightCatSama - minRange is good but the problem is once we hit the min range I want the slider to stop moving, rather than pushing the other one to keep the range. 
In the fiddle example, if I moved the right slider to 250, I want the left one to stop at 200, rather than cause them both to keep moving.

**Comment by NightCatSama** [comment]
How is this?

<https://jsfiddle.net/NightCatSama/2xy72dod/10467/>

**Comment by HMnadav** [comment]
Perfect! Should I add that to the computed() section?

**Comment by NightCatSama** [comment]
Yes, the sliding range of the slider needs to be calculated dynamically

**Comment by HMnadav** [comment]
Awesome! Thanks @NightCatSama !

**Comment by WilliamDASILVA** [comment]
Just a note, it should probably be included in the documentation. Was stuck with this and was wondering if the plugin could even do that! Thanks anyway
