### ISSUE TITLE
Generate sound when the slider go right or left 

### ISSUE THREAD

**Issue by mustafahamid** [NightCatSama/vue-slider-component#378]
Hi,  
 It will very awesome if WE can send to the slider a sound that will play when we change the slider right or left by using the key right left.  

 Thank,

**Comment by NightCatSama** [comment]
This very low-demand feature is not added to the component, you can add it yourself in the `keydownHook`.

**Comment by mustafahamid** [comment]
Can you show me how, please?

**Comment by NightCatSama** [comment]
No... Maybe you can go check the `<audio>` tag, or find out if there is a third-party library.
