### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function.

### ISSUE THREAD

**Issue by ashikalgar** [NightCatSama/vue-slider-component#379]
@NightCatSama 

After upgrading **"vue-slider-component"** **"2.4.1"**  to latest **3.0.33**, getting error **"Uncaught TypeError: Super expression must either be null or a function"**.

Below are the configuration of My current project.
Node - 10.16.4
Npm - 6.9.0
Yarn - 1.16.0

**Comment by NightCatSama** [comment]
Can you send the complete error stack?

Is there a possibility of circular dependencies?

**Comment by ashikalgar** [comment]
@NightCatSama: Please verify

Uncaught TypeError: Super expression must either be null or a function
    at x (vue-slider-component.umd.min.js?4971:6)
    at eval (vue-slider-component.umd.min.js?4971:6)
    at Module.fb15 (vue-slider-component.umd.min.js?4971:6)
    at r (vue-slider-component.umd.min.js?4971:1)
    at 2350 (vue-slider-component.umd.min.js?4971:1)
    at eval (vue-slider-component.umd.min.js?4971:1)
    at eval (vue-slider-component.umd.min.js?4971:1)
    at eval (vue-slider-component.umd.min.js?4971:1)
    at Object.599 (loanamountcalculator.build.js:756)
    at __webpack_require__ (loanamountcalculator.build.js:20)

**Comment by NightCatSama** [comment]
Sorry for the late reply.

It seems that the problem is not in the component, you can refer to this:

<https://medium.com/@anuhosad/react-errors-super-expression-must-either-be-null-or-a-function-4aac6e5173ad>

**Comment by syberon** [comment]
I tried to use this component in my site that uses requirejs to load all modules. Vue library loads without any problems via requirejs but if i try to load vue-slider umd file as a module it gives me the same error "**Uncaught TypeError: Super expression must either be null or a function**". Is this any way to use it with requrejs?

**Comment by NightCatSama** [comment]
@syberon I don't know why 😢 , using umd specification package should support amd.

**Comment by syberon** [comment]
This looks like when i trying to load the module it can not find globally defined Vue.
This is small example that works:
```
<html>
<head>
    <script src="/js/vue.js"></script>
    <script src="/js/vue-slider-component.umd.js"></script>
</script>
</head>
<body>
</body>
</html>
```
If i remove the inclusion of vue.js from the code i get the error that in topic of this tread:
**vue-slider-component.umd.js:1187 Uncaught TypeError: Super expression must either be null or a function**

This is code that i tried to use:

**index,html**
```
<html>
<head>
    <script type="text/javascript" charset="utf-8" data-main="/js/main.js" src="/js/require.js"></script>
</head>
<body>
</body>
</html>

```

**main.js**
```
require ([
    'vue',
    'vue-slider-component.umd'
], function (Vue) {
    new Vue({
        el: '#app'
    })
});
```
And this code gets to me the same error on 'vue-slider-component.umd' module loading:
**vue-slider-component.umd.js:1187 Uncaught TypeError: Super expression must either be null or a function**

It looks like the module tries to find the globally defined (or something else) Vue on load and throws this error if can't find it.

**Comment by NightCatSama** [comment]
@syberon Is it because of the loading order problem, you try this?
```js
require (['vue'], function (Vue) {
    require(['vue-slider-component.umd'], function(VueSlider) {
       // new Vue
    })
});
```

**Comment by syberon** [comment]
Yes, i tried this now, but without luck. Component still throw this error.

**Comment by NightCatSama** [comment]
@syberon Sorry, I have no clue 🤕 .

Do you want to try this?

<https://github.com/vuejs/vue-cli/issues/4084>

```js
// vue-slider-component.umd.js line: 5
define(['vue'], factory);
```

**Comment by syberon** [comment]
Thanks! This trick worked for me.
