### ISSUE TITLE
Is it possible to use this with the script tag?

### ISSUE THREAD

**Issue by JesseAldridge** [NightCatSama/vue-slider-component#38]
I don't understand any of the following:  webpack, es6, browserify, import, babel
Also, I am deploying my app on firebase, so I don't have control over the server.

Is it possible to use this widget via the <script> tag with ES5?  Could you include an example of this?  I can't figure out how to make it work.

**Comment by NightCatSama** [comment]
[fiddle](https://jsfiddle.net/NightCatSama/9pp3dqkq/1/)

**Comment by JesseAldridge** [comment]
Ah, I get it.  Thanks.  👍
