### ISSUE TITLE
Add support for internationalization with name and value in data

### ISSUE THREAD

**Issue by ratracegrad** [NightCatSama/vue-slider-component#380]
#### Describe the feature

Ability to pass an array of objects for the data for the slider.  The object would have both a name and value. Our app suppports multiple languages so we need to translate the text that is displayed on the marks on the slider. But I want the value be what is stored in the v-model. This allows me to control logic based on what is selected regardless of what text is displayed to the user.

#### Describe the solution you'd like

Have date that can be:
[{ name: 'Hello', value: 1}, {name: 'Goodbye', value: 2}]  or
[{ name: 'Gutten Tag', value: 1}, {name: 'Chust', value: 2}] or
[{ name: 'こんにちは', value: 1}, { name: 'さようなら', value: 2}]

Users would see the text that corresponds to their language. Regardless of what is displayed to the user, when they select an entry then the value is what is returned in the v-model. 
I cannot hardcode in my logic to check if the value in the v-model is 'Hello' || 'Gutten Tag' || 'こんにちは'  etc if we had more languages to our application.

**Comment by NightCatSama** [comment]
I think this need should not be solved inside the component, you can do it with `computed/getter`.

e.g. <https://jsfiddle.net/NightCatSama/2xy72dod/10481/>
