### ISSUE TITLE
How can i select the min value on the slider?

### ISSUE THREAD

**Issue by sanuann** [NightCatSama/vue-slider-component#381]
the `data` prop of my slider takes in an array. How can i select the `min` value on the slider if wish to? to select other values on the slider i can drag or click on it, but not for the min value. How do i select it?

**Comment by NightCatSama** [comment]
I don't know what problem you have encountered.

`min/max` will fail when using `data`.

**Comment by sanuann** [comment]
`<vue-slider v-model="input" :lazy="true" :data="interval"
                :marks="true" @change="sendData"></vue-slider>`

and i get this:

<img width="1130" alt="Screen Shot 2019-07-24 at 12 01 22 PM" src="https://user-images.githubusercontent.com/5114945/61809237-eb2cd280-ae0a-11e9-942c-3bda8d6d593e.png">

**Comment by NightCatSama** [comment]
It’s best to reproduce your problem.

<https://jsfiddle.net/NightCatSama/2xy72dod/10339/>

**Comment by sanuann** [comment]
https://jsfiddle.net/3evx8t5o/8/ how do the call the `sendData` method when i want to send the initial value (i.e. in this example - 0)?

**Comment by NightCatSama** [comment]
`@change` will only be called when the value changes.

If you want to initialize the call, then you should manually call it yourself elsewhere.
