### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by pavellzubkov** [NightCatSama/vue-slider-component#382]
#### Describe the bug

Little typo in docs:
direction prop
Type: 'ltr' | 'rtl' | 'ttb' | 'bbt'   need to change bbt to btt

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: [e.g. macOS, Windows, Linux]
 - Vue version: [e.g. v2.0, v2.5, v2.6]
 - Component Version: [e.g. v3.0.2]

**Comment by NightCatSama** [comment]
Thanks
