### ISSUE TITLE
Interval on multiple sliders

### ISSUE THREAD

**Issue by tchristerus** [NightCatSama/vue-slider-component#383]
### Description
The interval attribute does not work on sliders with multiple 'dots'. It seems like it is trying to divide the value, however for multiple sliders this value is an array and can therefore not be divided.

#### Used HTML:
```
 <vue-slider v-model="price" :min="minPrice" :max="maxPrice" :tooltip-placement="'bottom'" :interval="50"></vue-slider>
```
#### Console output:
```
[VueSlider error]: The prop "interval" is invalid, "(max - min)" cannot be divisible by "interval"
```

**Comment by NightCatSama** [comment]
`interval` is used to interval `max - min`, if not applicable, you can choose to use `data`.

**Comment by tchristerus** [comment]
You are right, the ```data``` works fine for this.

Thank you.
