### ISSUE TITLE
Is there a way to disable marks?

### ISSUE THREAD

**Issue by dz000** [NightCatSama/vue-slider-component#385]
#### Describe the feature
Sometimes it can be useful to display 'disabled' marks.

#### Describe the solution you'd like
It should not be possible to slide to certain marks when a disabled option is set.

**Comment by NightCatSama** [comment]
Are you referring to the mouse showing disabled flags when `disabled: true`?

**Comment by dz000** [comment]
Thank you for quick reaction!
What i would like to achieve is to disable certain marks. The slider should be enabled but certain marks should be displayed but not selectable. Is that possible?

**Comment by dz000** [comment]
I found that this behaviour can be achieved by setting min-max values for the dots. Thank you very much and sorry for bothering you!
