### ISSUE TITLE
JSDoc types can only be used inside documentation comments

### ISSUE THREAD

**Issue by aashrafu** [NightCatSama/vue-slider-component#386]
#### Describe the bug

ERROR in C:/**/node_modules/vue-slider-component/typings/typings/index.d.ts

63:52 JSDoc types can only be used inside documentation comments.
    62 | // Process
  > 63 | export type ProcessOption = Array<[number, number, Styles?]>                                              
    64 | export type ProcessFunc = (dotsPos: number[]) => ProcessOption
    65 | export type ProcessProp = boolean | ProcessFunc
    66 | export interface Process {
Version: typescript 2.9.2, tslint 5.10.0
.

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: Windows
 - Vue version: v2.5.16
 - Component Version: v3.0.33

**Comment by NightCatSama** [comment]
Is it possible because the typescript version is too low?

https://github.com/NightCatSama/vue-slider-component/blob/30424c0c47f336a4642962fbc676e17889cfb0cf/lib/typings/index.d.ts#L63

<https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#optional-elements-in-tuple-types>

**Comment by aashrafu** [comment]
@NightCatSama thanks, it seems like upgrading Typescript version solved this problem. So you do not support typescript version <3.0.0, right?

**Comment by NightCatSama** [comment]
@aashrafu Yes

If most people use typescript < 3.0, I can also consider a different way of writing.

But it's better to upgrade, now it's 3.5, and there's no harm in upgrading.

**Comment by baevdantes93** [comment]
its a fucking shit component, уёбище блядь ебаное
