### ISSUE TITLE
Slider multiple range jumps width when min value is not 0

### ISSUE THREAD

**Issue by HenryAveMedi** [NightCatSama/vue-slider-component#387]
#### Describe the bug
Hi, i have setup a multiple slider for select a range of years (from to)

`<vue-slider
      v-model="dataTimeModel"
      :min="1500"
      :max="2019"
      :min-range="1500"
      :max-range="2019"
      :tooltip="'always'"
      :tooltipPlacement="'bottom'"
      :order="true"
      :marks="marks"
    />`

when it loads, everything is perfect, but when i click to move the slider, it jumps to width -200% and position of dot goes to outside the screen
here is the fiddle reproduction of the error

https://jsfiddle.net/rd5j4fu8/2/

#### Additional context
When i change the minimum value to 0, everything goes well, but because i want to start from 1500, then it brakes

#### Environment (If you feel unrelated, please delete the block)
 - Vue version: [v2.6.10]
 - Component Version: [v3.0.33]

**Comment by HenryAveMedi** [comment]
never mind, i miss understood the usage of min-range/max-range., so it was my mistake in configuration, thank you very much for this great component though, very very usefull and powerful! 👍

**Comment by janswist** [comment]
> never mind, i miss understood the usage of min-range/max-range., so it was my mistake in configuration, thank you very much for this great component though, very very usefull and powerful! 👍

It would be more helpful if you would share what was the exact mistake in your configuration and showing how did you fixed it.
