### ISSUE TITLE
❓Support for single dot disabled state

### ISSUE THREAD

**Issue by vdiachenko** [NightCatSama/vue-slider-component#388]
[Support for single dot disabled state](https://github.com/NightCatSama/vue-slider-component/commit/2682913) –– this feature will be removed in ver >= 3.x?

**Comment by NightCatSama** [comment]
can use `dot-options`

<https://nightcatsama.github.io/vue-slider-component/#/basics/simple?hash=disabled-slider>

**Comment by vdiachenko** [comment]
I have only one dot and need to disable some values in the range, between min and max.

**Comment by NightCatSama** [comment]
You can filter out unwanted values with `marks` and `included`.

<https://nightcatsama.github.io/vue-slider-component/#/basics/marks?hash=use-with-included>

**Comment by vdiachenko** [comment]
what if marks and value for selection not the same?
![image](https://user-images.githubusercontent.com/7806034/62853098-fb421e80-bcf3-11e9-967f-7c6e16878749.png)

**Comment by NightCatSama** [comment]
I don't know what you want to do. 

The supported functions are all in the document. You can check it out first. 

You can talk about what you want to do in detail. It is best to restore it in the online example.

**Comment by vdiachenko** [comment]
https://jsfiddle.net/vdiachenko/yqogapbs/11/

**Comment by 7842424** [comment]
You can define dot options as an array and specify a minimum and maximum value for each dot.
https://jsfiddle.net/ermn1hoL/

**Comment by NightCatSama** [comment]
Updated to 3.0.37, this effect can be achieved with the `vue-slider-mark` component.

<https://jsfiddle.net/NightCatSama/fr6g3nws/26/>

**Comment by vdiachenko** [comment]
thanks!
