### ISSUE TITLE
Should Value mutations from parent trigger @callback event

### ISSUE THREAD

**Issue by dobromir-hristov** [NightCatSama/vue-slider-component#39]
Thinking out loud here. If we have 2 sliders that are bound to the same value, lets say one for mobile layout and one for desktop. If one changes, should the other emit a `callback`? 
Because a weird side effect would be that both sliders emit an event.  
What I mean is, we should emit a callback event only when the user triggers a change, or at least that should be by default.
Maybe I am wrong? Let me know what you think.

**Comment by NightCatSama** [comment]
You mean the two tandem component to call a `callback` only

**Comment by dobromir-hristov** [comment]
I mean that currently all the components emit a callback because they are all bound to the same value on the parent. Only the one that you interact with (drag, click) should emit an event.

**Comment by NightCatSama** [comment]
I see what you mean. 

But just according to the judgment of value are the same, it is very trouble.

I think you can add a param on the parameters of the `callback`, do you think?

**Comment by dobromir-hristov** [comment]
Well you can pass a unique ID with the callback but I still think its proper to try to distinguish between user generated input on the element and one from the outside.

**Comment by NightCatSama** [comment]
I found a simple way to implement it. just use `watch` to observer the value.

look this: [fiddle](https://jsfiddle.net/9pp3dqkq/5/)

**Comment by dobromir-hristov** [comment]
Yeah it works, but its a hacky solution to a problem that could lead to other problems.
If I have time I will try to come up with a fix and do a PR.

**Comment by dobromir-hristov** [comment]
Ok so I did some tests on your code. If we skip the syncValue method in the watcher, we practically eliminate the problem with external changes triggering the callback. 
```js
watch: {
		value(val, oldVal) {
			this.flag || this.setValue(val, true, 0)
		},
          }
```
Note that in your example/src and your main src they are slightly different. Params are switched a bit.
