### ISSUE TITLE
set min and max range  dynamically

### ISSUE THREAD

**Issue by ranga9** [NightCatSama/vue-slider-component#392]
How to set min and max range for a range slider dynamically

**Comment by NightCatSama** [comment]
Is it possible to dynamically set the `min` and `max` of `dot-options`?

**Comment by LedzZm** [comment]
use v-model="currentValue" in your component.
In your data return some default value like
data() {
  return {
    currentValue: [
      data[0],
      data[data.length - 1]
    ],
  } 
}

data can be an array that you pass as a prop to your component. Of course, you can also edit your data in your mounted function if you want to further extend/change your dynamic data.

I hope I understood your question correctly.
