### ISSUE TITLE
Incremental fixed steps

### ISSUE THREAD

**Issue by Zyles** [NightCatSama/vue-slider-component#393]
I have a range of dates like this:
1 month
3 months
6 months
1 year
2 years
3 years
5 years
10 years

How can I create a slider that only selects these values?

**Comment by NightCatSama** [comment]
If the interval is equally divided, you can use `data`, otherwise you can use `marks`.

**Comment by perlatsp** [comment]
@Zyles You can use marks as @NightCatSama  suggested. 
I had a similar case. Pass the data and use label slot to display the labels. 
```
<vue-slider :data="range" :marks="true" ....>
....
   <template v-slot:label="{ active, label,value }">
                <div :class="['vue-slider-mark-label', 'slider__label', { active }]">{{ value.label }}</div>
     </template>
....
</vue-slider>

```
