### ISSUE TITLE
Multiple sliders interacting

### ISSUE THREAD

**Issue by quimarche** [NightCatSama/vue-slider-component#394]
If I have multiple sliders, is there any way to stop one interacting with another?

For example, in a timetabling application, I have two lessons, one from 10:00 to 12:00, the other from 12:30 to 14:30. 

Moving either of the 12:30/14:30 sliders to the left pushes the 10:00/12:00 sliders to the left. I want to prevent that happening.

![Screenshot 2019-08-23 at 16 11 47](https://user-images.githubusercontent.com/149213/63603226-13058680-c5c1-11e9-8fce-c0a5168c2944.png)

**Comment by NightCatSama** [comment]
Use `enableCross` to disable inter-slider penetration. or use `minRange` to have a minimum spacing between the sliders.

<https://nightcatsama.github.io/vue-slider-component/#/basics/range>

**Comment by quimarche** [comment]
Got it, thanks. I used dotOptions to return an array of {max, min}, one for each slider value.
