### ISSUE TITLE
How to set secondary progress like the video buffer?

### ISSUE THREAD

**Issue by royorange** [NightCatSama/vue-slider-component#396]
We want to customize the videoplayer controls, so it's necessary to customize the video progress. The common use is awesome, but my question is how to set the secondary progress for video buffered (like youtube) ?

Seems "process" property is hard to achieve this feature, and in my scene, I need to change the common progress dot in "hover" state and keep the buffered progress as usual.

**Comment by NightCatSama** [comment]
This can be done using `process`, I wrote an example:

<https://jsfiddle.net/geLjv9wx/>

**Comment by royorange** [comment]
Thanks! It wroks good and solved the problem well.
Awesome component~
