### ISSUE TITLE
Range Disabled?

### ISSUE THREAD

**Issue by movepixels** [NightCatSama/vue-slider-component#397]
Not sure if this is a request or more so a question.

Is it possible to if you have say 3 sliders on a page with range of 0 - 100 but none of the sliders could overlap in range?
Slider 1 could be 0-50
Slider 2 could be 75 - 100
So slider 3 can only use 51-74?

In theory I would like a scroller to be for hours in a day, but you can have different sets of hours for a 24 hour peiod, but hours could not be used more than once or overlap.

So Range could be 12:00am - 6:00am [6:15am - 4pm used so excluded from range] then continue with 4:15 - 12:00am

**Comment by NightCatSama** [comment]
The slider can use `min/max` in `dotOptions` to limit the sliding range.

**Comment by movepixels** [comment]
But the range has to be concurrent. I did / cant see a way to allow 0 thru 10, then say block anything form 11-19, then allow 20-50

0--------allowed-------------10 - 11---------cant select in here----------19 - 20------allowed---------50

**Comment by NightCatSama** [comment]
Sorry, this setting is not supported.

But it should be possible to write by myself, I wrote an example:

<https://jsfiddle.net/NightCatSama/2xy72dod/10491/>
