### ISSUE TITLE
Range slider max range

### ISSUE THREAD

**Issue by LedzZm** [NightCatSama/vue-slider-component#398]
Hi,

This is more of a question, rather than a feature request. I am opening an issue for that and am sorry in advance if it was obvious and I did not see it.

My aim is to use min-range but if the dots collide, I do not want them to move. 
I hope my question is clear and I thank you in advance for your time.

**Comment by NightCatSama** [comment]
I wrote an example. Is that what you want?

<https://jsfiddle.net/NightCatSama/2xy72dod/10493/>

**Comment by LedzZm** [comment]
Yes thank you.

I extended it to work with custom data, like in my case.

Not sure if there is a more elegant way to do it but it works.
https://jsfiddle.net/450ysgut/4/

**Comment by NightCatSama** [comment]
There is no other way, only the way to limit the slider.

**Comment by LedzZm** [comment]
Well this works, so thanks. ;)
