### ISSUE TITLE
Slider does not get updated after a data change

### ISSUE THREAD

**Issue by jimut** [NightCatSama/vue-slider-component#399]
After initialisation if the data is changed the slider does not get updated. It does the update after a single click on the slider.

Open this pen.

https://codepen.io/jimut/pen/MWgPjyj

After 2 sec the data will get updated but the dot will remain in the same position. It will get placed in the correct position if you do a single click on it.

**Comment by NightCatSama** [comment]
<https://github.com/NightCatSama/vue-slider-component/issues/313#issuecomment-532598888>

**Comment by jimut-rentomojo** [comment]
Thanks
