### ISSUE TITLE
TsLinting Issue with component

### ISSUE THREAD

**Issue by joelchretien** [NightCatSama/vue-slider-component#400]
When I transpile this component, I get the following tslint error
```
ERROR in /home/joel/projects/enterprise/packages/builder/node_modules/vue-slider-component/typings/typings/global.d.ts
│22:3 Exports and export assignments are not permitted in module augmentations.
| declare module '*.scss' {
|   var content: any
|   export default content
|   ^
| }
|

```
If I add // @ts-ignore between the two lines, it works, but not sure what the best solution is here.

**Comment by NightCatSama** [comment]
How do you refer to components?

**Comment by joelchretien** [comment]
In <template>
<vue-slider :value="sliderWidth" @change="changed"></vue-slider>

In <script lang="ts">
import VueSlider from "vue-slider-component";
import "vue-slider-component/theme/default.css";

In @Component({
  components: {
  VueSlider
}
})

**Comment by NightCatSama** [comment]
I don't know where the problem is. 

Does the `exclude` in tsconfig.json include `node_modules`?
