### ISSUE TITLE
Using in a form for search filter

### ISSUE THREAD

**Issue by zefexdeveloper** [NightCatSama/vue-slider-component#401]
I'm creating a project using Laravel and right now I need to create a filtered search, like for pricing range (min, max). The backend accepts the url query to be something like `price_min=1000&price_max=5000`. I'm not an advanced Vue user so I was wondering, how to make usage of `vue-slider-component` in a form and when submitting the form make the url query look like that?

This is an example http://ideal.thesoftking.com/shopio/shop/13, on the left side there's a filter by price, if you press "apply"  it will be in the url query as `minprice` and `maxprice`.

**Comment by NightCatSama** [comment]
The component only controls the change of value, you can jump when you press "apply".

```vue
  <vue-slider v-model="value" />
```
```js
export default {
  apply() {
    this.$router.replace({
      ...this.$router,
      query: {
        ...this.$router.query,
        minprice: this.value[0],
        maxprice: this.value[0],
      }
    })
    // or location.href = location.href + (search ? '?' : ':') + `minprice=${this.value[0]}&maxprice=${this.value[1]}`
  }
}
```

**Comment by zefexdeveloper** [comment]
@NightCatSama it's an awesome example, like using Vue to make the requests and `$router` to replace the query on the browser so the user can copy.

I will try something like that, thank you.
