### ISSUE TITLE
Make dots to buttons

### ISSUE THREAD

**Issue by tfdbloom** [NightCatSama/vue-slider-component#402]
#### Describe the feature

Simple request: Making the dots to buttons instead of divs will enable them to be active when tabbing. Great feature for people using their keyboards. 

#### Describe the solution you'd like

Should be on by default, there really is no reason to not have it. I would go so far to say that it should not be a prop to choose.

**Comment by NightCatSama** [comment]
As you said, if the slider is changed to button , the component can use the tab key to switch the slider.

But getting the focus of the button doesn't mean that the component slider gets the focus, and there are a lot of things to modify. So I won’t modify it in the short term.

Thanks for your suggestion.

**Comment by raisonon** [comment]
Any thoughts for an interim work-around -- I'm using the slider with great effect using useKeyboard prop to quickly choose from an answer, but really missing the ability to tab between sliders... Screenshot to illustrate.

p.s. Thanks NightCatSama for great work

![image](https://user-images.githubusercontent.com/2080025/86819880-2a861a80-c080-11ea-89ad-7ef3969c9dc7.png)

**Comment by NightCatSama** [comment]
@raisonon @tfdbloom In version 3.2.1, keyboard tab is supported to access the slider, and the keyboard control parameters are true by default.

**Comment by raisonon** [comment]
Fantastic, just updated to 3.2.1 and can now tab between the sliders and see my slider dot highlighted (focused?) and move between sliders on pressing Tab.

Pressing Arrow Key Left and Arrow Key Right do not do anything when I tab to a new slider.

However, If I click on a label (and the slider then moves to that mark), then my keyboard left and right work as expected.

Do I need to add something in addition to get full keyboard controls on focus? Thanks as always

**Comment by NightCatSama** [comment]
@raisonon Ah, can you tell your component to pass parameters.

Is it normal if you try this example <https://jsfiddle.net/zre57b2t/>

**Comment by raisonon** [comment]
@NightCatSama Looks like it's when I add my custom data that it stops working as expected. I've adjusted the jsfiddle to demonstrate: https://jsfiddle.net/s7cqdjpa/14/

eg.

:data="sliderData"

where

sliderData: ["1", "2", "3", "4", "5"],

**Comment by NightCatSama** [comment]
@raisonon `value` needs to correspond to the value of `data`.

<https://jsfiddle.net/vkcuztg5/>

![动画](https://user-images.githubusercontent.com/13888962/86908252-d6933880-c148-11ea-9451-74d5ef5b213b.gif)

**Comment by raisonon** [comment]
Thanks for help. My value is an empty object and is populated based on which questions (sliders) are set...

eg. v-model="form.userAnswers[key]['answers'][question.id]"

Perhaps I need to preset all of my values to 1 rather than just having them set dynamically when they are selected with the slider...

**Comment by NightCatSama** [comment]
@raisonon  Yes, the value cannot be empty.

By the way, the `data` support object has just been updated in version 3.2.2.

Maybe it helps you, for example, you may not need to set `marks` 😅  .

<https://nightcatsama.github.io/vue-slider-component/#/basics/data?hash=when-data-is-object-type>
