### ISSUE TITLE
Change background color slider based in value

### ISSUE THREAD

**Issue by Albvadi** [NightCatSama/vue-slider-component#405]
Hi, 
I´m trying to colorize the background active slider based in the value with a computed property.
Something like this..

![image](https://user-images.githubusercontent.com/6285255/65702077-ad565f80-e082-11e9-8b96-bdd90060e204.png)
![image](https://user-images.githubusercontent.com/6285255/65702190-e1ca1b80-e082-11e9-8fa3-246cc177bcfe.png)

I am unable to colorize the active zone. Only can colorize grey zone and always is blue in active..

Can you help me?

Thanks for this awesome component!

**Comment by NightCatSama** [comment]
Can be implemented using the `process` parameter.

example: <https://jsfiddle.net/7wqvo2xc/>

document: <https://nightcatsama.github.io/vue-slider-component/#/basics/process?hash=when-the-type-of-process-is-function>

**Comment by Albvadi** [comment]
Hi,
first of all, thank you for take the time to help me, really appreciate.

I´m trying to incorporate your solution, and it´s very near, but there are a few details I´m not able to do.
Probably, it´s a Vue problem, but i¨m very very newbie...

I have two problmes to solve:
* The value it´s seted at the component mounted method, but the slider only it´s colorized when click on the dot and move the mouse(a little bit).
A example video for better explanation:
![ess](https://user-images.githubusercontent.com/6285255/65752168-7f1d6200-e10c-11e9-939f-11c11d7417b8.gif)

* I´m trying to colorize the active dot for each step, with the template and :step, but i´m not able to pass the value to compose the custom-step class. For this, if I replace `this.initialValue` for a static value (3 for example), all sliders are well initialited and colorized.

I encapsulate you slider in a custom component with an input...
This is all the code:

```vue
<template>
    <div style="padding: 0 50px;">
        <vue-slider
            v-model="value"
            :contained="false"
            v-bind="options"
            :min="0"
            :max="4"
            :adsorb="true"
            :interval="1"
            :dotSize="24"
            :marks="marks"
        >
            <template v-slot:step="{ label, active, value }">
                <div :class="['custom-step', { active }, { value }]"></div>
            </template>
        </vue-slider>
        <input type="hidden" :name="this.appname" :value="value" />
    </div>
</template>

<script>
    import VueSlider from "vue-slider-component";
    import "vue-slider-component/theme/default.css";

    export default {
        components: {
            VueSlider
        },
        props: ["appname", "initialvalue"],
        data() {
            return {
                value: "0",
                marks: {
                    0: "SIN EVALUAR",
                    1: {
                        label: "INICIACIÓN",
                        labelStyle: {
                            color: "red",
                            "font-weight": "bold"
                        },
                        stepActiveStyle: {
                            color: "yellow",
                            "background-color": "yellow"
                        }
                    },
                    2: {
                        label: "BÁSICO",
                        labelStyle: {
                            color: "orange",
                            "font-weight": "bold"
                        }
                    },
                    3: {
                        label: "AVANZADO",
                        labelStyle: {
                            color: "YellowGreen",
                            "font-weight": "bold"
                        }
                    },
                    4: {
                        label: "EXPERTO",
                        labelStyle: {
                            color: "green",
                            "font-weight": "bold"
                        }
                    }
                }
            };
        },
        mounted() {
            this.value = this.initialvalue;
        },
        computed: {
            color() {
                switch (this.value) {
                    case 0:
                        return "black";
                        break;
                    case 1:
                        return "red";
                        break;
                    case 2:
                        return "orange";
                        break;
                    case 3:
                        return "YellowGreen";
                        break;
                    case 4:
                        return "green";
                        break;
                }
            },
            options() {
                return {
                    data: this.data,
                    marks: true,
                    tooltip: "always",
                    process: dotsPos => [
                        [0, dotsPos[0], { backgroundColor: this.color }]
                    ],
                    tooltipStyle: {
                        backgroundColor: this.color,
                        borderColor: this.color
                    }
                };
            }
        }
    };
</script>

<style>
    .custom-step {
        width: 100%;
        height: 100%;
        border-radius: 50%;
        box-shadow: 0 0 0 3px #ccc;
        background-color: #fff;
    }
    .custom-step.active {
        box-shadow: 0 0 0 3px #3498db;
        background-color: #3498db;
    }
    .custom-step.active.black {
        box-shadow: 0 0 0 3px black;
        background-color: black;
    }
    .custom-step.active.red {
        box-shadow: 0 0 0 3px red;
        background-color: red;
    }
    .custom-step.active.green {
        box-shadow: 0 0 0 3px green;
        background-color: green;
    }
</style>
```

Call
```html
<range-slider appname="app-name" initialvalue=2></range-slider>
```

Thank you!

**Comment by NightCatSama** [comment]
The first problem should be caused by an incorrect type, ensuring that value is a numeric type.

```js
{
  value: 0, // '0' is wrong
}
// ...
this.value = +this.initialvalue; // Make sure initialvalue is a numeric type
```

The second question can be used `stepActiveStyle`.

example: <https://jsfiddle.net/NightCatSama/6mqhb1gv/13/>

Of course, using slot is also possible, but you are using it wrong.

example: <https://jsfiddle.net/NightCatSama/6mqhb1gv/17/>

**Comment by Albvadi** [comment]
> The first problem should be caused by an incorrect type, ensuring that value is a numeric type.

You are right. Changing to `+this.initialValue` makes all working well from init.. :tada: 


> The second question can be used `stepActiveStyle`.
> 
> example: https://jsfiddle.net/NightCatSama/6mqhb1gv/13/

I think this option is better... Tryed and all works fantasticly well

Again, thank you so much for all your time and support to help me! :blush:
