### ISSUE TITLE
Marks breaking page in IE11

### ISSUE THREAD

**Issue by mshaked1** [NightCatSama/vue-slider-component#407]
Including the marks prop breaks page and removes all of the parent's components from the DOM in IE11 when MarkOption key is an interpolated data value:
:marks="{ [someVal]: markerStyles }"

**Comment by NightCatSama** [comment]
Sorry, I don't understand what you have encountered.

Can you talk more in detail or provide a picture like gif?

In addition, marks does not support direct setting of styles, you should be like this:

```
:marks="{ 
  [someVal]: {
    label: someVal,
    style: markerStyles,
  }
}"
```

document: <https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=marks>
