### ISSUE TITLE
Slider thumb does not move dynamically

### ISSUE THREAD

**Issue by Swathikasoju** [NightCatSama/vue-slider-component#411]
#### Describe the bug

I am trying to pass the v-model value which updates dynamically. Then value in the tool tip gets updated but the slider thumb does not move till I click the mouse.

![image](https://user-images.githubusercontent.com/29271757/67749271-7a164000-fa35-11e9-98a4-c6d2c4de648e.png)

**Comment by NightCatSama** [comment]
What version are you using, can you reproduce it?

<https://jsfiddle.net/NightCatSama/2xy72dod/10494/>

**Comment by Swathikasoju** [comment]
> What version are you using, can you reproduce it?
> 
> https://jsfiddle.net/NightCatSama/2xy72dod/10494/

I am using the latest version. I am passing incremental value dynamically from 0 to 10 with delta seconds. for example it will start at 0.001, 0.234, 0.543, etc. till it reaches 10.
these values get updated in the tool tip, but I also want the slider thumb to move accordingly

**Comment by NightCatSama** [comment]
Under normal circumstances, it will definitely be updated dynamically. Does the console report an error?

**Comment by Swathikasoju** [comment]
> Under normal circumstances, it will definitely be updated dynamically. Does the console report an error?

I found the issue now, the values that are being passed are as string but it is not a data set. So it is not accepting. now if I parse it into integer it gets updated the I am missing the delta values. It does not accept the float value.

**Comment by NightCatSama** [comment]
Can set `interval = 0.001`.

<https://jsfiddle.net/NightCatSama/2xy72dod/10511/>

**Comment by Swathikasoju** [comment]
> Can set `interval = 0.001`.
> 
> https://jsfiddle.net/NightCatSama/2xy72dod/10511/

Thanks it worked!
