### ISSUE TITLE
Using `range` prop with `interval` prop makes slider pop out of the screen

### ISSUE THREAD

**Issue by janswist** [NightCatSama/vue-slider-component#414]
#### Describe the bug
Using `range` prop with `interval` prop makes dot pop out of the screen and then get back to the lower or highest value possible.

#### Additional context (If there is no relevant content, please delete the block)

Reproduction: https://jsfiddle.net/gdvcm3p8/

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: macOS
 - Vue version: v.2.6
 - Component Version: v.3.0.41

**Comment by NightCatSama** [comment]
Thank you for your feedback, fixed in version `3.0.43`.
