### ISSUE TITLE
Focus after modal

### ISSUE THREAD

**Issue by federicolucca** [NightCatSama/vue-slider-component#415]
Hi everyone,

I saw there is a similar issue but for the solution not works for me.
When the user with keyboard or mouse select a dot,a modal show up over and ask for some form data,after the submit of this data i need to get the focus back to the slider and permit to the user to move with keyboard to the next dot.

i try
          this.$refs.slider.focusSlider = 0
          this.$refs.slider.focusFlag = true
or 
          this.$refs.slider.$el.fovus()

but nothing
the last test was

          this.$refs.slider.$el.click()

but it puts the selected dot at the start of the slider

Federico

**Comment by NightCatSama** [comment]
Have you tried the `focus` method?

<https://nightcatsama.github.io/vue-slider-component/#/api/methods?hash=focusindex>

```js
// Single slider
this.$refs.slider.fovus()
// Multiple sliders
this.$refs.slider.fovus(1) // index
```
