### ISSUE TITLE
Can we have multiple colors on the slider without displaying dots?

### ISSUE THREAD

**Issue by Swathikasoju** [NightCatSama/vue-slider-component#416]
Can we display slider with multiple colors without displaying dots?
![image](https://user-images.githubusercontent.com/29271757/68948725-28a1db00-07c1-11ea-9764-aab9519c7c08.png)

**Comment by NightCatSama** [comment]
Yes, the attribute [`dotOptions`](https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=dotoptions) supports array types, which can be set style.

Or use [`slot`](https://nightcatsama.github.io/vue-slider-component/#/api/slots?hash=dot) to render the sliders separately according to `index`.

**Comment by Swathikasoju** [comment]
ok got it thank you!
