### ISSUE TITLE
Hide every other label

### ISSUE THREAD

**Issue by m-use** [NightCatSama/vue-slider-component#417]
I am creating a custom data slider. Is it possible to hide every other label, like pictured?

![image](https://user-images.githubusercontent.com/8843706/69761730-79042b80-1125-11ea-9365-9b165b8f9d83.png)

**Comment by NightCatSama** [comment]
Can be controlled using the `marks` parameter.

document: <https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=marks>

example: <https://jsfiddle.net/j0t78hcf/>

**Comment by m-use** [comment]
Thank you!
