### ISSUE TITLE
Slider renders above a modal dialog

### ISSUE THREAD

**Issue by davidyell** [NightCatSama/vue-slider-component#419]
#### Describe the bug

I am rendering a slider in my sidebar. My content can load a modal window component, which has a `z-index: 9000;` but the slider still renders above it. Adding a `z-index` to the `div.vue-slider` doesn't seem to change it.

#### Additional context

![Sidebar](https://i.imgur.com/GaNE3Tj.png)

#### Environment

 - OS & Version: Mac OS 10.14.6
 - Vue version: 2.5.13
 - Component Version: 3.0.44

**Comment by NightCatSama** [comment]
You can check if there is a hierarchy problem, it has nothing to do with the component.

**Comment by davidyell** [comment]
Yes, you're correct. I did not try a `0` value, which works. Apologies.
