### ISSUE TITLE
What changed in 3.0?

### ISSUE THREAD

**Issue by callumacrae** [NightCatSama/vue-slider-component#420]
Hello!

Big fan of this library, we find it really useful.

However, it breaks if I update from v2 to v3.

There's no release: https://github.com/NightCatSama/vue-slider-component/releases
And the changelog doesn't go back to 3.0.0: https://github.com/NightCatSama/vue-slider-component/blob/master/CHANGELOG.md

What breaking changes were there?

**Comment by NightCatSama** [comment]
Sorry, I didn't do the migration document.

The general usage is consistent, I listed the individual differences:

- Need to introduce the theme file separately.
- `tooltip-merge` is no longer supported. 
- `formatter` => `tooltip-formatter `
-  Added `marks` for better control of labels and marks.

More differences can be found in the documentation:
[v3.x](https://nightcatsama.github.io/vue-slider-component/#/api/props)
[v2.x](https://github.com/NightCatSama/vue-slider-component/tree/v2)

**Comment by NightCatSama** [comment]
If you happen to use `tooltip-merge`, it is currently only available through `slots`. Of course you can also choose not to upgrade to 3.x.

<https://github.com/NightCatSama/vue-slider-component/issues/412>

**Comment by upsilon** [comment]
The `input` event in 2.x was replaced with `change` event. It affects applications using `value` prop and `input` event instead of `v-model` to bind slider value.
