### ISSUE TITLE
Add an option to show the tooltip when hovering on the handles

### ISSUE THREAD

**Issue by cheap-glitch** [NightCatSama/vue-slider-component#423]
#### Describe the feature
It would be nice to have an option to show the tooltip when hovering on the handles.

#### Describe the solution you'd like
A `hover` option for the `tooltip` parameter:
```vue
<vue-slider v-model="model" :tooltip="'hover'"></vue-slider>
```
It would show the tooltip on both hovering and focusing one of the handles.

**Comment by NightCatSama** [comment]
When `tooltip="hover", is it possible to include "focus" function?

Because when dragging, the mouse is not always on the handle.

**Comment by NightCatSama** [comment]
Thanks for your feedback, `hover` and `active` parameters are supported in version 3.1.0.

`active` contains both `hover` and `focus` functions, and now the `tooltip` default parameter is `active`.

**Comment by cheap-glitch** [comment]
Awesome, thank you very much!

**Comment by Ali7862** [comment]
@NightCatSama I am using version 3.1.0. but not working for me can you help me?

**Comment by NightCatSama** [comment]
@Ali7862 Can you reproduce it in the example.
