### ISSUE TITLE
Allow min & max to be the same value

### ISSUE THREAD

**Issue by hannesaasamets** [NightCatSama/vue-slider-component#425]
#### Describe the feature

Allow `min` & `max` props to have the same value.

#### Additional context

There are business cases where sliders have only one valid value. In these times it makes little sense to render another component in it's place to show that value. There is no reason to show an error in that cases.

**Comment by NightCatSama** [comment]
A complete component must have a head and a tail, then the minimum and maximum values must be inconsistent, otherwise the component will become a point.

Maybe you can try the `data` prop.

```vue
<vue-slider v-model="value" :data="[value]" />
```
