### ISSUE TITLE
Add timeout to change request.

### ISSUE THREAD

**Issue by kylemilloy** [NightCatSama/vue-slider-component#426]
#### Describe the feature

Right now I have an xhr request firing that updates a search filter. I originally had this tied to drag-end so that it wouldn't throw out a request every time a change is emitted however the issue here is that when I click on the slide rail it only throws a change event...not a drag-end. or click or anything else. I've had to implement a timeout that gets reset each time a change event is fired.

#### Describe the solution you'd like

Ideally you'd be able to pass a prop to the slider to tell it to retard the intervals at which it emits change events. Something like: `<slider :timeout="1000"/>` which further down in the slider component would look like:

```ts
private syncValueByPos() {
    const values = this.control.dotsValue
    if (this.isDiff(values, Array.isArray(this.value) ? this.value : [this.value])) {
      this.emitChange(values.length === 1 ? values[0] : [...values]);
    }
  }

private emitChange(value) {
  if (this.delay === 0) {
    this.$emit('change', value);
    return;
  }

  clearTimeout(this.timeout);
  this.timeout = setTimeout(() => {
    this.$emit('change', value);
  }, this.delay);
}
```

Where timeout is a data attribute and delay is our timeout prop. If delay is 0 (which it should default to) it won't use timeouts and won't append changes to the end of the call stack.

**Comment by NightCatSama** [comment]
You should use `:lazy` and `@change`.

```vue
<vue-slider :lazy="true" @change="change">
```

As for latency and timing, you can implement it outside the component.

**Comment by kylemilloy** [comment]
Yep -- I'm already implementing it outside of the component....feature request would be to implement this inside the component. Ideally I'd like to keep the model updating where I can see what value I'm sliding to, but only triggering an update event after a given time.

**Comment by NightCatSama** [comment]
In lazy mode, you can use `@dragging` to get the drag value.

```vue
<vue-slider v-model="value" :lazy="true" @dragging="val => doSomeThing(val)" />
```

**Comment by kylemilloy** [comment]
Understood. But again this doesn't solve the issue of having timeout functionality nestled into the component. If it's something you'd like me to write a PR for or something you'd like to reject, lemme know.

**Comment by NightCatSama** [comment]
I think the timeout function is beyond the functional scope of a slider component. Sorry, it will not be added.

**Comment by kylemilloy** [comment]
No worries.
