### ISSUE TITLE
Issue regarding change event and lazy

### ISSUE THREAD

**Issue by kono5alive** [NightCatSama/vue-slider-component#427]
Hello!

Thanks for the wonderful component.  I'm having issues in my current application.  For a quick context update, I have an array of objects in my component's model which comes from the server, like {value:string, category:string}.  now, for each category, i have a list of values that are appropriate, and i've used the vue-slider-component multiple times, once for each category.  i've been unable to use the v-model attribute because i'm unsure if there's even a way to use the same array (or some computed variation) for all the sliders to be using the same thing (and basically just update/insert their category/value into the array). 

SO, with that said, i've had to resort to using the change event on sliders like so:
`
<vue-slider 
 v-on:change="(value) => { onComponentChange(value,references.characterComponentCategories.Hair) }" :data="componentRangeValues(references.characterComponentCategories.Hair)" value="default" :lazy="true"></vue-slider>
`
Note: The data attribute is looking at a computed field which does some lookups to figure out a simple string array of values to pass back for the category this slider acts on.

what i'm noticing if that, the onChange event fires fine when i slide away from the value "default" (which is always the first value in the reference list for the data), and since i'm not using model, i set value="default" so that the slider doesn't initialize with the '0' (default) value that it ships with.  However, when i slide back and return to "default" in the values of the slider, it never fires on the onChange event!  I'm wondering why this is, if the onChange noticed that i left default, the internal value should not be default anymore and whatever the value is on the slider, so theoretically i should be able to get onChange to fire when returning to it.  

Any guesses as to what might be causing this?

**Comment by NightCatSama** [comment]
In fact, components cannot distinguish whether you use `v-model` or `value`.

You can use `setValue` method instead of `value` initialization value.

```vue
this.$refs.slider.setValue('default')
```

**Comment by kono5alive** [comment]
Got it, will give it a shot and see if that resolves any issues! thanks!
