### ISSUE TITLE
Format input linkage

### ISSUE THREAD

**Issue by alexsonnay** [NightCatSama/vue-slider-component#429]
Hello,

Really great plugin so thanks ! Any idea how to dynamically format the input linkage ? 

v-model="price | number" isn't allowed and I haven't found any solution.

```
           <div class="inputs">
              <div>
                 <input v-model.number="price[0]" type="number" />
              </div>
              <div>
                 <input v-model.number="price[1]" type="number" />
              </div>
           </div>
         <vue-slider
          :min="0"
          :max="50000000"
          :interval="5000"
          v-model="price"
          :tooltip="'always'"
          :useKeyboard="true"
          :enable-cross="false"
          @change="clearErrorMsg"
        >
          <template v-slot:tooltip="{ value }">
            <div class="vue-slider-dot-tooltip-inner">
              {{ value | number }}
            </div>
          </template>
      </vue-slider>

computed: {
    price: {
      get() {
        return this.$store.state.filters.price;
      },
      set(value) {
        this.$store.commit("SET_PRICE", value);
      }
    },
  }

**Comment by NightCatSama** [comment]
What's wrong with using `v-model="value"` directly?

Using strings directly: <https://jsfiddle.net/4ofrabzs/1/>

Use `:value` and `@change`: <https://jsfiddle.net/4ofrabzs/2/>

**Comment by alexsonnay** [comment]
Thanks but the problem is that I can't use "v-model="value | number".

In your examples there is no input field where the value is automatically parsed.

What I want is for the input to be parsed the same way as the tooltip is, with thousand separator.

Any idea how to that ?

<img width="173" alt="image" src="https://user-images.githubusercontent.com/28756458/71960687-e8297100-31f5-11ea-9978-518b5b8835f2.png">

**Comment by NightCatSama** [comment]
Can't do this, `v-model` does not support filters.

See the official documentation for details.

**Comment by alexsonnay** [comment]
Even with a watch() ? And update value ?

**Comment by NightCatSama** [comment]
I don't quite understand what problems you encounter.

**Comment by alexsonnay** [comment]
In my screenshot, can you see that the input isn't formatted the same way as the tooltip ?

**Comment by NightCatSama** [comment]
So you want the values to be formatted, right?

**Comment by alexsonnay** [comment]
Exactly. I want the input AND the tooltip to be 41 470 000

**Comment by NightCatSama** [comment]
You can add a field to proxy the formatted value.

<https://jsfiddle.net/emz5a461/2/>

**Comment by alexsonnay** [comment]
Thanks but in your example, it's working because you put the value inside an H1 tag.

I want the number to be formatted inside the input tag. 

Is it possible ?

**Comment by NightCatSama** [comment]
Both `value` and `sliderValue` can be modified.

How to modify it externally has nothing to do with the component.

**Comment by alexsonnay** [comment]
Ok so you're not able to it as well...
Thanks
