### ISSUE TITLE
Is it possible to have a global config

### ISSUE THREAD

**Issue by Mushr0000m** [NightCatSama/vue-slider-component#432]
There is a lot of props and that's great, but is there a way to set global config to change the default options ?

**Comment by NightCatSama** [comment]
You can build your own components and use the default parameters.

example:
```
<template>
  <vue-slider
      tooltip="none"
      v-bind="$attrs"
  />
</template>

<script>
  export default {
    name: 'MySlider',
    inheritAttrs: false,
  }
</script>
```

It's just pseudocode. You can do it better.
