### ISSUE TITLE
Change event value not returned if it's 0 (zero)

### ISSUE THREAD

**Issue by ariona** [NightCatSama/vue-slider-component#434]
#### Describe the bug

I have set the min to 0, and i add change event to set the value of other component. But when the slide reach zero there is no return value on the change event.

```html
<VSlider
      ref="slider"
      :v-model="cvalue"
      :interval="interval"
      :marks="marks"
      :direction="direction"
      :height="height"
      :adsorb="true"
      tooltip="none"
      @change="onChange"
    />
```

```js
...
methods: {
    onChange(value){
      console.log(value); // 0 value not returned
      this.$emit('input', value);
    }
}
```

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: [e.g. macOS, Windows, Linux]
 - Vue version: [e.g. v2.0, v2.5, v2.6]
 - Component Version: [e.g. v3.0.2]

**Comment by NightCatSama** [comment]
Can you reproduce it in the online example.

<https://jsfiddle.net/2h7ap8mu/>

**Comment by ariona** [comment]
silly me, just typo on `:v-model` should be `v-model`

**Comment by RomPavel** [comment]
I can reproduce it online. U onlu need to use :value instead of :v-model and remove adsorb:true
![image](https://user-images.githubusercontent.com/31888768/83041279-fbc06180-a048-11ea-8397-2d6c880cc24e.png)
