### ISSUE TITLE
Showing tooltip on each hover

### ISSUE THREAD

**Issue by ijunaid8989** [NightCatSama/vue-slider-component#435]
Right now it's showing a hover when you clicked position, 

is there any possibility to see a tooltip any hover?

**Comment by NightCatSama** [comment]
Is this what you want?

<https://jsfiddle.net/ahzk46bo/>

**Comment by ijunaid8989** [comment]
Not like this, 

right now when I hover at any point it shows tooltip at the nob. and only the point of a nob.

I want to hover any point and see that point's no, without moving nob.

**Comment by NightCatSama** [comment]
Sorry, I still can't understand your needs.

**Comment by ijunaid8989** [comment]
![image](https://user-images.githubusercontent.com/13561999/74222630-c03a9b00-4cd6-11ea-867b-489eba81990a.png)

![image](https://user-images.githubusercontent.com/13561999/74222652-cc265d00-4cd6-11ea-971f-d46db4209526.png)

![image](https://user-images.githubusercontent.com/13561999/74222717-f24bfd00-4cd6-11ea-89c5-dccf3fdbdda4.png)


Now this is a blue bar.

as I click anywhere, thats fine.

What I want to develop is, when I hover anywhere on the blue bar, I see the timestamp attached on this point.

as you see we have number? in above example (which you made), I want to hover on anywhere and show that points value not  slider's or slider position value.

**Comment by NightCatSama** [comment]
This functional component cannot be directly implemented, I wrote an example, you can refer to：

<https://jsfiddle.net/zebw2r3a/>

**Comment by ijunaid8989** [comment]
Thank you so much for your all work I think we are very close right now.

as you know, when you move the slider, there is always one value. can you
just tell me how we can is there any event so whenever I hover at any
point, I can get value?


for example, when you move the slider to 42, it shows 42 and let say you
hover over a little bit next to it and we know it will be either 44 45 or
so on?

Can on hover, we can get that value? in short, hover at any place and get
the expected value of that point, which will be when slider will be at that
point.

Junaid Farooq
Software Developer - Evercam.io

**Comment by NightCatSama** [comment]
You can call component methods to get the value of a certain location.

<https://jsfiddle.net/4h59ardL/>

**Comment by ijunaid8989** [comment]
Thats it. Thank a lot.
