### ISSUE TITLE
Is there a way to get tooltip with the value when we hover on the slider rail?

### ISSUE THREAD

**Issue by Swathikasoju** [NightCatSama/vue-slider-component#439]
![image](https://user-images.githubusercontent.com/29271757/75448307-9ee2db80-5973-11ea-8911-ecbeddb337d3.png)

**Comment by NightCatSama** [comment]
You can refer to <https://github.com/NightCatSama/vue-slider-component/issues/435>

<https://jsfiddle.net/4h59ardL/>

**Comment by amaieras** [comment]
Hi,
And is it possible to show the tooltip only when hovering on the custom steps? And not on each point of the slider?

**Comment by Swathikasoju** [comment]
I implemented the tooltip on rail thank you 🙂
