### ISSUE TITLE
Can you integrate a way to bind 2 sliders together?

### ISSUE THREAD

**Issue by anneangersbach** [NightCatSama/vue-slider-component#44]
Hi :)

I'm currently trying to have 2 sliders work together. You can use them individually, or lock them together, so when you move the first, the second gets the same value.
You can compare it to [noUiSlider Locked Example](https://refreshless.com/nouislider/examples/#section-lock).

My function is a bit cheaper than noUI. I lock the second slider, and use the value from the first for both of them.
I have the following issue:
When I use click to change the value, the 2nd slider changes instantly. But when I drag the first slider, the second has a big delay.
![range-slider-lag](https://cloud.githubusercontent.com/assets/161883/24961118/22c883f0-1f98-11e7-9760-6cecff395bfa.gif)

I'll attach my settings and my function.

![image](https://cloud.githubusercontent.com/assets/161883/24960855/5bb47238-1f97-11e7-8ec3-1e01b4de1d5d.png)

both sliders have the same settings.

and the function: 
![image](https://cloud.githubusercontent.com/assets/161883/24960835/4fe267d0-1f97-11e7-9f9a-157913bbfbb0.png)

**Comment by NightCatSama** [comment]
To achieve drag-and-drop synchronization requires some settings.

I write a example: [https://jsfiddle.net/9pp3dqkq/6/](https://jsfiddle.net/9pp3dqkq/6/)
