### ISSUE TITLE
Different style on left and right "dot"

### ISSUE THREAD

**Issue by martinhschei** [NightCatSama/vue-slider-component#441]
I use this component to make a simple video editor and to mark the "in" an "out" of the clip - it works great! But - i would like to be able to easily have two different dots depending on the dot being the leftmost or rightmost dot.

Something like this would be great:

```
<template v-slot-right:dot> 
     <i class="fal fa-sign-in-alt"></i>
</template>

<template v-slot-left:dot> 
     <i class="fal fa-sign-out-alt"></i>
</template>
```

**Comment by NightCatSama** [comment]
You can use `index` to determine the left and right sliders.

```vue
<vue-slider>
  <template v-slot:dot="{ index }"> 
     <i class="fal fa-sign-out-alt" v-if="index === 0"></i>
     <i class="fal fa-sign-in-alt" v-if="index === 1"></i>
  </template>
</vue-slider>
```

**Comment by martinhschei** [comment]
Yes - thanks - it works very well!
