### ISSUE TITLE
How can values from 10,000 to 10,000,000 labeled be used?

### ISSUE THREAD

**Issue by chelkaz** [NightCatSama/vue-slider-component#442]
Custom Data not work with label
i want 
10000: "10 000r",
50000: "50 000r",
700000: "700 000r",
1000000: "1 000 000r",
10000000: "10 000 000r",

marks="marks"
does not work with amounts greater than 100

**Comment by NightCatSama** [comment]
Why `marks` does not work with amounts greater than 100?

<https://jsfiddle.net/o8jsh0pq/>
