### ISSUE TITLE
How can I set up limits ?

### ISSUE THREAD

**Issue by NadimD** [NightCatSama/vue-slider-component#443]
Greetings,

I have a slider with a min/max set to 0/245 with a step of 35.
I would like to set the start value to 35, which is working, but prevent the value to be dragged under 35, so that the scale stays right and the user can only drag between 35 and 245.

Any idea how to cover that ? I didn't find limits in the docs.
Thank you.

**Comment by NightCatSama** [comment]
The property `dotOptions` can set the `min` and `max` of the slider.

<https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=dotoptions>

**Comment by NadimD** [comment]
Excellent! I missed these two options in `dotOptions`. Thank you!
