### ISSUE TITLE
slider mark label active appears also for not selected values

### ISSUE THREAD

**Issue by anviksuteiriy** [NightCatSama/vue-slider-component#444]
![slider](https://user-images.githubusercontent.com/27537367/76957617-1d5fe700-693c-11ea-8282-a7f00dc67d82.png)
as you can see in the above image there i have applied `background-color: black;` for active value and i think ideally it should be applied for only selected value( which is not happening and all three are geting applied with color black)

![class](https://user-images.githubusercontent.com/27537367/76957619-1e911400-693c-11ea-9f72-61a6c0026983.png)

when inspected the code i can see class `vue-slider-mark-label-active` applied for None, Less, Normal value.

Is there a possible way that class `vue-slider-mark-label-active` is applied to only selected value instead of all.

Thanks for this amazing component !!

**Comment by NightCatSama** [comment]
Can be achieved using `marks`.

<https://jsfiddle.net/1dLw04a7/>

**Comment by anviksuteiriy** [comment]
thanks @NightCatSama, it worked !!!
