### ISSUE TITLE
Custom selection of drag start and drag end positions

### ISSUE THREAD

**Issue by otakuOP** [NightCatSama/vue-slider-component#446]
I am trying to achieve custom drag start and end position in vue slider. 
 I have data property and i would like to start my drag position from B and drag position ends at F.
A and G position are shouldn't clickable and draggable. 
https://jsfiddle.net/otakuOP/y8ksgvw6/9/
Any suggestions to how to achieve this one ?

**Comment by NightCatSama** [comment]
You can use `dotOptions` to limit the slider range.

e.g. <https://jsfiddle.net/e201Lwrv/>

**Comment by otakuOP** [comment]
@NightCatSama  Thanks :)
