### ISSUE TITLE
using marks with same distance to each other while beeing able to select every value from min to max

### ISSUE THREAD

**Issue by stormtroop** [NightCatSama/vue-slider-component#447]
Hello guys,

first of all thanks for this great component. 
Im currently using it to display specific slots, my problem is that i want the customer to be able to choose from 10-1000 which works with `marks` and by providing a min and max amount.
My problem is that the `vue-slider-mark` positioning seems to be related to the value, which means that values like 10, 12, 14 etc. doesnt have the same distance to each other.

I also tried out the data-property, the problem is the customer should also be able to choose values which are not inside of this array.

On top you can see what im trying to achive, on bottom you can see the results by just using marks:
 
![image](https://user-images.githubusercontent.com/15097024/78768918-e43ff300-798c-11ea-81b7-fe8810418904.png)

Do you have an idea how i can change the positioning to be equaly for `vue-slider-mark` ?

**Comment by NightCatSama** [comment]
It is currently impossible to achieve this function.

According to your needs, is there 748 selectable values in the last interval of 250-1000?

**Comment by stormtroop** [comment]
@NightCatSama yes,
the example above was made with the noUISlider. 
They provide a way (very similar to your marks) where you can not only assign a mark but also the range for it

**Comment by stormtroop** [comment]
@NightCatSama is there maybe a way to just positioning the `marks` like you are doing it for the `data` arrays, when i use `data` instead of `marks` its perfectly aligned just that you cannot choose anything which is not specified (like 251, 252)

**Comment by NightCatSama** [comment]
It is currently impossible to achieve this function.

According to your needs, is there 748 selectable values in the last interval of 250-1000?

**Comment by stormtroop** [comment]
> It is currently impossible to achieve this function.
> 
> According to your needs, is there 748 selectable values in the last interval of 250-1000?

yes

**Comment by NightCatSama** [comment]
I understand your needs, but this effect cannot be achieved at present. 

Maybe this feature will be added in the future, but there should be no changes recently, sorry 😢 .
