### ISSUE TITLE
railStyle,processStyle

### ISSUE THREAD

**Issue by Charsune** [NightCatSama/vue-slider-component#448]
大大您好，谢谢你提供的一个很棒的组件！我是刚学编程不久的新手，看不太懂文件。
请问将vue-slider-component引入组件后，该如何更改进度条的样式（颜色、行高之类的）

<img width="216" alt="截圖 2020-04-12 下午8 09 54" src="https://user-images.githubusercontent.com/33538421/79068459-96631c00-7cf9-11ea-9f43-0dc57239e412.png">

谢谢您

**Comment by NightCatSama** [comment]
改动不大的话可以使用 `processStyle`，如果改动较大的话建议直接修改主题文件。

具体可以参考文档：
<https://nightcatsama.github.io/vue-slider-component/#/zh-CN/style>

**Comment by Charsune** [comment]
谢谢大大的回覆。
不好意思，想请问一下这样写是哪边写错了。还是无法更改样式
<script>
import Header from "@/components/Header";
import VueSlider from 'vue-slider-component'
import 'vue-slider-component/theme/antd.css'
export default {
  data(){
    return{
      eyes: 50,
      rhinoplasty: 50,
      processStyle:{
        $bgColor:'#59E2F5',
        backgroundColor:'#59E2F5',
      },
      railStyle:{
        height:'8px',
      },
    };
  },
.....

**Comment by Charsune** [comment]
![截圖 2020-04-13 下午10 16 53](https://user-images.githubusercontent.com/33538421/79127441-7bb1a580-7dd4-11ea-9e90-87dde29b7725.png)

**Comment by NightCatSama** [comment]
`$bgColor` 不能这样用的，那是 `scss` 的用法。

另外控制高度最好直接使用组件的 `height` 参数

我写了个简单的例子你可以参考一下 <https://jsfiddle.net/NightCatSama/2xy72dod/10545/>

对了，如果样式改动较多，而且你也不怎么会使用 `scss` 的话。你也可以把直接把样式文件(例如 [antd.css](https://github.com/NightCatSama/vue-slider-component/blob/master/theme/antd.css) )拷贝下来。

然后去掉 `import 'vue-slider-component/theme/antd.css'` 改成你本地的 css 路径 `import './antd.css'`

**Comment by NightCatSama** [comment]
另外 `processStyle` 和 `processStyle` 的写法和 vue 自带的内联样式 `style` 写法一致，你可以参考[官方文档](https://cn.vuejs.org/v2/guide/class-and-style.html#%E5%AF%B9%E8%B1%A1%E8%AF%AD%E6%B3%95-1)

组件的参数可以看这里 <https://nightcatsama.github.io/vue-slider-component/#/zh-CN/api/props>

**Comment by Charsune** [comment]
好的，太感谢了！
