### ISSUE TITLE
slider dots position not correct when sum of abs values equals 160 000 000

### ISSUE THREAD

**Issue by uplanojevic** [NightCatSama/vue-slider-component#449]
Hello,

I am using your library, it helped me a lot. 
Thank you for the great work and your contribution.

Just wanted to inform you there is one edge case bug I've found. 
For example, when min = -80 000 000 and max = 80 000 000 slider dots don't function properly. Here is a fiddle with the reproducible bug: https://jsfiddle.net/49zoh75f/
Never the less, I found a potential work around. In the mentioned case, I set the interval to be 2 and with that, everything seems to work just fine.

Do you think this is ok? It would mean a lot if this bug can be fixed so I can avoid this workaround.

#### Environment 
 - OS & Version:  Windows
 - Vue version: v2.6.11
 - Component Version: v3.1.0

**Comment by NightCatSama** [comment]
Thanks for your feedback, it is fixed in version `v3.1.2`.
