### ISSUE TITLE
support for non linear sliders

### ISSUE THREAD

**Issue by unitedworx** [NightCatSama/vue-slider-component#45]
Congrats on the wonderful slider. I have been looking for a vuejs based range slider and this looks like a perfect solution except that it does not support non linear sliders.  Non linear support would be a great addition to this component!

A non linear slider allowing you to e.g have a slider from 0 to 20,000,000 while half the slider allowing you to span between 0 and 2,000 while the rest from 1,000 to 20,000,000 this is useful for a real estate website price range sliders to cover both low price ranges for rentals and high price ranges for sales.

Here is how this is covered by other sliders (not vue based but jquery based)

http://egorkhmelev.github.io/jslider/
look at heterogeneity example

http://refreshless.com/nouislider/slider-values/#section-non-linear
look at the non linear example

**Comment by NightCatSama** [comment]
This is a good idea.

I tried to support it, but I found that this is now with my component structure is very different, it is difficult to support it.

Sorry, this feature I can not achieve.

**Comment by unitedworx** [comment]
no problem, thanks fro considering. from what I have seen on the other slider this is done thought a calculate percentage function that translates a position on the slidice er to and actual value and vice versa.
