### ISSUE TITLE
reset call?? 

### ISSUE THREAD

**Issue by JamieGarcia123** [NightCatSama/vue-slider-component#450]
More of a i am not sure how to reset the slider to slide back to the default value. 

we have this implemented as a date and time range filter and we can reset those filters on the data side but the slider stays in position of the chosen filter....

For example i choose 2:00p.m. - 5:00p.m on out multi range slider and we call out reset filter method. the slider stays on that selected time

**Comment by NightCatSama** [comment]
Can you restore the problem in the online example.

<https://jsfiddle.net/NightCatSama/2xy72dod/10520/>

**Comment by JamieGarcia123** [comment]
https://jsfiddle.net/g904af58/  similar to this

**Comment by NightCatSama** [comment]
javascript has no such usage:
```js
return this.value = this.value[0,1]
```

Reset the default value can add a variable to save:
<https://jsfiddle.net/NightCatSama/2s0Lp7cr/>

**Comment by JamieGarcia123** [comment]
we resolved thank you
