### ISSUE TITLE
How to override inline css of active vue slider dot

### ISSUE THREAD

**Issue by otakuOP** [NightCatSama/vue-slider-component#451]
Hi,
I customized vue slider with my own design. I make the marks in my own position. Slots are very useful to achieve customized designs and labels. but For the active dot slot, I couldn't able to change the inline CSS of left property. 
I would like to apply the same left property position to the active vue slider dot. I tried to use dotStyle and dotOptions -> style to change the left property of the active dot but none of them worked for me to change the inline CSS. When I click on the marks, the active dot should stay at my own specified position. Currently left property value taking a position as 0, 33.33%,50%,66.66%,83.33%,100%.
I want to change the left property to 0,20,40,50,60,80,100. So active dot will stay at the position of the correct marks

https://jsfiddle.net/otakuOP/ok4qd8um/10/

Can you give me any suggestions to achieve this?

**Comment by NightCatSama** [comment]
The `data` property does not support custom segmentation.

You can use `marks` and `included` to achieve this function.

I wrote an example, you can refer to:
<https://jsfiddle.net/NightCatSama/15f36ey0/18/>
