### ISSUE TITLE
Crossing sliders but maintain slider 'identity'

### ISSUE THREAD

**Issue by pwichmann** [NightCatSama/vue-slider-component#452]
#### Describe the feature

Instead of returning a value array [min, max], is it possible to return a value array [value_slider_1, value_slider_2], where the position in the array encodes which slider it is.

#### Describe the solution you'd like

Allow sliders to cross but maintain the identity of the sliders.
Currently, if I move the left slider across the right one, it becomes the new right slider.
However, I want to be able to invert the range: If the left slider crosses the right slider, I would like to select the range from the formerly left slider until plus infinity, and from minus infinity until the formerly right slider.

**Comment by NightCatSama** [comment]
You can use the `order` attribute to keep the 'identity' of the slider, but the value is unsorted, you can add a value to sort it yourself.

e.g.
<https://nightcatsama.github.io/vue-slider-component/#/advanced/order>
