### ISSUE TITLE
Exposing focus dot index so that the user can know which dot was dragged

### ISSUE THREAD

**Issue by BhuvaneshShan** [NightCatSama/vue-slider-component#456]
#### Describe the feature

When a slider has multiple slider dots, I would like to know the slider dot index whose position was changed by the user. 

#### Describe the solution you'd like

Currently v-on:change returns all the values with the updated slider dot value. 
But the caller cannot know which value changed without storing and comparing with earlier dot values. This could help the caller know which position in the return values[] changed.

This could be achieved by either sending the 'focus dot index' when drag-start or drag-end is emitted.

**Comment by NightCatSama** [comment]
Thank you for your suggestion, it has been added in version v3.1.3.

<https://nightcatsama.github.io/vue-slider-component/#/api/events>

**Comment by BhuvaneshShan** [comment]
Thank you NightCatSama! Very fast turn around time.
