### ISSUE TITLE
features: play pause and drawing graph

### ISSUE THREAD

**Issue by bnping** [NightCatSama/vue-slider-component#457]
I wounder if the next version can contains play pause  and draw graph shown in photo below.
![image](https://user-images.githubusercontent.com/63243110/82818968-de9c5f00-9e9f-11ea-8a1b-061bbeff4b24.png)

this type of slider is very used in GIS like here 
 https://kepler.gl/demo/earthquakes ==> click try simple date to see

**Comment by NightCatSama** [comment]
These features should not be implemented by the slider component.
