### ISSUE TITLE
change Tooltip value or position on hover

### ISSUE THREAD

**Issue by bnping** [NightCatSama/vue-slider-component#458]
current implementation require that the user click to change the slider, i think it is better if we can change the the slider using only hover.

**Comment by NightCatSama** [comment]
Is this feature you want?

<https://nightcatsama.github.io/vue-slider-component/#/basics/simple?hash=dragonclick>

**Comment by bnping** [comment]
@NightCatSama thank to your response. in fact, this is not what i need. I do not need to do click to change the value or the position of slider. I need to change the Tooltip on the hover of mouse.  maybe a simple code like this
   when the mouse is on slider:
          postion = getMousePosition()
          sliderValue = getSliderValue(position)
          changeSliderTipPositionTo(sliderValue)

**Comment by NightCatSama** [comment]
I wrote an example, you can refer to <https://jsfiddle.net/ungb3m1q/1/>

**Comment by bnping** [comment]
@NightCatSama  thanks. your example works with mouse click but not hover.  we need use hover to move the Tooltip.

**Comment by NightCatSama** [comment]
Sorry, I sent the wrong link before, this is right.

<https://jsfiddle.net/oakpn09d/>

**Comment by NightCatSama** [comment]
This is the example of vue2.6.0+, if it is the previous version, `slot` and `slot-scope` are required.

**Comment by bnping** [comment]
@NightCatSama  thanks. that exactly the solution.  I add this line of code
  this.value =  this.tooltipValue so the tool tip move/follow the mouse. But i dont know if my line of code has pb in performance. 
here is your code after my line of code added.
https://jsfiddle.net/oakpn09d/

**Comment by NightCatSama** [comment]
Is it like this? <https://jsfiddle.net/r3xua1wg/>

**Comment by bnping** [comment]
@NightCatSama  yes thanks. can you put it in the examples in the doc, this may be helpful.
