### ISSUE TITLE
Dot position not restricted to max

### ISSUE THREAD

**Issue by mulhoon** [NightCatSama/vue-slider-component#46]
Hi, great component!

I've noticed an issue, maybe I am missing something...

If I set a slider `value` higher than the `max` value, the dot position is not restricted to the max value and breaks out of the slider.

How can I restrict it to the max? 

It would be great if it worked the same as the HTML input range - i.e. the value can still be set higher than the maximum, but the dot position is restricted to the maximum width.

Thanks, Nic

**Comment by NightCatSama** [comment]
This is a good suggestion later i will add.

**Comment by mulhoon** [comment]
Thanks for the quick update! It helped a lot.
