### ISSUE TITLE
Dots can go off rails when `min-range` is really small

### ISSUE THREAD

**Issue by WofWca** [NightCatSama/vue-slider-component#460]
#### Describe the bug

![image](https://user-images.githubusercontent.com/39462442/83713694-6716be80-a65b-11ea-8a5b-cea128d7a73a.png)

1. Set `:min-range` to a really small value, like `Number.MIN_VALUE`.
2. Drag any dot, move the cursor beyond the slider's rails.

<details>

<summary>Code</summary>

```vue
<template>
<vue-slider
  v-model="value"
  v-bind="options"
/>
</template>

<script>
export default {
  data () {
    return {
      value: [30, 50],
      options: {
        minRange: Number.MIN_VALUE,
        // The following line does not cause the bug.
        // minRange: 10e30 * Number.MIN_VALUE,
      },
    }
  },
}
</script>
```

</details>

(https://jsfiddle.net/ptonekmr/)

#### Additional context (If there is no relevant content, please delete the block)

I thought it would be intuitive for dots to drag each other when `min-range` is `0`, yet they behave as if `:min-range="undefined"`, so I resorted to this approach.

The bug does not appear in at least `3.0.26`.

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: Windows 10
 - Vue version: v2.6.11
 - Component Version: v3.1.5

**Comment by NightCatSama** [comment]
You can temporarily use a relatively small number instead, like `:min-range="0.01"`.
