### ISSUE TITLE
Allow value precision greater than 10^-7

### ISSUE THREAD

**Issue by blaney83** [NightCatSama/vue-slider-component#462]
#### Describe the feature

The currently slider cannot handle values beyond 7 decimals worth of precision. It would be nice if there was an option to support more precise values. The current solution is to round all values to the maximum allowable precision.

Current use-case (initial values): 
`                            "min": [
                                0.001010167098195791
                            ],
                            "max": [
                                0.9997572421887096
                            ]`

#### Describe the solution you'd like

Understanding that there may be a performance tradeoff for supporting greater precision, if a prop could be created to support these values. Otherwise, enabling this behavior by default would be best.

#### Additional context

Current behavior if you exceed the maximum precision:

![image](https://user-images.githubusercontent.com/42789727/84016974-5d07ff00-a97e-11ea-9d6e-98b44af3cf17.png)

#### ENV:

OS & Version: MacOS 10.15.4
Vue version: v2.6.11
Component Version: v3.1.5

**Comment by NightCatSama** [comment]
To achieve smaller accuracy, smaller spacing is required.

It should support more than 7 decimal places

<https://jsfiddle.net/p8tk32rL/>

**Comment by blaney83** [comment]
Fantastic. Thank you!
