### ISSUE TITLE
Add Rail background color between marks

### ISSUE THREAD

**Issue by Fujeremy** [NightCatSama/vue-slider-component#463]
#### Describe the feature

Change rail color between marks

#### Describe the solution you'd like

Currently process only allows you to use dots as the separator between different background colors of rails. 
Can we allow marks to also be included so that we can change the rail color between the marks

#### Additional context (If there is no relevant content, please delete the block)

<img width="709" alt="Screen Shot 2020-06-09 at 1 02 53 PM" src="https://user-images.githubusercontent.com/14296675/84177927-9d847d00-aa51-11ea-98c3-0e674d37c067.png">

**Comment by NightCatSama** [comment]
There is currently no such feature, but you can get the position of each mark to implement it yourself.

I wrote a simple example, you can refer to:
<https://jsfiddle.net/162qryaL/>

**Comment by Fujeremy** [comment]
thank you!
