### ISSUE TITLE
move slider on mousedown

### ISSUE THREAD

**Issue by 719media** [NightCatSama/vue-slider-component#464]
#### Describe the feature

It would be nice if  the slider could be dragged without having to explicitly touch the handle. Like how youtube works. I can click DOWN anywhere on the track and start dragging, and it works.

#### Describe the solution you'd like

Have the slider move on mousedown and not just click/mouseup so that drags can happen more easily.

**Comment by NightCatSama** [comment]
Have you tried the `drag-on-click` parameter?

<https://nightcatsama.github.io/vue-slider-component/#/basics/simple?hash=dragonclick>
