### ISSUE TITLE
Multiples steps like the noUiSlider

### ISSUE THREAD

**Issue by aislanmaia** [NightCatSama/vue-slider-component#465]
#### Describe the feature
In the documentation I can't find a way describing how to have multiple steps for each pixel of the Slider.

#### Describe the solution you'd like
Think of it like using a slider as a meter, so each space you drag the slider it corresponds to a value. This is handy for sliders representing distances, a meter gauge for fuel, temperature, etc. Like we have now, its behavior is like jumping step by step.

#### Additional context (If there is no relevant content, please delete the block)

Examples from noUiSlider
https://refreshless.com/nouislider/examples/

**Comment by NightCatSama** [comment]
Can you describe it more clearly, specifically which example in noUiSlider.

Is this the feature? <https://nightcatsama.github.io/vue-slider-component/#/basics/simple?hash=adsorb>

**Comment by aislanmaia** [comment]
I like something exactly like this: (this is using noUiSlider)

![slider-example](https://user-images.githubusercontent.com/2199137/85052500-69a30900-b16f-11ea-8991-1baa49497ff4.gif)

**Comment by NightCatSama** [comment]
This feature is currently not supported and there is no time to implement it recently, sorry. 😿

**Comment by NightCatSama** [comment]
example: <https://nightcatsama.github.io/vue-slider-component/#/basics/interval>

example source: <https://github.com/NightCatSama/vue-slider-component/pull/612>
