### ISSUE TITLE
Vue3: Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by sinasita** [NightCatSama/vue-slider-component#466]
Refering to the issue https://github.com/NightCatSama/vue-slider-component/issues/410, when I try to use vue-slider-component in vue3, I get the same error, even when using the latest version 3.15.

Any ideas on how to solve the issue?

**Comment by NightCatSama** [comment]
Ah, the component has not done any processing on the compatibility of vue3.0.

**Comment by johnenrick** [comment]
Vue 3 has been released, any update for this?

**Comment by johnenrick** [comment]
Nevermind, I used `npm install vue-slider-component@next --save` and it works :)
