### ISSUE TITLE
[v2]

### ISSUE THREAD

**Issue by darrellmalick** [NightCatSama/vue-slider-component#467]
#### Describe the bug

The bar is not visible.  The dots are.  Happening everywhere in my code.  Here are two examples:

<img width="267" alt="Screen Shot 2020-06-22 at 1 51 55 PM" src="https://user-images.githubusercontent.com/43726951/85284601-c5cb9d00-b48f-11ea-8c5c-4513cc7f233f.png">
<img width="542" alt="Screen Shot 2020-06-22 at 1 52 18 PM" src="https://user-images.githubusercontent.com/43726951/85284608-c9f7ba80-b48f-11ea-9476-5f3f4dd82bf8.png">

Here is relevant code from one of the pages:

```
<script>
import VueSlider from "vue-slider-component";
import "vue-slider-component/theme/default.css";
```
...

```
<template>
  <div>
    <div class="slider-text">
      <span>10</span>
      <span>slide to adjust</span>
      <span>100</span>
    </div>
    <vue-slider
      v-model="goalSlider"
      :min="10"
      :max="100"
      :interval="5"
      :marks="true"
      :hide-label="true"
      lazy
      @change="onSliderChange"
    />
    <p class="slider-p">
      Recommenation: Set the
      <strong>minimum</strong> number of problems you want to study each day. You can always do more. On average, problems take about 30 seconds each.
    </p>
  </div>
</template>
```

When I inspect the element, it looks like the problem is with the padding I show here.  If I disable this padding, the bar becomes visible.  

<img width="951" alt="Screen Shot 2020-06-22 at 2 08 43 PM" src="https://user-images.githubusercontent.com/43726951/85286140-5e631c80-b492-11ea-9b49-e7eca1d1ce7a.png">

This padding gives the inner div a zero height.

<img width="942" alt="Screen Shot 2020-06-22 at 2 14 30 PM" src="https://user-images.githubusercontent.com/43726951/85286425-ecd79e00-b492-11ea-9cea-8751a45c1386.png">

#### Environment 

 - Component Version:  v3.1.5

**Comment by NightCatSama** [comment]
It seems to be affected by `box-sizing: border-box`.

```css
.vue-slider {
    box-sizing: content-box;
}
```

**Comment by darrellmalick** [comment]
Ahhh, a nice simple solution.  Thank you!

**Comment by isaacjoy** [comment]
Not sure if this is linked, but my styling is also not there (although the functionality works like you showed). This only happens when I build my project though? Working on localhost. [I made a new bug issue here](https://github.com/NightCatSama/vue-slider-component/issues/468).

Hoping to fix this as looks really good on localhost!
