### ISSUE TITLE
Allow objects passed as data

### ISSUE THREAD

**Issue by BennyAlex** [NightCatSama/vue-slider-component#471]
#### Describe the feature

It would be nice to pass an array of objects to the data prop. Than you should be able to specify the property for the value and for the marks.
```

eg: <vue-slider v-model="selected" :data="myObjects" value-property="importantValue" mark-property="text">

export default {
		data()  {
			return {
				selected: null,
				myObjects: [{
                                          text: 'String 2',
                                          importantValue: '2'
                                         }, {
                                             text: 'Number 1',
                                             importantValue: 1
                                         }
                               ]
			}
		}
	}

```

<del>And v-model reflects the current choose, so selecting 'String 2' will change selected to '2' and 'Number 1' to 1.</del>

selected should hold the complete object.

**Comment by NightCatSama** [comment]
Currently it can only be achieved through `marks`.

<https://jsfiddle.net/6dsu4kjh/>

This is a good idea, I will consider adding `data` to support the object type function.

**Comment by BennyAlex** [comment]
@NightCatSama okay thanks.

v-model should hold the complete object than I think

**Comment by NightCatSama** [comment]
`v-model` supports object types that are not logical and will not be considered for implementation. 

The `data` support object is only a simplified way of writing `data + marks`.

**Comment by NightCatSama** [comment]
In version 3.2.0 data already supports object types.

example: <https://jsfiddle.net/NightCatSama/L5wfqgc0/2/>

**Comment by BennyAlex** [comment]
@NightCatSama 
so you didnt know it yourself? :)

There is no documentation about it, would be nice if you could add it :D

**Comment by NightCatSama** [comment]
The version updated the day before yesterday.

[document](https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=data)
[example](https://nightcatsama.github.io/vue-slider-component/#/basics/data?hash=when-data-is-arrayobject-type)

**Comment by BennyAlex** [comment]
Nice. On the range page, it's unclear how to archive two or more sliders, an hint that the value should be an array representing multiple sliders would be helpful :)

**Comment by NightCatSama** [comment]
Thanks for your suggestions, the documentation has been updated.
