### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by callumacrae** [NightCatSama/vue-slider-component#473]
Hey! Are you aware that this library doesn't work with vue 3 and do you have plans to fix it?

I'm getting this error:

![image](https://user-images.githubusercontent.com/472830/87860518-02c36c00-c936-11ea-8595-b1bad48d215e.png)

I believe this is because you can't extend `Vue` anymore, which is happening here: https://github.com/NightCatSama/vue-slider-component/blob/master/lib/vue-slider.tsx#L48

Let me know if there's anything I can do to help - although I'm completely unfamiliar with this library's code.

**Comment by NightCatSama** [comment]
Sorry, it is not yet compatible with Vue3. 

It will be compatible when the stable version of vue3 is released.

**Comment by NightCatSama** [comment]
The next version with vue3 support has been released, but it's still in beta, if you find any bugs you can report back to me!

```base
$ yarn add vue-slider-component@next
# npm install vue-slider-component@next --save
```
