### ISSUE TITLE
Marker not appear on first and last element

### ISSUE THREAD

**Issue by Pol1000** [NightCatSama/vue-slider-component#476]
Hi,
i'm using the slider and have a strange problem the marker and the label not be render on the first and last element.
The data for the slider in a collection of picture with some boolean value, if one is true the mark function i've passed write a letter.

![image](https://user-images.githubusercontent.com/712422/88515394-f0a79480-cfeb-11ea-91a3-9f74a03e5768.png)

As can see the marker stop one element before the label. same thing happen at the the first element, the label it's correctly write, but there's no marker in the slider.

thanks.

**Comment by NightCatSama** [comment]
Can you reproduce the question?

<https://jsfiddle.net/NightCatSama/2xy72dod/10520/>

**Comment by Pol1000** [comment]
Hi, it's long to reproduce the logic behind the dinamically creation of the data collection, and i don't know if i can port that outside the company.
sorry.

**Comment by Pol1000** [comment]
Was that, the css... i don't think about that....
sorry
