### ISSUE TITLE
Is it possible to use custom html on tooltip right now?

### ISSUE THREAD

**Issue by AndhikaR** [NightCatSama/vue-slider-component#477]
#### Describe the feature

First of all thank you for making this plugin! In the documentation i cant find any way to use custom html or some way to put icon in my tooltip, is it possible right now?

#### Describe the solution you'd like

Use custom html formatter in tooltip

**Comment by NightCatSama** [comment]
example: <https://nightcatsama.github.io/vue-slider-component/#/advanced/components-slots?hash=tooltip-slot>

docment: <https://nightcatsama.github.io/vue-slider-component/#/api/slots?hash=tooltip>

**Comment by AndhikaR** [comment]
Thank your for pointing it
