### ISSUE TITLE
Slider with data bound to Array<Object> changes label/value behavior when 

### ISSUE THREAD

**Issue by chadselph** [NightCatSama/vue-slider-component#479]
#### Describe the bug

With Array<Object> as `:data`, some `:data-value` property is ignored when the data gets reloaded.

It works fine at first, but when `:data`'s value gets pointed somewhere else, the `:data-value` is no longer used and the whole object is sent as the value.

Here's a minimal example: https://jsfiddle.net/wjhksxn4/6/

In my larger application, data is getting set from a Vuex update and `:data-label` was also getting ignored after data was updated; but I can't seem to reproduce that part.

#### Environment

 - Vue version: 2.6.11
 - Component Version: v3.2.2

**Comment by NightCatSama** [comment]
Thanks for your feedback, it has been fixed in v3.2.3. 😄
