### ISSUE TITLE
Error when testing a component that uses the slider

### ISSUE THREAD

**Issue by espiegel** [NightCatSama/vue-slider-component#48]
In the parent component that uses vue-slider I'm getting:

```
TypeError: undefined is not an object (evaluating 'this.$refs.process.offsetWidth')
  at webpack:///~/vue-slider-component/dist/index.js:1:0
```

Did anyone encounter something similar? I'm using vue-slider-component version 2.2.7

**Comment by NightCatSama** [comment]
Does your question be this? [Exceptions](https://github.com/NightCatSama/vue-slider-component#user-content-exceptions)
