### ISSUE TITLE
aria-label

### ISSUE THREAD

**Issue by ecarrera** [NightCatSama/vue-slider-component#481]
### ARIA input fields do not have accessible names

Users of screen readers and other assistive technologies need information about the behavior and purpose of controls on your web page. Native HTML controls like buttons and radio groups come with that information built in. For custom controls you create, however, you must provide the information with ARIA roles and attributes.

To be announced properly by assistive technologies, both native HTML controls and custom ARIA controls must have accessible names that convey their purpose.

_From: https://web.dev/aria-input-field-name/_

**Solution:**

I added the `aria-label` prop into `vue-slider.tsx`

```typescript
@Prop() ariaLabel?: string

...

aria-label={this.ariaLabel}

```

I tested it and it's working. Then tried to upload the branch but its locked.

**Comment by NightCatSama** [comment]
Thank you for your feedback. In version 3.2.4, you can set custom attributes on `dot`.

document: <https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=dotattrs>

**Comment by ecarrera** [comment]
Thanks @NightCatSama, running on 3.2.4.  💪🏻

**Comment by RobertJGabriel** [comment]
@NightCatSama Fantasic!!! Thank you
