### ISSUE TITLE
Adding HTML to the labels

### ISSUE THREAD

**Issue by tofl** [NightCatSama/vue-slider-component#485]
Hello,
#### Describe the feature
After checking the documentation for the component, I believe it is not possible to add HTML to the labels. Would it be possible to add the functionality?

#### Describe the solution you'd like

So in my case, the slider uses this array to set the labels and values:
```
<vue-slider
              v-model="shipInput.learningrate"
              :tooltip="'none'"
              :disabled="isDisabled"
              :data="..."
              :data-label="'label'"
              :data-value="'value'"
            />

...

return [
        {
          value: 'value1',
          label: 'Value #1',
        },
        {
          value: 'value2',
          label: 'Value #2',
        },
        {
          value: 'value3',
          label: 'Value #3',
        },
      ];
```

The thing is I need to add HTML to the labels like so:
```
return [
        {
          value: 'value1',
          label: '<span v-tooltip="My Tooltip">Value #1</span>',
        },
        ...
      ];
```
However, the HTML is not interpreted. Can this behavior be changed?

Thanks.

**Comment by NightCatSama** [comment]
You can use `slot`.

<https://nightcatsama.github.io/vue-slider-component/#/api/slots?hash=label>

**Comment by tofl** [comment]
It did the job, thanks. Is it possible to add a class only to the label which value is selected, and not the previous ones as well ?

**Comment by NightCatSama** [comment]
Like this?
```vue
    <vue-slider v-model="value" :marks="marks">
      <template v-slot:label="{ value: val }">
        <div :class="['vue-slider-mark-label', 'custom-label', { selected: val === value }]">{{ val }}</div>
      </template>
    </vue-slider>
```
