### ISSUE TITLE
请教一下 如果数值太多， 如何换行呢？

### ISSUE THREAD

**Issue by saplmm** [NightCatSama/vue-slider-component#486]
请教一下 如果数值太多， 如何换行呢？

**Comment by NightCatSama** [comment]
啥东西换行，label 吗，label 的话改样式就行了。修改 `.vue-slider-mark-label` 的样式，加个宽度，覆盖掉 `white-space: nowrap` 之类的。

**Comment by saplmm** [comment]
> 啥东西换行，label 吗，label 的话改样式就行了。修改 `.vue-slider-mark-label` 的样式，加个宽度，覆盖掉 `white-space: nowrap` 之类的。

横条，比如我范围选择的 数据有点多，1-10000，每一个值都要显示出来，那么slider 那个横条的宽度肯定就不够，这个时候就需要换行处理了

**Comment by NightCatSama** [comment]
不好意思，不支持这个功能。
