### ISSUE TITLE
Enable max/min while scale is defined 

### ISSUE THREAD

**Issue by ChiuMungZitAlexander** [NightCatSama/vue-slider-component#489]
#### Description
Consider the slider has a scale from 1 to 7. Now as a user, I should know the max should be 7, but the possible max is 5. 

Which means, the slider could have max scale 7, but the user could only drag/click 1 to 5. If the user drags/clicks the pointer to 6 or 7, it could return to 5.

I tried to use data(scale) and max together but failed.

#### Here's the code
```
<template>
  <div>
    <div>value: {{ value }}</div>
    <vue-slider
      v-model="value"
      :data="data"
      max="5"
      :marks="true"
    ></vue-slider>
  </div>
</template>

<script>
  module.exports = {
    components: {
      VueSlider
    },
    data: function () {
      return {
        value: 1,
        data: [1,2,3,4,5,6,7]
      }
    }
  }
</script>
```

Still possible to access 6.
![image](https://user-images.githubusercontent.com/22234622/93987683-719bc600-fdba-11ea-8f57-3aaece56ba57.png)

**Comment by NightCatSama** [comment]
You can use dotOptions to limit the range of a single slider.

<https://jsfiddle.net/qezk4hjL/>

**Comment by ChiuMungZitAlexander** [comment]
Thank you, will try.
