### ISSUE TITLE
Callback wont work

### ISSUE THREAD

**Issue by perottosson** [NightCatSama/vue-slider-component#491]
I cannot get the callback to work. 

```
<template>
  <div>
    <vue-slider id="slider" ref="slider" v-model="sliderv" v-bind="options" @callback="log">
  </div>
</template>

  methods: {
     log(val) {
        console.log(val);
      },
   }


```

returns nothing

What is missing?

**Comment by NightCatSama** [comment]
Now using the `@change` event, `@callback` is a method from version 2.x.

<https://nightcatsama.github.io/vue-slider-component/#/api/events?hash=change>
