### ISSUE TITLE
dot edge aligned with rail edge

### ISSUE THREAD

**Issue by bogdan1190** [NightCatSama/vue-slider-component#493]
Hi, 
I am trying to align the dot edge with the rail edge and I can't figure it out.  Is this possible? 
The contained prop does not help me in this case, because it makes the rail smaller. 
Current implementation (Dot center is aligned with rail edge)
![image](https://user-images.githubusercontent.com/11848436/94793855-c99e8200-03e3-11eb-99b4-059ea1c8e596.png)
What I want to do (Dot is aligned with rail when dot is at the edge of the rail.)
![image](https://user-images.githubusercontent.com/11848436/94794089-11250e00-03e4-11eb-85ce-38fff88b7f84.png)

Can I align the rail edge to match the dot edge instead?
Thank you

**Comment by NightCatSama** [comment]
Is that the prop you need? 

<https://nightcatsama.github.io/vue-slider-component/#/basics/simple?hash=contained>

**Comment by bogdan1190** [comment]
No not really, I tried it, problem is when contained is set to true. you have a smaller rail. I would like to have the same rail width and the dot edge (not center) to be aligned with the end of the rail. if you have a bigger dot like in the pictures above, the issues is that the dot is not contained because you can slide up until the center of it. so you get this:
![image](https://user-images.githubusercontent.com/11848436/94814393-f1044780-0401-11eb-81d5-37360f56795b.png)
what I want is this:
![image](https://user-images.githubusercontent.com/11848436/94814536-26a93080-0402-11eb-9468-222bc16fa677.png)


where the  dot edge align with the rail it should be value 0.

**Comment by bogdan1190** [comment]
Hi, again :)  I made a more descriptive example of what I am trying to achive. 
![image](https://user-images.githubusercontent.com/11848436/95712481-7e9b2f00-0c6d-11eb-9625-e5b1844a51e6.png)

see jsFiddle here : https://jsfiddle.net/v0uxkz8w/6/

Please let me know  if I can do something about this.

Thanks for the support and the slider. Have a great week!

**Comment by NightCatSama** [comment]
@bogdan1190 Version 3.2.6 fixed a bug where the mouse and slider positions were out of sync when `contained=true`.

Sorry, this feature still needs to be implemented by hacking. I've written a simple example:

<https://jsfiddle.net/k8ot9vxg/>

**Comment by bogdan1190** [comment]
Thank you, this works perfectly
