### ISSUE TITLE
关于禁止交叉穿越后的问题

### ISSUE THREAD

**Issue by DtStorm** [NightCatSama/vue-slider-component#496]
最新版本enable-cross为false时 动态新增点后，点击这个点并做出拖拽动作，这个点会迅速滑动到与下一个点重合，有解决办法吗？

**Comment by NightCatSama** [comment]
能否在在线例子中还原一下

<https://jsfiddle.net/861vzxyf/>

**Comment by DtStorm** [comment]
这个问题发现是我自己的问题，现在有一个新的问题，我想动态删除滑块点之后找到最近的点去显示激活状态，看你们官方文档有个focus方法，为何我通过这个方法传入我要替换点的index，总是会激活第一个点或者下一个点
![image](https://user-images.githubusercontent.com/56500428/96108580-53843a00-0f10-11eb-9021-eb63737abdaf.png)
![image](https://user-images.githubusercontent.com/56500428/96108800-9514e500-0f10-11eb-96c7-33f6d4bf9d51.png)

**Comment by NightCatSama** [comment]
在 v3.2.7 版本修复了这个问题，感谢反馈
