### ISSUE TITLE
how do i set min and max user can slide?

### ISSUE THREAD

**Issue by kamaroolkarim** [NightCatSama/vue-slider-component#498]
i have this kind of use case where i need to show all available options to user. user with free plan can only slide to **1 day**, meanwhile user with pro plan kat slide up to **1 week**. i expected the drag will stop when free user try to slide higher. how do i achieve this? i have tried setting up max value, doesn't seem to be work. 

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/6109672/95834803-fd789080-0d6f-11eb-8a49-428112fff53a.png">

**Comment by NightCatSama** [comment]
The `dotOptions` can be set to limit the sliding range of a single slider. [document](https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=dotoptions)

**Comment by kamaroolkarim** [comment]
@NightCatSama alright. let me test it first

**Comment by kamaroolkarim** [comment]
nice. it's working. thanks
