### ISSUE TITLE
Got error "(max - min) must be divisible by interval", but it is divisible

### ISSUE THREAD

**Issue by wspwebben** [NightCatSama/vue-slider-component#499]
#### Describe the bug

I'm trying to build a timeline, based on this slider component: I have an interval and a list of steps and I calculate which step should be shown at the moment, when interval changes, the step adjusts

When I got an interval, which is not divisible by the closest step, I normalize the interval with the difference, for example:

```
interval: [0, 81],
step: 2,
->
normalizedInterval: [0, 82] -> min: 0, max: 82
```

However, I still got the error message:

`[VueSlider error]: The prop "interval" is invalid, "(max - min)" must be divisible by "interval"`

I tried to debug the source code, but for some reason sourcemaps doesnt work and I could set a breakpoint in a lib

`console.log` in updated hook shows the numbers, I'm passing, are correct

How to replicate:

1. Adjust the screen width, so the step/interval is calculated as `3`
2. Drag the right handle to 81
3. The step will shrink to `2` and the interval will become `0, 82`, but the error will still be printed

https://codesandbox.io/s/pensive-breeze-m4swb?file=/src/components/Track.vue

**Comment by NightCatSama** [comment]
Sorry, this is an internal issue within the component. 

You can set `:silent="true"` to ignore this error if it doesn't affect your usage.
