### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by aaesis** [NightCatSama/vue-slider-component#50]
my code is only this one:

` <vue-slider v-model="value"
                                    :min="0"
                                    :max="100">
                        </vue-slider>`

`data () {
      return {
        value: 0,
}
`

i got an error: Cannot read property 'offsetWidth' of undefined

**Comment by NightCatSama** [comment]
You have to make sure that the component can be rendered to the page when it is initialized.

 [Solution](https://github.com/NightCatSama/vue-slider-component#user-content-exceptions)

**Comment by aaesis** [comment]
You are correct. I am using tab v-show in my tabs but I wouldn't change the behaviour of my tab, but i am confuse on how to implement or integrate in my code those solutions.

**Comment by NightCatSama** [comment]
You can try using `watch` to control the component refresh.

e.g.
```html
  <div v-show="show">
     <v-slider ref="slider"></v-slider>
  </div>
```

```js
  export default {
    data () {
      return {
        show: false
      }
    },
    watch: {
      show (val) {
        val && this.$refs.refresh()
      }
    }
  }
```

**Comment by aaesis** [comment]
alright thank you so much! now working!
