### ISSUE TITLE
Focus state does not get removed properly

### ISSUE THREAD

**Issue by Anubarak** [NightCatSama/vue-slider-component#503]
#### Describe the bug

In certain configurations the dots focus state is not removed properly. It is set, but after releasing the mouse it's still focused. We made a class to style it while it's focused but we would like to remove the style when the user stops dragging.

Here is a working example https://codepen.io/Anubarak/pen/abZjwvr I need to click somewhere else to remove the focus.

It works as expected here https://jsfiddle.net/NightCatSama/2xy72dod/10547/ the focus state + the tooltip  is removed when you stop dragging. How can we achieve the same in the codepen above?

#### Environment

 - OS & Version: tested on Mac and Windows 10
 - Vue version: latest Vue 2.6 (see codepen)
 - Component Version: 3.2.10 (see codepen)

**Comment by NightCatSama** [comment]
Disable keyboard control.

`:useKeyboard=false`

**Comment by Anubarak** [comment]
Awsome, thank you for your fast reply
It works now
