### ISSUE TITLE
Lazy V Model

### ISSUE THREAD

**Issue by Fifciu** [NightCatSama/vue-slider-component#504]
#### Describe the feature

I am using your component for Price filter in our ecommerce system. Unfortunately, the component updates his value so many times which causes sending so many filters requests. 

#### Describe the solution you'd like

It would be nice to add some props or just support .lazy v-model modifier to emit only the last value. Like in inpuit's onBlur event.

**Comment by NightCatSama** [comment]
`:lazy="true"`

<https://nightcatsama.github.io/vue-slider-component/#/basics/simple?hash=lazy>

**Comment by Fifciu** [comment]
Damn, indeed. Somehow I missed it, thanks a lot!
