### ISSUE TITLE
Allow drag specific element

### ISSUE THREAD

**Issue by educkf** [NightCatSama/vue-slider-component#505]
Hello!

Is there a way to not-enable the drag action when clicking on the label?
Or to specify a specific area/class where the drag action is activated? 

I am using a custom tooltip (via slot) with some input/select form fields on it. And when the select field is clicked, it is triggering the drag action.

Thanks

**Comment by NightCatSama** [comment]
If you want the tool not to be dragged, you can use `.stop`.

```vue
    <vue-slider v-model="value">
      <template v-slot:tooltip="{ value }">
        <div @mousedown.stop>{{ value }}</div>
      </template>
    </vue-slider>
```
