### ISSUE TITLE
Support both Vue2 & Vue3

### ISSUE THREAD

**Issue by adamberecz** [NightCatSama/vue-slider-component#506]
Are you going to have a version that will support **both** Vue2 & Vue3 not just as a separate library? Currently installing @next throws `Cannot call a class as a function` error in Vue2.

**Comment by NightCatSama** [comment]
Sorry, it's not possible.

**Comment by bf** [comment]
@adamberecz I also have trouble using this library with nuxt. Did you resolve the error message? Or did you switch to another library? If yes, which one? Thanks!

**Comment by adamberecz** [comment]
No I didn't. I've decided to create a custom Vue wrapper for [nouislider](https://refreshless.com/nouislider/) on my own.
