### ISSUE TITLE
Ordering for multiple slider not being applied if value is changed from vue context

### ISSUE THREAD

**Issue by ludwig801** [NightCatSama/vue-slider-component#507]
#### Description

When using a slider with multiple values, with **order** set to **true**, setting a minimum value from js which should trigger a reordering does not.

#### Example

**value**: [12, 18]

Setting value to [20, 18] with **$refs.slider.setValue([20, 18])** triggers neither a reordering nor an event.

#### Environment

 - OS: **Windows 10**
 - Vue: **v2.6.10**
 - Component Version: **v3.2.10**

**Comment by Kiwinka** [comment]
Hi, I think you have put the wrong component version. As far as I know, the newest is 3.2.10.

**Comment by NightCatSama** [comment]
Thanks for your feedback, fixed in version 3.2.11.

**Comment by ludwig801** [comment]
> Hi, I think you have put the wrong component version. As far as I know, the newest is 3.2.10.

Yeah, my bad, it was the wrong version!
