### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop. Expected Number, got String

### ISSUE THREAD

**Issue by Kiwinka** [NightCatSama/vue-slider-component#508]
Hello,

I'm working on a Vue project in Typescript. I use your component for the price range. I really like how it works, except for one problem. 

This is what I do:

```
<vue-slider
        :min="priceMin"
        :max="priceMax"
        v-model="priceValue"
        :enable-cross="false"
        :order="true"
        @error="error"
        @change="detectChange"
        :tooltip="'active'"
        :use-keyboard="false"
      ></vue-slider>
      <div class="row">
        <input placeholder="Min" v-model="priceValue[0]" @input="detectChange" type="number">
        <input placeholder="Max" v-model="priceValue[1]" @input="detectChange" type="number">
      </div>
```

```
  private priceValue = [this.dataFromBackEnd.priceMin, this.dataFromBackEnd.priceMax];
  private priceMin = this.dataFromBackEnd.priceMin;
  private priceMax = this.dataFromBackEnd.priceMax;
```

This is how it looks:
![image](https://user-images.githubusercontent.com/27009823/99728846-57305100-2aba-11eb-85b4-0362c7a78886.png)

All the data from backend are of type Number. However, in console, I have this error:
![image](https://user-images.githubusercontent.com/27009823/99728232-6bc01980-2ab9-11eb-97d3-5e9d422d473a.png)

If someone could just tell me what I'm doing wrong or what I'm missing, I would be very grateful. 

 - OS & Version: Windows 10
 - Vue version: 2.6.12
 - Component Version: 3.2.10
 - Typescript version: 4.0.5

**Comment by NightCatSama** [comment]
This is a Vue error, you can try to force a type conversion.

```
:max="+priceMax"
```

**Comment by Kiwinka** [comment]
Thank you, this helped me find a bug in my application <3 Nothing wrong with your component, it was my mistake.
