### ISSUE TITLE
index.js?ea37:1 [Vue-slider warn]: Prop[interval] is illegal, Please make sure that the interval can be divisible

### ISSUE THREAD

**Issue by Jack2509** [NightCatSama/vue-slider-component#51]
I have object slider with interval attribute equals 100.
And some config
watch: {
            price_low (val) {
                this.input_price_low = Math.ceil(val / this.sliderprops.interval) * this.sliderprops.interval;
            },
            price_high (val) {
                this.input_price_high = Math.floor(val / this.sliderprops.interval) * this.sliderprops.interval;
            },
            price_min (val) {
                this.price_min = Math.floor(val / this.sliderprops.interval) * this.sliderprops.interval;
            },
            price_max (val) {
                this.price_max = Math.ceil(val / this.sliderprops.interval) * this.sliderprops.interval;
            }
        }
Everytime I reload page vue-slider always throw that error. Please help me fix it.

**Comment by NightCatSama** [comment]
I can not find the cause of the error. 

When the warning is popped, what is `max` and `min` and `interval` for the component.
