### ISSUE TITLE
[vue3.x] Range slider wrong value when min becames max

### ISSUE THREAD

**Issue by Jesus82** [NightCatSama/vue-slider-component#510]
I have a range slider with the values `[6, 7.5]` and data `[6, 7.5]`, and then I want to change the values and data to `[7.5, 10]`. When I do that, a `change` event is fired and the values are changed to `[10, 7.5]`. This always happens when one of the elements of the value array is the **maximum** and then the array  is changed so that element becames the **minimum** (here `7.5` was the `max` and then in the next value is the `min`).

This didn't happen in 3.1.5

Live example https://jsfiddle.net/fk9b813x/

**Comment by NightCatSama** [comment]
Since the new `data` is not yet available within the component when value is set, you can add `nextTick` to fix the problem.

<https://jsfiddle.net/tanqz5w7/1/>
