### ISSUE TITLE
Support access to classes with props if prop (dotStyle, railStyle, etc) is a string than object. 

### ISSUE THREAD

**Issue by DasdWaller** [NightCatSama/vue-slider-component#511]
Sometimes we use TailwindCSS and it will be an easy for as if props style access on class than styles with object.
Sorry For the issue I didnt want to open new because the basic problem was this.

**Comment by NightCatSama** [comment]
Sorry, the component does not support directly modifying or adding the class name of the component.3

You can encapsulate a layer and modify it by manipulating the DOM.

e.g.
```js
  export default {
    props: ['dotClass'],
    mounted() {
      const dotElem = this.$el.querySelector('.vue-slider-dot-handle')
      dotElem.classList.add(...this.dotClass.split(' '))
    }
  }
```
```html
<my-slider dot-class="bg-gray-300 rounded-xl">
```
