### ISSUE TITLE
[vue3.x] Event Help Needed

### ISSUE THREAD

**Issue by crisp33** [NightCatSama/vue-slider-component#513]
#### Describe the bug

Probably not a bug, but I can't find documentation/example.  I can't seem to get the drag-end event to work (I want to update data table after end selection).   Can you give me a simple example of its using this or one of the events?

**Comment by NightCatSama** [comment]
Selecting the end can be done using the `change` event. `drag-end` is the end of dragging.

You can set [lazy](https://nightcatsama.github.io/vue-slider-component/#/basics/simple?hash=lazy) to update the value only after the end of dragging.

<https://nightcatsama.github.io/vue-slider-component/#/api/events>
