### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by Dirk94** [NightCatSama/vue-slider-component#516]
#### Describe the bug

Component doesn't render. Gives the error:
Error in render: "TypeError: Cannot call a class as a function"

<img width="916" alt="Screen Shot 2020-12-29 at 3 55 51 PM" src="https://user-images.githubusercontent.com/2823049/103292551-56120e00-49ee-11eb-8709-31c40bab26ca.png">

Code to replicate:
```
import VueSlider from 'vue-slider-component'
import 'vue-slider-component/theme/default.css'

Vue.component('vue-slider', VueSlider)
```

And then display the component.
```
<vue-slider v-model="value"></vue-slider>
```

#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: macOS
 - Vue version: v2.6
 - Component Version: Tested on: v3.0.46, v3.2

**Comment by NightCatSama** [comment]
Is it the same issue?

https://github.com/NightCatSama/vue-slider-component/issues/495

**Comment by donghyunkim1129** [comment]
The same problem occurs to me.
