### ISSUE TITLE
Value jumps when using an interval and linked input boxes

### ISSUE THREAD

**Issue by lgrayland** [NightCatSama/vue-slider-component#517]
**Description**
recently upgraded from 2.7 to 3.2 and have noticed a strange behaviour. I am using the slider to do a min and max value, also the min and max values are linked to input boxes which can be used to edit the value. If an interval is used (in the example 1000) but i set the min value from the input box so that it is less than the interval (500), when the max value slider is moved the min value jumps to 1000 rather than staying at the value set (if the value was 400 then it jumps to 0, moving to the closet interval). Can't see anything in the props to prevent this

**Example**

[jsfiddle](https://jsfiddle.net/LGrayland/eLf2dptb/19/)

**Comment by NightCatSama** [comment]
This is as expected, since the interval of 1000 is calculated internally for all selectable points ([0,1000,2000,3000.... .10000]). So 500 will be repositioned to 0 after the internal calculation.

**Comment by lgrayland** [comment]
So there will be no way to prevent this? As I said for my use case it would be possible to enter a value in the input box for one value and use the slider for the other and would not expect the value from the input box to be changed

**Comment by NightCatSama** [comment]
There is no way to achieve this directly, one way is to set the interval to 1, and then set the marks interval.

<https://jsfiddle.net/ck6vu05p/>
