### ISSUE TITLE
Ability to control dot position

### ISSUE THREAD

**Issue by pupipipu** [NightCatSama/vue-slider-component#519]
#### Describe the feature
Currently the `dot` slot will only be able to modify the inner content within `.vue-slider-dot`. If we want to do some customization to control the position for `mark` and the span of `process` element, the dot position won't be able to follow the customized position.

#### Describe the solution you'd like
Allow `dot` slot to replace the whole dot component (i.e. the `.vue-slider-dot`wrapper) rather than just the inner content.

#### Additional context (If there is no relevant content, please delete the block)
currently using version `3.2.11` in vue `2.6.11`

**Comment by NightCatSama** [comment]
The slidable position is calculated internally, even if you modify the slot, you can only change the display position.

Custom dot positions can be controlled using `marks` and `included`:
<https://jsfiddle.net/pba4n3m6/>

**Comment by antati-te** [comment]
Can you add a prop, to NOT move the other sliders?
So the range of any dot handle is from (prev dot handle + interval) to (next dot handle - interval).
