### ISSUE TITLE
鼠标滚轮的问题

### ISSUE THREAD

**Issue by fabin5** [NightCatSama/vue-slider-component#52]
有需求是鼠标滚轮滚动的时候，滚动条指针也跟着滚动，不过好像这个功能没有实现呢？

**Comment by NightCatSama** [comment]
什么意思。。。

**Comment by fabin5** [comment]
就是希望可以让鼠标滚轮滚动的时候，slider也能跟着滚动，和拖拽一样。  类似音量条那样子可以跟着鼠标的滚轮滚动

**Comment by NightCatSama** [comment]
是的，暂时不打算加入这个功能。你可以试试加入其它第三方插件实现。不好意思

**Comment by fabin5** [comment]
比如说什么呢？您有没有知道的比较好的，我找了一圈 没有找到

**Comment by NightCatSama** [comment]
我试了下一个叫[wheel-indicator](https://github.com/Promo/wheel-indicator)的插件

Demo：[fiddle](https://jsfiddle.net/9pp3dqkq/8/)

**Comment by fabin5** [comment]
谢谢，非常感谢
