### ISSUE TITLE
[vue3.x] Console Errors on v^4.0.0-beta.3

### ISSUE THREAD

**Issue by thespacedeck** [NightCatSama/vue-slider-component#521]
#### Describe the bug

I want to dynamically change the min,max,interval and value of slider

Here is the fiddle https://jsfiddle.net/whoweez/nyjw3o2u/3/

When the new max/min intersects with the new value you get errors. It works perfectly well with one dot (value handle) but not with a range slider

Can someone please assist.
Kind Regards

**Comment by NightCatSama** [comment]
If it does not affect the use of the component, you can turn off the warning with `slient: true`.

duplicate issue: https://github.com/NightCatSama/vue-slider-component/issues/343
