### ISSUE TITLE
[vue3.x] Add new dot on slider by clicking a button

### ISSUE THREAD

**Issue by adhi-a1** [NightCatSama/vue-slider-component#522]
Push new data to array of value doesnt dynamically add new dot handler on the slider.

I try to add the 3rd button on 12 by clicking add button, the console log showing that the array was updated, but the 3rd dot not showing on the slider. Can anyone help me how to accomplish this?

<template
<button @click="addDot">add
<vue-slider 
 :data="value'
 :min="0"
 :max="24"
<template

data: function () {
    return {
      value: [8, 10],
    };
  },
  methods: {
    addDot() {
      this.value.push(12);
    },
  },

 - OS & Version: [Windows]
 - Vue version: [v3.0.0]
 - Component Version: [v4.0.0-beta.3]

**Comment by NightCatSama** [comment]
`:data="value"` => `v-model="value"`

**Comment by adhi-a1** [comment]
Hello mates thx for ur fast respond, and great slider..

Can u help me to check this one?
https://jsfiddle.net/wba423u6/

The problem still exist there.. thx mate

**Comment by NightCatSama** [comment]
can use `concat`: <https://jsfiddle.net/j3m2tyw0/>

**Comment by adhi-a1** [comment]
Ahhhh thx mate ill  buy 3 cups of coffe tomorrow morning..  😀😀😀
