### ISSUE TITLE
"marks" use with "included" and "min-range" does not respect "min-range"

### ISSUE THREAD

**Issue by ludwig801** [NightCatSama/vue-slider-component#524]
#### Describe the bug

"min-range" props is not always respected using "marks" and "included" props.

Example using the following props:
 - marks: [0, 400, 1400]
 - included: true
 - min-range: 400

Using an initial value [0, 1400], the slider appears as so:
![image](https://user-images.githubusercontent.com/5622673/111344562-62644980-8674-11eb-9f4b-882620387b5e.png)

However, when sliding the minimum value up to what would amount to 1400, like so:
![image](https://user-images.githubusercontent.com/5622673/111344678-7c9e2780-8674-11eb-9c16-ec7103b168dc.png)

The slider snaps the minimum to its closest mark (1400, not 400), effectively ignoring the min range of 400, like so:
![image](https://user-images.githubusercontent.com/5622673/111344770-98a1c900-8674-11eb-86a3-96eb683f3696.png)

As it seems to me, when using a marks array and the included option is set to true, the slider always snaps any of the dots to their closest mark, completely ignoring whether the minimum range is being respected or not. The expected behaviour in the example above would be that the left dot was snapped back to 400, not 1400.

This bug also happens in the reverse situation, if the max dot is being dragged and is released closest to the mark of the minimum dot.

#### Environment

 - OS & Version: Windows (64 bit)
 - Browser: Microsoft Edge 89.0
 - Vue version: 2.6.10
 - Component Version: 3.2.11

**Comment by NightCatSama** [comment]
The case of two equal values can be handled in the change callback.

For example, you can fix it this way.
```
<vue-slider
    ref="slider"
    v-model="value"
    v-bind="options"
    @change="(val) => val[0] === val[1] && (value = [400, 1400])"
/>
```

Of course the specific scenario may require some logic, but it should be solvable.
