### ISSUE TITLE
How to manage reverse slide? 

### ISSUE THREAD

**Issue by PoojaJadav** [NightCatSama/vue-slider-component#528]
I need a slide with max to min. Suppose, we have two values `100`, `10`.

Code: 
```
      <vue-slider
            :tooltip="'focus'"
            :dotSize="18"
            :height="10"
            :max="10"
            :min="100"
            :reverse="true"></vue-slider>
```

**Comment by NightCatSama** [comment]
<https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=direction>

```
:min="10"
:max="100"
:direction="rtl"
```

**Comment by PoojaJadav** [comment]
> https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=direction
> 
> ```
> :min="10"
> :max="100"
> :direction="rtl"
> ```

This is not what I want, I want to drag point max to min. 
ie., 100,99,98,...,11,10.

**Comment by NightCatSama** [comment]
<https://jsfiddle.net/5Lds3fzt/1/>

**Comment by PoojaJadav** [comment]
Thank you so much for this code. This works just the way I wanted it to 😊
