### ISSUE TITLE
Selecting first value on scale

### ISSUE THREAD

**Issue by MulliganF02** [NightCatSama/vue-slider-component#529]
Hi. I am having issues getting the first value on the scale. Currently it only lets me select whatever value the minimum is and doesn't allow the slider to change. Any help would be greatly appreciated! I have tried changing events to see if that helps with function but so far no luck.

**Comment by NightCatSama** [comment]
Not quite sure what problem you are having.

Can you reproduce it in the online example and the results you expect?

**Comment by MulliganF02** [comment]
Results I was expecting: getting the value of what the person selects on the slider

Results I got:
![image](https://user-images.githubusercontent.com/40801017/113615114-72db6480-9621-11eb-9374-5f4ee8aeae34.png)

**Comment by MulliganF02** [comment]
![image](https://user-images.githubusercontent.com/40801017/113615195-8be41580-9621-11eb-858b-f5e644709504.png)

**Comment by NightCatSama** [comment]
Forgive me for still failing to understand your question. 😢
