### ISSUE TITLE
Do not use built-in or reserved HTML elements as component id: i

### ISSUE THREAD

**Issue by DowleyDeveloped** [NightCatSama/vue-slider-component#530]
I'm receiving a warning of `Do not use built-in or reserved HTML elements as component id: i` with this slider. I'm running:

```
import Vue from 'vue/dist/vue.js'
import VueSlider from 'vue-slider-component'
```
and if I console log this I recieve:

```
VueSliderDot: function o(t)​
VueSliderMark: function o(t)
cid: 3
component: function 30]</</</sr[n(t, e)​
directive: function 30]</</</sr[n(t, e)​
extend: function extend(t)​
extendOptions: Object { data: data()
, components: {…}, name: "i", … }
filter: function 30]</</</sr[n(t, e)
length: 0
​mixin: function mixin(t)
​name: "i"
​options: Object { components: {…}, directives: {}, name: "i", … }
​prototype: Object { constructor: o(t)
, value: Getter & Setter, silent: Getter & Setter, … }
​sealedOptions: Object { components: {…}, directives: {}, name: "i", … }
​super: function tr(t)​
superOptions: Object { components: {…}, directives: {…}, filters: {}, … }
​use: use(t)
```
I can only think this is down to the naming of the component. Is there a way to change this in the plugin as it's breaking all other JS on the site.

#### Environment

 - OS & Version: macOS
 - Vue version: 2.6.12
 - Component Version: 3.0.26

**Comment by NightCatSama** [comment]
Are you using it directly in `html`?

**Comment by DowleyDeveloped** [comment]
The name? No. 

This warning is on every page even if my component isn’t loaded because the warning is about the VueSlider itself

**Comment by NightCatSama** [comment]
It may be a problem with your build environment, because the component with name i is not used in the component library.

**Comment by DowleyDeveloped** [comment]
If I console log the VueSlider I can see name: “i”?

**Comment by DowleyDeveloped** [comment]
Ah ok. I’ll check it out, thanks for the quick reply!

**Comment by maximka777** [comment]
I've got same warning. What issue with build environment can cause that? @DowleyDeveloped did you fix it somehow?
