### ISSUE TITLE
Make labels appear before the slider

### ISSUE THREAD

**Issue by tofl** [NightCatSama/vue-slider-component#531]
#### Describe the feature
Make it possible to change the position of the labels relative to the slider. For example, in my case, the slider is vertical, the labels appear on the right of the slider and I'm using slots to display the different labels. Yet I found no way of moving the labels to the right of the slider.

#### Describe the solution you'd like
The same way there is a prop to change the direction of the slider (:direction="'ttb'"), it would be nice to have a similar prop to move the labels.

**Comment by NightCatSama** [comment]
like it? <https://jsfiddle.net/asubLz0v/>
