### ISSUE TITLE
[vue3.x] 无法对数组值进行双向更改

### ISSUE THREAD

**Issue by er-ya** [NightCatSama/vue-slider-component#532]
#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: [e.g. macOS, Windows, Linux]
 - Vue version: [e.g. v3.0.0]
 - Component Version: [e.g. v4.0.0-beta.1]
vue3无法对数组值进行双向更改
input的值改变 滑动输入条不会跟随输入值发生位置改变
但滑动时input输入框内的值会跟随滑动值发生变化

或者是我哪里写的有问题，请帮我看一下 谢谢

![QQ图片20210419151725](https://user-images.githubusercontent.com/65930247/115196342-6297af00-a122-11eb-9e70-3a7eea412973.png)
![QQ图片20210419151413](https://user-images.githubusercontent.com/65930247/115196345-63c8dc00-a122-11eb-9143-a7aec4592cf6.png)

**Comment by NightCatSama** [comment]
vue 是响应不到这样直接设置数组单个值的，你可以用 map 或 filter 去更改值，或者设置完后 `this.value = this.value.slice()` 去强制更新数组变化

**Comment by er-ya** [comment]
@NightCatSama  但是我给input输入框加了一个change事件发现当输入框的值改变的时候数组中的值同样也会改变，只是无法更新到滑动条上
![1](https://user-images.githubusercontent.com/65930247/115323745-3b40f080-a1bb-11eb-9e0d-f3b86ba2247f.png)

然后我还想问一下 这里这个v-model=“currentValue1”不可以写成v-model：value=“currentValue1” 当currentValue1是数组时加上：Value滑动条就会变成单个的
![2](https://user-images.githubusercontent.com/65930247/115324009-b1455780-a1bb-11eb-990e-d4cf3ab2d9bb.png)

麻烦您在帮我看一下哦！谢谢啦。

**Comment by NightCatSama** [comment]
@er-ya 
1. 是因为值虽然变了，但是 vue 没有监听到变化的。这个在 vue2 开始就是这样的，文档有写 <https://vuejs.org/v2/guide/list.html#Mutation-Methods>

2. 因为 vue3 默认名称是已经改成 modelValue 了，所以用 v-model:value 是没法同步到组件里的值的。

**Comment by er-ya** [comment]
@NightCatSama 好的，非常感谢，问题已经解决了，麻烦您了！
