### ISSUE TITLE
v-model not updated in vue3

### ISSUE THREAD

**Issue by tamanna-makkar** [NightCatSama/vue-slider-component#535]
When we try to update the `v-model` values, 
v-model value is updated, but the slider thumb is not moving 

How can I make the slider thumb working

**Comment by NightCatSama** [comment]
If value is an array, you can't set the value of the array directly, because vue doesn't respond to changes. You can check the documentation at <https://v3.vuejs.org/guide/list.html#maintaining-state>

<https://jsfiddle.net/dqwh8un2/>

**Comment by vakanbi** [comment]
I tried to use v-for instead of v-model but it doesn't reflect the changes.
