### ISSUE TITLE
[Feature request] Swipe support for mobile devices

### ISSUE THREAD

**Issue by GustavsR** [NightCatSama/vue-slider-component#54]
It'd be nice if you could add swipe support for all touch devices.

**Comment by NightCatSama** [comment]
What exactly is the touch device?

because the component is compatible with the mobile side.

( Maybe because my RegExp is not compatible with all the touch device ).

Thanks for feedback.

**Comment by GustavsR** [comment]
Android/iOS phones/tablets.

Actually, I did not test it with my phone before. Turns out that it works on a real Android device (you can drag the dot), but does not in Chrome device view.
You still can change the value of the slider by tapping anywhere on the slider bar, but when you try to drag the actual dot - it does not work.

http://image.prntscr.com/image/c5b1c9b54d624b63bb8c703677bd40e5.png

**Comment by NightCatSama** [comment]
Probably because you are PC mode when you initialize it.

After that, switching Chrome device view debugging causes the component's mode to not switch over.

You try to open the Chrome device view after the refresh page.

**Comment by GustavsR** [comment]
Ok, thanks for explanation. It works now.
