### ISSUE TITLE
Slider with data Objects not highlighting correct value

### ISSUE THREAD

**Issue by TomDeSmet** [NightCatSama/vue-slider-component#542]
I'm using vue-slider with data objects. On mounted I set the default value for the slider (in my original code this value comes from the Vuex store). The value of the slider is updated but visually the slider does not show the correct value.

You can see it in this JSFiddle: https://jsfiddle.net/TomDeSmet/q1adjvwg/5/

In this fiddle, the last answer should be selected, but it remains at the first answer.

**Comment by oddsquash** [comment]
Hello,

Does this fix your issue?
`this.value = this.options.data[4].data`

**Comment by TomDeSmet** [comment]
Yes it seems it does!
I found another workaround too, but this is better. A simple solution I didn't come to think of...
