### ISSUE TITLE
esModule Support

### ISSUE THREAD

**Issue by sihyungkim** [NightCatSama/vue-slider-component#546]
First, I would like to thank you for your hard work.

I am using `vitejs` and `vue2`.

However, this library does not support `esModule`.

Could you update for esModule?

Maybe you should use rollup.

I look forward to your positive reply.

**Comment by NightCatSama** [comment]
Try using `vue-slider-component/es/vue-slider`.

**Comment by maratfakhreev** [comment]
Hi @NightCatSama. Unfortunately es directory hasn't been working as expected or I've been doing smth wrong. When you try to use esm version the error is appeared b/c of not any scss files don't exist in directory. And also it's very strange to look for .scss extension exact in builded version. Could you please doublecheck it and if you need some details feel free to ask) thank you
<img width="874" alt="image" src="https://user-images.githubusercontent.com/1300497/182019637-050d65ae-521c-488b-8351-48bee0146e04.png">

**Comment by NightCatSama** [comment]
@maratfakhreev 

The `styles` folder is indeed missing, `es/` is generated with tsc, so scss will not be processed.

The solution is move the scss into `es/`, or use a script to replace the `.scss` with `.css` and compile the scss separately and put it in.

It seems that this problem has existed for a long time, and the scene of using es does not feel necessary, so `esModule` will be removed in the future. It is recommended to use directly.
