### ISSUE TITLE
[vue3.x] data property not functioning properly

### ISSUE THREAD

**Issue by theonlyladybug** [NightCatSama/vue-slider-component#547]
你好，我用如下例子，并不能显示出正确的字母：

```
<template>
    <div id='wrapper'>
        <vue-slider v-model="value" :data="data" tooltip="hover" :marks="true"></vue-slider>
    </div>
</template>
```
```
    data() {
        return {
            value: 'A',
            data: ['A', 'B', 'C', 'D']
        }
    },
```
上述code显示如下：
![Screen Shot 2021-06-05 at 10 18 38 PM](https://user-images.githubusercontent.com/43486558/120913426-01815780-c64c-11eb-8ae4-d7eda1ab7e00.png)

其原因可能和这一行code有关[vue-slider.tsx](https://github.com/NightCatSama/vue-slider-component/blob/vue3/lib/vue-slider.tsx#L111)。

将`:data`改为`:v-data`确实可以修复bug，但其行为和文档中所述不符。

#### Environment

 - OS & Version: [Linux]
 - Vue 3
 - Component Version: [v4.0.0-beta.3]

**Comment by NightCatSama** [comment]
写在 README 了

<https://github.com/NightCatSama/vue-slider-component#caution>

**Comment by theonlyladybug** [comment]
看到了，谢谢
