### ISSUE TITLE
Touch Device, not mobile

### ISSUE THREAD

**Issue by gabrielstuff** [NightCatSama/vue-slider-component#55]
Hi !
This is a really nice component. I really enjoy using it.
Unfortunately I'm not able to make it run properly on touch device. It works on mobile but not on desktop computer with a touch enable device.

On one side I test : http://hammerjs.github.io/ which works perfectly on the same touch enabled device.
On the other side I test vue-slider-component and I'm not able to drag the dot.

What could I do to debug this ?

Thanks,

**Comment by gabrielstuff** [comment]
I've been trying to fake the `isMobile` function with forcing returning `true` or `false`. It did not change anything.

**Comment by NightCatSama** [comment]
Do you want to debug on the mobile device, if so, please tell me the phone model.

If you are debugging in chrome, whether the same situation with the issue #54 .

**Comment by NightCatSama** [comment]
And, It is not working to modify isMobile after the component has been initialized.

**Comment by gabrielstuff** [comment]
I've modified the lib to return true/false and test. The lib is loaded with hardcoded value to test wether or not it change something.
It is a touch screen I'm trying to make it work on. Not a mobile device.

Thanks

**Comment by NightCatSama** [comment]
Sorry, I did not find the problem where, but I found that hammer is also using `touch` and `mouse` events.

Or there is no more information to tell me

**Comment by gabrielstuff** [comment]
They also use pointer events. I was wondering if it could come from here. Another thing is that I'm not sure if the `return true`for isMobile is sufficient to activate touch support.

**Comment by NightCatSama** [comment]
I found that there is a pointers event in ie 10+ browser. 

You can do the next test:
```js
document.body.addEventListener("mousedown", () => console.log('mouse events'), false);
document.body.addEventListener("touchstart", () => console.log('touch events'), false);
document.body.addEventListener("MSPointerDown", () => console.log('pointer events'), false);
```
