### ISSUE TITLE
松开鼠标拖动点还是跟着鼠标移动，不会结束，已经禁用了clickable

### ISSUE THREAD

**Issue by cjlhll** [NightCatSama/vue-slider-component#550]
#### Environment (If you feel unrelated, please delete the block)

 - OS & Version: [e.g. macOS, Windows, Linux]
 - Vue version: [e.g. v2.0, v2.5, v2.6]
 - Component Version: [e.g. v3.0.2]

**Comment by NightCatSama** [comment]
没能复现，能否在线例子还原一下
