### ISSUE TITLE
Class for last active mark

### ISSUE THREAD

**Issue by mrleblanc101** [NightCatSama/vue-slider-component#551]
#### Describe the feature

Hi, currently there is a class on all active mark.
Which prevent us from highlighting  the current value.
Here is what our design team came up with.
<img width="357" alt="Capture d’écran, le 2021-06-10 à 09 41 50" src="https://user-images.githubusercontent.com/17392251/121535680-5f0cff80-c9d0-11eb-973a-c82202504533.png">

#### Describe the solution you'd like
Would it be possible to add a class on the last active mark or the nearest to the value ?
Something like `vue-slider-mark-current` that would only apply to one mark instead of all the mark with value lower than the current value.

**Comment by NightCatSama** [comment]
Try using the `slot`: 
```vue
    <vue-slider v-model="value">
      <template v-slot:label="{ lvalue: labelValue }">
        <div :class="['vue-slider-mark-label', { active: labelValue === value }]">{{ label }}</div>
      </template>
    </vue-slider>
```

**Comment by mrleblanc101** [comment]
There is no `lvalue` or `labelValue` on the scoped-slot unless I'm misunderstanding

**Comment by mrleblanc101** [comment]
I made it work with the `@change` event, but I feel like this should be a core functionality as it's a pretty common pattern to hightlight only the current value and not all the active value. This would only require a new props and maybe adding the class by default as it wouldn't require every use to create a `v-slot:label` everytime

**Comment by mrleblanc101** [comment]
Ok, thanks I got it.
Much clearer after a short break.
I was able to make it work.
Was a bit more complicated because I wrap `vue-slider` into a component so I have 2 `value`, one from the scoped-slot and one from my v-model.
But I still think this should probably be built-it in a future version.
```
<template>
    <vue-slider ref="slider" v-bind="$attrs" :height="6" tooltip="none" adsorb v-on="$listeners" @change="onChange">
        <template #label="slot">
            <div :class="['vue-slider-mark-label', { 'vue-slider-mark-label-current': slot.value === value }]">
                {{ slot.label }}
            </div>
        </template>
    </vue-slider>
</template>

<script>
export default {
    model: {
        prop: 'value',
        event: 'change',
    },
    props: {
        value: {
            type: String,
            default: '',
        },
    },
};
</script>
```

**Comment by mrleblanc101** [comment]
Should I keep this open as a feature request or close since there is a workaround ?

**Comment by NightCatSama** [comment]
You can keep this issue, but it should not be realized in a short time. 😿

**Comment by piolet** [comment]
@mrleblanc101 Bonjour, rien à voir, mais comment implémentes-tu le slider avec cet aspect "<>" ?
J'aimerai bien avoir une telle apparence sur mon slider ;)

**Comment by mrleblanc101** [comment]
@piolet CSS
