### ISSUE TITLE
SassError: Invalid CSS after with old version 3.2.10

### ISSUE THREAD

**Issue by piolet** [NightCatSama/vue-slider-component#552]
Hi all,

I've an old version of vue-slider-component, but soon, i've an error when i build my project on my pipeline CI/CD

```
SassError: Invalid CSS after "...der-width: math": expected expression (e.g. 1px, bold), was ".div($size, 2);"
        on line 9 of node_modules/vue-slider-component/lib/styles/_triangle.scss
        from line 1 of node_modules/vue-slider-component/lib/theme/default.scss
        from line 35 of src/assets/scss/main.scss
>>     border-width: math.div($size, 2);

```

I don't understand this problem. If i download 3.2.10 zip, the source code for _triangle.scss don't contains `math.div` syntax.
But, in my node_modules, for 3.2.10, the source code contains math.div, but i can't compile that for the moment.

Why npm version is not the same as zip file ?

Thank you

**Comment by NightCatSama** [comment]
The 3.2.12 version contains `math.div`, 3.2.13 has been removed, you can download a zip again.

**Comment by piolet** [comment]
yes, but I don't want the Math.div.
I want to keep the version with the /, because for the moment, I can't upgrade my version of sass

And i'm talking about version 3.2.10 (not 3.2.12 :/ )

**Comment by piolet** [comment]
In fact, if I try to do an `npm install` with version 3.1.5 (or 3.2.10 whatever), the result I get in my node_modules directory contains a `_triangle.scss` file with the `math.div` correction.
But I would like to stay with the `/`, because I can't update my sass version for the moment.

I don't understand why the npm version is different from the one in the zip that you can get via this github page

(Sorry for the english if it's not clear, it's almost a Google translate ;) )

**Comment by NightCatSama** [comment]
@piolet 3.2.13 has removed the math.div, you can download it again

**Comment by piolet** [comment]
I just tested, everything works as before.

Thanks a lot
