### ISSUE TITLE
Unbind slider from colored bar until sliding stops on lazy mode

### ISSUE THREAD

**Issue by pedroadame** [NightCatSama/vue-slider-component#555]
#### Describe the feature

Hi! 

I have an use case where we want to use this component to represent the watched % of a video, where you can also slide to seek a position.

However, our design team came up with a solution that is not possible right now. We will be using the lazy prop because we want the seek to occur when the sliding stops. 

We wish to move the slider while keeping the "colored progress" on the current value, until the drag-end event occurs. 

#### Describe the solution you'd like

We wish to have a prop that makes the color bar follow the actual value instead of the actual slider, so the colored bar changes to match the slider when the drag ends.

Thank you!

**Comment by NightCatSama** [comment]
try it <https://jsfiddle.net/591o8f34/1/>

**Comment by pedroadame** [comment]
Works like a charm, thank you! @NightCatSama
