### ISSUE TITLE
Change slider and tooltip color based on value

### ISSUE THREAD

**Issue by man0099** [NightCatSama/vue-slider-component#557]
Hey, thank you for creating this component! 

**Is there a way to set different _slider and tooltip_ color as the value changes? 1-10 is red, 11-20 is yellow, 20-30 is green and so on.** 

I have had a look at the documents and various other slider components but as a new Vue developer, this is seemingly hard. If possible could I get a guide on how to do this? I believe you will help me. Cheers!

**Comment by NightCatSama** [comment]
It's easy to implement, `dotStyle` and `tooltipStyle` can be set directly, or you can use `slot`.

e.g.
```vue
<vue-slider v-model="value" :dot-style="{ background: value < 10 ? 'red' : 'yellow' }" />
// or
<vue-slider v-model="value">
  <template v-slot:dot>
    <div :class="value < 10 ? 'red-dot' : 'yellow-dot'"/>
  </template>
</vue-slider>
```

**Comment by man0099** [comment]
Great! Thanks for your help. I've managed to change alot but I want to fix these small problems. (Refer to screenshot)
![Capture](https://user-images.githubusercontent.com/86929805/124480109-8c2cb200-ddc4-11eb-9d45-9c2a1c836c2f.PNG)

I'd like to know how to change change the following:
1) Tooltip text color
2) The triangle below the tooltip's color
3) Shadow of the dot color

Here's the code I'm using
![1](https://user-images.githubusercontent.com/86929805/124480282-ba11f680-ddc4-11eb-90dc-79b7848b606b.PNG)

**Comment by NightCatSama** [comment]
@man0099 
Tooltip text color & The triangle below the tooltip's color:
```vue
:tooltip-style="{ color: 'red', borderColor: 'red' }"
```
Shadow of the dot color
```vue
:dot-style="{ boxShadow: '0 0 2px 1px red' }"
```

**Comment by man0099** [comment]
Thanks! Is there a way to change all 3 (background, boxShadow, and border) at once? As you can see my code looks pretty messy.
![Uploading Capture.PNG…]()

**Comment by man0099** [comment]
Thanks! Is there a way to change all 3 (background, boxShadow, and border) at once? As you can see my code looks pretty messy.
![Capture](https://user-images.githubusercontent.com/86929805/124511144-0bd17580-ddf3-11eb-8d0b-65c4acc07ae1.PNG)

**Comment by NightCatSama** [comment]
You can add a method to extract the color logic.
```vue
:dot-style="{ background: curColor, boxShadow: `0 0 2px 1px ${curColor}`, borderColor: curColor }"

computed: {
   curColor() {
     return this.value < 10 ? 'red' : 'yellow';
   }
}
```
