### ISSUE TITLE
How to hide certain data?

### ISSUE THREAD

**Issue by man0099** [NightCatSama/vue-slider-component#559]
In my :data I have an array of 0, 10, 15, 20, 25, 30, 35, 40, 45, 50 and so on...

I only want to show 0, 10, 20, 30, 40, 50 on the front end but give the user the ability to select 15, 25, 35 etc. How can I do this?

**Comment by NightCatSama** [comment]
You can set the data you want to display in `marks`.

example: <https://jsfiddle.net/d7xovacb/>
document: <https://nightcatsama.github.io/vue-slider-component/#/basics/marks>
