### ISSUE TITLE
feature request: TypeScript support

### ISSUE THREAD

**Issue by holiber** [NightCatSama/vue-slider-component#56]
Hi! It will be very helpful to have type declarations inside the repository for typescript projects.

**Comment by NightCatSama** [comment]
Sorry can not help you, I do not know how to use typescript.

**Comment by holiber** [comment]
Ok

**Comment by atilkan** [comment]
@NightCatSama It is not that hard to write type definitions.

**Comment by bolsonitro** [comment]
A commit like this can solve the problem: https://github.com/bolsonitro/teses-de-investimento/commit/919297b23e479126b9f366c043a128d796b49cb2
