### ISSUE TITLE
Make vertical slider height responsive?

### ISSUE THREAD

**Issue by Modjular** [NightCatSama/vue-slider-component#560]
#### Describe the feature

I have the slider in a flexbox and would like it to scale vertically depending on the size of the container its inside. Is this doable?

#### Describe the solution you'd like

I would like to just be able to set `style="height: 100%"`

#### Additional context (If there is no relevant content, please delete the block)

Sorry, I didn't know whether to report this as a bug or feature. If it can't be done, [could an explanation be added to the docs](https://nightcatsama.github.io/vue-slider-component/#/basics/simple?hash=set-the-slider-direction)?

**Comment by NightCatSama** [comment]
use `height="100%"`
