### ISSUE TITLE
can we put text into dot ?

### ISSUE THREAD

**Issue by kantaphit** [NightCatSama/vue-slider-component#563]
imagine if i have 1 slider about kilometers and i wanna put unit like km in to center of dot. 

can we do this ?

example

![image](https://user-images.githubusercontent.com/79431492/125887431-f695c0fb-1393-4723-b576-729ae6a4d8b0.png)

**Comment by NightCatSama** [comment]
You can use the slot to implement the `dot` style yourself.

document: <https://nightcatsama.github.io/vue-slider-component/#/api/slots?hash=dot>
example: <https://nightcatsama.github.io/vue-slider-component/#/advanced/components-slots?hash=slider-slot>
