### ISSUE TITLE
Can you please enable word wrap on labels for marks?  I have multi-word labels- e.g. 'not at all', 'extremely severe' others are one word labels like 'moderately.

### ISSUE THREAD

**Issue by peppermintbunny** [NightCatSama/vue-slider-component#566]

**Comment by NightCatSama** [comment]
`marks` supports object and function types, see the documentation for details

<https://nightcatsama.github.io/vue-slider-component/#/basics/marks>

**Comment by peppermintbunny** [comment]
Using the code you gave me I have been able to modify your component to meet my needs.  Thank you VERY much for your kind help.

**Comment by peppermintbunny** [comment]
Thank you for your help.  I have been able to get your component to do what I need.  Thank you.
