### ISSUE TITLE
Please can we have mark labels displayed above and below the same slider bar? e.g. my slider has say 8 marks, and each mark has a number starting at 0 and ending at 8.  In addition, some numbers also have a descriptive text like 'not at all' for 0, 'slightly' for 2, 'moderately' for 4, 'severe' for 6, and 'extremely servere' for 8.

### ISSUE THREAD

**Issue by peppermintbunny** [NightCatSama/vue-slider-component#567]

**Comment by NightCatSama** [comment]
You can use `slot` to customize the label.

![image](https://user-images.githubusercontent.com/13888962/127766345-a532a926-2020-4c22-ab29-9f0933837faa.png)

**Comment by peppermintbunny** [comment]
Thank you very much for replying to me.  I am new to vue and javascript so, please, can you give me a little more help.  
The code above looks as if it will provide me with a solution and I'm eager to try it out.  Please tell me:
1. where in your files and code do I insert your new code?
2. then do I run 'npm run deploy'?  Thank you again.
