### ISSUE TITLE
Min-Max value with custom data

### ISSUE THREAD

**Issue by exodusanto** [NightCatSama/vue-slider-component#57]
If i use custom data, even though i use numbers in string, min and max value works...
i use this workaround

```
...
data: ["2017", "2016", "2015","2014"],
min: -9999,
max: 9999
....
```

There is any solution ?

**Comment by NightCatSama** [comment]
When using custom data, `min` and `max` are invalid.

If you want to switch between the two modes, you can set `:data="undefined"`.

e.g.
```html
<vue-slider :data="data" :min="-999" :max="999" v-model="val"></vue-slider>
<button @click="switchNumberMode">switch mode</button>
```
```js
switchNumberMode () {
  this.data = undefined
  this.val = 200
}
```

**Comment by exodusanto** [comment]
@NightCatSama https://www.webpackbin.com/bins/-KkQ4SVe-I6YVhIlE1Kv

**Comment by NightCatSama** [comment]
This issue has been fixed in `version2.2.8`.

thank you for your help.

**Comment by exodusanto** [comment]
@NightCatSama ok, I tried 2.2.8 and it works but ... can you remove now ```console.log``` 😅

**Comment by NightCatSama** [comment]
@exodusanto i'm sorry, i forget it.:sweat_smile:

**Comment by NightCatSama** [comment]
Please upgrade to `v2.2.9`. :grin:
