### ISSUE TITLE
Make other dot handles to be fixed when minRange is defined

### ISSUE THREAD

**Issue by AnandTati** [NightCatSama/vue-slider-component#570]
#### Describe the feature

Make the other dot handles fixed when one of the dot handle is moved when minRange or maxRange is defined.

#### Describe the solution you'd like

I have two dot handles and minRange defined. When i move one of the handle, and the first one reaches within the minRange from second handle, the second handle starts moving in other direction.
I need a make the other dot handles fixed when one of the dot handle is moved when minRange or maxRange is defined.

Or if this feature already exists, please provide that information.

**Comment by Tofull** [comment]
There is a working solution on [this issue comment](https://github.com/NightCatSama/vue-slider-component/issues/373#issuecomment-502190658) using a computed [`:dot-options` props](https://nightcatsama.github.io/vue-slider-component/#/api/props?hash=dotoptions).
