### ISSUE TITLE
Component "fixed" and "non-fixed" at the same time depending on the moved slider

### ISSUE THREAD

**Issue by eschava** [NightCatSama/vue-slider-component#574]
#### Describe the feature

For component with two sliders, I need that it behaves as "fixed" when the first slider is moved and as non-fixed for the second one. Is it possible?

**Comment by NightCatSama** [comment]
Like this? <https://jsfiddle.net/qe8wjr70/>

**Comment by eschava** [comment]
> Like this? https://jsfiddle.net/qe8wjr70/

Works like a magic! Thanks a lot!

**Comment by eschava** [comment]
But it works for dragging only, right? Not for clicking

**Comment by NightCatSama** [comment]
Yes, it is not very good to judge when clicking, click on the left side fixed, the right side is not fixed, what about the middle?
