### ISSUE TITLE
max value error in console 

### ISSUE THREAD

**Issue by mrkazu** [NightCatSama/vue-slider-component#576]
If i try to raise the value of the slider above the max value i get an error in the console. as intended.
However, if i dynamicly change the max level before i increase the value of the slider i still get the message:
 "vue-slider.tsx:538 [VueSlider error]: The "value" must be less than or equal to the "max".

Everything works fine. i can increase the max value and also increase the slider value to follow the max value. its just that the error should not apear in console.

this hapens both in vue 2 and vue 3 using respectivie slider packages

**Comment by NightCatSama** [comment]
duplicate <https://github.com/NightCatSama/vue-slider-component/issues/343>
