### ISSUE TITLE
[vue3.x] TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by anfluff** [NightCatSama/vue-slider-component#578]
Hello.
I'm migrating my project from vue2 to vue3. On vue2 I used this slider alot and everithing works just fine.
On vue3 i've intalled `4.0.0-beta.5` version, but it throws me wierd error just from the beggining.

![image](https://user-images.githubusercontent.com/10028578/134512178-a4856cb4-510f-4386-a51c-23d2f140a41e.png)

Have no idea what could be the reason - it works fine on clean new vue3 project, but does not even start on mine. 
Probably there are some conflicts with other libraries or my config. Have you seen errors like this?

#### Environment

 - OS & Version: Windows
 - Vue version: 3.2.4
 - Component Version: 4.0.0-beta.5
 - Webpack: 5.53

**Comment by laranaedler** [comment]
Same Problem in version 3.2.14 but in version 4.0.0-beta4 it works
but cant use the beta version in productive systems

**Comment by deflopian** [comment]
Same problem with 4.0.0-beta.1 - 4.0.0-beta.5 versions
Vue 3.2.24
Node 16.13.1
Vite 2.7.1

**Comment by KristijanS99** [comment]
Anyone found a solution for this? I have the same issue on a Vite project with 4.0.0-beta.1 - 4.0.0-beta.5 versions too

**Comment by Eiryyy** [comment]
I faced the same problem. And I had no problem when using `@vue/compat`.

**Comment by EvanBldy** [comment]
Same problem here !

**Comment by MatzeSchmitt** [comment]
Hello together,

I would like to use this library and also face this issue.

Did everyone find a solution to this?

   Typescript InertiaJS / Vue Application

-    Vite 2.7.13
-    Vue 3.0.5
-    Vue Slider Component 4.0.0-beta.4

`Uncaught (in promise) TypeError: Object(...) is not a function
    at vue-class-component.esm-bundler.js:387:28
    at Array.forEach (<anonymous>)
    at r2.setup (vue-class-component.esm-bundler.js:380:18)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7045:29)
    at setupComponent (runtime-core.esm-bundler.js:7001:11)
    at mountComponent (runtime-core.esm-bundler.js:4922:13)
    at processComponent (runtime-core.esm-bundler.js:4897:17)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5037:21)`

Thank you and best regards!

Matthias

**Comment by lroal** [comment]
I am having the same problem. Running with vite.

**Comment by devopg** [comment]
yes up

**Comment by NightCatSama** [comment]
fixed in `4.0.0-beta.8`.
