### ISSUE TITLE
Tooltip stays in slider area not being cut

### ISSUE THREAD

**Issue by p1pchenk0** [NightCatSama/vue-slider-component#581]
#### Describe the feature

Currently if we have some label in tooltip, and this label has big width, then when slider is at 0, part of tooltip is being cut.
Same may be true if slider is near right side and max value is selected.

#### Describe the solution you'd like

On slider move calculate position of tooltip based on free space left from left/right side of tooltip

**Comment by NightCatSama** [comment]
You can use `slot` to customize the label style.

<https://nightcatsama.github.io/vue-slider-component/#/api/slots?hash=label>

**Comment by p1pchenk0** [comment]
Done by calculating difference between slider rail left offset and tooltip bubble offset
