### ISSUE TITLE
当添加process时 slider的总高度不会自适应变高 When adding process, the total height of the slider will not become adaptively higher

### ISSUE THREAD

**Issue by TianYa-Q** [NightCatSama/vue-slider-component#585]
#### Describe the bug
你好 有个小疑问
需要添加一个高度不确定的process，但是slider高度是固定的
会导致下面的元素重叠
我阅读了参数 似乎没有针对这个的设置
如果直接在外面加个固定高度的DIV 因为是不确定告诉的process也不是很方便
是我没有使用正确的方法吗？

Hello have a little question
Need to add a highly uncertain process, but the slider height is fixed
Will cause the elements below to overlap
I read the parameters and it seems that there is no setting for this
If you add a fixed-height DIV directly outside, it is not very convenient because it is uncertain to tell the process.
Am I not using the correct method?

**Comment by NightCatSama** [comment]
可以直接设置 height 呀

https://nightcatsama.github.io/vue-slider-component/#/zh-CN/api/props?hash=height

**Comment by NightCatSama** [comment]
这个没办法，因为 process 是绝对定位的，不是说能撑开的。可以加点逻辑去判断实现吧
