### ISSUE TITLE
Multiple inputs

### ISSUE THREAD

**Issue by avxkim** [NightCatSama/vue-slider-component#592]
There's example with a single input: https://nightcatsama.github.io/vue-slider-component/#/advanced/input

Is there a way to do that with 2 inputs? Value seems to be a single value, not an array.

**Comment by kostya110393** [comment]
`<span class="b-filter-price__from from">
                    <span v-show="showClass" class="b-filter-price__label-from">от</span>
                    <input type="text" v-model="valueInput[0]" @focus="focusInput" @keyup="minInput"
                    @blur="placeholder_min = min" :placeholder="placeholder_min" :name="this.attrname + '_from'"
                    class="b-filter-price__input defaultList"  />
                </span>
                <span class="b-filter-price__to to">
                    <span v-show="showClass" class="b-filter-price__label-to">до</span>
                    <input type="text" v-model="valueInput[1]" @focus="focusInput" @keyup="maxInput"
                    @blur="placeholder_max = max" :placeholder="placeholder_max" :name="this.attrname + '_to'"
                    class="b-filter-price__input defaultList" />
                </span>
                <span class="cloudLink" style="visibility: hidden;width: 1px; height: 1px;display: inline-block;">I</span>

                <vue-slider v-model="value" :min="min" :max="max" :interval="this.interval_slider"
                    :dotSize="[22, 22]" :tooltip="'none'" :enable-cross="false"
                    :process="true" @change="changeSlider" @drag-start="coordParent" @drag-end="countFind"
                    :labelStyle="{'color': '#323232', 'font-size': '11px'}"></vue-slider>`
