### ISSUE TITLE
[vue3.x] some errors with vitejs

### ISSUE THREAD

**Issue by jamesalways** [NightCatSama/vue-slider-component#595]
After I added this library to my project and  this error appeared, If I remove the library the error dissapear:

````
backend.js:726 An error occurred in hook walkComponentParents
callHandlers @ backend.js:726
callHook @ backend.js:317
walkComponentParents @ backend.js:374
(anonymous) @ backend.js:1625
async function (async)
(anonymous) @ backend.js:1614
emit @ VM1204:1
_replayBuffer @ VM1204:1
on @ VM1204:1
connect @ backend.js:1612
async function (async)
connect @ backend.js:1577
initBackend @ backend.js:1545
async function (async)
initBackend @ backend.js:1533
handshake @ backend.js:10952
postMessage (async)
n @ proxy.js:1
(anonymous) @ proxy.js:1
(anonymous) @ proxy.js:1
backend.js:727 TypeError: Cannot read properties of null (reading 'instanceMap')
    at ComponentWalker.mark (backend.js:5150)
    at ComponentWalker.captureId (backend.js:5071)
    at ComponentWalker.getComponentParents (backend.js:4985)
    at backend.js:5310
    at DevtoolsHookable.callHandlers (backend.js:723)
    at DevtoolsApi.callHook (backend.js:317)
    at DevtoolsApi.walkComponentParents (backend.js:374)
    at Object.<anonymous> (backend.js:1625)
````

<img width="854" alt="Screenshot 2021-11-16 at 12 31 33" src="https://user-images.githubusercontent.com/3009870/141977866-84dfef3d-bd1c-4fbd-87ed-46e12462bab9.png">

 - OS & Version:  macOS 11.6
 - Vue version: 3.2,22
 - Vite version: 2.7.0
 - Component Version: v4.0.0-beta.4

**Comment by xvaara** [comment]
I think those errors are from vue devtools not the component. Are you using the right version of that? You need the beta version for vue3. I'm using vite (2.6.13, since 2.7 isn't out yet)

**Comment by jamesalways** [comment]
I'll try as soon as possible without dev tools.

**Comment by xvaara** [comment]
Remember to disable the stable version of devtools, it's for vue2, beta is for vue3.

**Comment by jamesalways** [comment]
I still have the same error:
<img width="717" alt="Screenshot 2022-01-04 at 09 19 54" src="https://user-images.githubusercontent.com/3009870/148030225-911f22ad-7a7b-4cfa-b5be-4892c65ad692.png">
<img width="720" alt="Screenshot 2022-01-04 at 09 20 09" src="https://user-images.githubusercontent.com/3009870/148030227-93782194-a5cb-41cd-a62d-0f4851653369.png">
<img width="834" alt="Screenshot 2022-01-04 at 09 24 54" src="https://user-images.githubusercontent.com/3009870/148030231-12cceef6-91e8-4cd5-8b68-1588878311f7.png">
