### ISSUE TITLE
Progress is mistranslated as process

### ISSUE THREAD

**Issue by Anahkiasen** [NightCatSama/vue-slider-component#596]
#### Describe the bug

In the documentation and in the props of the component, `process` appears multiple times and I think it should be `progress` since the documentation often says "process bar". This made it hard for me to find the props I wanted and I suppose it is a mistake so thought I'd open an issue.

#### Additional context

![Screenshot 2021-11-24 at 11 04 02](https://user-images.githubusercontent.com/1321596/143217369-fd87490d-3be9-4210-84f7-e934aa34f31e.png)

**Comment by NightCatSama** [comment]
It's true that the semantics are wrong, but it's too costly to fix it now, so let's leave it as it is.
