### ISSUE TITLE
[vue3.x] Relations input with slider

### ISSUE THREAD

**Issue by kostya110393** [NightCatSama/vue-slider-component#599]
Hi guys. I have a problem with slider if i have two input. If i change value in any input my slider change only for the first time, after that slider don't want to change. You can check my project on website https://ankas.ru/mini-azs
https://codesandbox.io/s/vue-slider-component-data-example-forked-5dudo?file=/src/components/MyVueSlider.vue
 - OS & Version:  Linux
 - Vue version: [e.g. v3.2.19]
 - Component Version: [e.g. v4.0.0-beta.4]

**Comment by NightCatSama** [comment]
How you use it, please reproduce it in the online example

**Comment by kostya110393** [comment]
> How you use it, please reproduce it in the online example

I decided this mistake, but I don't remember how :-)  6 month I couldn't wait

**Comment by NightCatSama** [comment]
@kostya110393 Sorry friends, that time is very busy no time to maintain. 🤕
