### ISSUE TITLE
Browserify transform

### ISSUE THREAD

**Issue by ricvelozo** [NightCatSama/vue-slider-component#6]
Please, add **vueify** transform to `package.json`, to _vue-slider-component_ work with **Browserify**. This should be enough:

```json
"browserify": {
  "transform": ["vueify"]
}
```

Thanks!

**Comment by NightCatSama** [comment]
I'm sorry, I've never used browserify, isn't it only change the package.json, or need other operation, if you can, you can try to pull request.

**Comment by ricvelozo** [comment]
In reality, it needs to substitute the template strings for expressions too, because of [this bug](https://github.com/vuejs/vueify/issues/139). =/

If you allow me, I can PR with these two changes.

**Comment by NightCatSama** [comment]
of course

**Comment by ricvelozo** [comment]
Thanks! :smile: 

The `dist/` version has a conflict with Browserify, and I do not know how to fix at the time, so I left a note in README.

**Comment by NightCatSama** [comment]
npm has been updated, You can try whether normal use.

**Comment by ricvelozo** [comment]
Only works with full path of `.vue` file. Maybe if `main` value in `package.json` be changed to `vue-slider-component/src/vue2-slider.vue` it work. This modification can break webpack (I've never used webpack haha)?

**Comment by NightCatSama** [comment]
This may not be able to modify, because some people are not used `.vue` file, packaged in umd can allow more people to use.

**Comment by ricvelozo** [comment]
I understand. Nice component, anyway! :+1:
