### ISSUE TITLE
Other ways to bind data directly in component?

### ISSUE THREAD

**Issue by nexflo** [NightCatSama/vue-slider-component#60]
Hey,
directly binding values doesnt seem to work?
like inlining
<vue-slider v-bind={ 'min': 0,'max': 200,'interval': 50}></vue-slider>

Am i doing something wrong or is this not supported?

Thanks

**Comment by NightCatSama** [comment]
You can try this:
```html
<vue-slider v-bind="{ 'min': 0,'max': 200,'interval': 50}"></vue-slider>
```

**Comment by nexflo** [comment]
Thanks! I actually realised..the sliders work..seems i need to refresh the component...as the divs are not visible at first. How can i refresh the components? 
I saw there is a refresh function, how do I call that one.

Thanks again in advance!

**Comment by NightCatSama** [comment]
just like:
```html
<vue-slider ref="slider"></vue-slider>
<button @click="$refs.slider.refresh()">Refresh</button>
```
