### ISSUE TITLE
[vue3.2.23] [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.

### ISSUE THREAD

**Issue by Jazcash** [NightCatSama/vue-slider-component#603]
Am getting this warning using this component (version 4.0.0-beta.4) in electron:

![image](https://user-images.githubusercontent.com/1434248/151666850-c12fdd3b-19e0-4f1f-b203-df5140b7877c.png)

It's not critical at all, the component seems to behave just fine. Would just be nice to get rid of this warning is all. `silent: true` doesn't seem to help this.

**Comment by NightCatSama** [comment]
Fixed in the latest version.
