### ISSUE TITLE
[vue2.x] <How can control speed of marks points in slider.>

### ISSUE THREAD

**Issue by ashumsd7** [NightCatSama/vue-slider-component#614]
#### Speed control of marks when we pass data and marks props true.

When we leave the selector mark in between two points ( boundaries ) it moves towards the nearest point. I want to control speed of that movement. is it possible?
https://nightcatsama.github.io/vue-slider-component/#/basics/marks

Thanks.

**Comment by NightCatSama** [comment]
The animation time is controlled by `duration`.

You can change it at @drag-start and @drag-end.
