### ISSUE TITLE
Zoom property not working with btt direction

### ISSUE THREAD

**Issue by OFK0** [NightCatSama/vue-slider-component#618]
#### Describe the bug

I tried to make bottom to top slider. Slider parent component has scaled to 0.33333338.
I gave the scale amount to vue-slider component's **zoom** prop. But its not working. Positions are wrong.

After, i wondered how its working with top to bottom direction, its working correctly. I think, the problem occurs with bottom to top direction.

#### Environment

 - OS & Version: macOS
 - Vue version: v2.6.11
 - Component Version: v3.2.15

**Comment by NightCatSama** [comment]
Please provide live examples.

**Comment by NightCatSama** [comment]
The latest version has been fixed.
