### ISSUE TITLE
contained属性没有生效

### ISSUE THREAD

**Issue by Husiting-Alice** [NightCatSama/vue-slider-component#626]
#### Describe the bug
请教一下，"vue-slider-component": "3.2.15", 这个版本的contained属性值设为true没有生效，有同学有遇到过这个问题么？
![image](https://user-images.githubusercontent.com/33947948/173514009-d8923891-e048-40c6-905d-e88a67456c0c.png)

![image](https://user-images.githubusercontent.com/33947948/173513808-eb089b88-0498-4bd9-b1ca-b819b23948d0.png)
 - Component Version: [3.2.15]

**Comment by Husiting-Alice** [comment]
"vue-slider-component": "3.2.15",

**Comment by NightCatSama** [comment]
没有，看起来是有效的 <https://jsfiddle.net/gsz2baxt/>
