### ISSUE TITLE
Icon or HTML labels on scale

### ISSUE THREAD

**Issue by olifur** [NightCatSama/vue-slider-component#627]
#### Describe the feature

I would like to draw some icons or HTML labels on the scales, instead of just numbers.
I have seen this feature in rc-slider which is a react component.
For an example, please see here: https://stackoverflow.com/a/57654096/1958795

#### Describe the solution you'd like

I would like to have an option to use icons or HTML instead of just numbers, if you take a look at the react rc-slider component it could be configured like:
```javascript
 marks={{
    0: 0,
    30: <p style={{ color: 'green', fontSize: 20 }}>30</p>,
    50: <input type="button" value="50 hit" />,
    70: <i className="fas fa-3x fa-check"></i>,
    100: <i className="fas fa-2x fa-times"></i>
  }}
```
Best,
Oliver

**Comment by NightCatSama** [comment]
You can use the `slot`.

<https://nightcatsama.github.io/vue-slider-component/#/advanced/components-slots>
