### ISSUE TITLE
If the DOM is a hidden initial failure

### ISSUE THREAD

**Issue by artiely** [NightCatSama/vue-slider-component#63]
Such as use v-show

**Comment by NightCatSama** [comment]
yes, the documentation has this exceptions.

[https://github.com/NightCatSama/vue-slider-component#exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions)

**Comment by gnhuy91** [comment]
I read about the solutions, is total 4 steps required to get around the issue or just one of them? In my case, using `show` in combine with `v-show` does work.

**Comment by NightCatSama** [comment]
@gnhuy91 Just need one.
