### ISSUE TITLE
[vue3.x] [Vue warn]: Invalid prop: custom validator check failed for prop "tooltipPlacement".

### ISSUE THREAD

**Issue by whipsterCZ** [NightCatSama/vue-slider-component#634]
VueSlider works just fine, but i have console and log filled with warning

**[Vue warn]: Invalid prop: custom validator check failed for prop "tooltipPlacement".**

```
<VueSlider
          v-model="period"
          tooltip="always"
          tooltip-placement="bottom"
          :tooltip-formatter="periodTooltipFormatter"
          :min="1"
          :max="10"
          :interval="1"
        ></VueSlider>
```

#### Additional context

 - OS & Version: [ macOS monterey]
 - Vue version: [v3.2.37]
 - Nuxt version: [3.0.0-rc.1]
 - Component Version: [e.g. v4.0.0-beta.8]

**Comment by whipsterCZ** [comment]
i have tries

```
tooltip-placement="top"
tooltip-placement="left"
:tooltip-placement="placement" (ref)
:tooltip-placement="['bottom']"
```

**Comment by NightCatSama** [comment]
Thanks for your feedback, it's fixed in the latest 4.0.0-beta9 version.

**Comment by Aybee5** [comment]
@whipsterCZ how did you register the component please?

**Comment by whipsterCZ** [comment]
i dont understand the question. it depends on Vue version and whether you use CompositiontApi or OptionApi..

https://vuejs.org/guide/components/registration.html
