### ISSUE TITLE
The @change event does not emit a value of 0

### ISSUE THREAD

**Issue by peter31990** [NightCatSama/vue-slider-component#635]
The @change event does not emit a value of 0. Why?
:min="-600"
:max="0"
When I move the slider to 0 the event is not emitted.

**Comment by NightCatSama** [comment]
Can't reproduce what you said, please provide the online example.

<https://jsfiddle.net/Lp05vtc8/>

**Comment by MichaelObst** [comment]
I noticed this issue when I didn't have a v-model set. Even with a min -1 and max over zero you can't return to zero. Setting a v-model fixes the issue.

https://codesandbox.io/s/compassionate-framework-qgtbcc?file=/src/App.vue

**Comment by MichaelObst** [comment]
I noticed this when I didn't have a v-model set. Even when passing over zero from negative to positive, zero is ignored. Just set a v-mode land it fixes it though.

https://codesandbox.io/s/xenodochial-forest-3zy7by

**Comment by NightCatSama** [comment]
Yes, because you did not set the value, the default is always 0, so the internal judgment of the component will not trigger the change event if there is no change.

**Comment by callmeaponte** [comment]
I'm experiencing this issue as well.

@NightCatSama what about if the user changes the value from `0` to `1`, then back to `0`? No `change` event is fired, even though the value did indeed change from it's previous one.

**Comment by NightCatSama** [comment]
> @NightCatSama what about if the user changes the value from 0 to 1, then back to 0? No change event is fired, even though the value did indeed change from its previous one.

The internal determination is that there is no change, because the `value/v-model` is not passed, so it will always be 0 inside the component.

**Comment by NightCatSama** [comment]
@callmeaponte The usage in this example is wrong. vue3 uses `model-value` and not `value`.

document: https://github.com/NightCatSama/vue-slider-component#breaking-changes 

example: https://stackblitz.com/edit/vue-zuobkp?file=src%2FApp.vue

**Comment by callmeaponte** [comment]
Sorry for the confusion - I'm not actually using Vue 3 in my project, I just couldn't get a Vue 2 example working on StackBlitz. Good to know about the API change though.

Either way I'll just use `v-model` for now, still gets the job done 😁

**Comment by antonbehaeghe** [comment]
Sort of running into a similar issue. I initialise the slider with a value of 'undefined', and a min/max of 0-10. 0 is not selectable unless another value is selected first. I can't initialise with 0 because I need the user to explicitly set a value. How would I configure this?
