### ISSUE TITLE
How to build multiple sliders with markers?

### ISSUE THREAD

**Issue by charle-connoringold** [NightCatSama/vue-slider-component#637]
I'm trying to build the following slider:

![image](https://user-images.githubusercontent.com/84711365/179978743-a6aa1c17-9ab3-4b38-9670-1ae926918594.png)

I've built a bunch of other sliders with no issue but I just can't seem to figure out how to build this one and was hoping you could help?

**Comment by NightCatSama** [comment]
Multiple sliders? refers to the value of the array type?

**Comment by charle-connoringold** [comment]
Here's perhaps a better example:
![image](https://user-images.githubusercontent.com/84711365/180169271-232cbe2d-f7ed-4f42-b686-2cc9488f5c1d.png)
As you can see you have 2 slides that you can click on and select from a range. Hopefully, that makes sense.

**Comment by NightCatSama** [comment]
@charle-connoringold 

Just use the value of the array type.

example: https://jsfiddle.net/5ovnt4px/

<img width="713" alt="image" src="https://user-images.githubusercontent.com/13888962/180183131-b2aa5326-e6c9-4a96-80d8-0a04e6e93344.png">

**Comment by charle-connoringold** [comment]
@NightCatSama Thank you! That solve's my problem perfectly.
