### ISSUE TITLE
Tooltip slot

### ISSUE THREAD

**Issue by bobmoff** [NightCatSama/vue-slider-component#64]
Would be awesome if it could support custom tooltip, perhaps using a slot. 

I am trying to create this look that has separated styling for different parts of the value.

![2017-06-08 at 09 30](https://user-images.githubusercontent.com/1033236/26917077-1ddcec48-4c2d-11e7-8af4-15be76fe38ea.png)

**Comment by NightCatSama** [comment]
Yes, it is a good idea, I will add this function.

**Comment by bobmoff** [comment]
Sweet bananas, that was the fastest response I have ever experienced 🥇

**Comment by NightCatSama** [comment]
I added this feature, updated to version `2.3.1`. 😄 

doc: [https://github.com/NightCatSama/vue-slider-component#slot](https://github.com/NightCatSama/vue-slider-component#slot)

example: [https://nightcatsama.github.io/vue-slider-component/example/#demo7](https://nightcatsama.github.io/vue-slider-component/example/#demo7)

**Comment by bobmoff** [comment]
Wow! Your fast. I will try it out right now!

**Comment by bobmoff** [comment]
Works like a charm! 😃  Thx a bunch!

**Comment by NightCatSama** [comment]
You are welcome. it's a great idea.
