### ISSUE TITLE
Nuxt SSR build: Lexical error when importing default theme scss version

### ISSUE THREAD

**Issue by dsvgl** [NightCatSama/vue-slider-component#640]
#### Describe the bug

I'm using Nuxt in SSR mode. To prevent console warnings about css map not found, I am importing theme style from `lib/theme/default.scss` instead of `theme/default.css`. Like mentioned here: https://github.com/NightCatSama/vue-slider-component/issues/114#issuecomment-891886672

When doing a build, it fails with the following error (also see screenshot below):
`JisonLexerError: Lexical error on line 1: Unrecognized text.`
`Erroneous area:  $size * 0.5`

PostCss seems to doesn't like the plain sass vars inside a calc function in `_triangle.scss` (see screen below).
Writing it as `border-width: calc(#{$size} * 0.5);` fixes the problem.

#### Additional context

<img width="836" alt="Bildschirmfoto 2022-07-28 um 09 51 42" src="https://user-images.githubusercontent.com/97700093/181470894-267ded6d-0c46-4efd-a2b9-f71e8b3b034e.png">

Offending line:
![SCR-20220728-fmi](https://user-images.githubusercontent.com/97700093/181471028-b1ed4ba3-5c15-491d-ad0c-e223a3dfb087.png)

#### Environment

 - OS & Version: macOS
 - Vue version: v2.6.14
 - Nuxt version: v2.15.8
 - Component Version: 3.2.18

**Comment by NightCatSama** [comment]
`calc(#{$size} * 0.5)` compiled css will be `calc(10px * 0.5)`.

> You can also use [interpolation](https://sass-lang.com/documentation/interpolation) in a calculation. However, if you do, nothing in the parentheses that surround that interpolation will be simplified or type-checked, so it’s easy to end up with extra verbose or even invalid CSS. Rather than writing calc(10px + #{$var}), just write calc(10px + $var)!

https://sass-lang.com/documentation/values/calculations

**Comment by NightCatSama** [comment]
This error can be bypassed by referring directly to the css file.

**Comment by dsvgl** [comment]
@NightCatSama thx for the quick reply. Really appreciate it!
When using the css file, I get warning in console about missing css source map (in dev mode). Like mentioned here: https://github.com/NightCatSama/vue-slider-component/issues/114#issuecomment-891886672
> DevTools failed to load source map: Could not load content for http://localhost:3000/default.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
There is a reference-comment to a source map file at the bottom of the css file.
My workaround: I copied said css file into my src dir, removed the comment and use this now.
If you know a better way, I'm all ears :)

BTW: great slider, really enjoying it!

**Comment by NightCatSama** [comment]
I can't think of a better solution. 

Maybe can copy `default.scss` and `triangle.scss` for local use, that is also a recommended way to customize the theme. 😃

**Comment by dsvgl** [comment]
Okay, then I'll add more comments to our project so teammates know why this was done. 😄
