### ISSUE TITLE
Multiple handles

### ISSUE THREAD

**Issue by rickdg** [NightCatSama/vue-slider-component#65]
How hard would it be to add multiple handles?
And, then give them the ability to have different background colors.

**Comment by NightCatSama** [comment]
I don't quite understand what you mean.

If more than one slider, the data set into an array.

and give them different style can set prop `slider-style`. see [example](https://nightcatsama.github.io/vue-slider-component/example/#demo6)

**Comment by rickdg** [comment]
I was thinking more like this:
https://jsfiddle.net/5vhyyp37/3/

**Comment by NightCatSama** [comment]
Sorry, this mode is not supported.
