### ISSUE TITLE
Allow tabindex to be disabled

### ISSUE THREAD

**Issue by Flambe** [NightCatSama/vue-slider-component#650]
#### Describe the feature

I use the slider to only display values in my app. As the `tabindex` on the slider dots is forcefully set to always be on, this disrupts my users flow through the application as it picks up every slider dot on the page.

#### Describe the solution you'd like

The ability to toggle `tabindex` to -1 (aka disabling it).

**Comment by NightCatSama** [comment]
You can use `dotAttrs` to set it. 

`:dotAttrs="{ tabindex: -1 }"`

**Comment by Flambe** [comment]
I completely missed that! It works perfectly, thank you :)
