### ISSUE TITLE
After upgrading to 3.2.21 getting error, 3.2.20 works good with totally same options

### ISSUE THREAD

**Issue by lubuger** [NightCatSama/vue-slider-component#657]
#### Describe the bug

Getting error in console, page is not loaded at all.

**Cannot read properties of null (reading 'toString')**

#### Environment

 - OS & Version: Linux
 - Vue version: 2.7
 - Component Version: 3.2.21

**Comment by NightCatSama** [comment]
Thanks for the feedback, try version 3.2.22.

**Comment by lubuger** [comment]
Works good, thanks bro :) i guess it somehow even started to work smoother than before... Great, thanks one more time ;)
