### ISSUE TITLE
Error in index file

### ISSUE THREAD

**Issue by arsalansultani** [NightCatSama/vue-slider-component#66]
I am getting this error in console. Anyone knows how to solve it? 

 error  in ./~/vue-slider-component/dist/index.js

Syntax Error: Unexpected token � in JSON at position 0
    at Object.parse (native)

 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/section/searchPanel.vue 3:0-45
 @ ./src/components/section/searchPanel.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/section/section.vue
 @ ./src/components/section/section.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by NightCatSama** [comment]
Can you provide the how do you use?

Maybe you can try this way:

```js
import vueSlider from 'vue-slider-component/src/vue2-slider.vue'
```

**Comment by arsalansultani** [comment]
Still not working. 
I  import it as 
`import vueSlider from 'vue-slider-component/src/vue2-slider.vue'`
and then I used it as a component
`<slider></slider>`

**Comment by NightCatSama** [comment]
I write a simple [example](https://www.webpackbin.com/bins/-KmKNNqXaZ08UhJx7hmo).

**Comment by arsalansultani** [comment]
I copied exactly your code but still getting the error. something is wrong with the index.js file because in the error it says that 
```
Syntax Error: Unexpected token � in JSON at position 0
at Object.parse (native)
```

**Comment by NightCatSama** [comment]
but the `index.js` file  was not call `JSON.parse`, i doubt whether associated with webpack.

**Comment by NightCatSama** [comment]
oh, maybe this reason. 

[https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only)

**Comment by NightCatSama** [comment]
Components are using the template.
