### ISSUE TITLE
各位大老好

### ISSUE THREAD

**Issue by zhaobo0564** [NightCatSama/vue-slider-component#668]
![image](https://user-images.githubusercontent.com/49364302/206958627-e43c0f4d-c813-4c07-87b9-5e7d68fdf213.png)
这个proecess可以传递两个参数，如果我想要传递两个参数该怎么操作

**Comment by NightCatSama** [comment]
什么两个参数，你想实现什么东西

**Comment by zhaobo0564** [comment]
> 什么两个参数，你想实现什么东西

比如 
![image](https://user-images.githubusercontent.com/49364302/206981134-dda2553b-d33f-4962-a57d-e1d1ee2227a4.png)

当你有n个`<vue-slider>`的时候，对于每一个`<vue-slider>`输出不同的样式，那么你就必须有n 个process的方法，我想用一个process方法，它可以传递两个参数（dotspose, id）其中通过id来区分它是第几个`<vue-slider>`，然后来显示相应的颜色

**Comment by NightCatSama** [comment]
那你写个方法就可以了吧，再返回 process 方法的。

**Comment by zhaobo0564** [comment]
> 那你写个方法就可以了吧，再返回 process 方法的。
但是方法只有一个参数，方法自己不知道当前它要渲染的是那一个<vue-slider>，因为我这边有n个<vue-slider>的n非常大，我不可能对每一个<vue-slider>都写一个方法。所以需要一个参数来获取当前的process方法属于那一个<vue-slider>

**Comment by zhaobo0564** [comment]
> 那你写个方法就可以了吧，再返回 process 方法的。

初学者不太明白，可以在举个列子吗？

**Comment by NightCatSama** [comment]
```vue
getProcess(id) => {
  const color = id === 1 ? 'blur' : 'pink'
  return dotsPos => [[dotsPos[0], dotsPos[1], { background: color }]]
}

<vue-slider :process="getProcess(1)" />
<vue-slider :process="getProcess(2)" />
```
