### ISSUE TITLE
Know value of slider at point of hover.

### ISSUE THREAD

**Issue by xerosanyam** [NightCatSama/vue-slider-component#69]
I am using the slider as an audio progress bar.
Now there is a use case that, when I hover on the progress bar, I should know the timing at the point of hover by a tooltip or something similar, and if I like it I'll jump there, otherwise, i'll hover at some other point.

**Comment by NightCatSama** [comment]
I'm not very sure about your needs, is it necessary to display the value when the mouse hover?

**Comment by xerosanyam** [comment]
yes. user would like to choose the timestamp by hovering.
I am not asking you to implement it, but for suggestions on how to do it  ?

**Comment by NightCatSama** [comment]
Unfortunately, it is difficult to achieve this function at present.

Because the component itself does not deal with the progress of the hover state.

**Comment by xerosanyam** [comment]
okay. thanks for the prompt reply :smiley:
