### ISSUE TITLE
[vue3.x] warning vue-class-component@7.2.6 has incorrect peer dependency "vue@^2.0.0

### ISSUE THREAD

**Issue by nekooee** [NightCatSama/vue-slider-component#692]
when I use yarn install get this warning:
warning "vue-slider-component > vue-property-decorator > vue-class-component@7.2.6" has incorrect peer dependency "vue@^2.0.0".

 - Vue version: 3.2.47
 - Component Version: 3.2.24

**Comment by NightCatSama** [comment]
vue3 is installed using `@next`, the latest version is 4.1.0-beta.7
