### ISSUE TITLE
Slider omits intermediate values when moving fast

### ISSUE THREAD

**Issue by p0rsche** [NightCatSama/vue-slider-component#70]
When I move slider fast to left or right, say from 0 to 5, it omits intermediate values like (1,2,3,4) and show me only end value (sometimes it can be 0.. 2.. 5 or similar). I'm catching values using @callback. Is there any way to prevent omitting intermediate values? Or it is by system?

**Comment by NightCatSama** [comment]
Because when the mouse is too fast when the middle part is not triggered mousemove event caused.

But you can fix the problem by watch for the value.

I wrote a simple example, hoping to help you.

[https://jsfiddle.net/9pp3dqkq/13/](https://jsfiddle.net/9pp3dqkq/13/)

**Comment by p0rsche** [comment]
So it's by system. Thanks
