### ISSUE TITLE
Run error: npm run build

### ISSUE THREAD

**Issue by f1729** [NightCatSama/vue-slider-component#71]
I'm run ``` npm run build ``` on this project for contributing some things and ...

9069 ± : npm run build                                                ⏎ [23h3m]

> vue-slider-component@2.3.1 build /Users/luis/alertsOP/node_modules/vue-slider-component
> rm -rf ./dist && webpack --colors --hide-modules

Hash: d10c8d22a7979f424f81
Version: webpack 2.6.1
Time: 328ms
   Asset     Size  Chunks             Chunk Names
index.js  1.29 kB       0  [emitted]  main

```
ERROR in ./src/vue2-slider.vue
Module parse failed: /Users/luis/alertsOP/node_modules/vue-slider-component/src/vue2-slider.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template>
| 	<div ref="wrap" :class="['vue-slider-wrap', flowDirection, disabledClass, { 'vue-slider-has-label': piecewiseLabel }]" v-show="show" :style="wrapStyles" @click="wrapClick">
| 		<div ref="elem" class="vue-slider" :style="[elemStyles, bgStyle]">
 @ ./src/index.js 1:16-40
```

**Comment by NightCatSama** [comment]
May I have your loader dependencies on whether they have been fully installed.
