### ISSUE TITLE
How do you use vue-slider without .vue files?

### ISSUE THREAD

**Issue by Xeoncross** [NightCatSama/vue-slider-component#72]
Is there any way to directly add vue slider without needing webpack to build everything?

I tried copying the source style into a .css file and then including the index.js file but that doesn't work because of the module.exports wrapper.

**Comment by NightCatSama** [comment]
`index.js` already contains the style.

if you use `import vueSlider from 'vue-slider-component'` to import the component,  it is not included `.vue` file.

**Comment by NightCatSama** [comment]
Hope this can help you. [https://jsfiddle.net/NightCatSama/9pp3dqkq/](https://jsfiddle.net/NightCatSama/9pp3dqkq/)

**Comment by Xeoncross** [comment]
Thank you very much! Maybe you can add this link to the readme for other developers who just want to try out your component on codepen or jsfiddle.

**Comment by araichev** [comment]
@NightCatSama , could you include a non-default slider example in the jsfiddle, that is, one with properties, e.g. a lazy slider?  I can't figure out how overide the slider defaults.

**Comment by NightCatSama** [comment]
@araichev I added the default props. [https://jsfiddle.net/9pp3dqkq/107/](https://jsfiddle.net/9pp3dqkq/107/)

**Comment by araichev** [comment]
Thanks, but, as i said, i'm looking for a non-default slider example.

**Comment by NightCatSama** [comment]
@araichev  like this? [lazy slider](https://jsfiddle.net/9pp3dqkq/137/)

**Comment by araichev** [comment]
Thanks, and i apologize for overlooking the parameter settings in the vue-slider tag of your previous example.
