### ISSUE TITLE
Constrain Piecewise to inside slider?

### ISSUE THREAD

**Issue by inctor** [NightCatSama/vue-slider-component#73]
Hey,

I've tried to constrain the piecewise labels to be inside the slider, which partially works.
Which i've done with the following styles/setup:
https://jsfiddle.net/0zxrc3tq/2/

As seen, the "labels" are showing outside the actual slider, but what i'm trying to achieve is the following:
https://cl.ly/3Z3T132x3k0j

Can this be done in another way with this library?

**Comment by NightCatSama** [comment]
I upgraded to `@2.3.3` version support label slot.

Sorry, can only be done like this:
[https://jsfiddle.net/NightCatSama/0zxrc3tq/4/](https://jsfiddle.net/NightCatSama/0zxrc3tq/4/)

**Comment by inctor** [comment]
@NightCatSama Nothing to be sorry about, your solution is almost spot on, and only requires very minor tweaks, which i can easily do myself! Really well done, Thanks!

- Would hope eventually to have an option for constraining piecewise inside the slider :)
