### ISSUE TITLE
Slider dot doesn't cover 100% of slider width on dynamic content

### ISSUE THREAD

**Issue by LTroya** [NightCatSama/vue-slider-component#74]
I am trying to use this component in my project. It is a bootstrap project.

The component works perfectly. But when I need it cover the container full width, it slider dot doesn't cover all the width

![This is the capture of how it looks](https://user-images.githubusercontent.com/6491259/27895440-cbd674e0-61e0-11e7-8983-20d5c9acf8c5.png)

I have anything special in my source code.

Template

    <vue-slider ref="slider" v-model="logoForm.awesome_classic"></vue-slider>

In my component I import it like this:

    import vueSlider from 'vue-slider-component'

    components: {vueSlider},

If I set the width, it works. Like this

    <vue-slider v-bind="{width: 100}" ref="slider" v-model="logoForm.awesome_classic"></vue-slider>
    
I also try:

    let slider = this.$refs['slider'];
    slider.refresh();
I will appreciate any hint you can give me to solve this.

**Comment by NightCatSama** [comment]
When the `width` is a number, the default is to use px, have you ever tried this?

```html
<vue-slider v-bind="{width: '100%'}" ref="slider" v-model="logoForm.awesome_classic"></vue-slider>
```

**Comment by NightCatSama** [comment]
When the container width changes, you need to call `refresh`, or use `:realtime="true"` to update in real time.

**Comment by LTroya** [comment]
Oh. Thank you very much. It works. This is the way to call refresh right?

    let slider = this.$refs['slider'];
    slider.refresh();

**Comment by NightCatSama** [comment]
@LTroya yes.

**Comment by LTroya** [comment]
Ok. Thanks for the help
