### ISSUE TITLE
Clickable prop doesn't prevent dragging

### ISSUE THREAD

**Issue by matthew-carroll** [NightCatSama/vue-slider-component#76]
I think the "clickable" prop may have an issue.  When I set "clickable" to "false" I can still drag the slider.  I can't click on the slider to move the tab, but I can drag the tab left/right.  Shouldn't "clickable" disable both?

I'm using version 2.3.3.

**Comment by NightCatSama** [comment]
`clickable` just control component is triggered by click, if you want to disable click and drag can set `event-type="none"`

**Comment by matthew-carroll** [comment]
Thanks, that seems to work.
