### ISSUE TITLE
Doesn't reflow layout when changed

### ISSUE THREAD

**Issue by matthew-carroll** [NightCatSama/vue-slider-component#78]
I have some sliders in an area that expands/contracts based on some content that appears to their right.

When the content appears/disappears, the slider tracks correctly reflow their layout to take up the desired space.  However, the sliders and the process bar do not update accordingly.  The sliders and process bar remain where they were before the content change.

If I resize the browser then the sliders and process bar correctly reflow themselves.

**Comment by NightCatSama** [comment]
sorry this is a exception of the component.

Solution you can refer to here:
[https://github.com/NightCatSama/vue-slider-component#exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions)
