### ISSUE TITLE
[Question] Linked sliders

### ISSUE THREAD

**Issue by jaggero** [NightCatSama/vue-slider-component#79]
Hello, is it possible to link multiple sliders? I mean: total value of all sliders must be a specific value. And when one is changed other are changed too.

**Comment by NightCatSama** [comment]
Hello, the component does not provide this feature, but you can do it with an extra script.

**Comment by jaggero** [comment]
Thank you, is it possible to you write this kind of script? Some kind of this: https://github.com/heap-of-jquery/jquery-interconnected-sliders

**Comment by NightCatSama** [comment]
If you want to make this kind of difficult, sorry I can't help you.
