### ISSUE TITLE
Tooltips broken in Internet Explorer

### ISSUE THREAD

**Issue by ricvelozo** [NightCatSama/vue-slider-component#8]
The tooltips are broken in Internet Explorer (9, 10, and 11), because of `calc()` nested expressions in `translate`.

**Comment by NightCatSama** [comment]
I have modified the style, no longer use `calc()`. 

because my computer only ie8, so i didn't to test in ie(9, 10, 11). 

if this change is feasible, please tell me, thank you.

**Comment by ricvelozo** [comment]
The range sliders are still broken in IE + Edge. Some these have a tiny space between the balloon and arrow.

![printscreen-edge-vue-slider-default](https://cloud.githubusercontent.com/assets/1834764/20234431/4bfe827c-a862-11e6-93f2-91a0c72a4bfa.png)
![printscreen-edge-vue-slider-range](https://cloud.githubusercontent.com/assets/1834764/20234430/4bf9629c-a862-11e6-8078-5cfbd7e1dc5d.png)

**Comment by NightCatSama** [comment]
It's ok, ie always so strange, mainly to repair the two problems:
1.  `data-*` are case sensitive in ie.
2.  when the tooltip for the bottom or right, always 1 px deviation.

In the code I found another problem again.
At some point, click on the component failure process animation, the process will appear bug when the width reduction, and click on the location of the process.

**Comment by NightCatSama** [comment]
I have all repair, under ie11 test normal.

**Comment by ricvelozo** [comment]
Thanks! It's fixed! =D
