### ISSUE TITLE
Mobile slide

### ISSUE THREAD

**Issue by esaramago** [NightCatSama/vue-slider-component#80]
This component does not support sliding on mobile.

**Comment by NightCatSama** [comment]
Please provide your mobile type and environment.

**Comment by esaramago** [comment]
Sorry for the incomplete issue.

I just tried touch slide (swipe) on several devices.

**It works** as expected on:
- iPhone 4S (Safari)
- Lg G2 (Chrome 59)
- Samsung Neo (Chrome 59)

It **doesn't swipe** on:
- Microsoft Surface 3 (Chrome)
- Lenovo Tab 3 (Chrome 59 and Firefox)
- Also doesn't work on Emulated devices (Dev Tools) on Chrome 59 for Windows

**Comment by NightCatSama** [comment]
I am worried that the error is because the judge of the mobile RegExp is not correct, so you can try to set `:event-type="touch"`.

If still can not work, does the console have an error?

**Comment by esaramago** [comment]
It does work if you set `:event-type="touch"`. The problem is, of course, it stops working on desktop.
The console doesn't have any error.

**Comment by NightCatSama** [comment]
There is a great possibility because the regular expression of the device is not perfect.

There is also worry that when you switch to the simulation device debugging first refresh page, because the component will determine which type of event to bind when it is initialized.

**Comment by atakajlo** [comment]
I have the same problem too. Can you fix this without switching event-type?

**Comment by NightCatSama** [comment]
I do not know the `navigator.userAgent` that failed to match the phone, and there are now regular expressions from issue #58 .

So, maybe you can write your own regular expression to fix this problem. like it:
```html
<vue-slider :event-type="isMobile ? 'touch' : 'mouse'"></vue-slider>
// ...
export default {
  data () {
    isMobile: /(RegExp)/i.test((navigator.userAgent)
  }
}
```

If you can, welcome to submit a `pr` of the regular expression to me.
