### ISSUE TITLE
Failed to load slider when using on Dynamic Component 

### ISSUE THREAD

**Issue by theromie** [NightCatSama/vue-slider-component#82]
I am loading component dynamically like `<component :is="currentView"></component>` but slider range left and right stuck to 0.
I also use :real-time property but doesn't worked. How can i reinitialize vueslider?
`<vue-slider ref="slider1" v-bind="price" v-model="price.value" :real-time="true"></vue-slider>`

**Comment by NightCatSama** [comment]
`this.$ref.slider1.refresh()` can refresh the component.

**Comment by theromie** [comment]
Error in mounted hook: "TypeError: Cannot read property 'slider1' of undefined"

**Comment by NightCatSama** [comment]
oops, I am careless, it should be `this.$refs.slider.refresh()`.

[https://vuejs.org/v2/guide/components.html#Child-Component-Refs](https://vuejs.org/v2/guide/components.html#Child-Component-Refs)

**Comment by theromie** [comment]
This should be inside mounted()?

**Comment by NightCatSama** [comment]
After the component is rendered, then call this method.

**Comment by theromie** [comment]
No man not working

**Comment by NightCatSama** [comment]
You can see here can give you inspiration: [https://jsfiddle.net/9pp3dqkq/54/](https://jsfiddle.net/9pp3dqkq/54/)

**Comment by theromie** [comment]
Dude onclick of refresh is not going to 100

**Comment by NightCatSama** [comment]
![](http://7xqnme.com1.z0.glb.clouddn.com/17-8-8/75733114.jpg)

**Comment by theromie** [comment]
I am using getuikit and showing slider inside dropdown but dropdown failed to refresh vue slider

**Comment by NightCatSama** [comment]
Maybe you can try to listen for the `shown` event and call refresh later to refresh the component.

**Comment by theromie** [comment]
`UIkit.dropdown(element).shown({
    this.$refs.daysSlider.refresh();
     ^
});`
Syntax Error: this is a reserved word

**Comment by theromie** [comment]
I also have updated your jsfiddle to work with dropdown of uikit
[Snippets](https://jsfiddle.net/9pp3dqkq/92/)

**Comment by NightCatSama** [comment]
[https://jsfiddle.net/9pp3dqkq/94/](https://jsfiddle.net/9pp3dqkq/94/)

**Comment by theromie** [comment]
thanks its working

**Comment by theromie** [comment]
what if i want to do it like `UIkit.dropdown(element).shown({ this.$refs.daysSlider.refresh(); });`

**Comment by NightCatSama** [comment]
That's not the UIkit binding of events.

look it: [https://getuikit.com/docs/javascript#programmatic-use](https://getuikit.com/docs/javascript#programmatic-use)

```
$('#offcanvas').on('show', function () {
    // do something
});
```
