### ISSUE TITLE
toJSON error on drag event

### ISSUE THREAD

**Issue by d1manson** [NightCatSama/vue-slider-component#83]
Providing `this` as the data emitted with the `drag-[start|end]` event causes an error...

https://github.com/NightCatSama/vue-slider-component/blob/master/src/vue2-slider.vue#L486 

![screen shot 2017-08-07 at 11 35 32](https://user-images.githubusercontent.com/4244876/29023203-9a7d4890-7b64-11e7-9526-10db56fb9b9c.png)

**Comment by NightCatSama** [comment]
How do you call `toJSON` methods, the component itself is not the method.

**Comment by d1manson** [comment]
I'm using Vue 2.3.4..I wonder if it's something to do with the Vue dev tools. I'll get back to you asap

**Comment by d1manson** [comment]
Yeah, seems to be the dev tools...and there is an existing (closed) error..
https://github.com/vuejs/vue-devtools/issues/333

**Comment by Elevista** [comment]
I have this issue too.
Same dependency with package-lock.json and same dev tools version
but only mac chrome display this error. windows chrome shows nothing
