### ISSUE TITLE
Scoped style

### ISSUE THREAD

**Issue by adi518** [NightCatSama/vue-slider-component#87]
Isn't distributed component supposed to be non-scoped? I have hard time overriding your styles. I cloned your repo to my private server and removed it there. Thought I'd point it out still.

**Comment by NightCatSama** [comment]
Can be modified into non-scoped, but I have to make sure that all styles are in a parent class,
such as `.vue-slider-dot` will be modified to` .vue-slider-component .vue-slider-dot`.

If so, can you accept it?

**Comment by adi518** [comment]
Yes, that would be excellent. It's also how [`vue-select`](https://github.com/sagalbot/vue-select) did it.

**Comment by NightCatSama** [comment]
I have modified to a non-scope component.

Please update to version`2.3.8`.

Looking forward to your feedback.

**Comment by adi518** [comment]
That was quick. I'll check it out ASAP.

**Comment by adi518** [comment]
Excellent.
