### ISSUE TITLE
Can't style slider height + width

### ISSUE THREAD

**Issue by Tirke** [NightCatSama/vue-slider-component#90]
`sliderStyle`options doesn't take account of `height`and `width` so it's a bit harder to achieve a good custom style.

**Comment by NightCatSama** [comment]
The `width` and `height` of the slider is controlled by `dot-size` options.

So you can use these two settings to control the slider style.

**Comment by Tirke** [comment]
Oh didn't catch this one, thanks !

**Comment by Tirke** [comment]
`dot-size` is a unique options I can't style height + width individually. I wanted to be able to do so because we want to replace the dot by a rectangle, so I need widht ≠ height.

**Comment by NightCatSama** [comment]
I improved the priority of the `slider-style`, but the height still needs to use dot-size to control (contrary to vertical components.

please update to version`2.3.9`

**Comment by Tirke** [comment]
Seems good enough, will test, thanks for the quick update.
