### ISSUE TITLE
Can't drag slider on Windows 10 touch panel device?

### ISSUE THREAD

**Issue by roberttolton** [NightCatSama/vue-slider-component#91]
Hi,

In both Google Chrome and Microsoft Edge I'm unable to drag the slider with my finger on the touch panel.

I created a fork of the project, to remove the `isMobile` different template, and apply `@touchstart` and `@mousedown` events to the same element at once (the same approach Keen-UI's slider uses) but this has not made a difference:
https://github.com/fuelintegrated/vue-slider-component/blob/master/src/vue2-slider.vue

What would be needed to have this component work correctly on Windows 10 touch screens?

**Comment by NightCatSama** [comment]
Your revision is incomplete, because you didn't modify `bindEvent` method.

If you want to test the touch events, only need to set the prop `event-type="touch"`.

**Comment by roberttolton** [comment]
Ah, you're right, I've updated my file:
https://github.com/fuelintegrated/vue-slider-component/blob/master/src/vue2-slider.vue

Should you be testing for touch this way? As the device I'm using is a Dell All-In-One with Touch Screen, and the slider can't be used on desktop touch devices like it in this component's current state.

**Comment by roberttolton** [comment]
Unfortunately even with that edit it still doesn't seem to be working on the device.

**Comment by NightCatSama** [comment]
You mean the `mouse` and `touch` events doesn't work on the Touch Screen?

**Comment by roberttolton** [comment]
You can't drag the dot using your finger, only using the mouse. You can 'tap' the slider track to have the dot move to that location, which I'm guessing is just a `click` event.

I did wonder if Windows 10 wasn't passing `touch` events to the browser because I had a mouse plugged-in, so I un-plugged the mouse, but touching and dragging the dot still didn't work.

**Comment by NightCatSama** [comment]
Because I do not have equipment testing, so I can hardly find the reason.

If you can, you can set both components to `event-type="mouse"` and `event-type="touch"`.

**Comment by adi518** [comment]
I also ran into what seems to be a similar if not exact issue. I put my finger on the dot and I can't drag it in Chrome device mode.

**Comment by roberttolton** [comment]
@NightCatSama These props should both be added to where I am setting up the component in my HTML? Or in the source code?

**Comment by adi518** [comment]
@roberttolton you can wrap his component and have it passed by default instead of modifying his source.

**Comment by adi518** [comment]
In my case, I got to test the slider on a real mobile device (not the one mentioned in this issue) and it works just fine. I can move the dot without a problem. The bug I experienced was with Chrome emulator.

**Comment by adi518** [comment]
Possible [fix](https://coderwall.com/p/i817wa/one-line-function-to-detect-mobile-devices-with-javascript).
