### ISSUE TITLE
Vue 2.3.4 raising [Warn] errors for value property not having setter

### ISSUE THREAD

**Issue by sarahfmurray** [NightCatSama/vue-slider-component#92]
Since upgrading to Vue 2.3.4, I get console errors about the value property not having a setter.

`[Vue warn]: Computed property "value" was assigned to but it has no setter.`

I'm using the component in this way:
`<vueSlider v-model="value" v-bind="options" :min="min" :max="max" @input="update($event)"></vueSlider>`

How do I stop the console warnings?

**Comment by NightCatSama** [comment]
Can you see how your `value` is defined?

**Comment by sarahfmurray** [comment]
It's coming from the Vuex store:
`value() {
      return this.$store.state.currentValue;
    }`

**Comment by sarahfmurray** [comment]
Oh I understand, I need a get() and a set() for value. This isn't a bug.
