### ISSUE TITLE
Cannot read property 'elem' of undefined

### ISSUE THREAD

**Issue by kiloquad** [NightCatSama/vue-slider-component#94]
Everytime I try to interact with the slide I get the following error:

```
Uncaught TypeError: Cannot read property 'elem' of undefined
    at VueComponent.offset (app.js:3799)
    at Watcher.get (app.js:3034)
    at Watcher.evaluate (app.js:3053)
    at VueComponent.computedGetter [as offset] (app.js:3076)
    at VueComponent.getPos (app.js:3879)
    at VueComponent.boundFn [as getPos] (app.js:2704)
    at VueComponent.wrapClick (app.js:3887)
    at boundFn (app.js:2704)
    at HTMLDivElement.invoker (app.js:2931)
```

My PUG template is very basic:

```
  .year-picker
    vue-slider(ref="yearSlider" v-model="year")
```

any idea what I'm doing wrong?

I'm using `2.3.9` from npm.

**Comment by NightCatSama** [comment]
What is your vue version?

**Comment by NightCatSama** [comment]
Does this error occur on the component?

**Comment by kiloquad** [comment]
As far as I can tell. It happenes any time I try to interact with the component (click or slide)

I have it up on http://timeslide.world/ if you want to look. Ignore the mess of a site, I'm just starting things.

**Comment by NightCatSama** [comment]
Well, I'm sorry I do not know where there is a problem.

I found `$refs` compiled into `$els`, you can try not to package the component into app.js.

**Comment by kiloquad** [comment]
I'll try that tonight. Thanks for looking into it.

**Comment by v4lerio** [comment]
Same issue. No clue what is going in the wrong way.
Any solution found so far?

**Comment by cdbethune** [comment]
The import statements for the Vue 1.x and 2.x versions of this component are *very* similar:

Vue 1.x:
```js
import vueSlider from 'vue-slider-component/src/vue-slider.vue';`
```
Vue. 2.x:
```js
import vueSlider from 'vue-slider-component'`
```
You'll get the reported error if you accidentally import the Vue 1.x slider into a Vue 2.x project.
