### ISSUE TITLE
Slider Value is not showing

### ISSUE THREAD

**Issue by theromie** [NightCatSama/vue-slider-component#95]
https://jsfiddle.net/theromie/9pp3dqkq/113/
example with help to understand

**Comment by NightCatSama** [comment]
This exception is written on the document. 

[https://github.com/NightCatSama/vue-slider-component#exceptions](https://github.com/NightCatSama/vue-slider-component#exceptions)

**Comment by NightCatSama** [comment]
The easiest way is to use v-if instead of v-show, or call the `this.$refs.slider.refresh()` method after displaying the component.

**Comment by theromie** [comment]
if i use v-show should i use this.$refs.slider.refresh()

**Comment by NightCatSama** [comment]
yes.

**Comment by theromie** [comment]
https://jsfiddle.net/theromie/9pp3dqkq/115/
not working

**Comment by NightCatSama** [comment]
[https://jsfiddle.net/9pp3dqkq/117/](https://jsfiddle.net/9pp3dqkq/117/)

**Comment by theromie** [comment]
What if i have multiple slider??
do i need to create multiple 
`this.$nextTick(() => this.$refs.slider1.refresh())`
`this.$nextTick(() => this.$refs.slider2.refresh())`

**Comment by NightCatSama** [comment]
Yes you can do that.
```
this.$nextTick(() => {
  this.$refs.slider1.refresh()
  this.$refs.slider2.refresh()
})
```
of use `show`:
[https://jsfiddle.net/9pp3dqkq/118/](https://jsfiddle.net/9pp3dqkq/118/)

**Comment by karymont** [comment]
what if my slider is contained in a component  ex. <app-slider> would contain 
`<template>
<f7-label>Slider</f7-label>
<vue-slider ref="slider1" v-bind="slider">
 </vue-slider>
</template>`

i tried to add this.$nextTick(() => this.$refs.sliderTemp.refresh()) in mounted() however it's not working

**Comment by NightCatSama** [comment]
Because the reason for the exception is when the component is initialized and not rendered to the page, resulting in the size of the component can not be properly obtained.

So `refresh` is to re-get the size, so the need to render the component to the page after the call.
