### ISSUE TITLE
Slider incorrectly resizes when orientation changes on mobile devices

### ISSUE THREAD

**Issue by caseyronan** [NightCatSama/vue-slider-component#96]
See attached screenshots of the example page in portrait and landscape orientations on mobile (ignore overlapping text). The slider component does not resize correctly as can be seen with the incorrect piecewise label gaps. 

Issue is reproducible in my own project, as well as on the example page.
Thank you.

![portrait](https://user-images.githubusercontent.com/8730918/29944340-d1fc7122-8e62-11e7-90cd-ab59adf17ff4.png)

![landscape view](https://user-images.githubusercontent.com/8730918/29944342-d36c3f06-8e62-11e7-9550-3955f5b444b9.png)

**Comment by NightCatSama** [comment]
Sorry, so long ago to reply.

Now the component will only automatically update the component size when the resize event is triggered.

So in other cases, you need to call the `refresh` method to manually update.

**Comment by caseyronan** [comment]
No problem - I got it working already. Code for anyone interested...
```
mounted() {
  this.$nextTick(function () {
    // Orientation event for mobile users
    window.addEventListener('orientationchange', this.getOrientationChange);

    // Init
    this.getOrientationChange()
  })
},

methods: {
  getOrientationChange(event) {
    this.$refs.slider.refresh()
  },
},

```
