### ISSUE TITLE
It seems we need a mobile width/height `dotSize` option

### ISSUE THREAD

**Issue by adi518** [NightCatSama/vue-slider-component#98]
It seems you can't change the dot size for mobile with just CSS, because the translate range which the dot can slide on is calculated in Script.

I can add this on my own, by extending the component, adding the necessary prop and use `this.isMobile` to apply the mobile dot size, but of course, would be better if it was out of the box.

**Comment by adi518** [comment]
Ended up solving it like this:

```js
<script>
// https://github.com/NightCatSama/vue-slider-component/issues/98
import VueSliderComponent from 'vue-slider-component'

export default {
  name: 'WobiExtendedVueSliderComponent',
  extends: VueSliderComponent,
  props: {
    mobileDotSize: Number,
    default: 16
  },
  mounted() {
    if (this.isMobile) {
      this.$emit('mobile')
    }
  }
}
</script>
```

I listen to the event and set `dotSize` to `mobileDotSize` in my HOC. Reactivity does the rest.

**Comment by NightCatSama** [comment]
I think your solution is already great.
